### ISSUE TITLE
Domain/MultiDomain Validation

### ISSUE THREAD

**Issue by andrepereiradasilva** [ssllabs/ssllabs-scan#100]
In the api docs you have:
«validationType - E for Extended Validation certificates; may be null if unable to determine»

There is also a "D" for domain validation, right?

Interesting thing almost all i tested returned "null" but they are really multi-domain (SAN).
Shouldn't the SAN certificates be "D" or "MD" (multi-domain).

**Comment by ivanr** [comment]
Detection of DV and OV certificates is currently not implemented, because this sort of thing is still fuzzy because there are no widely-followed standards in practice.
