### ISSUE TITLE
No Secondary grade in API, and when will be the new version be in production

### ISSUE THREAD

**Issue by moheshmohan** [ssllabs/ssllabs-scan#101]
Is there a way to add secondary grade to API, like what we get on the web page, in the case where M or T are ignored. 

Also the the production API still gives old format, i,e does not include variables like "freak". Will it be fixed soon?

**Comment by ivanr** [comment]
The secondary grade is not in the API at the moment, but I will add it. As for your second question, we don't have a date when we'll be updating the production servers, but I expecting an update mid-April.

**Comment by moheshmohan** [comment]
Thanks for the update Ivan

**Comment by ivanr** [comment]
Added to 1.16.8, now running on development servers.
