### ISSUE TITLE
Wrong HSTS results for cdt.org (Yes instead of Invalid) and npmjs.com (Invalid instead of Yes)

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#102]
https://www.ssllabs.com/ssltest/analyze.html?d=cdt.org
https://dev.ssllabs.com/ssltest/analyze.html?d=cdt.org
> This server supports HTTP Strict Transport Security with long duration.
> Strict Transport Security (HSTS)	Yes   : max-age=31536000; includeSubDomains; preload

There is a colon before "max-age", Chrome and Firefox don't remember HTTPS. Discussion: https://community.qualys.com/thread/14925

https://www.ssllabs.com/ssltest/analyze.html?d=npmjs.com&s=23.235.47.162
https://dev.ssllabs.com/ssltest/analyze.html?d=npmjs.com&s=23.235.40.162
> Strict Transport Security (HSTS)	Invalid  max-age=2592000000; includeSubdomains

Chrome and Firefox don't have any problems with 82 years max-age. Perhaps, there should be a warning that HSTS is set only for www.npmjs.com, but not for npmjs.com. Even PayPal (one of the HSTS developers) had this problem: https://coderrr.wordpress.com/2010/12/27/canonical-redirect-pitfalls-with-http-strict-transport-security-and-some-solutions/

**Comment by selecadm** [comment]
Found the problem. Damn integer, this stuff doesn't scale!

https://www.ssllabs.com/ssltest/analyze.html?d=hsts2147483647.selecadm.name&hideResults=on
https://dev.ssllabs.com/ssltest/analyze.html?d=hsts2147483647.selecadm.name&hideResults=on

2147483647:
> This server supports HTTP Strict Transport Security with long duration. Grade set to A+.
> Strict Transport Security (HSTS)	Yes   max-age=2147483647

![image](https://cloud.githubusercontent.com/assets/10382329/6933322/27437524-d82e-11e4-84bb-a3948835c072.png)

![image](https://cloud.githubusercontent.com/assets/10382329/6933335/67aa886e-d82e-11e4-84e8-d9f530eb306c.png)

2147483648:
> Strict Transport Security (HSTS)	Invalid  max-age=2147483648

![image](https://cloud.githubusercontent.com/assets/10382329/6933370/051e4900-d82f-11e4-923a-bb46a37bd3d8.png)

![image](https://cloud.githubusercontent.com/assets/10382329/6933385/3141dba0-d82f-11e4-8a2a-69c902e5034d.png)

**Comment by ivanr** [comment]
This is now fixed in the development version: https://dev.ssllabs.com/ssltest/analyze.html?d=hsts2147483647.selecadm.name

I treat HSTS max-age as long, not integer. Do note that I still don't have a proper parser for the HSTS syntax. I will work on that separately as part of the next 1-2 releases.

Thanks!

**Comment by josephlhall** [comment]
Heya, btw, big fan.

We deleted the STS config line from nginx, restarted, then added it back and restarted again and the double colon from the STS header is now gone. Apologies for fixing it before you could get to parsing the HSTS syntax!

**Comment by selecadm** [comment]
Another thing to fix: the test should check whether Public-Key-Pins contains the current public key and the backup one which isn't sent by the server. Pins should be SHA256, not SHA1.

Currently, the test always shows Yes, even when a server pins nonsense.
https://dev.ssllabs.com/ssltest/analyze.html?d=hsts2147483647.selecadm.name&hideResults=on
> Public Key Pinning (HPKP)	Yes   SSL Labs HPKP abuse awareness

![image](https://cloud.githubusercontent.com/assets/10382329/6957411/2e0bceee-d903-11e4-8284-040758af292c.png)

**Comment by selecadm** [comment]
@josephlhall No worries! @ivanr can now practice on my server :). Turns out SSL Labs only checks for "max-age=nnn" occurrence somewhere. Look at this:
![image](https://cloud.githubusercontent.com/assets/10382329/6991982/34168a58-dabc-11e4-95b0-90e6d3391b21.png)

Yes, this still gets an A+. https://dev.ssllabs.com/ssltest/analyze.html?d=hsts2147483647.selecadm.name&hideResults=on

**Comment by ivanr** [comment]
This is now fixed in 1.20.2. I've built a proper parser for the HSTS header.

**Comment by josephlhall** [comment]
pretty damn awesome, ivanr!

On Wednesday, August 19, 2015, Ivan Ristić <notifications@github.com> wrote:

> This is now fixed in 1.20.2. I've built a proper parser for the HSTS
> header.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ssllabs/ssllabs-scan/issues/102#issuecomment-132815659>
> .
>


-- 
Joseph Lorenzo Hall
Chief Technologist
Center for Democracy & Technology
1634 I ST NW STE 1100
Washington DC 20006-4011
(p) 202-407-8825
(f) 202-637-0968
joe@cdt.org
PGP: https://josephhall.org/gpg-key
fingerprint: 3CA2 8D7B 9F6D DBD3 4B10  1607 5F86 6987 40A9 A871
