### ISSUE TITLE
Should consider BEAST mitigated server-side in case of shutting down TLS 1.0 connections

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#104]
I have just configured one of my sites to do connection shutdown in case of negotiating TLS 1.0.

How it looks:
![image](https://cloud.githubusercontent.com/assets/10382329/6994952/33e9a6aa-db34-11e4-8c25-e736d1216fdb.png)

Right after receiving TLSv1 Application Data, the server immediately sends Encrypted Alert without its own Application Data, then TCP FIN, despite BEAST mitigated client-side, because of no record splitting challenge.

Why don't I just disable TLS 1.0? Because nginx always uses protocols from default_server (the bug is wontfix), and the site in question uses SNI. It is impossible to disable TLS 1.0 on a virtual host without disabling on default, but I can just drop such connections later, about 250 milliseconds.

Current result:
> BEAST attack	Not mitigated server-side (more info)   TLS 1.0: 0xc014

Expected result:
> BEAST attack	Mitigated server-side (more info)   TLS 1.0 clients receive SSL_shutdown

**Comment by ivanr** [comment]
Sorry, it's not practical for me to change the test to accommodate your unique circumstances. Further, there's no penalty for BEAST non-mitigation, so it wouldn't actually change anything.
