### ISSUE TITLE
Production can't test openssl s_server (Assessment failed: No secure protocols supported)

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#105]
OS — Debian 7.8
TLS implementation — LibreSSL 2.1.6

Production — Assessment failed: No secure protocols supported

> openssl s_server -accept 443 -cert cert.pem -key key.pem -serverpref -cipher ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384 -tls1_2 -www
Using auto DH parameters
Using default temp ECDH parameters
ACCEPT
bad gethostbyaddr
780173348:error:1408F10B:SSL routines:SSL3_GET_RECORD:wrong version number:s3_pkt.c:338:
ACCEPT
bad gethostbyaddr
780173348:error:1408A10B:SSL routines:SSL3_GET_CLIENT_HELLO:wrong version number:s3_srvr.c:864:
ACCEPT
bad gethostbyaddr
780173348:error:1408A10B:SSL routines:SSL3_GET_CLIENT_HELLO:wrong version number:s3_srvr.c:864:
ACCEPT

Development — all good

**Comment by ivanr** [comment]
That's probably a byproduct of the fact that the initial handshake doesn't support your selected cipher suites. It will go away eventually when I rewrite the SSL Labs handshake, hopefully this year.
