### ISSUE TITLE
IE protocol support inconsistence

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#106]
Internet Explorer 10.0.9200.17267 Update 10.0.25 (KB3032359)
Windows 7 SP1

SSL 2, SSL 3 and TLS 1.0 are enabled. TLS 1.1 and TLS 1.2 are disabled.

https://www.ssllabs.com/ssltest/viewMyClient.html is opened directly.

False negative:
SSL 3 No
SSL 2 No

SSL_CK_DES_192_EDE3_CBC_WITH_MD5 (0x700c0)   INSECURE 168
Server Name Indication (SNI) No
OCSP stapling No
SSL 2 handshake compatibility Yes

![image](https://cloud.githubusercontent.com/assets/10382329/7027981/90fb8d44-dd5b-11e4-83ec-d2f1f9b1bfb0.png)

**Comment by selecadm** [comment]
Have to remove SSL 2 mentioning because it's not just about SSL 2.

TLS 1.1 false negative with SSL 2 and 3 disabled and all TLS enabled.

![image](https://cloud.githubusercontent.com/assets/10382329/7028609/945bd530-dd5f-11e4-81e2-4ef92ab35864.png)

SSL 3 false negative also.

On IE 6 / XP sometimes all protocols are "No", nonsense!

![image](https://cloud.githubusercontent.com/assets/10382329/7028722/5d069182-dd60-11e4-8679-414943b4536f.png)

**Comment by selecadm** [comment]
SSL 3 and TLS 1.0: all protocols are "No" after allowing mixed content, the latter is still "No", though.

![image](https://cloud.githubusercontent.com/assets/10382329/7028823/388467fc-dd61-11e4-9d97-71cf0720913a.png)

**Comment by selecadm** [comment]
TLS 1.0 false negative on IE 6 / XP when all protocols are enabled. How can the only one common protocol be "No"?

![image](https://cloud.githubusercontent.com/assets/10382329/7028985/916139ee-dd62-11e4-9647-3a86139a7c80.png)

**Comment by ivanr** [comment]
I am unable to reproduce these problems. Any chance of getting a PCAP of the traffic for a further investigation?

**Comment by selecadm** [comment]
Unlikely, because Google doesn't like my WIndows XP virtual machine and constantly sends 30 packets per second (TCP Retransmission FIN, PSH, ACK), even after restarting a VM.

**Comment by ivanr** [comment]
I _think_ I was able to replicate the problem reported on this ticket. It's not clear exactly what was causing it (I think it might be an Apache bug), but I managed to work around it in configuration. If you can, please give 1.19.12 a try: https://dev.ssllabs.com/ssltest/viewMyClient.html
