### ISSUE TITLE
SSLLABS API

### ISSUE THREAD

**Issue by moustafak** [ssllabs/ssllabs-scan#108]
Hello,

Not sure if this is the right place to ask about the ssllabs web api

I have identified an issue when an api request is made while a scan is in progress and there are multiple endpoints found. For example, if you call for statusMessage, statusDetailsMessage or serverName the API returns the status for the last endpoint that has not started yet and in "pending" state.. it will remain like this until all the other endpoints have finished then it will give you the updates for the final endpoint only.

So the issue here is I never get to see the status updates for the actual endpoints being scanned until it hits the final endpoint.

Sample code that is going through a loop:

for (var i = 0; i < response.endpoints.length; i++) {
var endpoint = response.endpoints[i];
$inprogress.html("Server Name:"+endpoint.serverName+"<br>Status: " +endpoint.statusMessage+ "<br>Progress: "+endpoint.statusDetailsMessage);
}

**Comment by ivanr** [comment]
Hmm, I don't think that's the case. Have a look at the example below.
Assessment of the first endpoint is complete and its statusMessage is "Ready". The assessment of the second point is in progress, and its statusMessage is "In progress".
```
{"host":"ironbee.com","port":443,"protocol":"HTTP","isPublic":false,"status":
  "IN_PROGRESS","startTime":1429123828454,"engineVersion":"1.16.7",
  "criteriaVersion":"2009i","endpoints":[{"ipAddress":"50.112.159.162",
      "serverName":"ec2-50-112-159-162.us-west-2.compute.amazonaws.com",
      "statusMessage":"Ready","grade":"B","gradeTrustIgnored":"B",
      "hasWarnings":false,"isExceptional":false,"progress":100,"duration":
      160358,"eta":4,"delegation":3},{"ipAddress":"54.218.95.8","serverName":
      "ec2-54-218-95-8.us-west-2.compute.amazonaws.com","statusMessage":
      "In progress","statusDetails":"TESTING_SUITE_PREFERENCE",
      "statusDetailsMessage":"Determining cipher suite preference",
      "progress":98,"eta":2,"delegation":3}]}
```

**Comment by moustafak** [comment]
Hi Ivan,

Thanks for your reply. I later realised my problem can be resolved with jquery using a loop to cycle through each endpoint and output all the data. This issue is now resolved.

I managed to get through about 95% of the API spec and pretty impressed with how it all works but i do see a few issues especially around the reliability of "chaining issues".

According to the API documentation and testing the chaining issues dont seem to be accurate or the messages are misleading?. For example, many websites I scan result for "www.verisign.com<http://www.verisign.com>" and it returns chain issue '4' indicating "unrelated or duplicate certificates in chain" but upon closer inspection using openssl and other ssl checkers the chain looks fine.. So i am not sure if this is a known issue? There are others but I would like to get your thoughts on this first.

Thanks,
Moustafa

On 16 Apr 2015, at 5:00 am, "Ivan Ristić" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hmm, I don't think that's the case. Have a look at the example below.
Assessment of the first endpoint is complete and its statusMessage is "Ready". The assessment of the second point is in progress, and its statusMessage is "In progress".

{"host":"ironbee.com<http://ironbee.com>","port":443,"protocol":"HTTP","isPublic":false,"status":
  "IN_PROGRESS","startTime":1429123828454,"engineVersion":"1.16.7",
  "criteriaVersion":"2009i","endpoints":[{"ipAddress":"50.112.159.162",
      "serverName":"ec2-50-112-159-162.us<http://ec2-50-112-159-162.us>-west-2.compute.amazonaws.com",
      "statusMessage":"Ready","grade":"B","gradeTrustIgnored":"B",
      "hasWarnings":false,"isExceptional":false,"progress":100,"duration":
      160358,"eta":4,"delegation":3},{"ipAddress":"54.218.95.8","serverName":
      "ec2-54-218-95-8.us<http://ec2-54-218-95-8.us>-west-2.compute.amazonaws.com","statusMessage":
      "In progress","statusDetails":"TESTING_SUITE_PREFERENCE",
      "statusDetailsMessage":"Determining cipher suite preference",
      "progress":98,"eta":2,"delegation":3}]}

**Comment by ivanr** [comment]
The finding on the www.verisign.com is correct. There is one extra certificate that's not needed. In general, I would ignore this warning because there might be situations when the extra certificate might be needed with very old devices. I am considering removing the warning altogether.

**Comment by moustafak** [comment]
Thanks Ivan

Regards,
Moustafa
