### ISSUE TITLE
[REGRESSION] Extension intolerant server fails with "Assessment failed: Internal Error" on production and "Assessment failed: No secure protocols supported" on development

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#109]
https://www.ssllabs.com/ssltest/analyze.html?d=login.mos.ru
> Assessment failed: Internal Error

https://dev.ssllabs.com/ssltest/analyze.html?d=login.mos.ru
> Assessment failed: No secure protocols supported

https://sslanalyzer.comodoca.com/?url=login.mos.ru
> Error -12: Unable to establish an SSL connection

This is also a regression. Previously there was full report with "TLS extension intolerance Yes".
Cipher order was something like this:
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_3DES_EDE_CBC_SHA
TLS_RSA_WITH_AES_128_CBC_SHA
TLS_RSA_WITH_RC4_128_MD5
TLS_RSA_WITH_RC4_128_SHA
So none of the clients use RC4, because 3DES is prioritized.

https://ssl-tools.net/webservers/login.mos.ru
> The webserver of login.mos.ru can not be reached.
Results incomplete
PFS 
not checked
DANE 
missing
Heartbleed 
not checked
Poodle 
not checked

https://ssltools.websecurity.symantec.com/checker/views/certCheck.jsp
> This server cannot be scanned for the Heartbleed vulnerability.
This server cannot be scanned for the Poodle (TLS) vulnerability.

![image](https://cloud.githubusercontent.com/assets/10382329/7106638/b6aa5946-e150-11e4-90e8-fe1a9c7841d1.png)

ServerHello:
![image](https://cloud.githubusercontent.com/assets/10382329/7106596/0f4f7d9e-e14f-11e4-8f32-8ac3596603df.png)

**Comment by selecadm** [comment]
Comodo has just successfully tested the server!

![image](https://cloud.githubusercontent.com/assets/10382329/7147601/bfce3bcc-e304-11e4-84fb-5845514b3302.png)
![image](https://cloud.githubusercontent.com/assets/10382329/7147628/e791dede-e304-11e4-9c93-f08963922d24.png)

**Comment by selecadm** [comment]
Finally!

https://www.ssllabs.com/ssltest/analyze.html?d=login.mos.ru

![image](https://cloud.githubusercontent.com/assets/10382329/7708853/749765ac-fe61-11e4-81fe-9e6de94d8894.png)

**Comment by ivanr** [comment]
Just FYI, nothing changed on our end :)

**Comment by selecadm** [comment]
Significant changes have been made recently: TLS 1.1 and TLS 1.2 enabled, ECDHE support, pseudo-root removed from the chain.

But how do you know that BEAST and POODLE are mitigated, if there is the lowest priority for RC4 and handshake simulation time out?

![image](https://cloud.githubusercontent.com/assets/10382329/7902960/7d9e73f2-07d5-11e5-8f78-9f99a8c524f4.png)
