### ISSUE TITLE
No indication of incomplete certificate chains

### ISSUE THREAD

**Issue by konklone** [ssllabs/ssllabs-scan#110]
When a domain has an incomplete certificate chain, like so:

> https://www.ssllabs.com/ssltest/analyze.html?d=ignet.gov

This isn't indicated in a reliable way in the resulting JSON response that I can find:

> https://gist.github.com/konklone/51eabb095e95f70577f8

I see an `issues: 2` field near the chain, and an `issues: 8` field on one of the certs, but that's the closest hint I have.

**Comment by ivanr** [comment]
Why is that unreliable? According to the docs, bit 1 of Chain.issues is set when the certificate chain is incomplete. Because there are no other issues, the value is 2, as in your example. ChainCert.issues value of 8 indicates that bit 3 is set, which indicates a weak signature algorithm.

**Comment by konklone** [comment]
Gah, that's my bad. I need to read the docs more closely, and will in the future. Thanks, @ivanr!
