### ISSUE TITLE
Correct place for HSTS header in redirections

### ISSUE THREAD

**Issue by anand-bhat** [ssllabs/ssllabs-scan#112]
The page that accepts entries to Google's HSTS Preload list (https://hstspreload.appspot.com) indicates that "If you are serving a redirect, that redirect must have the HSTS header, not the page it redirects to."

SSL Labs on the other hand requires the HSTS header on the final page for a site to be considered as one that supports HSTS. See https://community.qualys.com/message/28624#28624 and https://community.qualys.com/message/28548#28548

I'm not aware of the HSTS spec but if Google is right, can SSL Labs use the same determination (check redirecting "from" page and not the redirected "to" page) to decide if a site supports HSTS?

**Comment by ivanr** [comment]
HSTS can be wherever you want it to be, provided it serves its purpose. For example, having it on the first response or on the last works equally well, assuming the hostname is the same. That said, there is potential for trouble if more than one hostname is used; in that case, it's usually best to enable HSTS on all of them.
The theme of the May release of SSL Labs will be application security, and I expect that stricter HSTS checks will be introduced. It's probably that we'll display all HTTP responses and show presence/absence of HSTS on all of them.

**Comment by anand-bhat** [comment]
Excellent! Thanks @ivanr
