### ISSUE TITLE
"A" rating is given to servers that support or even force 56-bit encryption

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#114]
56-bit encryption supported with the lowest priority:
https://www.ssllabs.com/ssltest/analyze.html?d=des56-support.serverhello.com
https://dev.ssllabs.com/ssltest/analyze.html?d=des56-support.serverhello.com

56-bit encryption supported and prioritized:
https://www.ssllabs.com/ssltest/analyze.html?d=des56-force.serverhello.com
https://dev.ssllabs.com/ssltest/analyze.html?d=des56-force.serverhello.com

![image](https://cloud.githubusercontent.com/assets/10382329/7215480/f9dbb548-e5e2-11e4-822a-7a60c4904c04.png)

GlobalSign gives 0 points for Cipher Strength:
https://sslcheck.globalsign.com/en_US/sslcheck/?host=des56-support.serverhello.com
https://sslcheck.globalsign.com/en_US/sslcheck/?host=des56-force.serverhello.com

![image](https://cloud.githubusercontent.com/assets/10382329/7215482/10f15904-e5e3-11e4-9520-b12abc4bbe71.png)

Comodo marks 56-bit ciphers as insecure:
https://sslanalyzer.comodoca.com/?url=des56-support.serverhello.com
https://sslanalyzer.comodoca.com/?url=des56-force.serverhello.com

![image](https://cloud.githubusercontent.com/assets/10382329/7215483/23d138c8-e5e3-11e4-911e-723b8f2b69a3.png)

**Comment by bknowles** [comment]
Wow.  That's huge.  Shouldn't that get an "F" grade?

**Comment by selecadm** [comment]
@bknowles, good question! As this bug has received no attention for three weeks, we need to go deeper. Introducing des56.serverhello.com — the server that gets A+ while negotiating 56-bit encryption with 25% of simulated clients and not providing Strict Transport Security. Seriously?

https://www.ssllabs.com/ssltest/analyze.html?d=des56.serverhello.com
https://dev.ssllabs.com/ssltest/analyze.html?d=des56.serverhello.com

![image](https://cloud.githubusercontent.com/assets/10382329/7582153/91105a50-f893-11e4-8cf5-1207a51549eb.png)

![image](https://cloud.githubusercontent.com/assets/10382329/7582181/e26083b2-f893-11e4-8321-bb2732aba792.png)

**Comment by ivanr** [comment]
This bug has not received any attention yet, but it's not ignored. It will be addressed when its time comes. Piling messages here won't make it happen sooner.

**Comment by selecadm** [comment]
Excellent!
I like abusing scanner on a 80th level :).

**Comment by selecadm** [comment]
Did someone use this configuration for their own site? What the…

https://www.ssllabs.com/ssltest/analyze.html?d=ssl.c1m.us

![image](https://cloud.githubusercontent.com/assets/10382329/7784107/9710c6b0-0162-11e5-8fc0-d148437afe89.png)
![image](https://cloud.githubusercontent.com/assets/10382329/7784115/bef56230-0162-11e5-8ac2-75e1956dcc1b.png)

**Comment by ivanr** [comment]
This will be resolved with the next grading update.
