### ISSUE TITLE
Suggestion that Outlook 2011 on Mac be a Reference browser ...

### ISSUE THREAD

**Issue by albrandwood** [ssllabs/ssllabs-scan#116]
For an unknown reason, Microsoft only gives Outlook 2011 a choice of 10 ciphers ...

SSL2_DES_192_EDE3_CBC_WITH_MD5
SSL2_RC4_128_WITH_MD5
SSL2_DES_64_CBC_WITH_MD5
SSL2_RC4_128_EXPORT40_WITH_MD5
TLS_RSA_WITH_3DES_EDE_CBC_SHA
TLS_RSA_WITH_RC4_128_SHA
TLS_RSA_WITH_RC4_128_MD5
TLS_RSA_WITH_DES_CBC_SHA
TLS_RSA_EXPORT_WITH_RC4_40_MD5
TLS_RSA_EXPORT_WITH_DES40_CBC_SHA

I'd like to suggest that it be included as a "reference" browser, since it's not documented (this was pulled with wireshark) and maybe important to Exchange server administrators.

**Comment by selecadm** [comment]
But the only one secure cipher suite is TLS_RSA_WITH_3DES_EDE_CBC_SHA, and all reference browsers should support ECDHE for consistent results.
So Outlook 2011 still supports SSL 2 and RSA_EXPORT. Microsoft, you had one chance!

**Comment by ivanr** [comment]
@albrandwood was that Outlook connecting to a web server or connecting to the Exchange server to retrieve email? And it's a fully patched Outlook 2011? If you can connect from Outlook to dev.ssllabs.com and tell me your IP address I'll be able to add it to the simulations.

**Comment by ivanr** [comment]
Closing, as no one offered to help.
