### ISSUE TITLE
Keep stable API endpoint in the source instead of dev API

### ISSUE THREAD

**Issue by imrehg** [ssllabs/ssllabs-scan#119]
I've been using ssllabs-scan for a bit more than a month in a script. When I started I think there was only the master branch, which I didn't expect it to unstable. Just yesterday I started getting 403 errors, and been investigating for a while to see why. Found that in 6f3c6fd01fc2a8adc2ed04b3d6c640819b7146be the API endpoint is switched to the dev version of the API, which is unexpected, since

1) the master was the original branch
2) the API docs say `The main API entry point is "https://api.ssllabs.com/api/v2/".`, not saying that any version of the code would default to anything else, and the help text only shows `https://www.example.com/api/`, so can't immediately check where the request will go (only if debug output is added).

I feel this situation is confusing, and would be better (more consistent, and easier to use) if the stable endpoint is kept in the code in both branches, and for development the person doing it would invoke the binary with the relevant `-api=https://api.dev.ssllabs.com/api/v2/` switch.

**Comment by ivanr** [comment]
I am afraid that's not possible. The development branch will often rely on new features that are being added and which are present only on the development servers.
Normally, development servers should be pretty stable. The 403 errors you encountered are a glitch in my deployment script. I will leave this ticket open until I deal with it.
