### ISSUE TITLE
[Feature request] Argument to report version and exit

### ISSUE THREAD

**Issue by yourcelf** [ssllabs/ssllabs-scan#122]
In order to better automate checking installations in e.g. ansible setups, it would be very useful to have a version report for the ssllabs-scan binary -- e.g. "print version and exit".  The best I can figure right now is this, parsing out a version from the INFO notice printed to stderr:

    $ ./ssllabs-scan 2>&1 | sed -n '1 s/^.*SSL Labs v\(.*\)$/\1/p' 
    1.16.14 (criteria version 2009i)

This is rather obtuse, hits the network, and takes longer to run than it seems like it should for just reporting a version.  A simpler "-version" switch would be awesome.

**Comment by cognusion** [comment]
The app itself isn't versioned. That string is composed of elements pulled from the SSL Labs server while running a scan. That will change whenever the server does, and may negatively impact your package management.

**Comment by ivanr** [comment]
Actually, the app is versioned; the current stable version number is 1.1.0. However, the version number is not displayed. I think we can implement the -version switch to exit early (without contacting servers) provided no hosts were provided.

**Comment by cognusion** [comment]
I have looked through the code again, and the only place I find a version number of any kind is the USER_AGENT variable. If this is what you mean, I can have a pull request for this feature shortly.
