### ISSUE TITLE
[Feature request] Fetch all server certificate chains (e.g. ECC, RSA) from single host

### ISSUE THREAD

**Issue by linshunghuang** [ssllabs/ssllabs-scan#124]
Currently, if a server uses two certificates chains (for example, a ECC-256 certificate chain and a RSA-2048 certificate chain), SSL Labs API only shows one of them. It would be really nice to fetch all of them.

**Comment by selecadm** [comment]
Wouldn't even call this "Feature request". It is a necessary enhancement that was already discussed several times.

https://community.qualys.com/message/22672
> We already collect all certificates, but don't display them yet. It's a UI challenge because with multiple certificates also come multiple trust path.

**Comment by ivanr** [comment]
FYI, the v3 API now exports all certificates and much more.

**Comment by linshunghuang** [comment]
That's great, thanks!

**Comment by bhushan5640** [comment]
Fixed.
