### ISSUE TITLE
Impossible to test stat.myttk.ru

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#125]
https://www.ssllabs.com/ssltest/analyze.html?d=stat.myttk.ru
> Assessment failed: Cipher suite support test failed

https://dev.ssllabs.com/ssltest/analyze.html?d=stat.myttk.ru
> Assessment failed: Unexpected failure

The last thing I saw was "Testing OCSP stapling".

https://sslanalyzer.comodoca.com/?url=stat.myttk.ru

![image](https://cloud.githubusercontent.com/assets/10382329/7559124/fc9fba7a-f7b9-11e4-80a4-d36450ae2743.png)

![image](https://cloud.githubusercontent.com/assets/10382329/7559131/1ebc4614-f7ba-11e4-94d3-7352b0572395.png)

The server prioritizes 128-bit GCM over 256-bit CBC, good! Also, it doesn't even support static RSA, which is unusual and not desirable for domestic ISP billing (no support for IE on XP).

**Comment by selecadm** [comment]
OK, production has just tested successfully, but development shows "Unexpected failure" or "No secure protocols supported". Firewall, maybe?

![image](https://cloud.githubusercontent.com/assets/10382329/7899722/f650968e-0737-11e5-81d6-7b59079076d7.png)

![image](https://cloud.githubusercontent.com/assets/10382329/7899728/5b0771f6-0738-11e5-9acd-fe1a77a8dc29.png)

**Comment by ivanr** [comment]
After troubleshooting, I think this is a problem either with TCP connection failing because the connectivity is bad, or there being some sort of rate access control mechanism that starts blocking our connections after a period of time.
