### ISSUE TITLE
New cipher order in W7/8/8.1/2008R2/2012/2012R2 (KB3042058)

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#127]
For the browser Simulation:

https://technet.microsoft.com/library/security/3042058
https://support.microsoft.com/en-us/kb/3042058

**Comment by selecadm** [comment]
https://technet.microsoft.com/library/security/3042058
> the update will be available via Microsoft Update and WSUS in Q4 2015

**Comment by ivanr** [comment]
Thanks for the update. I don't want to make any changes right now, given that the update is optional until the end of 2015.
