### ISSUE TITLE
MS increase the minimum allowable DHE key length to 1024 bits

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#128]
For the browser Simulation:

https://technet.microsoft.com/en-us/library/security/MS15-055
https://support.microsoft.com/en-us/kb/3061518

The security update addresses the vulnerability by increasing the minimum allowable DHE key length to 1024 bits.

This update standardizes TLS False Start ciphers across Windows 8 and Windows 8.1 by removing False Start optimization during cipher negotiation for the following two ciphers on Windows 8 systems:
•TLS_RSA_WITH_RC4_128_SHA
•TLS_RSA_WITH_RC4_128_MD5

**Comment by selecadm** [comment]
Verified! Internet Explorer 10.0.9200.17357 on Windows 7 SP1 sends TCP FIN after seeing ServerKeyExchange with 768-bit parameters.

Server for testing — https://dh768.serverhello.com/

https://www.ssllabs.com/ssltest/analyze.html?d=dh768.serverhello.com
https://dev.ssllabs.com/ssltest/analyze.html?d=dh768.serverhello.com
> This server supports insecure Diffie-Hellman (DH) key exchange parameters. Grade set to F.
Cipher Suites (SSL 3+ suites in server-preferred order; deprecated and SSL 2 suites always at the end)
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x9f)   DH 768 bits (p: 96, g: 1, Ys: 96)   FS   INSECURE	256
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x9e)   DH 768 bits (p: 96, g: 1, Ys: 96)   FS   INSECURE	128
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (0x6b)   DH 768 bits (p: 96, g: 1, Ys: 96)   FS   INSECURE	256
TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x39)   DH 768 bits (p: 96, g: 1, Ys: 96)   FS   INSECURE	256
TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 (0x67)   DH 768 bits (p: 96, g: 1, Ys: 96)   FS   INSECURE	128
TLS_DHE_RSA_WITH_AES_128_CBC_SHA (0x33)   DH 768 bits (p: 96, g: 1, Ys: 96)   FS   INSECURE	128
TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA (0x16)   DH 768 bits (p: 96, g: 1, Ys: 96)   FS   INSECURE	112

**Comment by ivanr** [comment]
Done in 1.19.10.

**Comment by selecadm** [comment]
Nice!

Don't forget about this limitation when writing handshake rules for Chrome 45 and Firefox 39 ;).

**Comment by ivanr** [comment]
Why, when I have you to remind me! :)

**Comment by selecadm** [comment]
> Why, when I have you to remind me! :)

Ahh, so sweet!

![image](https://cloud.githubusercontent.com/assets/10382329/8355372/91b33950-1b57-11e5-8b4e-61443587a495.png)
