### ISSUE TITLE
SCSV shouldn't be a criterion if only newest TLS version available

### ISSUE THREAD

**Issue by J0WI** [ssllabs/ssllabs-scan#129]
Servers that allow only TLS 1.2 can't get an A+ anymore.

**Comment by selecadm** [comment]
Huh?

https://www.ssllabs.com/ssltest/analyze.html?d=hsts2147483647.selecadm.name
https://dev.ssllabs.com/ssltest/analyze.html?d=hsts2147483647.selecadm.name
> This server supports HTTP Strict Transport Security with long duration. Grade set to A+.

> Downgrade attack prevention	Unknown (requires support for at least two protocols)

**Comment by J0WI** [comment]
Confirm, can't reproduce anymore.
