### ISSUE TITLE
any interest in a docker PR?

### ISSUE THREAD

**Issue by jumanjiman** [ssllabs/ssllabs-scan#130]
@ivanr Are you interested in a PR to add docker build files to create a tiny image that contains a statically-compiled binary and CA certificates (and nothing else)?

I put together https://github.com/jumanjiman/docker-ssllabs-scan that uses a build container to statically compile the binary, then create a runtime image that contains just the binary and ca cert bundle.

If you're interested, i can put together a PR.

however, it requires some effort on your part too. you would need to:

* publish images to docker hub
* work with docker (the company) to try to get the image designated "official" (maybe)

for my images, i use circle ci.
I suspect that an official image would want to use docker hub "automated builds" to generate new image after every code release of ssllabs-scan, tagged appropriately with version number.

**Comment by ivanr** [comment]
Given that I've never used Docker, I'd prefer if you maintained the Docker build separately. I can point to it in the documentation. I won't have time to look after it.

By the way, why do you need to bundle CA certificates? Is it for Go to be able to validate the certificate on the API servers?

**Comment by jumanjiman** [comment]
> Given that I've never used Docker, I'd prefer if you maintained the Docker build separately.

sure, np

> I can point to it in the documentation.

cool



> why do you need to bundle CA certificates? Is it for Go to be able to validate the certificate on the API servers?

correct. the alternatives are:

* embed ca certs in go source code (yuck)
* use `--insecure` flag (yuck).
