### ISSUE TITLE
Development now considers no TLS 1.2 support worse than CRIME

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#131]
TLS 1.0 only + TLS compression

PRODUCTION
![image](https://cloud.githubusercontent.com/assets/10382329/7670464/18166936-fcae-11e4-92b4-0a461e8ed76a.png)

DEVELOPMENT
![image](https://cloud.githubusercontent.com/assets/10382329/7670473/bb6ea526-fcae-11e4-916d-39aff8d60a54.png)

As of 4 May 2015, 20,9% of Android users are vulnerable to CRIME. Shouldn't TLS compression support result in "F"?

Further, there is no rating distinguishability between SSL 3 + TLS 1.0 and TLS 1.0 only.

![image](https://cloud.githubusercontent.com/assets/10382329/7670504/f80e32fc-fcaf-11e4-9a22-050390aac6dd.png)

**Comment by ivanr** [comment]
No, the CRIME cap is now C, but the message was incorrect. Fixed in 1.17.9. You're right that the CRIME cap should be greater than C, but it's too late to change that for the release planned for this week.
