### ISSUE TITLE
Cached results with expired certificate are misleading

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#132]
Perhaps, SSL Labs should automatically change cached results grage to T.

![image](https://cloud.githubusercontent.com/assets/10382329/7677154/7105051c-fd52-11e4-96ce-d96199830141.png)

![image](https://cloud.githubusercontent.com/assets/10382329/7677077/cb7de1c2-fd51-11e4-80ae-136536e444ea.png)

![image](https://cloud.githubusercontent.com/assets/10382329/7677096/0dbbcbe4-fd52-11e4-9ccd-9f9ebf8eb25d.png)

**Comment by ivanr** [comment]
Hmm, I would expect such sites to get an F. Could you please send me the server hostname privately so that I have a look? Thanks.

**Comment by selecadm** [comment]
Sent through Qualys Community.

**Comment by ivanr** [comment]
Yes, I see what you mean. The grade is decided at scan time, but the "expired N ago" message is created whenever the page is displayed. I should add a special check for expiration and display something like "stale results" warning.

**Comment by ivanr** [comment]
In 1.20.x I expire the results from the cache if one of the certificates expired since the test.
