### ISSUE TITLE
Long duration and failed tests for secureradio.net

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#133]
Debian 7.8
nginx 1.8.0 + LibreSSL 2.1.6

PRODUCTION
https://www.ssllabs.com/ssltest/analyze.html?d=secureradio.net

Previous results:
> Session resumption (caching)	No (IDs assigned but not accepted)
Test duration	300.686 seconds

![image](https://cloud.githubusercontent.com/assets/10382329/7688818/6de43318-fdb0-11e4-8ef9-6c15843f42b1.png)
![image](https://cloud.githubusercontent.com/assets/10382329/7689012/cfc60736-fdb1-11e4-8d0c-a2c4bfdf8017.png)

Current results:
> OCSP stapling	No   INTOLERANT
Test duration	280.172 seconds

Could you describe precisely what it means?

![image](https://cloud.githubusercontent.com/assets/10382329/7688833/9b11fa32-fdb0-11e4-834a-830ff7b70fad.png)
![image](https://cloud.githubusercontent.com/assets/10382329/7689023/e8c49fe0-fdb1-11e4-8a61-7588ec2c637f.png)

DEVELOPMENT
https://dev.ssllabs.com/ssltest/analyze.html?d=secureradio.net&s=95.213.147.64

> Session resumption (caching)	Yes
OCSP stapling	Yes
Test duration	109.522 seconds

![image](https://cloud.githubusercontent.com/assets/10382329/7688931/48af4c94-fdb1-11e4-8af7-2880c7e52531.png)
![image](https://cloud.githubusercontent.com/assets/10382329/7689043/0d8494ca-fdb2-11e4-822e-8416e52e354f.png)

**Comment by selecadm** [comment]
Fixed currently.

![image](https://cloud.githubusercontent.com/assets/10382329/7689483/68094604-fdb5-11e4-94b9-f035c585ac57.png)
![image](https://cloud.githubusercontent.com/assets/10382329/7689504/861dcd22-fdb5-11e4-823a-254db9691127.png)

**Comment by ivanr** [comment]
If a test is slower than usually, that's an indication of a slow underlying network. Because SSL Labs runs only one connection at a time, slow connections make the entire assessment much slower.

I didn't see any failed tests, am I missing something? OCSP stapling intolerant means that the server aborted a TLS connection when we indicated client-side support for stapling.

**Comment by selecadm** [comment]
> OCSP stapling intolerant means that the server aborted a TLS connection when we indicated client-side support for stapling.

If a server is really intolerant to OCSP stapling extension, shouldn't modern clients receive "Protocol or cipher suite mismatch"? I've seen servers that are intolerant to all TLS extensions, but how can one be intolerant to this extension exactly?

Yes, those were some network issues, probably because it was late evening in my time zone, the usual time when entertainment sites experience high loads.
