### ISSUE TITLE
Production is no longer able to resolve cyrillic .moscow domains

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#135]
Subj. Pick any site from Google results for "site:москва", try to test on production, see "Unable to resolve domain name". Development works.

![image](https://cloud.githubusercontent.com/assets/10382329/7760541/507b9c4a-0025-11e5-9c72-b15daf4ddf8d.png)

![image](https://cloud.githubusercontent.com/assets/10382329/7760576/8bc8fa22-0025-11e5-9ee7-3cb3a8b80fc7.png)

**Comment by selecadm** [comment]
OK, production has just successfully tested mine, but still not others'. Weird!

**Comment by ivanr** [comment]
FYI, I checked a few at random and they all resolved fine.
