### ISSUE TITLE
Reword insecure DH message to include reference to Logjam

### ISSUE THREAD

**Issue by anand-bhat** [ssllabs/ssllabs-scan#137]
The message for insecure DH currently states `"This server supports insecure Diffie-Hellman (DH) key exchange parameters. Grade set to F."` with the "More Info" link pointing to "https://weakdh.org/". I think it would be beneficial to add a reference to Logjam in this message now that there is a named vulnerability that people may be heard about.

I'm thinking something similar to what's being worded for FREAK -- `"This server supports 512-bit export suites and might be vulnerable to the FREAK attack. Grade set to F."`

![image](https://cloud.githubusercontent.com/assets/7332442/7782312/bba6de62-00de-11e5-9f47-d372d153fd1c.png)

**Comment by ivanr** [comment]
Done, although not yet published anywhere.
