### ISSUE TITLE
Extended Validation should not be "Yes" for non-transparent certificates issued after 1 January 2015

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#138]
StartCom and Deutsche Telekom don't know how to obtain public audit records, thus no EV in Chrome. Perhaps, the result should be yellow "No Certificate Transparency information".

https://www.ssllabs.com/ssltest/analyze.html?d=map.geo.admin.ch&s=54.171.185.147

> Valid from Mon, 11 May 2015 04:06:54 UTC
Extended Validation	Yes
Certificate Transparency	No

![image](https://cloud.githubusercontent.com/assets/10382329/7788491/1f399124-0245-11e5-89eb-104775bb5e2d.png)

https://www.ssllabs.com/ssltest/analyze.html?d=telesec.de

> Valid from Wed, 08 Apr 2015 09:37:52 UTC
Extended Validation	Yes
Certificate Transparency	No

![image](https://cloud.githubusercontent.com/assets/10382329/7788506/82ee7856-0245-11e5-8c09-cbc4c1f93835.png)

**Comment by selecadm** [comment]
+ Verizon

https://www.ssllabs.com/ssltest/analyze.html?d=internetbanking.argenta.be

> Valid from	Fri, 08 May 2015 15:21:39 UTC
Issuer	Verizon Public SureServer EV SSL CA G14-SHA2
Extended Validation	Yes
Certificate Transparency	No

![image](https://cloud.githubusercontent.com/assets/10382329/9030817/f75d4a9e-39b0-11e5-81b7-46ca2d4bb54c.png)

**Comment by ivanr** [comment]
For now, I added a warning if no SCT information is available. Getting things 100% right is a lot of work: first I need to process the whitelist, then I have to verify the SCTs and also check the independence requirements. I am going to consider it after I am done with other more useful features.
