### ISSUE TITLE
"Extended Validation No" for certificates issued from "E-Tugra Extended Validated CA"

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#139]
https://www.ssllabs.com/ssltest/analyze.html?d=e-tugra.com.tr

> Issuer E-Tugra Extended Validated CA
Extended Validation	No

![image](https://cloud.githubusercontent.com/assets/10382329/7817404/6adc83b8-03dd-11e5-99d2-718dd9c531e6.png)

![image](https://cloud.githubusercontent.com/assets/10382329/7817415/7260f560-03dd-11e5-82ab-07385280cdf8.png)

**Comment by ivanr** [comment]
Fixed in 1.19.19, now on the dev server: https://dev.ssllabs.com/ssltest/analyze.html?d=e-tugra.com.tr
