### ISSUE TITLE
Update Footnote Regarding "Virtual SSL Hosting"

### ISSUE THREAD

**Issue by vtlynch** [ssllabs/ssllabs-scan#140]
In the "Protocols" section, a footnote will be displayed if a server relies on SNI and also support SSL 2 and 3. This footnote will declare that SNI is not supported by these protocol versions.

The exact wording is: 

"This site requires support for virtual SSL hosting, but SSL 2.0 and SSL 3.0 do not support this feature."

For added clarify, this should be updated so that the term "SNI" is referenced within the footnote:

"This site requires support for virtual SSL hosting **(SNI)**, but SSL 2.0 and SSL 3.0 do not support this feature."

A similar footnote appears in the "Handshake Simulation" section where the message refers to both virtual hosting and SNI in this format.

![image](https://cloud.githubusercontent.com/assets/8700646/7845797/3a35c828-0487-11e5-9ab7-7368db9d94d2.png)

**Comment by selecadm** [comment]
Or at least change "virtual SSL hosting" to "virtual TLS hosting", so that it makes sense. Virtual hosting is impossible in SSL, only TLS.

**Comment by ivanr** [comment]
Fixed (not yet deployed anywhere).
