### ISSUE TITLE
[ENHANCEMENT] Non-WWW prefix handling should show a warning when WWW host uses REVOKED certificate

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#141]
Example: https://www.ssllabs.com/ssltest/analyze.html?d=rc4.io
82.163.78.64 — current production, not valid for WWW
82.163.77.97 — previous production, valid for WWW, but revoked

https://www.ssllabs.com/ssltest/analyze.html?d=rc4.io&s=82.163.78.64

> Prefix handling Non-prefixed access only, but DNS not configured for prefix
Revocation status Good (not revoked)
Trusted Yes

https://www.ssllabs.com/ssltest/analyze.html?d=rc4.io&s=82.163.77.97

> Prefix handling Both (with and without WWW)
Revocation status Revoked INSECURE
Trusted No NOT TRUSTED

**Comment by ivanr** [comment]
My idea is to fix this by running a separate test for every hostname + SNI + IP address combination separately. For example, a thorough test would try: rc4.io  + no_sni + IP, rc4.io + sni + IP, www.rc4.io  + no_sni + IP, www.rc4.io + sni + IP.
The problem with that approach is that it will produce too much data, most of it might not be relevant. Thus, I'd also need to have a diff algorithm to detect if there are any differences, and hide the results if there are not. This approach is also much slower.
So the ultimate problem is that, although a thorough test would catch various edge cases, most sites don't have such problems!
