### ISSUE TITLE
time Format in API Response Host:testTime 

### ISSUE THREAD

**Issue by lgbff** [ssllabs/ssllabs-scan#143]
i use the API call analyze, in Response become a Host:testTime anser.
for instanse: 1433147148701
When i convert this to usable format with:
#date -d @1433147148701
I becom the follow:
Mo 16. Aug 08:11:41 CEST 47384
(on german Debian Linux)

I'm al litbe bit confused ;-)

**Comment by drwetter** [comment]
the last 3 digits are millseconds

    date -d @1433147148  ==> Mon Jun  1 10:25:48 CEST 2015

**Comment by selecadm** [comment]
Let's just try to remove the last digit.

http://onlineconversion.com/unix_time.htm

1433147148701
Mon, 16 Aug 47384 06:11:41 GMT

143314714870
Fri, 19 Jun 6511 03:01:10 GMT

14331471487
Fri, 23 Feb 2424 12:18:07 GMT

1433147148
Mon, 01 Jun 2015 08:25:48 GMT

Yep, that's it!

**Comment by lgbff** [comment]
ahh, thx for the hint.
