### ISSUE TITLE
Geo DNS resolution

### ISSUE THREAD

**Issue by pierro222** [ssllabs/ssllabs-scan#144]
Since we use a Geo DNS for our URL, would be fantastic either :
- to choose where names are resolved
- to put the IP address to test to force the URL resolution

**Comment by ivanr** [comment]
There's an easier way: create a new DNS entry that resolves to all the individual IP addresses you have.

**Comment by seccubus** [comment]
The last option is usefull in other cases as well. E.g. when you are building a box and want to check if the certificate is OK before it goes life or if you have multiple nodes behind a (global)load balancer and don't want to leak their FQDNs via the SAN section in the domain names.
