### ISSUE TITLE
Handshake simulator doesn't take RSA key size into account

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#145]
Handshake simulator shows successful Safari negotiations for servers with 8192-bit RSA keys.

Safari on iOS 8 just throws an error, but Safari on iOS 6 even crashes with EXC_CRASH (SIGABRT) code.

Other Safari versions — help wanted.

PRODUCTION
https://www.ssllabs.com/ssltest/analyze.html?d=rsa8192.serverhello.com
https://www.ssllabs.com/ssltest/analyze.html?d=dh8192.serverhello.com

DEVELOPMENT
https://dev.ssllabs.com/ssltest/analyze.html?d=rsa8192.serverhello.com
https://dev.ssllabs.com/ssltest/analyze.html?d=dh8192.serverhello.com

How it should be:
> Client does not support RSA keys > 4096 bits

**Comment by ivanr** [comment]
Fixed in 1.19.10.

**Comment by selecadm** [comment]
Nice!

Don't forget about this limitation when writing handshake rules for Chrome 45 and Firefox 39 ;).
