### ISSUE TITLE
False POODLE alert in the red rectangle for SSL3 + RC4 only servers 

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#146]
When a server supports only SSL3 protocol and RC4-based cipher suites, the following message appears:
> This server is vulnerable to the POODLE attack and supports only SSL 3. Grade set to F. 

This is wrong, since:
>Protocols
TLS 1.2	No
TLS 1.1	No
TLS 1.0	No
SSL 3   INSECURE	Yes
SSL 2	No

> Cipher Suites (SSL 3+ suites in server-preferred order; deprecated and SSL 2 suites always at the end)
TLS_RSA_WITH_RC4_128_SHA (0x5)   WEAK	128
TLS_RSA_WITH_RC4_128_MD5 (0x4)   WEAK	128

> BEAST attack	Mitigated server-side   SSL 3: 0x5
POODLE (SSLv3)	No, mitigated   SSL 3: 0x5
-
POODLE (TLS)	Inconclusive

Actually, such configuration receives two SSL3 alerts:
> This server is vulnerable to the POODLE attack and supports only SSL 3. Grade set to F.
This server uses SSL 3, which is obsolete and insecure. Grade capped to B.

Instead, there should be one warning:
>This server supports only SSL 3. Grade set to F.

Also, why is POODLE TLS "Inconclusive"? It should be "No, TLS not supported".

**Comment by ivanr** [comment]
Can you please provide a hostname to test with?

**Comment by ivanr** [comment]
Actually, no need. The rating guide is clear that servers that support SSLv3 as their best protocol get an F. Thus, the grade is correct, but the message isn't. This is now fixed in v1.18.5.

**Comment by selecadm** [comment]
Thanks!

![image](https://cloud.githubusercontent.com/assets/10382329/8080598/84b57a8e-0f76-11e5-8481-b08e08ddb680.png)

![image](https://cloud.githubusercontent.com/assets/10382329/8080618/ab02264c-0f76-11e5-841c-78ffa6836361.png)

But, how do you check TLS compression support for SSL-only servers?

**Comment by selecadm** [comment]
> But, how do you check TLS compression support for SSL-only servers?

Now "TLS compression" is "SSL/TLS compression". Pretty smart!

![image](https://cloud.githubusercontent.com/assets/10382329/8159428/429993c2-136f-11e5-8d0b-640f7fd8fbf2.png)

**Comment by ivanr** [comment]
Thanks for the nudge ;)
