### ISSUE TITLE
[API security] Variable leakage on the results page for servers with SSL3 support and SNI-based cipher suites

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#148]
https://www.ssllabs.com/ssltest/analyze.html?d=very.badssl.com

This server supports SSL3 and its SNI-based cipher suite is TLS_RSA_WITH_RC4_128_MD5 (0x4).

Here is the list for non-SNI clients:

![image](https://cloud.githubusercontent.com/assets/10382329/8072684/fb85977a-0f21-11e5-9bb1-7d70b2f1bd73.png)

So we end up with this:

![image](https://cloud.githubusercontent.com/assets/10382329/8072743/33643eac-0f23-11e5-8862-5cc908ba525f.png)

> This server uses SSL 3, which is obsolete and insecure. Grade capped to B.
IE 6 / XP   No FS 1	  No SNI 2	SSL 3	TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)   No FS	112
POODLE (SSLv3)	No, mitigated (more info)   SSL 3: 0x$_f.hex($beastSuiteSsl3)
-

So I am now considering implementing a TLS server that will make SSL Labs leak its RSA primes. LOL, JK.

**Comment by ivanr** [comment]
The variable leakage has been addressed: https://dev.ssllabs.com/ssltest/analyze.html?d=very.badssl.com

Also, the test is now better at handling the case where suites with SSLv3 are different from the suites at the best protocol. It's not perfect (this will be fully resolved once we switch to full per-protocol suite testing), but it will get the job done in the majority of cases.

Thanks!

**Comment by selecadm** [comment]
Now SSL Labs shows CBC being used for BEAST mitigation.

> Cipher Suites (sorted by strength; the server has no preference)
TLS_RSA_WITH_RC4_128_MD5 (0x4)   WEAK	128
Suites used only for BEAST mitigation (TLS 1.0 and earlier)
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)	128

**Comment by ivanr** [comment]
Yes, that should be correct (I checked manually yesterday).
