### ISSUE TITLE
Wrong cipher suites for Windows Phone 8.1/IE11

### ISSUE THREAD

**Issue by martinsuchan** [ssllabs/ssllabs-scan#149]
Hi,
it looks like the SSLLabs uses wrong cipher suite set for Windows Phone 8.1/IE11.

First of all there are two different version of WP8.1
- WP8.1 RTM also called Lumia Cyan
- WP8.1 Update 1/GDR1 also called Lumia Denim
each of these variants got different cipher suite. Note there is also newer WP8.1 GDR2, just tested the suites there - same as on GDR1.

WP8.1 RTM list is here: http://imgur.com/v8JcoC4
WP8.1 Update 1 list is here: https://community.qualys.com/message/26645

Current list on SSLLabs is different to both of these sets:
https://www.ssllabs.com/ssltest/viewClient.html?name=IE%20Mobile&version=11&platform=Win%20Phone%208.1

We've found this recently because one of our servers supports currently only TLS_DHE_RSA... ciphers and TLS_RSA_WITH_RC4_128_SHA, none of which is supported on WP8.1 RTM.

**Comment by ivanr** [comment]
I don't see any differences between what we show and https://community.qualys.com/message/26645 Am I wrong? The cipher order we use is from a device I bought 1-2 months ago.

**Comment by ivanr** [comment]
Do you have any links that might point to how common is one WP8.1 version versus the other? Perhaps both should feature on our user agent list. Thanks.

**Comment by martinsuchan** [comment]
Hi, for about 99% of Windows Phone devices in Europe is this update already available. but some users might not have updated their phones yet, see:
http://www.microsoft.com/en/mobile/support/software-update/wp8-software-update/availability-in-europe/
But in US the problem is much wider, for about half of devices is WP8.1 Update 1 not yet available, see:
http://www.microsoft.com/en/mobile/support/software-update/wp8-software-update/availability-in-north-america/
Having both versions in the test suite might be a good idea!

**Comment by ivanr** [comment]
Do you have access to a Lumia Cyan device? If so, could you please visit dev.ssllabs.com and tell me your IP address? Thanks. (That should be enough to add the device to the simulations.)

**Comment by martinsuchan** [comment]
I was unable to find actual WP8.1 RTM device for the test yet, but I opened the page in WP8.1 RTM emulator, that should be identical, my IP address: 94.113.79.200

**Comment by ivanr** [comment]
Thanks. I had that older version in my database, but it was disabled. After checking that its capabilities are the same as yours, I put it back in. Fixed in the dev 1.19.10.

**Comment by martinsuchan** [comment]
Just a technicality - the WP8.1 versions are called just "Windows Phone 8.1" and "Windows Phone 8.1 Update 1".
Cyan and Denim are technically Nokia Lumia firmware versions that were released together with WP8.1 and WP8.1 Update 1 respectively. HTC and Samsung devices received no Cyan or Denim firmware update, only WP8.1 and WP8.1 Update 1.
Here's Microsoft article where it's officially naming these updates, for the reference:
https://www.windowsphone.com/en-us/how-to/wp8/basics/whats-new-in-windows-phone

**Comment by ivanr** [comment]
So Cyan is WP81 and Denim GDR1? And what's GDR2?

**Comment by martinsuchan** [comment]
GDR2 or Update 2 was delivered recently to some devices or is preinstalled on some new devices like new Lumia 640, but it's not expected to be released globally. There was also no Lumia firmware update related to the GDR2 and when I checked the TLS cipher suites on GDR2, they are same as on GDR1.
As far as I know most WP devices will go directly to Windows 10 instead in late Q3/Q4 this year.

**Comment by ivanr** [comment]
All right. I am calling them WP8.1 and WP8.1 Update now: https://dev.ssllabs.com/ssltest/clients.html Thanks for your help.
