### ISSUE TITLE
Windows 10/Microsoft Edge cipher suites

### ISSUE THREAD

**Issue by martinsuchan** [ssllabs/ssllabs-scan#150]
Hi,
Windows 10 is hitting RTM in just couple of weeks so it should be probably useful to include Windows 10/Microsoft Edge browser cipher suites in the ssllabs test as well.

I've checked the browser settings on Windows 10 for PCs, build 10130 on dev.ssllabs.com:
My IP address 77.75.74.248 

Protocols 

TLS 1.2 Yes 
TLS 1.1 No 
TLS 1.0 Yes 
SSL 3 No 
SSL 2 No 

Cipher Suites (in order of preference) 

TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)   Forward Secrecy  256 
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)   Forward Secrecy  128 
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)   Forward Secrecy  256 
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027)   Forward Secrecy  128 
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)   Forward Secrecy  256 
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)   Forward Secrecy  128 
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x9f)   Forward Secrecy  256 
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x9e)   Forward Secrecy  128 
TLS_RSA_WITH_AES_256_GCM_SHA384 (0x9d)  256 
TLS_RSA_WITH_AES_128_GCM_SHA256 (0x9c)  128 
TLS_RSA_WITH_AES_256_CBC_SHA256 (0x3d)  256 
TLS_RSA_WITH_AES_128_CBC_SHA256 (0x3c)  128 
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)  256 
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)  128 
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)   Forward Secrecy  256 
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)   Forward Secrecy  128 
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (0xc024)   Forward Secrecy  256 
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (0xc023)   Forward Secrecy  128 
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a)   Forward Secrecy  256 
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (0xc009)   Forward Secrecy  128 
TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 (0x6a)   Forward Secrecy2  256 
TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 (0x40)   Forward Secrecy2  128 
TLS_DHE_DSS_WITH_AES_256_CBC_SHA (0x38)   Forward Secrecy2  256 
TLS_DHE_DSS_WITH_AES_128_CBC_SHA (0x32)   Forward Secrecy2  128 
TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)  112 
TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA (0x13)   Forward Secrecy2  112 

And here are the results of Windows 10 Mobile, build 10080
http://imgur.com/a/rZXHh = the same as on Windows 10 for PCs.

It's possible that these suites might change before RTM, although not very likely. It's also quite strange that TLS 1.1 is not supported when tested on dev.ssllabs.com. Standard ssllabs.com test shows support for both 1.0, 1,1 and 1.2.

**Comment by martinsuchan** [comment]
Apparently the cipher suite in Windows 10 is now identical to current suite in Windows 8.1, so unless there is a difference in RTM, I don't think it should be added as a new entry to SSLLabs tests.

**Comment by ivanr** [comment]
I'll probably add it at some point, just so that people don't wonder about what Windows 10 clients are doing.

**Comment by ivanr** [comment]
@martinsuchan are you sure that the suites on Windows 10 are identical to 8.1? Because I expect that Windows 10 will have support for ECDHE+RSA+GCM; earlier versions shouldn't have these suites.

**Comment by martinsuchan** [comment]
You're right, the list is a bit different. 0xc030 is not supported (yet?) in Windows 8.1.

**Comment by ivanr** [comment]
Done. I've added Windows 10 to the dev build 1.19.10: https://dev.ssllabs.com/ssltest/viewClient.html?name=Edge&version=12&platform=Win%2010%20%28Build%201030%29

**Comment by martinsuchan** [comment]
Just an update, Windows 10 is officially released. The label should be changed to just
**Edge / Win 10**
It's not called Edge 12, just Edge right now. Note the About box actually says **Microsoft Edge 20.10240.16384.0** but there was no discussion about Edge version number from what I heard.

**Comment by ivanr** [comment]
Are the TLS capabilities in the final release identical to those from build 10130?

**Comment by martinsuchan** [comment]
Yes, just checked.
Btw. IE11 running on Windows 10 got same TLS capabilities as Edge, but there is no need to list it separately.

**Comment by ivanr** [comment]
I updated the names in 1.20.1, now running in development. For now I have two entries, one each for IE11 and Edge, even though the capabilities are identical.

**Comment by martinsuchan** [comment]
Another update, [Microsoft released recommendation](http://blogs.windows.com/msedgedev/2015/09/21/understanding-versions-in-an-evergreen-browser/) about Edge browser numbering and the first version should really be called "Edge 12" and the current version in Windows 10 Insider Preview and probably the first version in upcoming Windows 10 Mobile RTM will be "Edge 13".

By the way Microsoft mixed the cipher suites order in Edge 13 to this - keeping all PFS+AEAD suites at the top, following by PFS suites and the rest at the end:

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10547

TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)   Forward Secrecy  256 
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)   Forward Secrecy  128 
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)   Forward Secrecy  256 
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)   Forward Secrecy  128 
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x9f)   Forward Secrecy  256 
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x9e)   Forward Secrecy  128 
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (0xc024)   Forward Secrecy  256 
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (0xc023)   Forward Secrecy  128 
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)   Forward Secrecy  256 
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027)   Forward Secrecy  128 
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a)   Forward Secrecy  256 
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (0xc009)   Forward Secrecy  128 
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)   Forward Secrecy  256 
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)   Forward Secrecy  128 
TLS_RSA_WITH_AES_256_GCM_SHA384 (0x9d)  256 
TLS_RSA_WITH_AES_128_GCM_SHA256 (0x9c)  128 
TLS_RSA_WITH_AES_256_CBC_SHA256 (0x3d)  256 
TLS_RSA_WITH_AES_128_CBC_SHA256 (0x3c)  128 
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)  256 
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)  128 
TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)  112 
TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 (0x6a)   Forward Secrecy2  256 
TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 (0x40)   Forward Secrecy2  128 
TLS_DHE_DSS_WITH_AES_256_CBC_SHA (0x38)   Forward Secrecy2  256 
TLS_DHE_DSS_WITH_AES_128_CBC_SHA (0x32)   Forward Secrecy2  128 
TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA (0x13)   Forward Secrecy2  112

**Comment by martinsuchan** [comment]
Windows 10 update with Edge 13 is now officially available, see:
http://blogs.windows.com/windowsexperience/2015/11/12/first-major-update-for-windows-10-available-today/
IE11 has again the same cipher suites list as Edge in this version of Windows.

**Comment by ivanr** [comment]
FYI, I've added Edge 13 to 1.21.11 (to be released soon). That said, please open new tickets in the future :)

**Comment by ealashwali** [comment]
@martinsuchan @ivanr Hi, I was searching about how can I get the list of supported TLS versions in Windows IE or Edge. I cam across your posts. Can you please point to me where can I get the list of supported TLS versions in Microsoft Edge or IE ??

**Comment by martinsuchan** [comment]
@ealashwali Hi, the easiest way might be downloading official free Microsoft virtual machines with Windows 10 and Edge and test the supported Cipher suites there: 
https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
