### ISSUE TITLE
mark IDEA ciphers as weak

### ISSUE THREAD

**Issue by J0WI** [ssllabs/ssllabs-scan#152]
IDEA ciphers are deprecated for many reasons. They should be marked as weak and affect the grade.

**Comment by selecadm** [comment]
Was already discussed in Qualys Community exactly 11 months ago: https://community.qualys.com/message/24026#24026

14.07.2014
> I don't think IDEA is supported by any browser. But, it's obsolete and shouldn't be used. I'll look into it.

**Comment by ivanr** [comment]
Unless they're actually weak in some way, I see no reason to penalise the use of IDEA specifically.
