### ISSUE TITLE
Warn about https to http downgrade redirects

### ISSUE THREAD

**Issue by hickford** [ssllabs/ssllabs-scan#154]
The 'HTTP forwarding' section (under Miscellaneous) could warn about downgrade redirects from https to http. This is usually (always?) a bug.

It's a bug for https://www.stackoverflow.com which redirects to http://stackoverflow.com rather than the secure site https://stackoverflow.com

A different example is https://bbc.co.uk redirects to https://www.bbc.co.uk redirects to http://www.bbc.co.uk . There's no secure version of the page.

1. https://www.ssllabs.com/ssltest/analyze.html?d=stackoverflow.com
2. https://www.ssllabs.com/ssltest/analyze.html?d=www.bbc.co.uk

What do you think?

**Comment by selecadm** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=winhost.com

> HTTP status code	200

This is wrong, since only WWW stays on HTTPS when requested. https://winhost.com redirects to HTTP.

**Comment by LordMike** [comment]
@selecadm well.. the HTTP code ends up at 200, but it starts with a 301 to http://www.winhost.com

I get that this is hard (detecting redirects to HTTP)  because of the insane amount of ways to redirect. But perhaps a simple check for the basic will cover it?

E.g. when following redirects, at each step - check if a link goes to "http://". If any redirected link is over HTTP - the site is vulnerable, even if it ends up at an HTTPS site.

**Comment by ivanr** [comment]
I've added a warning if a redirection to plaintext is detected. At this time, there is no grade penalty, but there will be in the future. I will also add better detection of various configuration problems. For example, we currently don't follow redirections to plaintext, even though they might eventually lead back to encryption.

**Comment by LordMike** [comment]
But even if "they might eventually lead back to encryption", you'll still count it as vulnerable (in the future), right?

**Comment by hickford** [comment]
Looks good, thanks Ivan https://dev.ssllabs.com/ssltest/analyze.html?d=stackoverflow.com

**Comment by hickford** [comment]
Here's a https-http-https redirect trails:

    >http -h get https://www.online-go.com
    HTTP/1.1 301 Moved Permanently
    Connection: close
    Content-length: 0
    Location: http://online-go.com/

    >http -h get http://www.online-go.com
    HTTP/1.1 301 Moved Permanently
    Connection: close
    Content-length: 0
    Location: http://online-go.com/

    >http -h get https://online-go.com
    HTTP/1.1 200 OK

**Comment by hickford** [comment]
More concerningly, in online banking https://banking.smile.co.uk/ redirects to http://www.smile.co.uk/

**Comment by hickford** [comment]
Another redirect walk starts and ends https but goes via http

1. https://www.codiscope.com
2. http://codiscope.com
3. https://codiscope.com

**Comment by selecadm** [comment]
Yet another:

1. https://sslshopper.com
2. http://www.sslshopper.com
3. https://www.sslshopper.com

**Comment by hickford** [comment]
Another example https://www.ssllabs.com/ssltest/analyze.html?d=www.talktalk.co.uk

https://www.talktalk.co.uk/ redirects to http://sales.talktalk.co.uk redirects to https://www.talktalk.co.uk/shop/ . While the end URL is secure, an attacker could man-in-the-middle the insecure link to redirect users somewhere else.
