### ISSUE TITLE
Key Exchange & Cipher Strength MAX-out at 90%. Any Suggestions on how to bring these up to 100%?

### ISSUE THREAD

**Issue by wdkissiv** [ssllabs/ssllabs-scan#159]
SSLLABS-scan Reports Certificate & Protocol @ 100%. However, Key Exchange & Cipher Strength MAX-out at 90%. Any Suggestions on how to bring these up to 100%?
	
My server is hosted on a CentOS v6 VM machine.(Apache)
VM is running on top of CentOS v6 with WHM Server control panel.
Website is BillKiss.com 
Any ideas?

**Comment by RobTho** [comment]
https://www.ssllabs.com/projects/rating-guide/index.html
Key or DH parameter strength >= 4096 bits (e.g., 4096) 100%
Cipher strength Score >= 256 bits (e.g., 256) 100%

**Comment by wdkissiv** [comment]
Rob,

MANY Thanks.

Bill

William D. Kiss, CEO
Global 1 Research & Development, Ltd.
DIRECT Cell: +1.484.357.2339
e-mail: wdkiss13@gmail.com

**Comment by ivanr** [comment]
@wdkissiv In the future, please post questions of this nature to the SSL Labs community pages: https://community.qualys.com/community/ssllabs Thanks.

**Comment by wdkissiv** [comment]
Ivan,

Thanks for your responding to this question... however I'm still left with
the question.

What do I have to do to increase my scores?

Change my Certificate? I have an EV Cert from COMODO.
How do I get the Key or DH parameter strength up to 4096?

How do I get the Cipher strength Score up to 256?

I have bought your book (Hasn't arrived yet...) but really would appreciate
your answers to these questions.

Many thanks.
Bill


William D. Kiss, CEO
Global 1 Research & Development, Ltd.
DIRECT Cell: +1.484.357.2339
e-mail: wdkiss13@gmail.com

**Comment by wdkissiv** [comment]
Ivan,

Sorry, not enough coffee yet...
This site actually has a GoDaddy EV Cert, not Comodo (another one of my
sites).

I'm working on getting ONE site up to 100% in all categories, then doing
the rest of them.

Thanks in advance for your help.
Bill

William D. Kiss, CEO
Global 1 Research & Development, Ltd.
DIRECT Cell: +1.484.357.2339
e-mail: wdkiss13@gmail.com

**Comment by wdkissiv** [comment]
Rob,

SSL Report v1.19.33 I managed to achieve 4-100 scores on Certificate /
Protocol Support / Key Exchange / Cipher Strength on my Apache Server
www.BillKiss.com

Upgraded Report v1.21.13, however has downgraded the key exchange to a 90
score.
Any idea on what parameters need to change to get a 100?

I see the addition of ALPN , HSTS Preloading and Public Key Pinning
Report-Only specifications.  Any suggestions?

Thanks.
Bill

William D. Kiss, CEO
Global 1 Research & Development, Ltd.
DIRECT Cell: +1.484.357.2339
e-mail: wdkiss13@gmail.com

**Comment by RobTho** [comment]
hmm
try to remove static ciphers
TLS_RSA_WITH_AES_256_GCM_SHA384 (0x9d)  256 
TLS_RSA_WITH_AES_256_CBC_SHA256 (0x3d)  256 
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)  256

**Comment by wdkissiv** [comment]
Thanks,  will try tonight.
Bill

**Comment by RobTho** [comment]
Hi,

beside you really can remove the static ones, the root cause why it is not 100% should be the this

https://dev.ssllabs.com/projects/rating-guide/index.html

Table 4. Key exchange rating guide
Key exchange aspect Score
Weak key (Debian OpenSSL flaw) 0%
Anonymous key exchange (no authentication) 0%
Key or DH parameter strength < 512 bits 20%
Exportable key exchange (limited to 512 bits) 40%
Key or DH parameter strength < 1024 bits (e.g., 512) 40%
Key or DH parameter strength < 2048 bits (e.g., 1024) 80%
>>>>>>>> Key or DH parameter strength < 4096 bits (e.g., 2048) 90%  <<<<<<<<
>>>>>>>>Key or DH parameter strength >= 4096 bits (e.g., 4096) 100% <<<<<<<<

and your Server use

TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384  ECDH secp256r1 (eq. 3072 bits RSA) 
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384  ECDH secp256r1 (eq. 3072 bits RSA)
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA  ECDH secp256r1 (eq. 3072 bits RSA)
