### ISSUE TITLE
Normalization of DH warnings

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#160]
RSA with no DHE

Current:
> Uses common DH primes	No
DH public server param (Ys) reuse	No, DHE suites not supported

Expected:
> Uses common DH primes	No, DHE suites not supported
DH public server param (Ys) reuse	No, DHE suites not supported

Usual green for "No, DHE suites not supported".

ECC

Current:
> Uses common DH primes	No
DH public server param (Ys) reuse	No, DHE suites not supported

Expected:
> Uses common DH primes	No, ECDSA certificate, DHE not possible
DH public server param (Ys) reuse	No, ECDSA certificate, DHE not possible

Bold green for "No, ECDSA certificate, DHE not possible" (bold as a reward for using ECC).

**Comment by ivanr** [comment]
I improved the DH wording in 1.19.14, but not the other thing. Two reasons: each line reports one detection; I don't want to mix that with other stuff. A server might have DHE enabled if it has an ECDSA certificate if it also has an RSA certificate. Cheers.
