### ISSUE TITLE
What is the purpose of 'certHostnames'

### ISSUE THREAD

**Issue by mike-csis** [ssllabs/ssllabs-scan#161]
Hey,

What is the purpose of the field 'certHostnames' ?

When scanning Cloudflare sites, many hostnames will be represented, but the field is not set (null). I've seen references to it being set, but haven't been able to reproduce it myself.

**Comment by ivanr** [comment]
I've updated the docs to explain: https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs.md

"certHostnames[] - the list of certificate hostnames collected from the certificates seen during assessment. The hostnames may not be valid. This field is available only if the server certificate doesn't match the requested hostname. In that case, this field saves you some time as you don't have to inspect the certificates yourself to find out what valid hostnames might be."

**Comment by roycewilliams** [comment]
Now that I understand the purpose, I'd like to request that it be altered. :)

If possible, it would be better if certHostnames was always present. I would rather check the grade to definitively determine if a mismatch exists, and always have certHostnames available for diagnostic purposes. 

If this needs to be opened as a new issue, I'd be happy to create one.

**Comment by LordMike** [comment]
I second @roycewilliams .. In cases where I'd want the hostnames programmatically, I'd prefer one way of fetching them instead of alternating between "manual" and "straightforward".

**Comment by roycewilliams** [comment]
I've opened #163 for the semi-related enhancement request noted above.
