### ISSUE TITLE
Documentation for v1.18.1 ?

### ISSUE THREAD

**Issue by LordMike** [ssllabs/ssllabs-scan#162]
Hey,

The API (at https://api.ssllabs.com/api/v2/info) says version `1.18.1`, but the API docs are for `1.16.x`. Are there any differences that need to be implemented to bring a client up to version `1.18.1` ?

**Comment by ivanr** [comment]
Check out the master branch https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs.md
