### ISSUE TITLE
[ENHANCEMENT] Show key strength equality

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#164]
Current:
> Key	RSA 2048 bits (e 65537)

Suggestion:
> Key	RSA 2048 bits (e 65537), equal to 112-bit symmetric encryption

Similar:
> Key	RSA 3072 bits (e 65537), equal to 128-bit symmetric encryption
Key	RSA 4096 bits (e 65537), equal to 144-bit symmetric encryption
Key	RSA 7680 bits (e 65537), equal to 192-bit symmetric encryption
Key	RSA 15360 bits (e 65537), equal to 256-bit symmetric encryption

Hmm, how many bits of security for RSA 8192 and 16384? Those are obviously more common than 7680 and 15360.

Similar for ECC, but also mentioning RSA:
> Key	EC 256 bits, equal to 3072-bit RSA and 128-bit symmetric encryption
Key	EC 384 bits, equal to 7680-bit RSA and 192-bit symmetric encryption
Key	EC 521 bits, equal to 15360-bit RSA and 256-bit symmetric encryption

**Comment by ivanr** [comment]
This (or something similar) will have to wait for the next major update of the UI. Sorry. The principal reason is that I'd rather focus on new features (such as DANE, better HSTS checking, etc).
