### ISSUE TITLE
[DEVELOPMENT REGRESSION] Impossible to get A+ in case of a non-200 response

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#166]
1.19.14 now requires HTTP 200 for HSTS and HPKP, despite the fact that these headers can be sent even when a fatal 5xx error occurs.

PRODUCTION

![image](https://cloud.githubusercontent.com/assets/10382329/8379570/907c5fee-1c29-11e5-840d-c6960c4a4d0f.png)

![image](https://cloud.githubusercontent.com/assets/10382329/8379592/c9eaf754-1c29-11e5-87a6-01fde9900be3.png)

DEVELOPMENT

![image](https://cloud.githubusercontent.com/assets/10382329/8379630/fd50d7e4-1c29-11e5-9d57-a99d29634df5.png)

![image](https://cloud.githubusercontent.com/assets/10382329/8379651/1fe57116-1c2a-11e5-890d-732d6a10f6bb.png)

The server responds with 301 redirect to the HSTS preloaded site, no reason to cap the grade.

**Comment by ivanr** [comment]
Please provide the original hostname to test. Thanks.

**Comment by selecadm** [comment]
Looks like after I created some servers for testing this had already been fixed :(.

**Comment by ivanr** [comment]
Indeed, I needed the original hostname to verify that the issue was fixed. Sorry for the trouble.
