### ISSUE TITLE
Attempting to scan an unresolvable server results in "Unable to resolve domain name" even after adding a DNS record

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#169]
1. Try to scan a server before adding a DNS record
2. Get "Unable to resolve domain name"
3. Add DNS record
4. See "Unable to resolve domain name" again
5. Realize you now have to use dev server
6. If you performed step 1 on dev too, cry
7. ??????
8. Create a new issue about this

**Comment by ivanr** [comment]
Should be fixed in 1.19.20. I tested it ;)

**Comment by ivanr** [comment]
Forgot to mention: assessments with DNS failures are cached for one minute. At the DNS level, there's no more caching of negative results at all. Positive results respect TTL.
