### ISSUE TITLE
Test browser still can connect by RC4 as fallback

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#170]
Hi Ivan,

maybe you could add a test (to viewMyClient.html) that detects if a Client browser still supports RC4 as a fallback ?

Cause if it supports RC4 as fallback only, RC4 is not shown up in cipher suites list anymore.
But of cause it still can connect by RC4.

I assume it could be tested in similar way like you did for Poodle, Freak or Logjam.
If you just test if an access to a RC4 only server (extra port) is possible or not.

BR,
Rob

**Comment by selecadm** [comment]
Rejected: https://community.qualys.com/thread/15085#29307

@ivanr, maybe it's worth advertising https://RC4.IO or using its fallback servers on non-standard ports on viewMyClient.html (with "powered by RC4.IO" message).

**Comment by RobTho** [comment]
Problem
FF 39 release notes says
https://www.mozilla.org/en-US/firefox/39.0/releasenotes/
"Disable use of RC4 except for temporarily whitelisted Hosts"
But https://RC4.IO  and https://rc4.serverhello.com can be accessed by FF 39
Both are NOT on http://mxr.mozilla.org/mozilla-central/source/security/manager/ssl/IntolerantFallbackList.inc
and they still can be accessed when security.tls.insecure_fallback_hosts.use_static_list = false
So FF 39 release notes are wrong !

**Comment by RobTho** [comment]
As well i mean not a full test which Show all RC4 ciphers that are supported.
A test that just show RC4 (with any rc4 cipher) fallback still works would be enough.
So just like the short logjam or poodle test on top

**Comment by RobTho** [comment]
FF 39 Default is still
security.tls.unrestricted_rc4_fallback = true
only if you set to false all RC4 excapt whitelisted are blocked.

If you additionally set 
security.tls.insecure_fallback_hosts.use_static_list = false 
Really all RC4 is blocked.

**Comment by RobTho** [comment]
FF 39 Releasenotes are updated now
https://www.mozilla.org/en-US/firefox/39.0/releasenotes/
https://bugzilla.mozilla.org/show_bug.cgi?id=999544

**Comment by J0WI** [comment]
RC4 will be disabled in 2016 on any major browser.

**Comment by ivanr** [comment]
Closing this old ticket. I think there's little value in adding this test, considering that RC4 is definitely on the way out.
