### ISSUE TITLE
HTTP error 

### ISSUE THREAD

**Issue by oxitech239** [ssllabs/ssllabs-scan#171]
On the below date i got repeated errors when running multiple scans

2015/07/06 16:03:34 [ERROR] HTTP request failed: Get https://api.ssllabs.com/api/v2/analyze?host=publichost.tld&all=done&fromCache=on&maxAge=8&ignoreMismatch=on: EOF

on this date there were also errors mentioning 'connection reset by peer'

**Comment by ivanr** [comment]
This could be because we were having some network connectivity issues on two occasions, one on the 6th and another on the 7th. No problems since. Is the site working for you now?

If the problem happens again, please try with the API on the dev server.

**Comment by oxitech239** [comment]
Thanks for the update, this would have indeed been the the root cause for the disruptions.
