### ISSUE TITLE
GradeTrustIgnored: T - how?

### ISSUE THREAD

**Issue by LordMike** [ssllabs/ssllabs-scan#172]
Hi,

I've discovered a site with a grade T, and then if trust is ignored, it's still T. This happens in both dev and production. The site is `jezzper.dk`.

https://www.ssllabs.com/ssltest/analyze.html?d=jezzper.dk
https://dev.ssllabs.com/ssltest/analyze.html?d=jezzper.dk

![image](https://cloud.githubusercontent.com/assets/1027111/8633654/ecdccdfe-27d3-11e5-8fe7-d1422eebee0a.png)

**Comment by LordMike** [comment]
Also, `GradeTrustIgnored` seems to disagree with `Grade` in certain cases, I've found 7 differing sites.

Host | Grade | GradeTrustIgnored
------ | ----------- | -------
europaeiske.dk | C | D
leasinglink.dk | F | B
lektiekonsulenterne.dk | F | A
delightmobile.dk | F | C
xn--pigmtten-d0a.dk | F | A
talordentligt.dk | F | C
plantevalg.dk | C | D

**Comment by ivanr** [comment]
Fixed in 1.19.30 (now running in development). Thanks!
