### ISSUE TITLE
SSL Labs shows "Chain issues None" but extra-downloads the first and only intermediate

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#177]
https://www.ssllabs.com/ssltest/analyze.html?d=aeroexpress.ru
https://dev.ssllabs.com/ssltest/analyze.html?d=aeroexpress.ru

The server sends intermediate which SHA1 fingerprint is "ef90b2b86f4756ebe7d36ff3015d63523a0076e9".

AuthorityInfoAccess links to intermediate which SHA1 fingerprint is "902ef2deeb3c5b13ea4c3d5193629309e231ae55".

![image](https://cloud.githubusercontent.com/assets/10382329/8720801/b4b6c54a-2bbd-11e5-86df-5bc5f15bc562.png)

No explanation of what is wrong, should it be fixed, and how. Bad UI.

**Comment by ivanr** [comment]
There are no chain issues reported because the first path is complete and valid. The fact that another path can be made by following AIA is not important.
