### ISSUE TITLE
--hostfile and 429 response

### ISSUE THREAD

**Issue by J0WI** [ssllabs/ssllabs-scan#184]
If I start a test using the --hostfile operator to test a list of hosts, I get a 429 response after a few seconds.

The idea of --hostfile is, that I'm able to easily check a bulk of hosts, but in practise I'm spammed full of ```Sleeping for 30 seconds after a 429 response``` entries, even when I allow to use cached results.

**Comment by ivanr** [comment]
This should be fixed in master. Please give it a try and reopen if you continue to experience problems.
