### ISSUE TITLE
Certificate common names end at a comma

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#185]
https://www.ssllabs.com/ssltest/analyze.html?d=trustwave.com

Trustwave Extended Validation SHA256 CA

![image](https://cloud.githubusercontent.com/assets/10382329/8851185/800a44f4-3156-11e5-879f-edcafc6d6609.png)

Trustwave Extended Validation SHA256 CA, Level 1

![image](https://cloud.githubusercontent.com/assets/10382329/8851198/943d2086-3156-11e5-8b0e-ee0d3366c9d9.png)

E = ca@trustwave.com
CN = Trustwave Extended Validation SHA256 CA, Level 1
O = Trustwave Holdings, Inc.
L = Chicago
S = Illinois
C = US

**Comment by ivanr** [comment]
Fixed, not yet deployed. Thanks!
