### ISSUE TITLE
Idea, add indication of "modern cipher suite" according to Chrome?

### ISSUE THREAD

**Issue by martinsuchan** [ssllabs/ssllabs-scan#186]
When you open web secured by TLS in Chrome, it tells you in certificate and connection details either:

**Your connection to ... is encrypted using a modern cipher suite** if the connection uses **TLS 1.2 + PFS + AEAD** cipher suite,
![modern](https://cloud.githubusercontent.com/assets/3041397/8856296/465a781e-316a-11e5-830c-7df70a31df4c.png)

or **Your connection to ... is encrypted using an obsolete cipher suite** otherwise, even though it might be secure and strong cipher suite.
![obsolete](https://cloud.githubusercontent.com/assets/3041397/8856297/46601404-316a-11e5-9a72-3ad1e3843974.png)

Do you think ssllabs scan should point this out and maybe give A+ rating ony if "modern" cipher suite is used when visiting the site in Chrome? Or it's too specific rating that should not be mentioned in the test?

**Comment by ivanr** [comment]
Something like that is possible, but it won't be tied to Chrome. It could probably be along the lines of: you're using best possible encryption with all clients. But, the trouble there is, across 40 devices we simulate, it might be difficult to define "best". It might be a matter of opinion. In any case, it will have to wait for the next rating upgrade.
