### ISSUE TITLE
Impossible to test the www. subdomain and falsly report about it

### ISSUE THREAD

**Issue by tdelmas** [ssllabs/ssllabs-scan#187]
When submitting "www.example.com", ssllabs check "example.com" and not "www.example.com" so it's not possible to check if the configuration of the www subdomain is correct.

When submitting another.example.com the page "ssl report" listing the different IPs tested display  the grade (A+ for example) for "another.example.com" and "www.another.example.com" even if the certificate is not valid for www.another.example.com

I agree that in most case, the configuration of these two domains are the same but : 
- I think it's important to allow the possibility to really check the www subdomain
- When checking the example.com domain, it may report if the certificate is also valid for the www subdomain (but it shouldn't say "everything is fine" for the www subdomain without really checking it)

**Comment by selecadm** [comment]
SSL Labs always checks WWW, even for subdomains on any levels. If WWW resolves to another IP-address, there will be a separate test.

**Comment by tdelmas** [comment]
I agree that if the IPs are different, it's a strong hint about a possible configuration mismatch, but it's just a hint.

It's nice that ssllabs also check the www subdomain if it's on another IP, but it's sad that **if you want to and ask to specifically check the www subdomain, ssllabs will check the main domain instead**, if they share the same IP.

For example : 
- the domain https://tdelmas.ovh get A+ 
- the domain https://www.tdelmas.ovh have the same configuration except the HSTS header set to 60seconds so it should get an A. ssllabs display that : 
![ssl1](https://cloud.githubusercontent.com/assets/1955774/8864455/6af8ceea-31a2-11e5-96bd-7c06428a3c88.PNG)

- the domain https://blog.tdelmas.ovh get A+
ssllabs display : 
![ssl2](https://cloud.githubusercontent.com/assets/1955774/8864484/a6086df6-31a2-11e5-8fc3-e6ad495ab193.PNG)
Event if the **certificate is not valid** for www.blog.tdelmas.ovh.

(The example are on dev.ssllabs.com and not on www.ssllabs.com because only the dev version see the ipv6 address (Thanks for that !), but the production version have the same flaws)

So ssllabs does not allow you to check the www subdomain and lies about it's configuration...

**Comment by selecadm** [comment]
Also, http://npmjs.com sets HSTS only for WWW subdomain http://www.npmjs.com
http://npmjs.com requests won't be modified to HTTPS by browsers.

https://www.ssllabs.com/ssltest/analyze.html?d=npmjs.com
https://dev.ssllabs.com/ssltest/analyze.html?d=npmjs.com

Shouldn't get A+.

**Comment by frnkblk** [comment]
Interesting, when I pulled it up on dev I get analyses on two sites, and npmjs.com gets a B, not an A+.

![image](https://cloud.githubusercontent.com/assets/4812492/8892176/e00fe1ae-3310-11e5-8892-bc1c97ac654b.png)

**Comment by selecadm** [comment]
It's the same for production. Looks like npmjs.com without WWW prefix supports RC4 and uses default DH parameters, but this server only serves redirects to WWW which has A+ rating.

Interesting how such a company does HTTPS in such a wrong way.

**Comment by ivanr** [comment]
This will be changed in the next major upgrade. BTW, are you sure that "sad" is the right word? Unfortunate, maybe, but sad? :)

**Comment by ivanr** [comment]
Fixed in 1.22.2, now running on dev. More refinements will follow.
