### ISSUE TITLE
40-bit encryption is shown as the strongest

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#188]
https://www.ssllabs.com/ssltest/analyze.html?d=mar.mil.br
https://dev.ssllabs.com/ssltest/analyze.html?d=mar.mil.br

![image](https://cloud.githubusercontent.com/assets/10382329/8884509/e3e8cfb8-325f-11e5-9c72-5bfbd13590b8.png)

**Comment by ivanr** [comment]
I know it's not ideal, but (in 1.19.33, on the dev server) it says "deprecated and SSL 2 suites at the end".

**Comment by selecadm** [comment]
So why aren't other suites at the end?

https://www.ssllabs.com/ssltest/analyze.html?d=eservicetest.bolagsverket.se
https://dev.ssllabs.com/ssltest/analyze.html?d=eservicetest.bolagsverket.se

![image](https://cloud.githubusercontent.com/assets/10382329/8925623/ced7d9b6-3511-11e5-9284-c6e315513918.png)
