### ISSUE TITLE
Provide more information about non-leaf certificates in server chain

### ISSUE THREAD

**Issue by andrepereiradasilva** [ssllabs/ssllabs-scan#19]
The api results doesn't return some information that is in the online version.
I detected this ones:
- Chain certificates: [Signature Algorithm (ex: for SHA1 warnings) | Key ]
- PCI compliant
- FIPS-ready

**Comment by andrepereiradasilva** [comment]
Don't know if you know, but ENISA plublished a new recommendations report. They divided their old report in two:

**Study on cryptographic protocols**
http://www.enisa.europa.eu/activities/identity-and-trust/library/deliverables/study-on-cryptographic-protocols

**Algorithms, key size and parameters report 2014**
http://www.enisa.europa.eu/activities/identity-and-trust/library/deliverables/algorithms-key-size-and-parameters-report-2014

**Comment by ivanr** [comment]
Done in 1.16.1, now running on dev.ssllabs.com. New fields are: sigAlg, notBefore, notAfter, keyAlg, keyStrength, keySize.
