### ISSUE TITLE
GCM + RC4 servers get "RC4 with modern browsers"

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#190]
https://www.ssllabs.com/ssltest/analyze.html?d=payments.chronopay.com
https://dev.ssllabs.com/ssltest/analyze.html?d=payments.chronopay.com

payments.chronopay.com supports only AES GCM suites and TLS_RSA_WITH_RC4_128_SHA. Any modern browser in 2015 year is expected to support GCM, and won't negotiate RC4.

**Comment by ivanr** [comment]
The issue here is that TLS_RSA_WITH_RC4_128_SHA is negotiated with all Safari versions, but the message is inaccurate. It should say with "TLS 1.2 or some such thing".

**Comment by ivanr** [comment]
Fixed by changing "browsers" to "protocols". That leaves less to interpretation. Not yet deployed.
