### ISSUE TITLE
[DEVELOPMENT REGRESSION] POODLE (TLS) Inconclusive (Timeout) for servers without TLS support

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#191]
v1.19.33 shows this for SSL3 server:
> POODLE (TLS)	Inconclusive (Timeout)

How it was:
> POODLE (TLS)	No, because server doesn't support TLS

**Comment by ivanr** [comment]
Please provide a hostname to test with. Thanks.

**Comment by ivanr** [comment]
Fixed, not yet deployed anywhere. Thanks!
