### ISSUE TITLE
"Not trusted (certificate on blacklist)" for a valid and publicly trusted certificate

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#192]
https://www.ssllabs.com/ssltest/analyze.html?d=diginotar.fail
https://dev.ssllabs.com/ssltest/analyze.html?d=diginotar.fail

> This server's certificate is not trusted, see below for details.
Revocation status	Unchecked (only trusted certificates can be checked)
Trusted	No   NOT TRUSTED
Certification Paths
Path #1: Not trusted (certificate on blacklist)

![image](https://cloud.githubusercontent.com/assets/10382329/8991758/5ce2253e-3703-11e5-90bb-22395a801990.png)

![image](https://cloud.githubusercontent.com/assets/10382329/8991779/8027bce8-3703-11e5-9389-206a8c952808.png)

![image](https://cloud.githubusercontent.com/assets/10382329/8991741/4a18a3ec-3703-11e5-9871-d3aff1bc646e.png)

![image](https://cloud.githubusercontent.com/assets/10382329/8991801/9e073d56-3703-11e5-842a-d7543730ff89.png)

![image](https://cloud.githubusercontent.com/assets/10382329/8991821/c273fa44-3703-11e5-9792-68ec39abab9d.png)

![image](https://cloud.githubusercontent.com/assets/10382329/8991941/5caea5d2-3704-11e5-868d-943efdea0c5b.png)

DigiCert had refused to issue a certificate, but this domain successfully passed Comodo brand validation in 20 minutes.

![image](https://cloud.githubusercontent.com/assets/10382329/8995553/da97c120-371a-11e5-8238-0a16822ac303.png)

![image](https://cloud.githubusercontent.com/assets/10382329/8995592/241d79a2-371b-11e5-8d67-8dea5711355c.png)

![image](https://cloud.githubusercontent.com/assets/10382329/8995648/8cc3aa62-371b-11e5-9fb6-f52f5383e65e.png)

**Comment by ivanr** [comment]
Indeed, my blacklist is very crude and only looks for the word "diginotar" anywhere in the certificate. That was easier to implement that actually getting the blacklisted certificates :)

**Comment by ivanr** [comment]
Fixed in 1.20.9. It's a crude fix that only ignores the mention of "diginotar" in the leaf certificate.
