### ISSUE TITLE
Too many new assessments too fast. Please slow down.

### ISSUE THREAD

**Issue by hickford** [ssllabs/ssllabs-scan#193]
Hi. I wrote a script that uses the SSL Labs API. As of 1st August, it fails with the error (HTTP 429):

> Too many new assessments too fast. Please slow down.

I'm surprised because I wrote my script to be gentle on the API. I make 20 requests per day. Here's how I use the SSL Labs API: 

1. 9am cronjob: request assessments `https://api.ssllabs.com/api/v2/analyze?fromCache=on&publish=on&host=` for 10 different hosts. Ignore the results (usually "In progress")
2. 9.05am cronjob: request again `https://api.ssllabs.com/api/v2/analyze?fromCache=on&publish=on&host=` for the same 10 hosts. Parse the results. Publish to https://uk-banks-ssl-security.divshot.io/

How would you rather I use the API?

**Comment by ivanr** [comment]
Does this answer your question? https://sourceforge.net/p/ssllabs/mailman/message/34291130/

**Comment by ivanr** [comment]
That said, isn't it easier to simply use ssllabs-scan and let it handle the API for you, giving you back just the results. (Hint: the version in master is the best at the moment. It's in the queue to be promoted to stable.)

**Comment by hickford** [comment]
> The next production version of SSL Labs (v1.19.x) introduces a required cool-off period after each new assessment during which another assessment cannot be requested. In v1.19.x the cool-off period is 1000 ms.

Hi Ivan, thanks for your reply. Okay so simplest solution would be:

1. Add 1 second sleep to my script's loop between hosts

But you suggest:

1. Rewrite cronjob to use `ssllabs-scan` app, parse the results from that

That sounds sensible to me, let me try that.

**Comment by hickford** [comment]
Okay I tried `ssllabs-scan -usecache=true -hostfile=hosts.txt` but the results aren't in the format I expected, but a mix of messages to stderr. How can I get the results in a json file? I'd like the concatenation of the responses I get from the http API:

* https://api.ssllabs.com/api/v2/analyze?fromCache=on&host=https://bank.barclays.co.uk/
* https://api.ssllabs.com/api/v2/analyze?fromCache=on&host=https://personal.co-operativebank.co.uk/
* https://api.ssllabs.com/api/v2/analyze?fromCache=on&host=https://www1.firstdirect.com/
* https://api.ssllabs.com/api/v2/analyze?fromCache=on&host=https://www.halifax-online.co.uk/
* https://api.ssllabs.com/api/v2/analyze?fromCache=on&host=https://www.hsbc.co.uk/

Can you help? Thanks for your time, hopefully this will be useful to other readers too.

**Comment by ivanr** [comment]
Apologies, there was a bug in master that prevented the printing of the results to stdout. It's now fixed. This should be how you invoke it:
    $ ssllabs-scan.go --usecache --maxage=23 --hostfile=test-hosts.txt > results.json

**Comment by hickford** [comment]
Thanks

    ssllabs-scan --usecache --hostfile=hosts.txt > results.json

worked for me
