### ISSUE TITLE
commandline doesnt work

### ISSUE THREAD

**Issue by robarpanet** [ssllabs/ssllabs-scan#194]
I have created a folder labelled ssllabs i nthe root directory and have changed dir in DOS, but running the command ssllabs-scane [webaddress] only returns ssllabs-scan is not a recognised internal or external command.
ive listed the contents of the folder and they are identical to the zipfile downloaded and all permsissions set are RW.
Tried running the comand fro a DOS prompt with elevated prvelidges but same result.

**Comment by selecadm** [comment]
Programming language is required: http://golang.org/

32-bit: https://storage.googleapis.com/golang/go1.4.2.windows-386.msi
64-bit: https://storage.googleapis.com/golang/go1.4.2.windows-amd64.msi

**Comment by ivanr** [comment]
@robarpanet have you downloaded binaries from here https://github.com/ssllabs/ssllabs-scan/releases or did you get the source code directly from the repository? The binaries should work (if you get the correct version), but for the source code you first need to install Go, then run it with "go run ssllabs-scan.go", for example. Or compile it, then run it.
