### ISSUE TITLE
"Server doesn't support TLS" for community.qualys.com

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#195]
Qualys Communtiy itself seems to have been vulnerable to POODLE TLS, with patches applied semi-successfully, "Inconclusive" result on SSL Labs and red "Vulnerable" on Comodo SSL Analyzer.

https://www.ssllabs.com/ssltest/analyze.html?d=community.qualys.com
https://dev.ssllabs.com/ssltest/analyze.html?d=community.qualys.com

> POODLE (TLS)	No, because server doesn't support TLS

![image](https://cloud.githubusercontent.com/assets/10382329/9030707/ea1b01de-39ae-11e5-9f5e-9875667ce8e4.png)

**Comment by ivanr** [comment]
According to SSL Labs, there's no POODLE TLS there. The message is incorrect; you reported this on another bug and that was fixed, but not yet deployed to dev. The message is Inconclusive (Timeout). I'll forward this ticket to the site operators.

**Comment by ivanr** [comment]
According to Comodo, there's no POODLE TLS there: https://sslanalyzer.comodoca.com/?url=community.qualys.com

**Comment by selecadm** [comment]
The following servers are shown as vulnerable:
+ qualys.com
+ seal.qualys.com
+ browsercheck.qualys.com

https://sslanalyzer.comodoca.com/?url=qualys.com
https://sslanalyzer.comodoca.com/?url=seal.qualys.com
https://sslanalyzer.comodoca.com/?url=browsercheck.qualys.com

I noticed this about 4 months ago.

**Comment by ivanr** [comment]
For qualys.com, I know for a fact that the most recent POODLE TLS patch has been applied (because SSL Labs was detecting the problem before the patch ;) Still, I will forward to the network admins.
