### ISSUE TITLE
PLAINTEXT false positive for unionstandardbank.com.ua

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#196]
https://www.ssllabs.com/ssltest/analyze.html?d=unionstandardbank.com.ua
https://dev.ssllabs.com/ssltest/analyze.html?d=unionstandardbank.com.ua

199.83.134.49
> HTTP status code	301
HTTP forwarding	http://unionstandardbank.com.ua   PLAINTEXT

![image](https://cloud.githubusercontent.com/assets/10382329/9057874/a18339f8-3aa5-11e5-827e-8ef0a9ef50bc.png)

192.230.80.49
> HTTP status code	200

149.126.77.49
> HTTP status code	200

![image](https://cloud.githubusercontent.com/assets/10382329/9057842/7c9b3c94-3aa5-11e5-89fe-cab6e6bd082b.png)

curl -I https://unionstandardbank.com.ua/
> HTTP/1.1 200 OK
Server: nginx/1.8.0
Date: Tue, 04 Aug 2015 09:40:14 GMT
Content-Type: text/html; charset=UTF-8
Connection: close
X-Powered-By: PHP/5.4.41-0+deb7u1
Vary: Accept-Encoding,Cookie
Cache-Control: max-age=3, must-revalidate
WP-Super-Cache: Served supercache file from PHP
Set-Cookie: visid_incap_555464=iHTw2emVQG2gl/ls9GukgH6IwFUAAAAAQUIPAAAAAADqfmu8c1eMY2vCVAg+yC/6; expires=Wed, 02 Aug 2017 12:04:22 GMT; path=/; Domain=.unionstandardbank.com.ua
Set-Cookie: incap_ses_197_555464=tzZUIO6+zRjbMBfULOO7An6IwFUAAAAADIqctEBIy6Nu91CLa2bUNw==; path=/; Domain=.unionstandardbank.com.ua
Set-Cookie: ___utmvmOOuwEfa=mBkGtfnFyVs; path=/; Max-Age=900
Set-Cookie: ___utmvaOOuwEfa=KoBmKOq; path=/; Max-Age=900
Set-Cookie: ___utmvbOOuwEfa=qZE
    XWIOfalW: wtC; path=/; Max-Age=900
X-Iinfo: 8-148186337-148186375 NNNN CT(50 119 0) RT(1438681214463 88) q(0 0 2 1) r(2 2) U6
X-CDN: Incapsula

**Comment by ivanr** [comment]
Not when you try https://www.unionstandardbank.com.ua

**Comment by selecadm** [comment]
Stupid WWW again, I hate it.
