### ISSUE TITLE
[ERROR] HTTP request failed (master branch)

### ISSUE THREAD

**Issue by fishouttah20** [ssllabs/ssllabs-scan#197]
Using the master branch source, I'm unable to get through an (admittedly large) hostfile without it bombing out with an error. Tried throughout the day today, even using --usecache to quickly get back to where it died.

It always ends in an error like this:

2015/08/05 00:33:53 [ERROR] HTTP request failed: Get https://api.dev.ssllabs.com/api/v2/analyze?host=xxxxx&all=done&fromCache=on&ignoreMismatch=on: EOF (ref#1)
exit status 1

Giving up and using Stable. Wanted to use Master based on indication it was about to be promoted, wanted to make sure you were aware of issues.

**Comment by fishouttah20** [comment]
or maybe it's just that the api.dev server isn't as stable. If that's the case, please close.

**Comment by ivanr** [comment]
Please update your copy and try again. There's a retry mechanism to retry failed HTTP connections, but there was also a bug preventing its activation.

**Comment by fishouttah20** [comment]
Great, thanks, updated and running again. I'll close once it's done.

**Comment by fishouttah20** [comment]
Works like a champ now. Thanks for the great service, api and cli tool!
