### ISSUE TITLE
[DEVELOPMENT] goto fail false negative

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#198]
PRODUCTION
![image](https://cloud.githubusercontent.com/assets/10382329/9079103/f1e6acd2-3b4e-11e5-8cbd-f5c195df440d.png)

DEVELOPMENT
![image](https://cloud.githubusercontent.com/assets/10382329/9079105/ff0c1f8c-3b4e-11e5-8a31-1559401bff2b.png)

[![Deja Vu](https://img.youtube.com/vi/z_KmNZNT5xw/0.jpg)](https://www.youtube.com/watch?v=z_KmNZNT5xw)

**Comment by ivanr** [comment]
I no longer have a vulnerable device so I unable to test myself. Are you able to open https://dev.ssllabs.com:10443 (from a vulnerable device)? I've checked that there are no firewall restrictions.

**Comment by selecadm** [comment]
Yes, but "click here" links to the production server, had to manually replace "www" with "dev".

Still false negative on viewMyClient.html

**Comment by ivanr** [comment]
Unable to reproduce; closing for now.
