### ISSUE TITLE
Incorrect message for IE 6 / XP "SSL 2 Client chooses one of the supported SSL 2 suites"

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#199]
Servers that support SSL 2 with all cipher suites disabled get this:

> IE 6 / XP   No FS 1	  No SNI 2	SSL 2	Client chooses one of the supported SSL 2 suites	-

How it should be:

> IE 6 / XP   No FS 1	  No SNI 2	SSL 2	No suites offered by server	-

**Comment by ivanr** [comment]
Please provide example hostname. Thanks.

**Comment by selecadm** [comment]
The server configuration can be changed several times a day, better to show what I mean here:

![image](https://cloud.githubusercontent.com/assets/10382329/9286959/fc45af3a-4309-11e5-8991-4f0ff64cffcc.png)

**Comment by ivanr** [comment]
I know exactly what you mean, but I was hoping not to have to standup a server to replicate the bug.

**Comment by selecadm** [comment]
Sent through Qualys Community.

**Comment by ivanr** [comment]
Fixed in 1.20.1. Thanks!
