### ISSUE TITLE
[DEVELOPMENT] Empty space for certificates without Common Name

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#200]
Production:
https://www.ssllabs.com/ssltest/analyze.html?d=google.com

> Equifax / Equifax Secure Certificate Authority

Development:
https://dev.ssllabs.com/ssltest/analyze.html?d=google.com

Nothing is shown.

**Comment by ivanr** [comment]
Fixed, not yet deployed. Thanks!
