### ISSUE TITLE
meaning of PoodleTls values -2 and -3?

### ISSUE THREAD

**Issue by roycewilliams** [ssllabs/ssllabs-scan#201]
Some hosts return a value of -2 or -3 for PoodleTLS. What do these mean?

Some hosts returning -2 are associated with certificate name mismatch.

Some hosts returning -3 show either "No", or "No, because server doesn't support TLS" status.

**Comment by ivanr** [comment]
I updated the docs so that all possible values are documented:
https://github.com/ssllabs/ssllabs-scan/blob/stable/ssllabs-api-docs.md

poodleTls - results of the POODLE TLS test:
    -3 - timeout
    -2 - TLS not supported
    -1 - test failed
    0 - unknown
    1 - not vulnerable
    2 - vulnerable
