### ISSUE TITLE
Idea. Display data for a selection of websites over time.

### ISSUE THREAD

**Issue by LordMike** [ssllabs/ssllabs-scan#202]
Just an idea.

Could be cool if Ssllabs would store all reports created over time, and be able to present graphs like those in the link. Even a raw dump of historical data could be useful.

Source:
https://twitter.com/spazef0rze/status/633954769707466752

**Comment by ivanr** [comment]
That's a rough plan for SSL Pulse v2 https://www.trustworthyinternet.org/ssl-pulse/ Although I don't generally like the idea of showing the results of individual web site assessments. In aggregate, yes.
