### ISSUE TITLE
incorrect or undocumented issue types?

### ISSUE THREAD

**Issue by wyardley** [ssllabs/ssllabs-scan#203]
This might actually be an API issue, but I am looking at the list of response codes for cert issues at:

https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs.md

issues - list of certificate issues, one bit per issue:

    bit 0 (1) - no chain of trust
    bit 1 (2) - not before

However, I'm getting some additional response codes, for example,
 "endpoints.0.details.chain.certs.0.issues": 10
and:
 "endpoints.0.details.chain.issues": 6

or, for a self-signed cert:
 "endpoints.0.details.cert.issues": 65
(since 64 is "self-signed", wondering if this is an off-by-one issue?)

I'd rather not post the details, but can provide them privately if needed, but wondering:
1) Could there be an off-by-one in the way ssllabs-scan reports self-signed certs?
2) Are there additional issue types that are not documented in the link above?

**Comment by wyardley** [comment]
obviously the chain issues are different codes, but there's still no '6'.

**Comment by nextPrime** [comment]
The response and the doc are correct. For example, the code 65 (meaning that bit 0 and bit 6 are set) indicates the issues are self-signed (bit 6) and no chain of trust (bit 0). Similarly, code 10 indicates "hostname mismatch" and "not before" issues.

**Comment by seccubus** [comment]
Since all API users have to make this calculation it would be great if we had this value as text field somewhere as well.

**Comment by wyardley** [comment]
Thanks for the quick responses. Had considered that, sorry for not working on it a bit longer.

Does seem like it would be more consistent with the rest of the interface to make it show up as a list of values, but should be easy enough to do the calculation.

**Comment by wyardley** [comment]
ps - In case it's helpful for anyone else, this is how I did the conversion, not sure if there's a simpler way:
```python
    bits_as_list = list()
    index = 0
    for bit in reversed(bin(value)[2:]):
        bit = int(bit)
        if bit == 1:
            bits_as_list.append(index)
        index += 1
    return bits_as_list
```
