### ISSUE TITLE
[DEVELOPMENT REGRESSION] Explicitly disabled HSTS is "Unknown" again

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#204]
Production:
> Strict Transport Security (HSTS)	Disabled   max-age=0
Public Key Pinning (HPKP)	No

Development:
> Strict Transport Security (HSTS)	Unknown (failed HTTP request?)
Public Key Pinning (HPKP)	No

Originally implemented here: https://community.qualys.com/thread/12846
Broken here: https://github.com/ssllabs/ssllabs-scan/issues/102#issuecomment-132815659

**Comment by ivanr** [comment]
Should be fixed in 1.20.9.
