### ISSUE TITLE
[ENHANCEMENT] Handshake simulation with and without TLS extensions

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#205]
LibreSSL 2.2.2 rejects Android 2 handshakes because of no TLS extensions. Android uses TLS_EMPTY_RENEGOTIATION_INFO_SCSV cipher suite instead of renegotiation_info extension.

1. Grab the info about supported protocols and suites.
2. Send ClientHello similar to server capabilities with TLS_EMPTY_RENEGOTIATION_INFO_SCSV and without any extensions.
2. Send ClientHello similar to server capabilities with renegotiation_info extension.
3. If the former fails but the latter succeeds, there should be this message instead of the current:

> Server aborts on ClientHello without TLS extensions

![image](https://cloud.githubusercontent.com/assets/10382329/9541595/65deda08-4d72-11e5-98bf-112ce7f2ab43.png)

LibreSSL issue: https://github.com/libressl-portable/portable/issues/122

"Protocol or cipher suite mismatch" is wrong, there IS protocol and cipher suite match, and a server doesn't send such alerts.

**Comment by ivanr** [comment]
AFAIK, that bug has been fixed. Either way, in most cases it's not possible to tell why the server refused a particular connection.
