### ISSUE TITLE
Empty certificate object returned for leaseplanbank.de

### ISSUE THREAD

**Issue by seccubus** [ssllabs/ssllabs-scan#206]
See: https://www.ssllabs.com/ssltest/analyze.html?d=leaseplanbank.de&s=195.182.13.83 and https://www.ssllabs.com/ssltest/analyze.html?d=www.leaseplanbank.de&s=195.182.13.83

JSON response from API:
   "leaseplanbank.de" : {
      "protocol" : "HTTP",
      "status" : "READY",
      "port" : 443,
      "host" : "leaseplanbank.de",
      "endpoints" : [
         {
            "statusDetailsMessage" : "Testing SSL 2.0",
            "progress" : -1,
            "ipAddress" : "195.182.13.83",
            "duration" : 155,
            "details" : {
               "nonPrefixDelegation" : true,
               "key" : {},
               "hostStartTime" : 1440583216386,
               "chain" : {},
               "suites" : {},
               "prefixDelegation" : false,
               "cert" : {},
               "protocols" : []
            },
<snip>
   "www.leaseplanbank.de" : {
      "protocol" : "HTTP",
      "status" : "READY",
      "port" : 443,
      "host" : "www.leaseplanbank.de",
      "endpoints" : [
         {
            "statusDetailsMessage" : "Testing SSL 2.0",
            "progress" : -1,
            "ipAddress" : "195.182.13.83",
            "duration" : 155,
            "details" : {
               "nonPrefixDelegation" : true,
               "key" : {},
               "hostStartTime" : 1440583216386,
               "chain" : {},
               "suites" : {},
               "prefixDelegation" : false,
               "cert" : {},
               "protocols" : []
            }

The cert property for endpoint 195.182.13.83 is an empty object.

**Comment by selecadm** [comment]
Your second link is wrong. WWW subdomain resolves to 195.182.13.80, not 195.182.13.83

The main host and WWW host use different certificates. @ivanr, is it the problem?

**Comment by seccubus** [comment]
Both have two endpoints, in the www test the non-www url is included and vise-versa.

**Comment by ivanr** [comment]
The cert objects are empty because the test didn't reach the stage at which the certificates are fetched. Is that the entire JSON response from the API? Because it's missing many fields, for example "statusMessage", "grade", and so on. I ran the test a minute ago and the output was fine.

**Comment by seccubus** [comment]
No, below is the full response. 

----8X----------
   "www.leaseplanbank.de" : {
      "protocol" : "HTTP",
      "status" : "READY",
      "port" : 443,
      "host" : "www.leaseplanbank.de",
      "endpoints" : [
         {
            "statusDetailsMessage" : "Testing SSL 2.0",
            "progress" : -1,
            "ipAddress" : "195.182.13.83",
            "duration" : 155,
            "details" : {
               "nonPrefixDelegation" : true,
               "key" : {},
               "hostStartTime" : 1440583216386,
               "chain" : {},
               "suites" : {},
               "prefixDelegation" : false,
               "cert" : {},
               "protocols" : []
            },
            "eta" : -1,
            "statusDetails" : "TESTING_PROTO_2_0",
            "statusMessage" : "Unable to connect to server",
            "delegation" : 1
         },
         {
            "hasWarnings" : false,
            "progress" : 100,
            "ipAddress" : "195.182.13.80",
            "grade" : "A",
            "gradeTrustIgnored" : "A",
            "duration" : 122286,
            "details" : {
               "nonPrefixDelegation" : false,
               "key" : {
                  "debianFlaw" : false,
                  "size" : 4096,
                  "strength" : 4096,
                  "alg" : "RSA"
               },
               "sniRequired" : false,
               "httpStatusCode" : 200,
               "hostStartTime" : 1440583216386,
               "hasSct" : 0,
               "compressionMethods" : 0,
               "vulnBeast" : true,
               "chain" : {
                  "issues" : 16,
                  "certs" : [
                     {
                        "issues" : 0,
                        "notAfter" : 1495805869000,
                        "issuerLabel" : "Verizon Public SureServer EV SSL CA G14-SHA2",
                        "issuerSubject" : "CN=Verizon Public SureServer EV SSL CA G14-SHA2,OU=Cybertrust,O=Verizon Enterprise Solutions,L=Amsterdam,C=NL",
                        "keyAlg" : "RSA",
                        "subject" : "CN=sparen.leaseplanbank.de,O=LeasePlan Corporation N.V.,L=Almere,ST=Flevoland,C=NL,2.5.4.5=#13083339303337303736,1.3.6.1.4.1.311.60.2.1.3=#13024e4c,2.5.4.15=#131256312e342c20436c6175736520382e352e32",
                        "crlRevocationStatus" : 2,
                        "notBefore" : 1432647471000,
                        "keyStrength" : 4096,
                        "revocationStatus" : 2,
                        "sigAlg" : "SHA256withRSA",
                        "keySize" : 4096,
                        "label" : "sparen.leaseplanbank.de",
                        "ocspRevocationStatus" : 2,
                        "raw" : "-----BEGIN CERTIFICATE-----\nMIIG+zCCBeOgAwIBAgIURqvAHo/zRmvXNWXNTCKuBtUFiDIwDQYJKoZIhvcNAQELBQAwgZQxCzAJ\r\nBgNVBAYTAk5MMRIwEAYDVQQHEwlBbXN0ZXJkYW0xJTAjBgNVBAoTHFZlcml6b24gRW50ZXJwcmlz\r\nZSBTb2x1dGlvbnMxEzARBgNVBAsTCkN5YmVydHJ1c3QxNTAzBgNVBAMTLFZlcml6b24gUHVibGlj\r\nIFN1cmVTZXJ2ZXIgRVYgU1NMIENBIEcxNC1TSEEyMB4XDTE1MDUyNjEzMzc1MVoXDTE3MDUyNjEz\r\nMzc0OVowgb4xGzAZBgNVBA8TElYxLjQsIENsYXVzZSA4LjUuMjETMBEGCysGAQQBgjc8AgEDEwJO\r\nTDERMA8GA1UEBRMIMzkwMzcwNzYxCzAJBgNVBAYTAk5MMRIwEAYDVQQIEwlGbGV2b2xhbmQxDzAN\r\nBgNVBAcTBkFsbWVyZTEjMCEGA1UEChMaTGVhc2VQbGFuIENvcnBvcmF0aW9uIE4uVi4xIDAeBgNV\r\nBAMTF3NwYXJlbi5sZWFzZXBsYW5iYW5rLmRlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC\r\nAgEA7FHds4TBHqHJw7yZneKQ6r9MbsEJah131cMvE6hGK0RzFBat6Zs1P8V33XhYHnXen3ufc4gf\r\nU5xOZ5J0e6pD1N9HA2/mEUuJT3RYh0/ftRn6EmMl0OH5RG96eseUd3MfIGat/BL31PGMxk9szYLg\r\ny2j2uRB7l+29QPc4uXVN5lYVUUhZkSqnHUVBTNGzMXC9IT/+AF9jAZ1xHEgup7Lrm2mr2rVVf7CA\r\ncf01OnyyMbuH9kBERsa5jIhbI3A6hogjioFJ963uz7O1bGv7rSPgpRbOavayx5VkW0EFT+z8wvLb\r\nG/52wzJAfUQOBJBp6AxrMdirBoWaWDrdNr6Ke7YmMOoTnqWG7M1E85PomUcT2YnGNFRBl8ijSsmE\r\ns7YzbNEhVlYDIQ1Ov94Pclmmh2fR33PCW9FkoNxbaAp5knhAFHEEecqJzkBkmla6dPz+sQjxnFkt\r\nvN7vq6A+/F/J0Nu6Bp6PzUEy+jqYA/KmPooMR2unIDY5lSoS8kr3ao7UH0Rm8BjLjTeW7nFpQVZl\r\nNFl7P3fB8UiV8HtmipQ7HgOQ3W0K+Cm9x7zgyfZ4YniHadF+an3WDC6ikNaZQIoH71G9COuTdp4l\r\nUQWpyPSaLqEHHoP8Joczegj98WwklhxrZ5oGudMXTd7gLIdLISnmeO8jCLDC1HElVY8yWU+YkWCo\r\nYtkCAwEAAaOCAhcwggITMAwGA1UdEwEB/wQCMAAwTQYDVR0gBEYwRDBCBgorBgEEAbE+AWQBMDQw\r\nMgYIKwYBBQUHAgEWJmh0dHBzOi8vc2VjdXJlLm9tbmlyb290LmNvbS9yZXBvc2l0b3J5MIGsBggr\r\nBgEFBQcBAQSBnzCBnDAuBggrBgEFBQcwAYYiaHR0cDovL3Zjc3NldjE0Mi5vY3NwLm9tbmlyb290\r\nLmNvbTA0BggrBgEFBQcwAoYoaHR0cDovL2NhY2VydC5vbW5pcm9vdC5jb20vdmNzc2V2MTQyLmNy\r\ndDA0BggrBgEFBQcwAoYoaHR0cDovL2NhY2VydC5vbW5pcm9vdC5jb20vdmNzc2V2MTQyLmRlcjBU\r\nBgNVHREETTBLghdzcGFyZW4ubGVhc2VwbGFuYmFuay5kZYIUd3d3LmxlYXNlcGxhbmJhbmsuZGWC\r\nGmFuZm9yZGVybi5sZWFzZXBsYW5iYW5rLmRlMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggr\r\nBgEFBQcDAQYIKwYBBQUHAwIwHwYDVR0jBBgwFoAU241k67lOmWfcfWtFM9bq5jq7newwQAYDVR0f\r\nBDkwNzA1oDOgMYYvaHR0cDovL3Zjc3NldjE0Mi5jcmwub21uaXJvb3QuY29tL3Zjc3NldjE0Mi5j\r\ncmwwHQYDVR0OBBYEFCR2u+Ly2JVQ3F1NUbx1RuxrQ1vVMA0GCSqGSIb3DQEBCwUAA4IBAQCjOoNC\r\nbnyvPVCXW6KBtAGKRBKYrIJHF+tUy1y8v9HM6pnEh2qwAN1lTuVhKiqSNFtFZvtkTCxCwAIYTKtW\r\nCRpMHEvd8ocYSci6HkFiXHI6Kmw0Yrq4ZnqsiIXGUCn7jkEpY7Oa8NpwpcfqQ8gXFffSPmmyOyM5\r\nR0J3Fgb0IaTV1S+RDarWDEvbbO+NTjv+8G6mrMLmhKZYCC8tSdrGMvI9eFFZHJS3Ax9EmKmoAPxy\r\n5aF177eE6SSl262Cn4+PqSZSZXoJo9Dr8ycO/unuUZmzAxPTwsmMhouw3BL3iD8H5HIVyY4YLPzs\r\nmWYp6Zqw4VwJ/bFJ3yaj44AHOKlcSmWQ\r\n-----END CERTIFICATE-----\n"
                     },
                     {
                        "issues" : 0,
                        "notAfter" : 1633564799000,
                        "issuerLabel" : "Cybertrust Global Root",
                        "issuerSubject" : "CN=Cybertrust Global Root,O=Cybertrust, Inc",
                        "keyAlg" : "RSA",
                        "subject" : "CN=Verizon Public SureServer EV SSL CA G14-SHA2,OU=Cybertrust,O=Verizon Enterprise Solutions,L=Amsterdam,C=NL",
                        "crlRevocationStatus" : 2,
                        "notBefore" : 1412582400000,
                        "keyStrength" : 2048,
                        "revocationStatus" : 2,
                        "sigAlg" : "SHA256withRSA",
                        "keySize" : 2048,
                        "label" : "Verizon Public SureServer EV SSL CA G14-SHA2",
                        "ocspRevocationStatus" : 2,
                        "raw" : "-----BEGIN CERTIFICATE-----\nMIIEzzCCA7egAwIBAgILBAAAAAABSOXEhcswDQYJKoZIhvcNAQELBQAwOzEYMBYGA1UEChMPQ3li\r\nZXJ0cnVzdCwgSW5jMR8wHQYDVQQDExZDeWJlcnRydXN0IEdsb2JhbCBSb290MB4XDTE0MTAwNjA4\r\nMDAwMFoXDTIxMTAwNjIzNTk1OVowgZQxCzAJBgNVBAYTAk5MMRIwEAYDVQQHEwlBbXN0ZXJkYW0x\r\nJTAjBgNVBAoTHFZlcml6b24gRW50ZXJwcmlzZSBTb2x1dGlvbnMxEzARBgNVBAsTCkN5YmVydHJ1\r\nc3QxNTAzBgNVBAMTLFZlcml6b24gUHVibGljIFN1cmVTZXJ2ZXIgRVYgU1NMIENBIEcxNC1TSEEy\r\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsA6YQJWjcUzqsYRQKaLLpuMUIT2UJKOx\r\nqivk+km6emv9pnTF6EvhbUbxapbnxVKbfi82BZha/XHmocoGytwOq8aSfgQxRkonLhHVWflTvcig\r\nyMiTfCm4L6gpNy5a6S+W569u6LvXYdE4QX1Btwsc6t/Eg8jIQqEDknEvcuJbxpb4a40Fr47ubr5/\r\nBV8clegw09or4gxA9BFJx5wR4CxwN0sXLscrVFuF8HeRvqc3af3oXoEkxKOP3dEa/nlE/vF3C+En\r\nLCUvQgLxAAM54IGOXmNq26lNIBQiSONclesbX/o6Gy/UB3o+uL8l+6VI1SXxH4C4dXxNsNOOyyDJ\r\nRBPN1wIDAQABo4IBeDCCAXQwDgYDVR0PAQH/BAQDAgHGMBIGA1UdEwEB/wQIMAYBAf8CAQAwHQYD\r\nVR0OBBYEFNuNZOu5Tpln3H1rRTPW6uY6u53sMFAGA1UdIARJMEcwRQYKKwYBBAGxPgFkATA3MDUG\r\nCCsGAQUFBwIBFilodHRwOi8vY3liZXJ0cnVzdC5vbW5pcm9vdC5jb20vcmVwb3NpdG9yeTA1BgNV\r\nHR8ELjAsMCqgKKAmhiRodHRwOi8vY3JsLm9tbmlyb290LmNvbS9jdGdsb2JhbC5jcmwwgYQGCCsG\r\nAQUFBwEBBHgwdjBDBggrBgEFBQcwAoY3aHR0cHM6Ly9jYWNlcnQub21uaXJvb3QuY29tL0N5YmVy\r\ndHJ1c3RHbG9iYWxSb290X3JzLmNydDAvBggrBgEFBQcwAYYjaHR0cDovL2N0cm9vdHNoYTIub2Nz\r\ncC5vbW5pcm9vdC5jb20wHwYDVR0jBBgwFoAUtgh7DXrMrCBMhlYyXs+rboUtcFcwDQYJKoZIhvcN\r\nAQELBQADggEBAIdh00cWEkaGNejP0Z46eI8O5mazLqdTY4LKvHdQ68gFU8MrgrTHdSDYjhPnWQgu\r\nKuFUHS5a5ax75PbKc/GRelk+/VZgLw4Uj+iZvFIGJrRV1LV0gn/WIrhDkcTgP0pgCOrpRwpnjHII\r\nr+p9qwvhfOEHj6dREftbLSbb1cKn+ojnxJi8f2puFODFWax5BlCxPYdjNLPBtEsylZ4ptU5FeyZ+\r\nlX85Yy9QaTpSRAI0bjbWYBn6jDudC/u+lUKDNjrMwWOuRHoCOPyGrLFvv5tQZFLCtn2ghqjRH0Mu\r\nI75zLLK5fnEIGeDqSNCyYv0aeosdfygtkqUwarOXommwyBIzzPg=\r\n-----END CERTIFICATE-----\n"
                     },
                     {
                        "issues" : 8,
                        "notAfter" : 1639555200000,
                        "issuerLabel" : "Cybertrust Global Root",
                        "issuerSubject" : "CN=Cybertrust Global Root,O=Cybertrust, Inc",
                        "keyAlg" : "RSA",
                        "subject" : "CN=Cybertrust Global Root,O=Cybertrust, Inc",
                        "crlRevocationStatus" : 0,
                        "notBefore" : 1166169600000,
                        "keyStrength" : 2048,
                        "revocationStatus" : 0,
                        "sigAlg" : "SHA1withRSA",
                        "keySize" : 2048,
                        "label" : "Cybertrust Global Root",
                        "ocspRevocationStatus" : 0,
                        "raw" : "-----BEGIN CERTIFICATE-----\nMIIDoTCCAomgAwIBAgILBAAAAAABD4WqLUgwDQYJKoZIhvcNAQEFBQAwOzEYMBYGA1UEChMPQ3li\r\nZXJ0cnVzdCwgSW5jMR8wHQYDVQQDExZDeWJlcnRydXN0IEdsb2JhbCBSb290MB4XDTA2MTIxNTA4\r\nMDAwMFoXDTIxMTIxNTA4MDAwMFowOzEYMBYGA1UEChMPQ3liZXJ0cnVzdCwgSW5jMR8wHQYDVQQD\r\nExZDeWJlcnRydXN0IEdsb2JhbCBSb290MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA\r\n+Mi8vRRQZhP/8NN57CPytxrHjoXxEnOmGaoQ25yiZXRadz5RfVb23CO21O1fWLE3TdVJDm71aofW\r\n0ozSJ8bi/zafmGWgE07GKmSb1ZASzxQG9Dvj1Ci+6A74q05IlG2OlTEQXO2iLb3VOm2yHLtgwEZL\r\nAfVJrn5GitB0jaEMAs7u/OePuGtm839EAL9mJRQr3RAwHQeWP032a7iPt3sMpTjr3kfb1V05/Iin\r\n89cqdPHoWqI7n1C6poxFNcJQZZXcY4Lv3b93TZxiyWNzFtApD0mpSPCzqrdsxacwOUBdrsTiXSZT\r\n8M4cIwhhqJQZugRiQOwfOHB3EgZxpzAYXSUnpQIDAQABo4GlMIGiMA4GA1UdDwEB/wQEAwIBBjAP\r\nBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBS2CHsNesysIEyGVjJez6tuhS1wVzA/BgNVHR8EODA2\r\nMDSgMqAwhi5odHRwOi8vd3d3Mi5wdWJsaWMtdHJ1c3QuY29tL2NybC9jdC9jdHJvb3QuY3JsMB8G\r\nA1UdIwQYMBaAFLYIew16zKwgTIZWMl7Pq26FLXBXMA0GCSqGSIb3DQEBBQUAA4IBAQBW7wojoFRO\r\nlZfJ+InaRcHUowAl9B8Tq7ejhVhpwjCt2BWKLePJzYFa+HMjWqd8BfP9IjsO0QbE2zZMcwSO5bAi\r\n5MXzLqXZI+O4Tkogp24CJJ8iYGd7ix1yCcUxXOl5n4BHPa2hCwcUPUf/A2kaDAtE52Mlp3+yybh2\r\nhO0j9n0Hq0V+09+zv+mKts2oomcrUtW3ZfA5TGOgkXmTUg9U3YO7n9GPp1Nzw8v/MOx8BLjYRB+T\r\nX3EJIrduPuocA06dGiBh+4E37F78CkWr1+cXVdCg6mCbpvbjjFspwgZgFJ0tl0ypkxWdYcQBX0jW\r\nWL1WMRJOEcgh4LMRkWXbtKaIOM5V\r\n-----END CERTIFICATE-----\n"
                     }
                  ]
               },
               "poodle" : false,
               "supportsRc4" : false,
               "sessionResumption" : 2,
               "sessionTickets" : 0,
               "suites" : {
                  "preference" : true,
                  "list" : [
                     {
                        "name" : "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
                        "ecdhStrength" : 3072,
                        "id" : 49200,
                        "ecdhBits" : 256,
                        "cipherStrength" : 256
                     },
                     {
                        "name" : "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384",
                        "ecdhStrength" : 3072,
                        "id" : 49192,
                        "ecdhBits" : 256,
                        "cipherStrength" : 256
                     },
                     {
                        "name" : "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
                        "ecdhStrength" : 3072,
                        "id" : 49172,
                        "ecdhBits" : 256,
                        "cipherStrength" : 256
                     }
                  ]
               },
               "rc4WithModern" : false,
               "prefixDelegation" : true,
               "sims" : {
                  "results" : [
                     {
                        "attempts" : 1,
                        "client" : {
                           "version" : "2.3.7",
                           "isReference" : false,
                           "name" : "Android",
                           "id" : 56
                        },
                        "errorCode" : 1
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 769,
                        "suiteId" : 49172,
                        "client" : {
                           "version" : "4.0.4",
                           "isReference" : false,
                           "name" : "Android",
                           "id" : 58
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 769,
                        "suiteId" : 49172,
                        "client" : {
                           "version" : "4.1.1",
                           "isReference" : false,
                           "name" : "Android",
                           "id" : 59
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 769,
                        "suiteId" : 49172,
                        "client" : {
                           "version" : "4.2.2",
                           "isReference" : false,
                           "name" : "Android",
                           "id" : 60
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 769,
                        "suiteId" : 49172,
                        "client" : {
                           "version" : "4.3",
                           "isReference" : false,
                           "name" : "Android",
                           "id" : 61
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49200,
                        "client" : {
                           "version" : "4.4.2",
                           "isReference" : false,
                           "name" : "Android",
                           "id" : 62
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49172,
                        "client" : {
                           "version" : "5.0.0",
                           "isReference" : false,
                           "name" : "Android",
                           "id" : 88
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 769,
                        "suiteId" : 49172,
                        "client" : {
                           "version" : "Jan 2015",
                           "isReference" : false,
                           "name" : "Baidu",
                           "id" : 94
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49200,
                        "client" : {
                           "version" : "Jan 2015",
                           "isReference" : false,
                           "name" : "BingPreview",
                           "id" : 91
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49172,
                        "client" : {
                           "version" : "43",
                           "isReference" : true,
                           "name" : "Chrome",
                           "id" : 108,
                           "platform" : "OS X"
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49172,
                        "client" : {
                           "version" : "31.3.0 ESR",
                           "isReference" : false,
                           "name" : "Firefox",
                           "id" : 84,
                           "platform" : "Win 7"
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49172,
                        "client" : {
                           "version" : "39",
                           "isReference" : true,
                           "name" : "Firefox",
                           "id" : 109,
                           "platform" : "OS X"
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49172,
                        "client" : {
                           "version" : "Feb 2015",
                           "isReference" : false,
                           "name" : "Googlebot",
                           "id" : 97
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "client" : {
                           "version" : "6",
                           "isReference" : false,
                           "name" : "IE",
                           "id" : 100,
                           "platform" : "XP"
                        },
                        "errorCode" : 1
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 769,
                        "suiteId" : 49172,
                        "client" : {
                           "version" : "7",
                           "isReference" : false,
                           "name" : "IE",
                           "id" : 19,
                           "platform" : "Vista"
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "client" : {
                           "version" : "8",
                           "isReference" : false,
                           "name" : "IE",
                           "id" : 101,
                           "platform" : "XP"
                        },
                        "errorCode" : 1
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 769,
                        "suiteId" : 49172,
                        "client" : {
                           "version" : "8-10",
                           "isReference" : true,
                           "name" : "IE",
                           "id" : 23,
                           "platform" : "Win 7"
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49192,
                        "client" : {
                           "version" : "11",
                           "isReference" : true,
                           "name" : "IE",
                           "id" : 102,
                           "platform" : "Win 7"
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49192,
                        "client" : {
                           "version" : "11",
                           "isReference" : true,
                           "name" : "IE",
                           "id" : 104,
                           "platform" : "Win 8.1"
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 769,
                        "suiteId" : 49172,
                        "client" : {
                           "version" : "10",
                           "isReference" : false,
                           "name" : "IE",
                           "id" : 64,
                           "platform" : "Win Phone 8.0"
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49172,
                        "client" : {
                           "version" : "11",
                           "isReference" : true,
                           "name" : "IE",
                           "id" : 65,
                           "platform" : "Win Phone 8.1"
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49192,
                        "client" : {
                           "version" : "11",
                           "isReference" : true,
                           "name" : "IE",
                           "id" : 106,
                           "platform" : "Win Phone 8.1 Update"
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49200,
                        "client" : {
                           "version" : "12",
                           "isReference" : true,
                           "name" : "Edge",
                           "id" : 107,
                           "platform" : "Win 10 (Build 10130)"
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "client" : {
                           "version" : "6u45",
                           "isReference" : false,
                           "name" : "Java",
                           "id" : 25
                        },
                        "errorCode" : 1
                     },
                     {
                        "attempts" : 1,
                        "client" : {
                           "version" : "7u25",
                           "isReference" : false,
                           "name" : "Java",
                           "id" : 26
                        },
                        "errorCode" : 1
                     },
                     {
                        "attempts" : 1,
                        "client" : {
                           "version" : "8u31",
                           "isReference" : false,
                           "name" : "Java",
                           "id" : 86
                        },
                        "errorCode" : 1
                     },
                     {
                        "attempts" : 1,
                        "client" : {
                           "version" : "0.9.8y",
                           "isReference" : false,
                           "name" : "OpenSSL",
                           "id" : 27
                        },
                        "errorCode" : 1
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49200,
                        "client" : {
                           "version" : "1.0.1l",
                           "isReference" : true,
                           "name" : "OpenSSL",
                           "id" : 99
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49200,
                        "client" : {
                           "version" : "1.0.2",
                           "isReference" : true,
                           "name" : "OpenSSL",
                           "id" : 98
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 769,
                        "suiteId" : 49172,
                        "client" : {
                           "version" : "5.1.9",
                           "isReference" : false,
                           "name" : "Safari",
                           "id" : 32,
                           "platform" : "OS X 10.6.8"
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49192,
                        "client" : {
                           "version" : "6",
                           "isReference" : true,
                           "name" : "Safari",
                           "id" : 33,
                           "platform" : "iOS 6.0.1"
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 769,
                        "suiteId" : 49172,
                        "client" : {
                           "version" : "6.0.4",
                           "isReference" : true,
                           "name" : "Safari",
                           "id" : 34,
                           "platform" : "OS X 10.8.4"
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49192,
                        "client" : {
                           "version" : "7",
                           "isReference" : true,
                           "name" : "Safari",
                           "id" : 63,
                           "platform" : "iOS 7.1"
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49192,
                        "client" : {
                           "version" : "7",
                           "isReference" : true,
                           "name" : "Safari",
                           "id" : 35,
                           "platform" : "OS X 10.9"
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49192,
                        "client" : {
                           "version" : "8",
                           "isReference" : true,
                           "name" : "Safari",
                           "id" : 85,
                           "platform" : "iOS 8.4"
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49192,
                        "client" : {
                           "version" : "8",
                           "isReference" : true,
                           "name" : "Safari",
                           "id" : 87,
                           "platform" : "OS X 10.10"
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49200,
                        "client" : {
                           "version" : "Jan 2015",
                           "isReference" : false,
                           "name" : "Yahoo Slurp",
                           "id" : 92
                        },
                        "errorCode" : 0
                     },
                     {
                        "attempts" : 1,
                        "protocolId" : 771,
                        "suiteId" : 49200,
                        "client" : {
                           "version" : "Jan 2015",
                           "isReference" : false,
                           "name" : "YandexBot",
                           "id" : 93
                        },
                        "errorCode" : 0
                     }
                  ]
               },
               "ocspStapling" : false,
               "heartbleed" : false,
               "fallbackScsv" : true,
               "supportsNpn" : false,
               "renegSupport" : 2,
               "openSslCcs" : 1,
               "cert" : {
                  "issues" : 0,
                  "notAfter" : 1495805869000,
                  "issuerSubject" : "CN=Verizon Public SureServer EV SSL CA G14-SHA2,OU=Cybertrust,O=Verizon Enterprise Solutions,L=Amsterdam,C=NL",
                  "crlURIs" : [
                     "http://vcssev142.crl.omniroot.com/vcssev142.crl"
                  ],
                  "notBefore" : 1432647471000,
                  "revocationInfo" : 3,
                  "altNames" : [
                     "sparen.leaseplanbank.de",
                     "www.leaseplanbank.de",
                     "anfordern.leaseplanbank.de"
                  ],
                  "ocspURIs" : [
                     "http://vcssev142.ocsp.omniroot.com"
                  ],
                  "issuerLabel" : "Verizon Public SureServer EV SSL CA G14-SHA2",
                  "crlRevocationStatus" : 2,
                  "subject" : "CN=sparen.leaseplanbank.de,O=LeasePlan Corporation N.V.,L=Almere,ST=Flevoland,C=NL,2.5.4.5=#13083339303337303736,1.3.6.1.4.1.311.60.2.1.3=#13024e4c,2.5.4.15=#131256312e342c20436c6175736520382e352e32",
                  "sgc" : 0,
                  "revocationStatus" : 2,
                  "sigAlg" : "SHA256withRSA",
                  "validationType" : "E",
                  "sct" : false,
                  "commonNames" : [
                     "sparen.leaseplanbank.de"
                  ],
                  "ocspRevocationStatus" : 2
               },
               "poodleTls" : -3,
               "forwardSecrecy" : 4,
               "logjam" : false,
               "freak" : false,
               "protocols" : [
                  {
                     "id" : 769,
                     "version" : "1.0",
                     "name" : "TLS"
                  },
                  {
                     "id" : 770,
                     "version" : "1.1",
                     "name" : "TLS"
                  },
                  {
                     "id" : 771,
                     "version" : "1.2",
                     "name" : "TLS"
                  }
               ],
               "heartbeat" : false
            },
            "eta" : 2,
            "statusMessage" : "Ready",
            "delegation" : 2,
            "isExceptional" : false
         }
      ],
      "testTime" : 1440583339221,
      "startTime" : 1440583216386,
      "engineVersion" : "1.19.33",
      "isPublic" : false,
      "criteriaVersion" : "2009j"
   }
---8X-----------------

**Comment by ivanr** [comment]
There's no bug here. If the endpoint statusMessage field is not Ready, the data is going to be incomplete in one way or another, depending on the progress of the scan.

**Comment by seccubus** [comment]
I started fetching the result, because the general status for www.leaseplanbank.de is "READY":


     "www.leaseplanbank.de" : {
        "protocol" : "HTTP",
        "status" : "READY",
        "port" : 443,

Are you saying that API clients till need to test the status of all the underlying endpoints?

**Comment by ivanr** [comment]
Yes, because individual endpoints can fail (e.g., if there is no server response).

**Comment by seccubus** [comment]
However, in this case there is no error on the endpoints. One of the endpoint assessments is still running yet the overall status is set to ready. To me that is odd.

Given this paragraph from the api docs:

  1.  The assessment is now in progress. Call analyze periodically (without the startNewparameter!) until the assessment is finished. You can tell by observing the Host.statusfield for either READY or ERROR values.

I assumed the ready state meant that I could stop polling the api and read and interpret the results.

If I need to  check the endpoint status as well, then what value of statusMessage or statusDetail should I be looking for. This is not very clear to me from the documentation.

Could running an assessment of www.leaseplanbank.de<http://www.leaseplanbank.de> and leaseplanbank.de<http://leaseplanbank.de> at the same time cause some sort of racecondition?

**Comment by ivanr** [comment]
I think the API would benefit from having another field to indicate endpoint status. At this time, you can tell that endpoint assessment is complete by looking at statusDetailsMessage, when it says "Ready". I also think progress is always 100 in this case. Having a "status" field with values "READY" or "ERROR" would make it easier to handle.

**Comment by ivanr** [comment]
For now, I've updated the API docs to indicate that statusMessage is Ready on a successful endpoint assessment.
