### ISSUE TITLE
Test example.com without the www

### ISSUE THREAD

**Issue by HLFH** [ssllabs/ssllabs-scan#207]
Hi,

IMHO, this is a big issue: https://community.qualys.com/thread/15208

SSL Labs should be able to test example.com without the www.

Thanks in advance,

**Comment by ivanr** [comment]
I think what will happen is that SSL Labs will continue to test both variants, but change the behaviour slightly so that both are tested even when there is only one IP address behind. In the meantime, removing the undesired variant can be used as a workaround.

**Comment by ivanr** [comment]
Fixed in 1.22.2, now running on dev. More refinements will follow.
