### ISSUE TITLE
Enhancement: Apple App Transport Security compatibility

### ISSUE THREAD

**Issue by kozmic** [ssllabs/ssllabs-scan#208]
With iOS 9 and OSX 10.11, Apple will be stricter of what sertificates it accepts out of the box through App Transport Security [1]. It would be nice if your service could show a flag showing if the server is comptaible with these new requirements or not. Is this within the scope of this service?

[1] https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/

**Comment by selecadm** [comment]
Before submitting an issue, please check the development server.

https://dev.ssllabs.com/ssltest/viewClient.html?name=Safari&version=9&platform=OS%20X%2010.11
https://dev.ssllabs.com/ssltest/viewClient.html?name=Apple%20ATS&version=9&platform=iOS

Handshake simulation for Apple ATS already takes new requirements into account:

Failure on SHA1 certificate
https://dev.ssllabs.com/ssltest/analyze.html?d=t.co&s=199.16.156.75&hideResults=on
> Apple ATS 9 / iOS  R	Client requires SHA2 certificate signatures	Fail3

Failure on 1024-bit certificate
https://dev.ssllabs.com/ssltest/analyze.html?d=ww1.emu.edu.tr&hideResults=on
> Apple ATS 9 / iOS  R	Client does not support RSA keys < 2048 bits	Fail3

**Comment by kozmic** [comment]
Sorry, I didnt know about the dev-server. Verified that it's already implemented on the development server, so closing issue. Great work you guys do! :)
