### ISSUE TITLE
CBC is shown as used for BEAST mitigation

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#209]
https://www.ssllabs.com/ssltest/analyze.html?d=pcrws.centralbank.gov.af

> Suites used only for BEAST mitigation (TLS 1.0 and earlier)
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)	256

Despite the fact that BEAST exists because of CBC flaws.

Previously reported here: https://github.com/ssllabs/ssllabs-scan/issues/148

**Comment by ivanr** [comment]
I couldn't see that text on the site you mention, but I improved the language anyway.
