### ISSUE TITLE
Trying to scan a host that was requestet to not scan break API

### ISSUE THREAD

**Issue by J0WI** [ssllabs/ssllabs-scan#211]
If you try to scan a host, that was requested to not test it, breaks the API.
You will never get a response and the script will never end.
If you call the URL directly, you get: ```{"errors":[]}```

I expect the same result as in the web interface, a message like "The owner of this site requested that we do not test it", but replacing "we" with "Qualys SSL Labs" or similar. Otherwise it would be confusing, if you publish the results on a third party website.

**Comment by ivanr** [comment]
Fixed in 1.20.11 (will be deployed to dev soon).

**Comment by J0WI** [comment]
The Test UI on https://dev.ssllabs.com/ssltest/ is now broken if you try to test an URL that resolves on localhost.

**Comment by selecadm** [comment]
Can't see any difference.

> Assessment failed: IP address is from private address space (RFC 1918)

**Comment by J0WI** [comment]
seems to be fixed now
