### ISSUE TITLE
iOS 9 simulation correct ?

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#212]
https://dev.ssllabs.com/ssltest/viewClient.html?name=Apple%20ATS&version=9&platform=iOS%209

iOS 9 Simulation on DEV Shows that iOS 9 only supports TLS 1.2 and only ECDHE.
Is this correct ?

**Comment by selecadm** [comment]
This is a simulation for App Transport Security, not Safari.

For Safari this should be the same or at least similar: https://dev.ssllabs.com/ssltest/viewClient.html?name=Safari&version=9&platform=OS%20X%2010.11

**Comment by RobTho** [comment]
oh, got it
