### ISSUE TITLE
Incorrect Key Exchange score when offering DHE and ECDHE

### ISSUE THREAD

**Issue by TheWolfH** [ssllabs/ssllabs-scan#213]
When a server uses a 4096-bit RSA certificate and offers both DHE (4096-bit DH parameters) and ECDHE key exchange (256-bit ECDH parameters), it is awarded a perfect 100% score for its key exchange.
However, 256-bit ECDH is believed to be equivalent to 3072-bit RSA, which - according to the Server Rating guide - should be awarded a score of 90%.
Actually, I think the current score of 100% should be kept for this kind of setup, as it reflects the current recommendations for up-to-date TLS security. However, maybe the Server Rating guide should be updated to include the standards used for assessing ECDHE key exchanges (currently, there is no mention of such standards, just for DH(E)).

Example website conforming to the mentioned configuration: https://www.ssllabs.com/ssltest/analyze.html?d=bulldog-hosting.de

**Comment by selecadm** [comment]
256-bit ECC certificates get 90% key exchange, >= 384-bit — 100%.

Numeric grades on the right have already been deleted from the development server. You just shouldn't use them for measuring TLS configuration security.

https://dev.ssllabs.com/ssltest/analyze.html?d=bulldog-hosting.de&hideResults=on
![image](https://cloud.githubusercontent.com/assets/10382329/9836565/fa40f5f8-5a26-11e5-9c30-b4761ba2f352.png)

**Comment by TheWolfH** [comment]
I'm not talking about certificates, but about ECDH parameters. If you use 256-bit ECDH parameters, you are (inconsistently with the Server Rating guide) awarded the full score.
Also, the 100% can still be seen by looking at how far the bar reaches. So if the numeric values are to be deleted (I have no problem with that), the whole diagram right to the total grade should be removed.

**Comment by selecadm** [comment]
Yes, ECDH curves just aren't taken into account. As long as it's >= 256-bit, it's not that important as DH parameters.
> the whole diagram right to the total grade should be removed
You are right. Will probably be completely deleted soon.

**Comment by ivanr** [comment]
Fixed, not yet deployed. I like the categories because they make it easier to understand where problems are. So we may keep them in the future in some shape, but the numbers are definitely going away.
