### ISSUE TITLE
newAssessmentCoolOff  vs maxAssessments 

### ISSUE THREAD

**Issue by wsw70** [ssllabs/ssllabs-scan#214]
I would like to start up to `maxAssessments` in parallel (each of the threads would assess a site and pick a a new one once the previous one is done).

How does this work with `newAssessmentCoolOff`? When launching my scans for the threads, it is not easy to enforce the `newAssessmentCoolOff` limitation and even so, it breaks the ability of scanning in parallel (which is controlled by `maxAssessments`).

How should these two limits work together?

**Comment by ivanr** [comment]
Just before you create a new thread, check that enough time passed since the last thread you created. If it hasn't, pause for a while, then continue.

**Comment by wsw70** [comment]
Well in that case I do not understand why having `maxAssessments`? This suggests that I can have several scans running in parallel. With `newAssessmentCoolOff`being 1000 seconds (~20 min) and an assessment lasting 2-5 min - if I enforce `newAssessmentCoolOff` I will have mostly idle loops, with practically no chance for parallel scans. 

Since `maxAssessments` is 20 or 30 I belive I am missing something in how the API should be accessed ([Protocol Usage](https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs.md#protocol-usage) does not mention the cool off).

**Comment by seccubus** [comment]
newAssessmentCoolOff is measured in milliseconds, not seconds.

**Comment by wsw70** [comment]
Ahhhh, thank you - in that case it does indeed makes sense :)

**Comment by seccubus** [comment]
Fwiw: I allways sleep newAssessmentCoolOff milliseconds before starting a new scan. I'm not too bothered about sleeping 1000 milliseconds too much.

**Comment by ivanr** [comment]
Sorry, I omitted to document the cool-off unit. It is milliseconds. I'll update the docs now.

**Comment by LordMike** [comment]
@ivanr: remember to document this one :)

**Comment by ivanr** [comment]
Already did it: https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs.md
