### ISSUE TITLE
Not seeing new fields of 1.19.33

### ISSUE THREAD

**Issue by LordMike** [ssllabs/ssllabs-scan#215]
Hi,

I'm not seeing the new fields: 
* dhPrimes
* dhUsesKnownPrimes
* dhYsReuse

.. on reports claiming to be analyzed with: `engineVersion=1.19.33`. Such as here:
https://api.ssllabs.com/api/v2/analyze?host=facebook.com&fromCache=on&all=done

Is this intentional?

I am seeing the `logjam` field, so not all is missing.

**Comment by ivanr** [comment]
You're not seeing them because the server doesn't support DHE at all. I think "null" is the correct answer in this case. Maybe you could use another field along the lines of "dhSupported"?

**Comment by LordMike** [comment]
I'm unsure if it would make sense to have a field purely to tell if another field is present, given that if the other field isn't present it's self-explanatory.

Perhaps just writing in the docs that the fields are absent when not applicable.

**Comment by ivanr** [comment]
Done.
