### ISSUE TITLE
[DEVELOPMENT REGRESSION] Explicitly disabled HSTS is "Unknown" again and again (21 September 2015)

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#217]
@ivanr, every time you mess with HSTS, you break "max-age=0" treatment.

![image](https://cloud.githubusercontent.com/assets/10382329/9993683/a8f4cb1e-6081-11e5-8866-7130c31ed1f9.png)

**Comment by ivanr** [comment]
Sorry, but you're always going to get those on the development server. I haven't finished messing with HSTS yet, but I might tomorrow.

**Comment by ivanr** [comment]
This should be fixed in 1.20.20. Please reopen if it isn't. Thanks!
