### ISSUE TITLE
To use real random ClientHello.Random

### ISSUE THREAD

**Issue by bolano** [ssllabs/ssllabs-scan#218]
Hi,
 
We found in SSL server test, the ClientHello.Random is set to all-zero. Using all-zero ClientHello.Random is a known feature of sslsqueeze(sslsqueeze/sslsqueeze.c at master · mmgaggle/sslsqueeze · GitHub), a famous SSL attacking tool. Thus, our server filters ClientHello whose random is all-zero. Unfortunately, the SSL server test says our server doesn't support HTTPS.

So, would you please use a real random "ClientHello.Random" in the test?
 
Best regards,
Guang

**Comment by ivanr** [comment]
Done and deployed on dev.ssllabs.com. Assessment of the server you gave to me succeeded.
