### ISSUE TITLE
API need support for domain name associated specific IP

### ISSUE THREAD

**Issue by zen2** [ssllabs/ssllabs-scan#219]
When you use a proxy or a CDN you want to to test SSL on a specific IP that handle a HTTP/HTTPS domain name. This specific IP is reffered as origin server and can host an SSL domain while the DNS of this domain do'nt reffer to this server but reffer to the CDN or the proxy.

A request is effective in two steps if object is not in cache:
     www.mydomain.com =(CNAME)=> CDN/PROXY
    CDN/PROXY => origin.mydomain.com =(A or CNAME)=> ORIGIN-SERVER

So an option to specify an IP (or an FQDN to resolve) would be really usefull.

**Comment by LordMike** [comment]
It'd probably open up for more issues than benefits. You could instead create a new subdomain name, pointing to the "new" IP, and then check that (ignoring any name mismatch errors along the way).

Wouldn't that work?

**Comment by seccubus** [comment]
No, it wouldn;t work.

You sometimes want to check if the TLS config is OK before you put something life, this is currently not possible.

Frank Breedijk, Security Officer, Schuberg Philis, M: +31 (0)6 438 22 637

From: Michael Bisbjerg
Reply-To: ssllabs/ssllabs-scan
Date: Thursday 24 September 2015 11:54
To: ssllabs/ssllabs-scan
Subject: Re: [ssllabs-scan] API need support for domain name associated specific IP (#219)


It'd probably open up for more issues than benefits. You could instead create a new subdomain name, pointing to the "new" IP, and then check that (ignoring any name mismatch errors along the way).

Wouldn't that work?

**Comment by fishouttah20** [comment]
Check out testssl.sh, rbsec\sslcan and cipherscan, all here on github if you need internal scanning capabilities.

**Comment by seccubus** [comment]
We do use those as well, but they have a disadvantage over ssllabs. 

* They don't grade our setup, journalists and end customers do, using ssllabs. 
* They require us to keep them up to date and sometimes they lag behind, Ivan and thus SslLabs is very up to date and usually gives us the latest results and insights. 
* simply are not as feature rich as ssl labs

They have a benefit over ssllabs: results are much easier to interpret then the somewhat cryptic results of the ssllabs api

**Comment by zen2** [comment]
The main problem to use other tools is that you can't compare it directly.
Main purpose to compare SSL at origin level or CDN level is to check about specific errors that can be issued depending if objects is in cache or not.

So en ip/fqdn option would be really usefull.

I think there is people that could use it on prepoduction or hidden production servers too.

**Comment by ghusk** [comment]
A little late to the thread but this is a feature I need.

I would have to second this request.  I'm currently trying to test a new load balancer configuration before go live and so I want to test the production domain names spoofed to IPs on the test vips

**Comment by LordMike** [comment]
@ghusk, you can use http://xip.io/. You won't get the certificate name
matched up, but it'll give you the rest of the analysis data.

Mvh.
Michael

**Comment by ghusk** [comment]
Thanks I’ll take a look, yesterday I used  rbsec/sslscan as it ran off my local hosts file but I’d appreciate a better method.

Gareth

**Comment by ivanr** [comment]
Sorry, there are currently no plans to support testing based on IP address.
