### ISSUE TITLE
Certificate not checked against HPKP header

### ISSUE THREAD

**Issue by LordMike** [ssllabs/ssllabs-scan#220]
I'm playing around with HPKP right now. Am I correct in observing, that when the certificate used is not in the HPKP's "pins" list, Ssllabs won't notify the user?

In such case, it should be presented as a warning or an error. You could help the user a little as well by presenting them their SPKI hash for use in the header :).

**Comment by selecadm** [comment]
https://dev.ssllabs.com/ssltest/analyze.html?d=er.ru&hideResults=on

> Invalid or incomplete HPKP information supplied. More information available below.

> Subject	*.er.ru
Fingerprint SHA1: e4e8e5b4826c5748da4d564c78193e7ce2b404e9
Pin SHA256: l65DLk35++ICAyHtzj+thE3CtTjjvaKhc26+Ns+hbhI=

> RapidSSL SHA256 CA - G3
Fingerprint SHA1: 0e34141846e7423d37f20dc0ab06c9bbd843dc24
Pin SHA256: 6X0iNAQtPIjXKEVcqZBwyMcRwq1yW60549axatu3oDE=

> In trust store	GeoTrust Global CA   Self-signed	
Fingerprint SHA1: de28f4a4ffe5b92fa3c503d1a349a7f9962a8212
Pin SHA256: h6801m+z8v3zbgkRHpq6L29Esgfzhj89C1SyUCOQmqU=

> Public Key Pinning (HPKP)	Incomplete   No pins matched
pin-sha256="HXXQgxueCIU5TTLHob/bPbwcKOKw6DkfsTWYHbxbqTY="; max-age=86400

**Comment by LordMike** [comment]
Was this check present already?
Or just on dev?

-----Original Message-----

**Comment by selecadm** [comment]
Implemented on the development: https://github.com/ssllabs/ssllabs-scan/issues/69#issuecomment-141944397
