### ISSUE TITLE
[DEVELOPMENT] Automatic hideResults doesn't always work

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#221]
Took this on 25 September 2015, 11:07 UTC

![image](https://cloud.githubusercontent.com/assets/10382329/10118139/2037589a-6479-11e5-8118-f16884f26c4f.png)

Having your site in recent results alone is a bigger issue than having it among many others on production.

**Comment by selecadm** [comment]
Another one:

![image](https://cloud.githubusercontent.com/assets/10382329/10441547/c70f7e5a-7152-11e5-8b50-402b00dfe442.png)

**Comment by ivanr** [comment]
That's probably not a bug as such. Looking at the code, I think someone used the API and explicitly set publish to true (the default is false).
