### ISSUE TITLE
ECDHE suite is shown to be used in SSL3

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#222]
https://www.ssllabs.com/ssltest/analyze.html?d=google.com
https://dev.ssllabs.com/ssltest/analyze.html?d=google.com

This is normal:
> IE 6 / XP   No FS 1	  No SNI 2	SSL 3	TLS_RSA_WITH_RC4_128_SHA (0x5)   No FS   RC4	128

This isn't:
> BEAST attack	Mitigated server-side (more info)   SSL 3: 0xc011, TLS 1.0: 0xc011

> TLS_ECDHE_RSA_WITH_RC4_128_SHA (0xc011)   WEAK	128

Clients supporting SSL3 max and servers responding are unlikely to support ECDHE.

**Comment by ivanr** [comment]
Possibly, but since BEAST detection is not really relevant any more, I am going to leave it as is.
