### ISSUE TITLE
Reflect Chrome's "modern" vs "obsolete" cipher suite dichotomy in the scan results.

### ISSUE THREAD

**Issue by terryburton** [ssllabs/ssllabs-scan#223]
Chrome displays a message regarding the use of obsolete ciphers unless an AEAD cipher with PFS key exchange under TLS 1.2 is provided in the cipher suite.

Perhaps the scan results should cap the grade below an "A" (perhaps at "A-") in such circumstances?

References:

https://code.google.com/p/chromium/codesearch#chromium/src/chrome/browser/ui/website_settings/website_settings.cc&l=527
https://code.google.com/p/chromium/codesearch#chromium/src/net/ssl/ssl_cipher_suite_names.cc&sq=package:chromium&type=cs&l=364

**Comment by selecadm** [comment]
Duplicate: https://github.com/ssllabs/ssllabs-scan/issues/186
