### ISSUE TITLE
False warning about certificate name mismatch?

### ISSUE THREAD

**Issue by martinsuchan** [ssllabs/ssllabs-scan#224]
See here:
https://www.ssllabs.com/ssltest/analyze.html?d=penezenka.seznam.cz&s=77.75.76.99&hideResults=on
Same happens on dev now.

![capture](https://cloud.githubusercontent.com/assets/3041397/10215960/05691bd8-6826-11e5-9c33-0d2940358006.PNG)

It shows that there is name mismatch, but I cannot see any mismatch there. Also when I click "ignore the mismatch", the result succeeds without any warnings.

**Comment by selecadm** [comment]
On DNS level 77.75.76.99 serves WWW subdomain, but the certificate isn't valid for WWW. This is what SSL Labs didn't even try to tell.

**Comment by martinsuchan** [comment]
So the problem is both in DNS server, that serves unwanted www subdomain, and ssllabs test, that does not show detail of this problem.
Can the ssllabs test be fixed to show the actual detail of this problem?

**Comment by ivanr** [comment]
I plan to fix this soon, but there's at least one ticket for it. Closing this one.

**Comment by ivanr** [comment]
Fixed in 1.22.2, now running on dev. More refinements will follow.
