### ISSUE TITLE
"The SHAppening" 

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#233]
maybe consider to lower Rating when SHA-1 ?
https://sites.google.com/site/itstheshappening/

**Comment by selecadm** [comment]
Grading changes aren't discussed here. Please use Qualys Community and Twitter.

I would suggest exact changes here if it was the right place.

**Comment by RobTho** [comment]
ok than let's say due tue SHA-1 normally can be "upgraded" for free to SHA-2 and even outdated OS like XP can Support SHA-2 there should be no real excuse to stay on SHA-1 and SHA-1 pages should get max B or maybe C rating.

**Comment by selecadm** [comment]
Only after 1 January 2016.

Sites without dual certificates setups continue to serve RSA SHA1 certs even to ECDSA-compatible clients. Companies continue to obtain SHA1 certificates even today, they just ask CAs to use notAfter date 31 December 2015 23:59:59 UTC or earlier.
Sites on CDN also use SHA1 certs from Comodo and GlobalSign not valid in 2016 and rightfully
receive no warnings.

**Comment by ivanr** [comment]
A site is not insecure if it uses SHA1. The problem with SHA1 is if a CA is attacked during issuance. Thus, any downgrades of SHA1 would only server as an early warning so that sites can prepare for the impeding turning off in 2016 (at the end or earlier).
