### ISSUE TITLE
DH for Chrome 45 not taken into account

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#234]
Sorry, forgot to do my job: https://github.com/ssllabs/ssllabs-scan/issues/128#issuecomment-114792796

https://dev.ssllabs.com/ssltest/analyze.html?d=dh768.serverhello.com&hideResults=on

> Chrome 45 / OS X  R	TLS 1.2	TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x9e)   FS	128

**Comment by ivanr** [comment]
Fixed, not yet deployed. Thanks!
