### ISSUE TITLE
Reflect the fact GCM is better than CBC

### ISSUE THREAD

**Issue by smunaut** [ssllabs/ssllabs-scan#238]
If you force only support for 256 bit ciphers, you can get a 100 score for "Cipher Strength".
However for pretty much all browsers, this means that it'll work but only in CBC mode.

But GCM mode is better. Actually AES 128 GCM is considered better than AES 256 CBC ... so to make sure my clients can use the best encryption, I had to willingly diminish the score to '90' because I now allow 128 bits if GCM mode is used.

I'd say the cipher strength scoring should take mode into account and consider AES 128 GCM at least as good as AES 256 CBC.

**Comment by selecadm** [comment]
I can't even count how many times this was suggested.

> However for pretty much all browsers, this means that it'll work but only in CBC mode.

If you use ECC certificate and support CHACHA20_POLY1305, only Firefox and Googlebot negotiate CBC. All other GCM-capable clients support modern 256-bit encryption.

Recently I complained about wrong chain order and AES_256_CBC prioritized over AES_128_GCM. The admins' argument against fixing this is A grade on SSL Labs with zero warnings. (╯°□°）╯︵ ┻━┻

**Comment by smunaut** [comment]
Well if it's been suggested so many times, maybe there is a reason for it ...

the "and support CHACHA20_POLY1305" is a pretty big IF ...

When I support AES_256_CBC and AES_128_GCM, I can make browsers pick AES_128_GCM, that's not an issue. The main issue is that adding AES 128 GCM to the list of supported cipher effectively applies a _penalty_ to your score despite being a security _improvement_ ...

**Comment by smunaut** [comment]
Closing 5 year old issue ... no idea if this was ever implemented but if it wasn't, it will obviously never be.
