### ISSUE TITLE
Support scan of non-www domains with wildcard DNS record

### ISSUE THREAD

**Issue by HLFH** [ssllabs/ssllabs-scan#239]
Hi,

For my domain example.com, I have a wildcard DNS record. SSL Labs should be able to test example.com without the www, and even if I have potentially the "www" variant from the DNS, because of my wildcard DNS record. Nginx 301 redirect is a workaround, not a permanent fix, because I won't use www SLD at all.

SSL Decoder tool [does not have this issue](https://ssldecoder.org/).

Sources: [1#](https://community.qualys.com/message/30832#30832), [#2
](https://community.qualys.com/message/31509#31509)
Thanks in advance,
HLFH

**Comment by ivanr** [comment]
Fixed in 1.22.2, now running on dev. More refinements will follow.
