### ISSUE TITLE
Let's Encrypt + chain issues gets A+

### ISSUE THREAD

**Issue by J0WI** [ssllabs/ssllabs-scan#240]
If you issue a cert with Let's Encrypt but have chain issues on your server, you will still get an A+:

1 Sent by server foo.bar
2 **Extra download** Let's Encrypt Authority X1
3 **Extra download** **Not in trust store** ISRG Root X1 Self-signed
Grade: A+

**Comment by selecadm** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=helloworld.letsencrypt.org

> Chain issues	None

The first path is complete and trusted. The second is produced by following authorityInfoAccess.
By design.

https://github.com/ssllabs/ssllabs-scan/issues/177
> There are no chain issues reported because the first path is complete and valid. The fact that another path can be made by following AIA is not important.

**Comment by J0WI** [comment]
Okay, the UI is really bad here. I think this becomes more important now, because all Let's encrypt users will be affected and may ask themselves the same question.

**Comment by StephenBrown2** [comment]
I'm not sure that's a problem, since the grade is still A+, and it reports No issues, just warns that there are extra downloads if you take the second path.

**Comment by selecadm** [comment]
Let's Encrypt AIA now serves intermediate under root trusted by Mozilla and others, so this is even the second time there is nothing to fix here.

https://twitter.com/selecadm/status/663035333504815104
