### ISSUE TITLE
[v1.20.28] HPKP max-age=0 abuse

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#241]
https://dev.ssllabs.com/ssltest/analyze.html?d=hpkp-max-age-zero.serverhello.com&hideResults=on

HPKP and HPKP-RO disappear from the report page.

**Comment by ivanr** [comment]
Confirmed. One of the HPKP states is "disabled", but I don't handle that case in the UI currently.

**Comment by selecadm** [comment]
I thought there would be fail-safe approaches to handle situations like this. Just imagine everything being disabled, you would sing "Blank space" song by infosec pro :D.

**Comment by ivanr** [comment]
Fixed now in 1.21.0. Thanks!
