### ISSUE TITLE
SSLabs running continously 

### ISSUE THREAD

**Issue by vladimirc81** [ssllabs/ssllabs-scan#242]
Hi all,
This is server side config:

server_name www.vladimircicovic.com vladimircicovic.com ; (nginx) 

And I put to analyse instead of www.vladimircicovic.com by mistake vladimircicovic.com 
And now is currently running and does not stop it

Could you please find in process list, and kill running process bastard ? :) 

here is url that is running:

https://www.ssllabs.com/ssltest/analyze.html?d=vladimircicovic.com&latest

**Comment by ivanr** [comment]
Do you have any connection throttling on the server? On the dev site, the behaviour is different -- after a while it is no longer possible to connect to the server.

**Comment by vladimirc81** [comment]
I did stop server in process - because it was running long but - currently it is working with SSL and does nod report trough ssllab tool that there is www.vladimircicovic.com and not vladimircicovic.com SSL.

You can check simple loading page or trough tool like

http://tools.pingdom.com/fpt/#!/oBiVS/https://www.vladimircicovic.com

Not big deal - but it was long running ( i was not rl using for others just for test )

**Comment by vladimirc81** [comment]
au , sorry i have security that prevent SSLlab tools to work regular - it blocked after some times. My fault. sorry.

**Comment by ivanr** [comment]
It's possible that the throttling implementation leaves a TCP connection hanging, which is why the test is still "running". If so, I probably don't have an I/O timeout configured somewhere. I will take a look.

**Comment by ivanr** [comment]
I don't know if you did anything, but the test I initiated completed after 450.831 seconds.

**Comment by vladimirc81** [comment]
first site have weird security , second https://www.ssllabs.com/ssltest/analyze.html?d=blog.vladimircicovic.com works because it does not dont do advance security (something) but at end it works, it is server side

**Comment by ivanr** [comment]
I didn't see anything unusual in the code; the connection and read timeouts are enforced. If you want to pursue this further please use dev.ssllabs.com for testing and reopen the issue. Thanks!
