### ISSUE TITLE
Simulations should take HTTP/2 TLS requirements into account

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#243]
https://lists.cert.at/pipermail/ach/2015-November/002009.html

**Comment by ivanr** [comment]
Fixed in 1.21.3.

**Comment by selecadm** [comment]
Prod
https://www.ssllabs.com/ssltest/analyze.html?d=http2-inadequate.serverhello.com&hideResults=on

Dev
https://dev.ssllabs.com/ssltest/analyze.html?d=http2-inadequate.serverhello.com&hideResults=on

> Chrome 45 / OS X  R	Server negotiated HTTP/2 with blacklisted suite (HTTP/2 INADEQUATE_SECURITY)
TLS 1.2 > h2     TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA   EC 24	Fail3

> Firefox 41 / OS X  R	Server negotiated HTTP/2 with blacklisted suite (HTTP/2 INADEQUATE_SECURITY)
TLS 1.2 > h2     TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA   EC 24	Fail3

> IE 11 / Win 10  R	Server negotiated HTTP/2 with blacklisted suite (HTTP/2 INADEQUATE_SECURITY)
TLS 1.2 > h2     TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384   EC 24	Fail3

> Edge / Win 10  R	Server negotiated HTTP/2 with blacklisted suite (HTTP/2 INADEQUATE_SECURITY)
TLS 1.2 > h2     TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384   EC 24	Fail3

> Safari 9 / iOS 9  R	Server negotiated HTTP/2 with blacklisted suite (HTTP/2 INADEQUATE_SECURITY)
TLS 1.2 > h2     TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384   EC 24	Fail3

> Safari 9 / OS X 10.11  R	Server negotiated HTTP/2 with blacklisted suite (HTTP/2 INADEQUATE_SECURITY)
TLS 1.2 > h2     TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384   EC 24	Fail3

> Apple ATS 9 / iOS 9  R	Server negotiated HTTP/2 with blacklisted suite (HTTP/2 INADEQUATE_SECURITY)
TLS 1.2 > h2     TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384   EC 24	Fail3

What does "EC 24" mean?

**Comment by ivanr** [comment]
Re: "EC 24" I haven't finished that bit yet. It's the curve ID, I should show the name instead. I also need to show DH parameter size where applicable.
