### ISSUE TITLE
Production main page shows 1-year-old news

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#244]
https://www.ssllabs.com/

![image](https://cloud.githubusercontent.com/assets/10382329/10987626/212decae-8446-11e5-9b1a-4e3d01f2513c.png)

**Comment by StephenBrown2** [comment]
Perhaps there was a caching error?

![qualys ssl labs](https://cloud.githubusercontent.com/assets/1148665/10989316/69f41818-840b-11e5-9fbc-5a86ebfded06.png)

**Comment by ivanr** [comment]
SSL Labs code releases don't package the latest news. If you visit the SSL Labs homepage within up to 15 minutes after a new version is deployed you will see a placeholder, which is the news from last year. Fresh news items are fetched from the Community site every 15 minutes.
