### ISSUE TITLE
TLS_FALLBACK_SCSV requirement for A+

### ISSUE THREAD

**Issue by LordMike** [ssllabs/ssllabs-scan#245]
Hi,

When testing various Windows servers (which do not provide TLS_FALLBACK_SCSV), I can never really reach an A+, if I want to provide TLS 1.0-1.2 at the same time. According to Ivan, Ssllabs will only see past this as a requirement for A+, if the server only supports one protocol.

Given that the TLS_FALLBACK_SCSV feature is important mainly due to SSL 2 and 3, as fallbacks to those protocols is bad, would it be possible to look past the requirement if SSL 2 and 3 are disabled?

This way, servers with otherwise really good configurations (FS-only, TLS1.0+, OCSP stapling, HSTS, ..) can never reach A+ if they run Microsoft IIS.

**Comment by ivanr** [comment]
Hi. Yes, that's on my todo list to re-evaluate for the next scoring update. I need to check, but modern browsers don't fall back to lower protocol versions any more. (Or will stop falling back in the near future.)

**Comment by selecadm** [comment]
I wanted to suggest the same on Qualys Community because of browsers tending not to perform fallbacks instead. GitHub isn't the place to discuss SSL Labs grading changes :(. Sadness…
