### ISSUE TITLE
SSL Labs fails to construct cipher suite preferences for CloudFlare Universal SSL paid customers

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#246]
https://twitter.com/eastdakota/status/661965818264064000

Sites that use individual CloudFlare Universal SSL certificates get the following on both prod and dev:

> Cipher Suites (sorted by strength; we could not determine if the server has a preference)

**Comment by ivanr** [comment]
Please provide an example for troubleshooting.

**Comment by selecadm** [comment]
Prod
https://www.ssllabs.com/ssltest/analyze.html?d=wmcasher.ru

Dev
https://www.ssllabs.com/ssltest/analyze.html?d=wmcasher.ru

**Comment by ivanr** [comment]
I think this might be because they have started fingerprinting TLS clients and changing behaviour based on what they detect. I suspect that causes issues with SSL Labs, which is a unique client.
I am going to be changing the cipher detection code soon, perhaps that fixes this problem.

**Comment by selecadm** [comment]
Also notice that you show RSA chain instead of ECDSA for all other dual deployments I have seen so far.

**Comment by ivanr** [comment]
This seems to be working now.
