### ISSUE TITLE
Grade T not shown for site with untrusted cert

### ISSUE THREAD

**Issue by anand-bhat** [ssllabs/ssllabs-scan#248]
bobibanking.com (2001:e48:22:100a:0:0:0:11)

https://www.ssllabs.com/ssltest/analyze.html?d=www.bobibanking.com&s=2001%3ae48%3a22%3a100a%3a0%3a0%3a0%3a11&hideResults=on&ignoreMismatch=on

![image](https://cloud.githubusercontent.com/assets/7332442/11018966/63ea68ea-85b0-11e5-85c1-af9436e4dd8e.png)

![image](https://cloud.githubusercontent.com/assets/7332442/11018968/805936be-85b0-11e5-9849-3f7b74933a85.png)

![image](https://cloud.githubusercontent.com/assets/7332442/11018969/8cc5101c-85b0-11e5-9022-779c18a71ea9.png)

Shouldn't this be a T, like https://www.ssllabs.com/ssltest/analyze.html?d=sugar.pureharvest.com.au?

**Comment by selecadm** [comment]
No, if a site receives F grade, it has bigger problems than just trust. F grade because of 40-bit encryption, POODLE TLS and even 6-year-old renegotiation gap.

Also, sites with revoked certificates receive F instead of T.

> Shouldn't this be a T, like https://www.ssllabs.com/ssltest/analyze.html?d=sugar.pureharvest.com.au?

There is no intermediate sent, so it should receive T instead of B.
