### ISSUE TITLE
CAPI doesn't follow HTTPS AIA information

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#251]
CAPI doesn't follow HTTPS AIA information, is this something we need to warn about?
https://twitter.com/ericlaw/status/663706420701872128

**Comment by selecadm** [comment]
Yes.
https://twitter.com/selecadm/status/663707180269441024

Prod
https://www.ssllabs.com/ssltest/analyze.html?d=dell.com&s=143.166.135.105

Dev
https://dev.ssllabs.com/ssltest/analyze.html?d=dell.com&s=143.166.135.105

> Extra download	Verizon Public SureServer CA G14-SHA1

**Comment by ivanr** [comment]
Done in 1.22.10, now running on dev.ssllabs.com.
