### ISSUE TITLE
Always getting "the other" certificate

### ISSUE THREAD

**Issue by joydragon** [ssllabs/ssllabs-scan#254]
If you go to a IP address that responds for multiple certificates the interface always resolve for other certificate even if it recognizes the first one.
You can look at this example:
https://www.ssllabs.com/ssltest/analyze.html?d=falabella.cl
https://www.ssllabs.com/ssltest/analyze.html?d=falabella.com
Both test resolve to the same IP addresses, and the main one always get the other domain, if it's the .cl goes for the .com and vice-versa.
What can be done there?

**Comment by selecadm** [comment]
Both _falabella.cl_ and _falabella.com_ aren't configured for HTTPS. The default certificate on 200.10.171.36 is for _secure.falabella.com_
