### ISSUE TITLE
statusMessage: Unexpected failure, statusDetails: TESTING_COMPRESSION

### ISSUE THREAD

**Issue by RonnieVink** [ssllabs/ssllabs-scan#255]
While using the SSL Server Test I get an unexpected failure after accepting the certificate mismatch warning.

In the Apache access log I noticed the following request: GET / HTTP/1.0 and in the error log I noticed [error] [client 64.41.200.104] request failed: error reading the headers.
 
Right after the above mentioned failure and error message the Apache child process tends to exit. I wasn't able to reproduce the above mentioned error by using the openssl s_client, as mentioned by Ivan in another thread on this community. The result is the same in the access log, however I don't see an error in the error log as mentioned above while using the openssl s_client sending the same request.
 
I noticed the SSL Labs APIs and used it to run another scan to get some more information regarding the unexpected failure and the child process exiting.
After the scan I got the following result:
 
{"host":"HOSTNAME","port":443,"protocol":"HTTP","isPublic": false,"status":"READY","startTime":1446562720153,"testTime":
  1446562742152,"engineVersion":"1.19.33","criteriaVersion":"2009j", "cacheExpiryTime":1446563342152,"endpoints":[{"ipAddress":"IP",
   "serverName":"HOSTNAME","statusMessage": "Unexpected failure","statusDetails":"TESTING_COMPRESSION",
   "statusDetailsMessage":"Testing compression","progress":-1,"duration": 21405,"eta":-1,"delegation":1}]}
 
Would the above imply that the TESTING_COMPRESSION caused the unexpected failure and the child process to exit? Could you provide some details on how to reproduce this behaviour manually?

From an older thread I found the following mentioned by Ivan:
 
https://community.qualys.com/thread/12434
 
In SSL Labs I use custom code, which simulates a client that supports compression. When I tried to do the same with OpenSSL it turned out to be very difficult, because OpenSSL wouldn't even attempt to use compression and it was not clear why.
 
I've just tested sslyze with one domain name, and it seems to work correctly https://github.com/iSECPartners/sslyze/
 
I downloaded the latest sslyze release from https://github.com/nabla-c0d3/sslyze and ran the scan. It worked without problems and the Apache child process didn't exit. However I'm not sure if sslyze compression test is similar. Could you provide details regarding the compression test to test behavior on my Apache server?

Please let me know if you need more information. Your help is much appreciated.

**Comment by ivanr** [comment]
I think the easiest way is to run tcpdump and record all traffic from SSL Labs. If the Apache child process crashes and the SSL Labs test is interrupted, the last captured ClientHello should be the one that caused the problem. You can then try to re-sent the same packet to see if it crashes the server.

**Comment by ivanr** [comment]
Closing, unless new information comes to light.
