### ISSUE TITLE
Cipher Strength of '90' while a 112 bit suite is included

### ISSUE THREAD

**Issue by osirisinferi** [ssllabs/ssllabs-scan#259]
While checking the hostname `jouw.postnl.nl`, I came across the following bug (I think):

In the `Summary` chapter the `Cipher Strength` item gets a rating of 90. According to the "Cipher Strength" chapter of the "SSL Server Rating Guide"[1], this would imply a strongest cipher of at least 256 bits (b/c >=256 = 100 according to `Table 5`) and a weakest cipher of at least 128 bits (b/c the weakest cipher should result in a score of 80 to get to an average of 90. And <256 bits = 80 [but >=128, b/c <128 = 20]).

But if you look at the `Cipher Suites` section in the `Configuration` chapter, there's this:

"TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)	112"

For some reason it mentions a 112 bits cipher suite, which would imply a weakest cipher rating of 20 (<128 bits) and therefore an overal rating of 60.

If I look at the output of `openssl ciphers -v DES-CBC3-SHA`:

```
DES-CBC3-SHA            SSLv3 Kx=RSA      Au=RSA  Enc=3DES(168) Mac=SHA1
```

It says 168 bits, which would be more than the 128 required for the score of 80.

Therefore I'm thinking the strength of the TLS_RSA_WITH_3DES_EDE_CBC_SHA suite is listed erroneously in the Cipher Suites list?

**Comment by selecadm** [comment]
The 3DES strength is rather opinion-based. It's been a long time since Firefox and Chrome consider 3DES 112-bit, but Windows so far has still been considering 3DES 168-bit.

112-bit is still strong enough, no reason to downgrade the score more. Still, 3DES is mostly needed only for Windows XP which is EOL and has vulnerabilities making browsing dangerous regardless of HTTPS.

**Comment by osirisinferi** [comment]
The 112 bit strength of the 168 bits key length keying option 1 of triple des comes from the meet-in-the-middle-attack vulnerability I found out[1].

Even so, if one argues "112-bit is still strong enough, no reason to downgrade the score more.", this should be reflected in the Guide, right? Because now Table 5 says it should receive a score of 20 for this (averaged to 60).

So two options if triple DES shouldn't be penalized: the table should change or the bit strength of triple DES?

[1]: http://stephanemoore.com/pdf/meetinthemiddle.pdf

**Comment by ivanr** [comment]
3DES is the only suite with "non-standard" strength so it was difficult to classify; the rating algorithm classifies it in the same category as 128-bit suites, even though the actual strength is 112 bits (or 108, depending on whom you ask). This should have been documented, but I forgot about it. It's going to go away soon anyway.

**Comment by cem-** [comment]
What is going away soon?

**Comment by ivanr** [comment]
To be honest, I have no idea what I wanted to say there exactly :)
