### ISSUE TITLE
Path to root certificate

### ISSUE THREAD

**Issue by mcarpenter** [ssllabs/ssllabs-scan#26]
[Opening issue here as requested by Ivan http://sourceforge.net/p/ssllabs/mailman/message/33042217/]

I've been playing with the API a little and one of the things that I think is missing (or, at least, that I'd like to see) is the discovered chain to the root.

I think I read that the backend uses mozilla's trusted roots so I could presumably query some other source for these but that seems clumsy: could the discovered path to the root (if any) be in each response? I understand it shouldn't be part of `endpoint_data.details.certs` (since these are the chain certificates returned by the server, right?) so perhaps it could be a new attribute of endpoint_data.details`?

**Comment by ivanr** [comment]
FYI, as of 1.21.8, the root store is exposed via the /getRootCertsRaw API call.

**Comment by ivanr** [comment]
This is done in the v3 API, running on dev.ssllabs.com. No docs, though, but easy to see in the output.
