### ISSUE TITLE
Provide solution for complete (i.e. incuding client certificate) case

### ISSUE THREAD

**Issue by ssten** [ssllabs/ssllabs-scan#260]
https://www.ssllabs.com/ssltest/index.html is a fine tool.
But.
First of all it loops on test of private (i.e. requireing valid client certificate, SSLVerifyClient require in terms of Apache web server) server.
That is an error.
In the second, adding a simple browser check doesn't cover expected in common solution check of client certificate.

I don't know clientcert-based solutions, which uses public CAs.
Administrating one of such resources I want to use Qualys SSL Labs tool to automate it's certificates check.
To do so we need the following:
1. Make project distributable, like W3C validator https://validator.w3.org/source/
2. Provide facility and properly document adding into private Qualys SSL Labs tools mirror (because allowing external access to *private* resource looks not a good idea, especially with 3rd part distributing of valid client certificate) custom CA and client certificates.
Option for check CA certificates will be highly appreciated.

**Comment by ivanr** [comment]
Sorry, we have no plans to change the deployment model to allow for private installations. Our focus (at least for the time being) is on public web sites.

**Comment by roycewilliams** [comment]
@ssten, the closest you'll probably get is the "testssl.sh" bash script, which runs standalone on most UNIX-likes, including Cygwin and Mac OS X. http://testssl.sh/
