### ISSUE TITLE
Restrict robust FS to ECDH >= 256-bit and DH >= 2048-bit

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#262]
Subj.

**Comment by J0WI** [comment]
Today, 'robust' should mean the server forces FS...
The only browser without FS support is IE on XP and they are broken anyway.

**Comment by selecadm** [comment]
But forcing FS doesn't make sense if it's, for example, 768-bit DH. This is what this bug is about.

https://twitter.com/selecadm/status/667377548515504129

https://community.qualys.com/thread/15119

**Comment by J0WI** [comment]
Sure. I forked this to #265

**Comment by ivanr** [comment]
Fixed.

**Comment by selecadm** [comment]
A server that supports 224-bit and 256-bit ECDH and forces 224-bit successfully gets FS "with modern browsers", including 224-bit with green FS. Considered normal?

**Comment by ivanr** [comment]
Yes, it is. I implemented two thresholds: below 2048 is weak, below 1024 is insecure. EC strength of 224 bits is about 2048 RSA/DH bits. If you deploy with a 160-bit or 192-bit curve you should see a "weak" warning.
