### ISSUE TITLE
Windows 10 Mobile / Edge 13

### ISSUE THREAD

**Issue by martinsuchan** [ssllabs/ssllabs-scan#263]
Hi,
first phones with **Windows 10 Mobile RTM** [were just released](http://www.windowscentral.com/lumia-950-review). The Client test results are identical to Edge 13 on desktop Windows 10, see here: https://github.com/ssllabs/ssllabs-scan/issues/150

User Agent:
Mozilla/5.0 (Windows Phone 10.0; Android 4.2.1; DEVICE INFO) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586

TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c) Forward Secrecy 256 
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b) Forward Secrecy 128 
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030) Forward Secrecy 256 
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f) Forward Secrecy 128 
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x9f) Forward Secrecy 256 
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x9e) Forward Secrecy 128 
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 (0xc024) Forward Secrecy 256 
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 (0xc023) Forward Secrecy 128 
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028) Forward Secrecy 256 
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (0xc027) Forward Secrecy 128 
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a) Forward Secrecy 256 
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (0xc009) Forward Secrecy 128 
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014) Forward Secrecy 256 
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013) Forward Secrecy 128 
TLS_RSA_WITH_AES_256_GCM_SHA384 (0x9d) 256 
TLS_RSA_WITH_AES_128_GCM_SHA256 (0x9c) 128 
TLS_RSA_WITH_AES_256_CBC_SHA256 (0x3d) 256 
TLS_RSA_WITH_AES_128_CBC_SHA256 (0x3c) 128 
TLS_RSA_WITH_AES_256_CBC_SHA (0x35) 256 
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f) 128 
TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa) 112 
TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 (0x6a) Forward Secrecy2 256 
TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 (0x40) Forward Secrecy2 128 
TLS_DHE_DSS_WITH_AES_256_CBC_SHA (0x38) Forward Secrecy2 256 
TLS_DHE_DSS_WITH_AES_128_CBC_SHA (0x32) Forward Secrecy2 128 
TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA (0x13) Forward Secrecy2 112

**Comment by ivanr** [comment]
Could you please visit dev.ssllabs.com (using a device with Windows 10 RTM)  and tell me your IP address?

**Comment by martinsuchan** [comment]
Done, my IP: 77.75.74.248, Nokia Lumia 1520.

**Comment by ivanr** [comment]
Great, thanks. I've added it to 1.21.11, which is being released doon.
