### ISSUE TITLE
"Downgrade attack prevention	Unknown (requires support for at least two protocols)" should clarify that SSL2 doesn't count

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#266]
Subj.

**Comment by ivanr** [comment]
Fixed.

**Comment by selecadm** [comment]
> Downgrade attack prevention	Unknown (requires support for at least two TLS versions)

I said that only SSL2 doesn't count, not SSL2 and SSL3.

> Protocols
TLS 1.2	No
TLS 1.1	No
TLS 1.0	Yes
SSL 3	No
SSL 2	YesD
(D) Protocol is supported, but with all cipher suites disabled

> Downgrade attack prevention	Unknown (requires support for at least two TLS versions)

> Protocols
TLS 1.2	No
TLS 1.1	No
TLS 1.0	Yes
SSL 3   INSECURE	Yes
SSL 2	No

> Downgrade attack prevention	Yes, TLS_FALLBACK_SCSV supported

**Comment by ivanr** [comment]
Yes, our course. My bad. I fixed it for the second time (not deployed yet).
The message is now "requires support for at least two protocols, excl. SSL2".
