### ISSUE TITLE
Show if domain is in HTTPS Everywhere 

### ISSUE THREAD

**Issue by intchloe** [ssllabs/ssllabs-scan#267]
Hello,

right now SSLlabs shows if a domain is in the preload-HSTS list but it would also be good to show if the domain exists in HTTPS Everywhere. As we know HTTPS Everywhere can stop sslstripping attacks so I think it would be wise to include this.

HTTPS Everywhere has an atlas: https://www.eff.org/https-everywhere/atlas/

Regards,
Chloe

**Comment by selecadm** [comment]
Were you inspired by this thread? https://community.qualys.com/thread/15707
Or we can consider this a dupe.

My opinion is that having a site in HTTPS Everywhere list should be a warning. Properly configured sites wouldn't be in that list in the first place.

**Comment by drwetter** [comment]
> My opinion is that having a site in HTTPS Everywhere list should be a warning. 
> Properly configured sites wouldn't be in that list in the first place.

Not that easy.

For some percent you seem right.

For the others you're assuming that you know exactly what HTTPS everywhere is doing. I am not sure about it. I run a site which has enabled both http and https. On the latter I run strict transport security and key pinning since a longer time and one day it popped up @ HTTPS everywhere .

And: It wouldn't penalize those who really deserve it IMO. Prominent example: ebay.de.  HTTPS everywhere says it's buggy and thus it's not on the list (other TLDs though).

**Comment by nextPrime** [comment]
> Properly configured sites wouldn't be in that list in the first place.

Not necessarily. Even EFF's own websites are in the list. If a website is in HSTS-preload list, I don't think there is a need for the administrator to *remove* this site from the HTTPS Everywhere list.

[1] https://github.com/EFForg/https-everywhere/blob/master/src/chrome/content/rules/EFF.xml
[2] https://www.ssllabs.com/ssltest/analyze.html?d=www.eff.org&s=69.50.225.155&hideResults=on

**Comment by selecadm** [comment]
> For the others you're assuming that you know exactly what HTTPS everywhere is doing. I am not sure about it. I run a site which has enabled both http and https. On the latter I run strict transport security and key pinning since a longer time and one day it popped up @ HTTPS everywhere .

Properly configured == 301 redirect to HTTPS location. From your description, looks like there wasn't such.

Regarding TOFU: it's better to request HSTS preloading which is hard-coded in the browsers' source than relying on a browser extension.

**Comment by drwetter** [comment]
> Properly configured == 301 redirect to HTTPS location. From your description, looks like there 
> wasn't such.

<OT> That's true. OTOH there is no confidential data and what I am offering on downloads is mostly pgp signed (integrity). HTTPS would be academically ok, practically overdoing it like the "HTTPS Everywhere for IETF discussion" @ the IETF mailing list. With the subtle difference I am not IETF ;-) 

For the same reason preloading would be overdoing it. I rather then give way for the sites which really have an advantage from preloading. As we all know we can't preload half the world into the browsers.

**Comment by J0WI** [comment]
Note that preloaded HSTS domains are being removed from HTTPS Everywhere.

**Comment by ivanr** [comment]
I don't see why we should report if a site is in HTTPSEverywhere. Properly configured sites don't need to be there and we warn if a site is not properly configured.
