### ISSUE TITLE
Something wrong with the bar for "protocol support"

### ISSUE THREAD

**Issue by KommX** [ssllabs/ssllabs-scan#268]
There seems to be something wrong with the "protocol support" bar for https://www.ssllabs.com/ssltest/analyze.html?&hideResults=on&d=download.cyanogenmod.org

![protocol](https://cloud.githubusercontent.com/assets/7859245/11420626/98fb7b36-942f-11e5-83b8-faa1ad9ae60e.png)

The server supports TLS 1.0, 1.1, 1.2 and doesn't support the old SSL 2/3 protocols, so that looks fine to me.

**Comment by selecadm** [comment]
> This server supports weak Diffie-Hellman (DH) key exchanges parameters. Grade capped to B.

See? That's the reason ;).

**Comment by KommX** [comment]
Are you sure?

Why should a weak key exchange influence the "Protocol Support" score but not the "Key Exchange" score?

**Comment by selecadm** [comment]
It influences both, "Key Exchange" is 80% because of this also. Must be at least 90% to be considered secure.

**Comment by ivanr** [comment]
This is a bug. The key exchange category should be capped, not the protocol one. Fixed.
