### ISSUE TITLE
Support OCSP Must-Staple TLS Feature Extension

### ISSUE THREAD

**Issue by tdelmas** [ssllabs/ssllabs-scan#269]
As Firefox support it, could you consider to check for OCSP Must-Staple ?

https://blog.mozilla.org/security/2015/11/23/improving-revocation-ocsp-must-staple-and-short-lived-certificates/

https://community.qualys.com/thread/13306

**Comment by selecadm** [comment]
https://must-staple.serverhello.com
Prod: https://www.ssllabs.com/ssltest/analyze.html?d=must-staple.serverhello.com&hideResults=on
Dev: https://dev.ssllabs.com/ssltest/analyze.html?d=must-staple.serverhello.com&hideResults=on

https://must-staple-no-ocsp.serverhello.com
Prod: https://www.ssllabs.com/ssltest/analyze.html?d=must-staple-no-ocsp.serverhello.com&hideResults=on
Dev: https://dev.ssllabs.com/ssltest/analyze.html?d=must-staple-no-ocsp.serverhello.com&hideResults=on

Firefox Nightly:
> Secure Connection Failed
An error occurred during a connection to must-staple-no-ocsp.serverhello.com. A required TLS feature is missing. Error code: MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING

**Comment by bhushan5640** [comment]
dev.ssllabs.com now supports ocsp must staple

**Comment by tdelmas** [comment]
Awesome! Tests pass with success, I'll close the issue.

**Comment by ivanr** [comment]
The original test servers are no longer available. To view the new feature try this: https://dev.ssllabs.com/ssltest/analyze.html?viaform=on&d=sslanalyzer.comodoca.com

**Comment by tdelmas** [comment]
When the certificate specify must-staple but the server doesn't staple, the message

> This server certificate supports OCSP must staple but OCSP response is not stapled.

Is in orange (like a warning). Shouldn't it be red, as it is an error and downgrade the grade?

**Comment by ivanr** [comment]
Yes, I agree. Can you share the hostname for testing?

**Comment by tdelmas** [comment]
@ivanr Sure, you can test it with https://dev.tdelmas.ovh : https://dev.ssllabs.com/ssltest/analyze.html?d=dev.tdelmas.ovh
I'll try keep that domain broken until https://github.com/chromium/badssl.com/issues/114 is solved
