### ISSUE TITLE
Allow tests port 995 (POP3 over SSL)

### ISSUE THREAD

**Issue by hickford** [ssllabs/ssllabs-scan#270]
My granddad can't check his email because his client rejects the pop3 server:

> SSL Security Error. Server returned error "SSL error: unable to verify the first certificate"

I'm curious to know why but SSL Server Test won't help me https://www.ssllabs.com/ssltest/analyze.html?d=pop.tools.sky.com:995

> Ports other than 443 not supported

Port 995 is the standard port for [POP3 over SSL](https://en.wikipedia.org/wiki/Post_Office_Protocol), so I think it would be reasonable to allow tests. People want to know the email servers they use are secure, just as they do about websites they use.

* * *

How does the general standard of SSL configuration for email servers compare to that of web servers? I wouldn't be surprised if it's much lower.

**Comment by hickford** [comment]
The webmail gets grade C https://www.ssllabs.com/ssltest/analyze.html?d=skyid.sky.com

**Comment by selecadm** [comment]
> SSL Security Error. Server returned error "SSL error: unable to verify the first certificate"

It uses Extended Validation from Symantec. Does his client support SHA2 certificates?

https://sslanalyzer.comodoca.com/?url=pop.tools.sky.com%3A995

![image](https://cloud.githubusercontent.com/assets/10382329/11456961/a9a8064c-96ab-11e5-9990-b3815b4915b6.png)
![image](https://cloud.githubusercontent.com/assets/10382329/11456962/cbca066c-96ab-11e5-8fbc-e7c14e49a749.png)

> Certificate chain
 0 s:/1.3.6.1.4.1.311.60.2.1.3=GB/businessCategory=Private Organization/serialNumber=02247735/C=GB/postalCode=TW7 5QD/ST=Middlesex/L=Isleworth/street=Grant Way/O=Sky Plc/OU=IS-Yahoo/CN=pop.tools.sky.com
   i:/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 EV SSL CA - G3
-----BEGIN CERTIFICATE-----
MIIG0zCCBbugAwIBAgIQTH6xJ0k5tAZjvV11CfH4FTANBgkqhkiG9w0BAQsFADB3
MQswCQYDVQQGEwJVUzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xHzAd
BgNVBAsTFlN5bWFudGVjIFRydXN0IE5ldHdvcmsxKDAmBgNVBAMTH1N5bWFudGVj
IENsYXNzIDMgRVYgU1NMIENBIC0gRzMwHhcNMTUwNDIwMDAwMDAwWhcNMTcwNDIw
MjM1OTU5WjCB4zETMBEGCysGAQQBgjc8AgEDEwJHQjEdMBsGA1UEDxMUUHJpdmF0
ZSBPcmdhbml6YXRpb24xETAPBgNVBAUTCDAyMjQ3NzM1MQswCQYDVQQGEwJHQjEQ
MA4GA1UEEQwHVFc3IDVRRDESMBAGA1UECAwJTWlkZGxlc2V4MRIwEAYDVQQHDAlJ
c2xld29ydGgxEjAQBgNVBAkMCUdyYW50IFdheTEQMA4GA1UECgwHU2t5IFBsYzER
MA8GA1UECwwISVMtWWFob28xGjAYBgNVBAMMEXBvcC50b29scy5za3kuY29tMIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA0PzZRy/UfdYDGfWYnvO1TtXx
kgrZUzJYkpPS+TowYiXiB0TzcrtifqdO2r/1qfg6A9eY+Gn3jJAalSJsMA88nSmm
e88YR6GCRjMFMN9t96D5nkknXENhu1FYNprk8jJLL2rVybkdHPRRPU7h+cg5DYdI
+wknbn/xQKRZulADTE7YCeHSaVe51Qwe11iaRl0YHBfjywwUPoBQv5O3BJFpfvvZ
E6cjmOhQi+gI8VtypzcMhs92oBlE6zcGtoTA+iQDCy3Q6pm0Ezdnz9fmQcTX74F8
dYHzyjEHeeqb3Pu7YBsJZP7uoHhkUv/ysSB2OXTsvMgDcv0kHLhTgE6GvGFvrQID
AQABo4IC7DCCAugwHAYDVR0RBBUwE4IRcG9wLnRvb2xzLnNreS5jb20wCQYDVR0T
BAIwADAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUF
BwMCMGYGA1UdIARfMF0wWwYLYIZIAYb4RQEHFwYwTDAjBggrBgEFBQcCARYXaHR0
cHM6Ly9kLnN5bWNiLmNvbS9jcHMwJQYIKwYBBQUHAgIwGRoXaHR0cHM6Ly9kLnN5
bWNiLmNvbS9ycGEwHwYDVR0jBBgwFoAUAVmr5906C1mmZGPWzyAHV9WR52owKwYD
VR0fBCQwIjAgoB6gHIYaaHR0cDovL3NyLnN5bWNiLmNvbS9zci5jcmwwVwYIKwYB
BQUHAQEESzBJMB8GCCsGAQUFBzABhhNodHRwOi8vc3Iuc3ltY2QuY29tMCYGCCsG
AQUFBzAChhpodHRwOi8vc3Iuc3ltY2IuY29tL3NyLmNydDCCAX0GCisGAQQB1nkC
BAIEggFtBIIBaQFnAHYApLkJkLQYWBSHuxOizGdwCjw1mAT5G9+443fNDsgN3BAA
AAFM1nE2PwAABAMARzBFAiEA+M1RYb66y1j8Lwv1bK6Wtrl7cy69G/glAbnNnPUJ
H4oCIGRpFjn/mIRXe2EKuLG1/oIE6ljqBpNQYsrJix7/RGujAHUAVhQGmi/XwuzT
9eG9RLI+x0Z2ubyZEVzA75SYVdaJ0N0AAAFM1nE3YQAABAMARjBEAiAGUFN0nl/z
se0LpyOLHZrFMpO8ycov4/rjZPCGMgcGuQIgIfXXKpjWQuP2cjHeg6P6JlCrkeVX
u1RUt/OIC6zXGmQAdgBo9pj4H2SCvjqM7rkoHUz8cVFdZ5PURNEKZ6y7T0/7xAAA
AUzWcTZfAAAEAwBHMEUCIQD9zl5HaQ4fO2/iHrRf8133twuD9mSC/KISCeXJj40e
yAIgBdceLhNtSjWC4wgjtloMJaJtTblmuI4iKJGjGttKSF0wDQYJKoZIhvcNAQEL
BQADggEBADpTYsClGiFaEWpFFfw3Eakjdvat/sqyRMgafVxbQJaSxYBxmEl0EeXG
Y8iBiQsmfgzxyq5DNiGefU8wayVupk2jIaegqBtIrId3C617pCO5Tcu/gQ78Jyqw
nu+z4cHMrNlEFrphbWjj5FfeRQn5Vyos9AzWRcxyYG6ZkAT4fsRVxR3u4FeVrnv4
DQPzOrhrrRhOJscm1IdKPnBd36JcJTbOfIk8N4PqJO6PSbhZfUxD1MuF9P44cPxe
36ZgD2GwlcGV16TEU6Ar41jneBU1QQlrBA9yGG5pHlAWYyJFj/s3zVR+rKgKMBXI
NjhAvmyvWI70DWLM68RdStfGiJa6R/Y=
-----END CERTIFICATE-----
 1 s:/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 EV SSL CA - G3
   i:/C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=(c) 2006 VeriSign, Inc. - For authorized use only/CN=VeriSign Class 3 Public Primary Certification Authority - G5
-----BEGIN CERTIFICATE-----
MIIFKzCCBBOgAwIBAgIQfuFKb2/v8tN/P61lTTratDANBgkqhkiG9w0BAQsFADCB
yjELMAkGA1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQL
ExZWZXJpU2lnbiBUcnVzdCBOZXR3b3JrMTowOAYDVQQLEzEoYykgMjAwNiBWZXJp
U2lnbiwgSW5jLiAtIEZvciBhdXRob3JpemVkIHVzZSBvbmx5MUUwQwYDVQQDEzxW
ZXJpU2lnbiBDbGFzcyAzIFB1YmxpYyBQcmltYXJ5IENlcnRpZmljYXRpb24gQXV0
aG9yaXR5IC0gRzUwHhcNMTMxMDMxMDAwMDAwWhcNMjMxMDMwMjM1OTU5WjB3MQsw
CQYDVQQGEwJVUzEdMBsGA1UEChMUU3ltYW50ZWMgQ29ycG9yYXRpb24xHzAdBgNV
BAsTFlN5bWFudGVjIFRydXN0IE5ldHdvcmsxKDAmBgNVBAMTH1N5bWFudGVjIENs
YXNzIDMgRVYgU1NMIENBIC0gRzMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
AoIBAQDYoWV0I+grZOIy1zM3PY71NBZI3U9/hxz4RCMTjvsR2ERaGHGOYBYmkpv9
FwvhcXBC/r/6HMCqo6e1cej/GIP23xAKE2LIPZyn3i4/DNkd5y77Ks7Imn+Hv9hM
BBUyydHMlXGgTihPhNk1++OGb5RT5nKKY2cuvmn2926OnGAE6yn6xEdC0niY4+wL
pZLct5q9gGQrOHw4CVtm9i2VeoayNC6FnpAOX7ddpFFyRnATv2fytqdNFB5suVPu
IxpOjUhVQ0GxiXVqQCjFfd3SbtICGS97JJRL6/EaqZvjI5rq+jOrCiy39GAI3Z8c
zd0tAWaAr7MvKR0juIrhoXAHDDQPAgMBAAGjggFdMIIBWTAvBggrBgEFBQcBAQQj
MCEwHwYIKwYBBQUHMAGGE2h0dHA6Ly9zMi5zeW1jYi5jb20wEgYDVR0TAQH/BAgw
BgEB/wIBADBlBgNVHSAEXjBcMFoGBFUdIAAwUjAmBggrBgEFBQcCARYaaHR0cDov
L3d3dy5zeW1hdXRoLmNvbS9jcHMwKAYIKwYBBQUHAgIwHBoaaHR0cDovL3d3dy5z
eW1hdXRoLmNvbS9ycGEwMAYDVR0fBCkwJzAloCOgIYYfaHR0cDovL3MxLnN5bWNi
LmNvbS9wY2EzLWc1LmNybDAOBgNVHQ8BAf8EBAMCAQYwKQYDVR0RBCIwIKQeMBwx
GjAYBgNVBAMTEVN5bWFudGVjUEtJLTEtNTMzMB0GA1UdDgQWBBQBWavn3ToLWaZk
Y9bPIAdX1ZHnajAfBgNVHSMEGDAWgBR/02Wnwt3su/AwCfNDOfoCrzMxMzANBgkq
hkiG9w0BAQsFAAOCAQEAQgFVe9AWGl1Y6LubqE3X89frE5SG1n8hC0e8V5uSXU8F
nzikEHzPg74GQ0aNCLxq1xCm+quvL2GoY/Jl339MiBKIT7Np2f8nwAqXkY9W+4nE
qLuSLRtzsMarNvSWbCAI7woeZiRFT2cAQMgHVHQzO6atuyOfZu2iRHA0+w7qAf3P
eHTfp61Vt19N9tY/4IbOJMdCqRMURDVLtt/JYKwMf9mTIUvunORJApjTYHtcvNUw
LwfORELEC5n+5p/8sHiGUW3RLJ3GlvuFgrsEL/digO9i2n/2DqyQuFa9eT/ygG6j
2bkPXToHHZGThkspTOHcteHgM52zyzaRS/6htO7w+Q==
-----END CERTIFICATE-----
 2 s:/C=US/O=VeriSign, Inc./OU=VeriSign Trust Network/OU=(c) 2006 VeriSign, Inc. - For authorized use only/CN=VeriSign Class 3 Public Primary Certification Authority - G5
   i:/C=US/O=VeriSign, Inc./OU=Class 3 Public Primary Certification Authority
-----BEGIN CERTIFICATE-----
MIIE0DCCBDmgAwIBAgIQJQzo4DBhLp8rifcFTXz4/TANBgkqhkiG9w0BAQUFADBf
MQswCQYDVQQGEwJVUzEXMBUGA1UEChMOVmVyaVNpZ24sIEluYy4xNzA1BgNVBAsT
LkNsYXNzIDMgUHVibGljIFByaW1hcnkgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkw
HhcNMDYxMTA4MDAwMDAwWhcNMjExMTA3MjM1OTU5WjCByjELMAkGA1UEBhMCVVMx
FzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMR8wHQYDVQQLExZWZXJpU2lnbiBUcnVz
dCBOZXR3b3JrMTowOAYDVQQLEzEoYykgMjAwNiBWZXJpU2lnbiwgSW5jLiAtIEZv
ciBhdXRob3JpemVkIHVzZSBvbmx5MUUwQwYDVQQDEzxWZXJpU2lnbiBDbGFzcyAz
IFB1YmxpYyBQcmltYXJ5IENlcnRpZmljYXRpb24gQXV0aG9yaXR5IC0gRzUwggEi
MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCvJAgIKXo1nmAMqudLO07cfLw8
RRy7K+D+KQL5VwijZIUVJ/XxrcgxiV0i6CqqpkKzj/i5Vbext0uz/o9+B1fs70Pb
ZmIVYc9gDaTY3vjgw2IIPVQT60nKWVSFJuUrjxuf6/WhkcIzSdhDY2pSS9KP6HBR
TdGJaXvHcPaz3BJ023tdS1bTlr8Vd6Gw9KIl8q8ckmcY5fQGBO+QueQA5N06tRn/
Arr0PO7gi+s3i+z016zy9vA9r911kTMZHRxAy3QkGSGT2RT+rCpSx4/VBEnkjWNH
iDxpg8v+R70rfk/Fla4OndTRQ8Bnc+MUCH7lP59zuDMKz10/NIeWiu5T6CUVAgMB
AAGjggGbMIIBlzAPBgNVHRMBAf8EBTADAQH/MDEGA1UdHwQqMCgwJqAkoCKGIGh0
dHA6Ly9jcmwudmVyaXNpZ24uY29tL3BjYTMuY3JsMA4GA1UdDwEB/wQEAwIBBjA9
BgNVHSAENjA0MDIGBFUdIAAwKjAoBggrBgEFBQcCARYcaHR0cHM6Ly93d3cudmVy
aXNpZ24uY29tL2NwczAdBgNVHQ4EFgQUf9Nlp8Ld7LvwMAnzQzn6Aq8zMTMwbQYI
KwYBBQUHAQwEYTBfoV2gWzBZMFcwVRYJaW1hZ2UvZ2lmMCEwHzAHBgUrDgMCGgQU
j+XTGoasjY5rw8+AatRIGCx7GS4wJRYjaHR0cDovL2xvZ28udmVyaXNpZ24uY29t
L3ZzbG9nby5naWYwNAYIKwYBBQUHAQEEKDAmMCQGCCsGAQUFBzABhhhodHRwOi8v
b2NzcC52ZXJpc2lnbi5jb20wPgYDVR0lBDcwNQYIKwYBBQUHAwEGCCsGAQUFBwMC
BggrBgEFBQcDAwYJYIZIAYb4QgQBBgpghkgBhvhFAQgBMA0GCSqGSIb3DQEBBQUA
A4GBABMC3fjohgDyWvj4IAxZiGIHzs73Tvm7WaGY5eE43U68ZhjTresY8g3JbT5K
lCDDPLq9ZVTGr0SzEK0saz6r1we2uIFjxfleLuUqZ87NMwwq14lWAyMfs77oOghZ
tOxFNfeKW/9mz1Cvxm1XjRl4t7mi0VfqH5pLr7rJjhJ+xr3/
-----END CERTIFICATE-----
-
Server certificate
subject=/1.3.6.1.4.1.311.60.2.1.3=GB/businessCategory=Private Organization/serialNumber=02247735/C=GB/postalCode=TW7 5QD/ST=Middlesex/L=Isleworth/street=Grant Way/O=Sky Plc/OU=IS-Yahoo/CN=pop.tools.sky.com
issuer=/C=US/O=Symantec Corporation/OU=Symantec Trust Network/CN=Symantec Class 3 EV SSL CA - G3
-
No client certificate CA names sent
-
SSL handshake has read 4979 bytes and written 431 bytes
-
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 1D0E8EE147CBB650EEA5574C6BFE1CA2AE878C3736E7F07060B94174990A9F4D
    Session-ID-ctx:
    Master-Key: 73D1341C96DEEB27FD71C51B0F6196D22B66FE7746453B0D1E16FE0AD66C8DC5F94217C357E14BFAD10F0E4151BEF47F
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 300 (seconds)
    TLS session ticket:
    0000 - 0f f7 96 e0 e8 0f 2c 83-6b 02 a2 65 78 b9 14 25   ......,.k..ex..%
    0010 - d0 04 64 1c de 3d 87 e7-9b 79 20 f6 8c 7f 61 55   ..d..=...y ...aU
    0020 - 8b a8 e4 e4 a9 72 aa 18-49 e5 3c 14 8c 3d 22 43   .....r..I.<..="C
    0030 - ff 44 e5 0f 4e 0f 58 62-e4 29 5e c0 82 ee 89 3b   .D..N.Xb.)^....;
    0040 - 9e c5 3a 45 6e fd 08 f0-f4 75 27 e0 4c 2a 97 41   ..:En....u'.L*.A
    0050 - 55 06 88 c2 25 5c ba e8-fa eb be f6 dc 5b d6 c6   U...%\.......[..
    0060 - 2a 45 12 91 11 7b 33 83-9e e7 c9 5a e0 17 fe 2e   *E...{3....Z....
    0070 - 0e cc 5d 1c 12 d4 53 2e-8c 7a a4 69 b0 22 57 96   ..]...S..z.i."W.
    0080 - a1 10 38 fa 05 40 a3 b0-eb 13 d0 9b 97 19 60 00   ..8..@........`.
    0090 - ef 38 54 f8 8a d5 c7 a6-a9 5e 5f 7b 71 9c f8 ca   .8T......^_{q...
    Start Time: 1448799019
    Timeout   : 300 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
---
+OK hello from popgate-1.8.1_01.20166 pop025.mail.ir2.yahoo.com

**Comment by hickford** [comment]
Thanks. The client is GMail. I previously set it up to download email from the sky.com account using the "Check email from other accounts (using POP3)" feature  https://support.google.com/mail/answer/21289?hl=en-GB

**Comment by hickford** [comment]
Hum I can't see anything obviously wrong with that server. Any ideas why Gmail rejects it?

https://helpforum.sky.com/t5/Sky-Yahoo-Mail/Invalid-Security-Certificate/m-p/2378916#M56065

**Comment by selecadm** [comment]
Nothing seems to be wrong with the certificate. Though it has Signed Certificate Timestamps embedded as an X.509 extension, it's not marked critical, so should cause any problems.

**Comment by ivanr** [comment]
I couldn't see anything wrong with the certificate either. Inspection of other ports and protocol should come in the future. Closing this ticket as it's about something else.

**Comment by hickford** [comment]
Hi again. Would you consider allowing tests ports 993, 995 and 465? This would allow testing of IMAP, POP3 and SMTP email servers. People want to know the email servers they use as secure, just as they do about websites they use.

Port list: https://www.fastmail.com/help/technical/ssltlsstarttls.html

> * IMAP uses port 143, but SSL/TLS encrypted IMAP uses port 993.
> * POP uses port 110, but SSL/TLS encrypted POP uses port 995.
> * SMTP uses port 25, but SSL/TLS encrypted SMTP uses port 465.

**Comment by hickford** [comment]
I wouldn't be surprised to learn many email servers still allow SSL 3, or have other bad configuration. Some ISPs, schools, businesses may not have reviewed them in years.

**Comment by ArchangeGabriel** [comment]
I think that allowing anyport is probably easier. ;) Since you might also want to be able to check on STARTTLS ports, so that’s 7 ports total for email purposes.

@hickford In the meantime, you can use https://www.htbridge.com/ssl/.
