### ISSUE TITLE
[ENHANCEMENT] Warn about supporting cipher suites not used by any simulated client

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#271]
https://wiki.mozilla.org/Security/Server_Side_TLS#Intermediate_compatibility_.28default.29

These preferences result in 75% of the supported suites not used by any simulated client. The list includes CAMELLIA cipher and even DHE_DSS key exchange. This stupidity must be stopped.

What I suggest:

![image](https://cloud.githubusercontent.com/assets/10382329/11615316/4cf2a22c-9c6e-11e5-9b3b-63fea32edf4b.png)

**Comment by nextPrime** [comment]
I disagree. Not used by simulated clients doesn't mean these cipher suites are not used by any clients in the real world. Feature phones, Internet of Things, televisions, proxies, etc. are not in SSL Labs simulation list. Also, users are able to customize TLS cipher suites used by their browsers.

If you compare [the SSLLabs' handshake simulation of en.wikipedia.org](https://www.ssllabs.com/ssltest/analyze.html?d=en.wikipedia.org&s=208.80.153.224&hideResults=on) and [the actual data](https://grafana.wikimedia.org/dashboard/db/tls-ciphers), you can find that AES128-SHA is not used in all simulations, but it's actual usage is 0.1966%, which is not small given the popularity of Wikipedia.

**Comment by selecadm** [comment]
If a client supports AES, I expect it to support at least DHE also. I can only think about one client that supports AES without ephemeral exchange: Windows Embedded POSReady 2009 with KB3081320 installed.
Other from that, it's probably malicious bots or clients misconfigured so much that I don't want them to be able to connect to my servers.
Or it's a patched Windows Server 2003, but honestly it's better not to be used as a client.

The main issue here is that the configs offered use cipher suites groups instead of explicit, making it less understandable, then they completely ruin it by adding DHE_DSS. Server admins who use such configs don't even understand what DHE_DSS is, otherwise they would realize how stupid it is.

**Comment by J0WI** [comment]
The server should provide only secure ciphers. But the client should also be free to choose whatever he prefer.

**Comment by ivanr** [comment]
Well, it's difficult to say what is and isn't needed. We simulate only so many clients and it's possible that some of these suites are actually needed. I'd rather focus on asking people to do more important things, for example supporting HSTS.
