### ISSUE TITLE
HS for Android 6.0.1

### ISSUE THREAD

**Issue by ItzLevvie** [ssllabs/ssllabs-scan#272]
Add Handshake Simulation support for Android 6.0 (Marshmallow).

**Comment by ivanr** [comment]
Do we know if Android 6 has a "web view" that's different from the latest Chrome?

**Comment by fishouttah20** [comment]
Android 6.0 now uses the Android System WebView app from the Google Play Store, allowing them to update Webview as they do Chrome. Given this I think the answer to your question is "no", although I'm not sure how quickly after a Chrome release, the Webview update follows. Either way, attached are screenshots of the SSLLabs client page browsed to using the Google Play Store app "WebView" (so I could browse to ssllabs).
![screenshot_20151230-143021-2](https://cloud.githubusercontent.com/assets/11758944/12052048/e16c2936-af02-11e5-9777-9db7b97c4674.png)
![screenshot_20151230-143012-2](https://cloud.githubusercontent.com/assets/11758944/12052049/e17ea70a-af02-11e5-903a-d5188a1a8eae.png)
