### ISSUE TITLE
Protocol, cipher suite and elliptic curve shown in grey under "Protocol or cipher suite mismatch"

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#276]
https://www.ssllabs.com/ssltest/analyze.html?d=newcard.beeline.ru
https://dev.ssllabs.com/ssltest/analyze.html?d=newcard.beeline.ru

![image](https://cloud.githubusercontent.com/assets/10382329/11703144/9693b2e6-9eed-11e5-8e55-1c76635bf2b3.png)

>Apple ATS 9 / iOS 9  R	Protocol or cipher suite mismatch
TLS 1.0   TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA   ECDH secp256r1

Huh?

This happens for every server with ECDHE but without TLS 1.2 support.

**Comment by ivanr** [comment]
That's because Apple ATS requires at least TLS 1.2.
