### ISSUE TITLE
Assessment failed: Unknown EC curve: ffff

### ISSUE THREAD

**Issue by rob-collins** [ssllabs/ssllabs-scan#277]
My scan results in the following error message:

Assessment failed: Unknown EC curve: ffff

Can you provide more information about what this error means? Thanks!

**Comment by ivanr** [comment]
It's a bug. I can fix, but I need to know the name of the server where it happens.

**Comment by rob-collins** [comment]
stg-ws.healthcarepays.net

I have opened the firewall so you should have temporary access the server. Please let me know when you are done troubleshooting so I can reset the firewall. Thanks!

**Comment by ivanr** [comment]
This seems to be a bug in your server. It returns curve 0xffff, which doesn't exist as far as I know. I am also unable to communicate with it using openssl unless I disable ECDHE (and thus all named curves). Browsers seem to work fine, though. What is the server software?

**Comment by rob-collins** [comment]
I am in the process of tweaking the server config to maximize security, so if my server configuration has something stupid, please feel free to tell me!

Tomcat8, Java8
ciphers="TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_RSA_WITH_AES_128_CBC_SHA, TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_RSA_WITH_AES_256_CBC_SHA384, TLS_RSA_WITH_AES_256_CBC_SHA"

**Comment by ivanr** [comment]
This is not something you can mess up in configuration; a TLS server is not allowed to request a named curve that the client doesn't support. My guess is that this is a bug in the TLS stack when a large number of named curves are offered by a client.
Are you using BSAFE (as mentioned in that bug report)? If not, consider reporting the problem to Tomcat developers. On the SSL Labs side, I'll see if I can convert this problem to a non-fatal failure.

**Comment by rob-collins** [comment]
I am writing a follow-up to help anyone that stumbles across this or a similar issue. I was able to work around this problem by making the following change in jre/lib/security/java.security:

> security.provider.1=sun.security.provider.Sun
> security.provider.2=sun.security.rsa.SunRsaSign
> **security.provider.3=org.bouncycastle.jce.provider.BouncyCastleProvider**
> **#security.provider.3=sun.security.ec.SunEC**
> security.provider.4=com.sun.net.ssl.internal.ssl.Provider
> security.provider.5=com.sun.crypto.provider.SunJCE
> security.provider.6=sun.security.jgss.SunProvider
> security.provider.7=com.sun.security.sasl.Provider
> security.provider.8=org.jcp.xml.dsig.internal.dom.XMLDSigRI
> security.provider.9=sun.security.smartcardio.SunPCSC

I included the Bouncy Castle jars in lib/ext and swapped in the BC provider in place of the SunEC provider.

**Comment by hickford** [comment]
See also https://www.ssllabs.com/ssltest/analyze.html?d=mail.google.com&s=216.58.195.229

> Assessment failed: Unknown EC curve: 1d
