### ISSUE TITLE
Wrong certificate in case of SNI

### ISSUE THREAD

**Issue by RaymiiOrg** [ssllabs/ssllabs-scan#278]
The SSL Labs test gives me an M on ponify.nl because it thinks it gets a
cert from cipherli.st.

htps://ssllabs.com/ssltest/analyze.html?d=ponify.nl&s=178.62.214.186&hideResults=on&ignoreMismatch=on

However, they're two different certs on the same server with SNI.
Firefox and chrome don't complain, as does the openssl s_client.

As well as:
https://ssldecoder.org/?host=ponify.nl:178.62.214.186&port=443&fastcheck=0
https://ssldecoder.org/?host=cipherli.st:178.62.214.186&port=443&fastcheck=0

**Comment by selecadm** [comment]
Similar. No mismatch, just wrong cert also:
https://www.ssllabs.com/ssltest/analyze.html?d=selectel.ru
https://dev.ssllabs.com/ssltest/analyze.html?d=selectel.ru

> Issuer	RapidSSL SHA256 CA - G3

![image](https://cloud.githubusercontent.com/assets/10382329/11732426/184403aa-9fb5-11e5-8008-5177ce2880a5.png)

**Comment by selecadm** [comment]
It's all because of WWW subdomain. www.ponify.nl exists in DNS, but isn't configured server-side, so your server sends default certificate and confuses SSL Labs.

Remove WWW subdomain from DNS records.

**Comment by RaymiiOrg** [comment]
After configuring the www. domain in the webserver it seems to work. It's weird that that is a bug on your side because I specificly ask to check the non-www domain. If I want to check the www. domain I would enter that.

**Comment by selecadm** [comment]
SSL Labs always checks WWW subdomain regardless of input, including WWW subdomains of subdomains.

See also issues https://github.com/ssllabs/ssllabs-scan/issues/187, https://github.com/ssllabs/ssllabs-scan/issues/207, https://github.com/ssllabs/ssllabs-scan/issues/224, https://github.com/ssllabs/ssllabs-scan/issues/239

**Comment by RaymiiOrg** [comment]
@selecadm I wasn't aware of that. Thanks for letting me know. Seems to be a bug for a while now. The dev version also has it...

**Comment by ivanr** [comment]
Fixed in 1.22.2, now running on dev. More refinements will follow.
