### ISSUE TITLE
Chrome 47 / OS X, OCSP stapling

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#279]
https://www.ssllabs.com/ssltest/viewClient.html?name=Chrome&version=47&platform=OS%20X
https://dev.ssllabs.com/ssltest/viewClient.html?name=Chrome&version=47&platform=OS%20X

> OCSP stapling	Yes

Support OCSP stapling on Mac
https://code.google.com/p/chromium/issues/detail?id=430714
WontFix
-

**Comment by ivanr** [comment]
From my point of view, if Chrome requests stapled OCSP responses from servers, they support it. If they then don't do anything with them, it's their bug, not mine. Yes, it would be better to have more accurate information, but I am not going to spend time reading bug reports for all clients out there.
