### ISSUE TITLE
Server send too many certs, not recognized

### ISSUE THREAD

**Issue by KommX** [ssllabs/ssllabs-scan#280]
https://www.ssllabs.com/ssltest/analyze.html?&hideResults=on&d=banking.dkb.de
https://dev.ssllabs.com/ssltest/analyze.html?d=banking.dkb.de&hideResults=on

This server sends 3 certs but only needs to send 2. In the past I saw many test results where this was recognized and led to a little warning saying that this is unnecessary.

**Comment by ivanr** [comment]
This is not a bug. The sent certificates form a chain. Although a shorter chain might be possible with come clients, the longer chain might still be necessary for older clients.

**Comment by selecadm** [comment]
Huh? Why did it stop being a chain issue? Especially when the CA recently started considering it so. 

Now I don't see this being considered an issue by Symantec also. What happened?

**Comment by ivanr** [comment]
Previously, it was wrong to highlight this case as a chain issue in SSL Labs. The warning might have been correct with any one trust store, but when you consider a larger number of trust stores, each with different roots, different paths might be needed to trust to be established.

For that reason, SSL Labs now warns about extra certs if there are duplicates or certificates that do not form a chain.

**Comment by KommX** [comment]
Ok, I understand. But what does "In trust store" in the "Certifications Path" section then mean? Which trust store does the test consider to come to this result?

**Comment by ivanr** [comment]
SSL Labs uses Mozilla's trust store. In the future, I plan to have determine trust separately for each of the major trust stores (e.g., Windows, OSX, and Mozilla).
