### ISSUE TITLE
Make RootCerts generation sort order deterministic to avoid changes

### ISSUE THREAD

**Issue by plaintextcity** [ssllabs/ssllabs-scan#282]
I have a "watch" script to check various URL's to detect changes, including the certificate trust lists included in Mozilla and Microsoft.  The getRootCertsRaw provides the same CTL function, so I added the URL to my watch list to see when it changes.  My script just uses curl to pull the resource, then generates a sha1sum and compares with the last known sum, and keeps versions that change.  Very simple :)

IE:
curl.exe -o ssllabs.txt https://api.dev.ssllabs.com/api/v2/getRootCertsRaw
sha1sum ssllabs.txt

The versions below were retained because the were different, as you can see there are only two sizes:

    > dir ssllabs*
    11/30/2015  XX:XX PM           249,663 ssllabs.txt.20151130
    12/01/2015  XX:XX AM           249,663 ssllabs.txt.20151201
    12/04/2015  XX:XX AM           245,887 ssllabs.txt.20151204
    12/07/2015  XX:XX AM           245,887 ssllabs.txt.20151207
    12/10/2015  XX:XX AM           245,887 ssllabs.txt.20151210
    12/11/2015  XX:XX AM           245,887 ssllabs.txt.20151211

However, the sha1sum's changed:

    301781365f439d26b58dd097173e301f4f50ea7e *ssllabs.txt.20151130
    3eb9ded503cb71b2e2dabbe5f6da2fd48fbf1c93 *ssllabs.txt.20151201
    298102354145183a6723d6d307d56652a123217c *ssllabs.txt.20151204
    275ba303c510da69fc79f2a5900e8e80d966ac66 *ssllabs.txt.20151207
    f98d21ef3671f0953941ebef65a205d670ed9d0f *ssllabs.txt.20151210
    58391350a3a483f74429aad587691c9534775ea2 *ssllabs.txt.20151211

If there's a way to force a specific order to avoid changes that would help.  Worst case I could just sort the files before calculating the sha1sum.

**Comment by ivanr** [comment]
What happened there is that the JVM keeps its trust anchors in a Set, where they are not ordered. I am now sorting them by CN. Does this work: https://api.dev.ssllabs.com/api/v2/getRootCertsRaw
