### ISSUE TITLE
Trust of Symantec Class 3 root

### ISSUE THREAD

**Issue by plaintextcity** [ssllabs/ssllabs-scan#283]
Symanatec on 12/1 announced ["Discontinued Use of VeriSign G1 Roots"](https://knowledge.symantec.com/support/ssl-certificates-support/index?page=content&id=ALERT1941&actp=LIST&viewlocale=en_US)

This makes sense as the G1 root is 1024bit.

Further information is provided in [Licensing and Use of Root Certificates](https://www.symantec.com/page.jsp?id=roots):

> Root 2
> VeriSign Class 3 Public Primary CA
> Description: This root CA is the root used for Secure Site Pro Certificates, Premium SSL Certificates > and Code Signing Certificates. Effective December 1, 2015, Symantec has discontinued the use of the VeriSign G1 root for issuance of public SSL certificates. **This root CA will be used to issue non-public SSL certificates.** Browsers/root store operators are encouraged to remove/untrust this root from their root stores. 

Google responded to this with a blog [Proactive measures in digital certificate security](https://googleonlinesecurity.blogspot.com/2015/12/proactive-measures-in-digital.html)

The gist of which is that rather than "UNTRUST" the root, Google feels it neccessary to actively "DISTRUST" it.  On twitter Ryan Sleevi clarified this and said that any certificate that has a chain to the G1 root, **even if it has another valid chain** will be DISTRUSTED.   This seems like a very dangerous plan, which depends on site operators removing the cross certified intermediates from their bundles to avoid the chain.  SSLLabs server scan already provides a warning to do this, however the warning may need to be escalated to mark the site as T UNTRUSTED if a chain to the old root is resolved.  (This can't happen of course if SSLLabs itself removes the root).

Further risk with this whole plan has to do with Intermediate Certificate Authority caching.  In some browsers, an ICA will be cached.  This could make cross-certified chains resolve after a different site has been loaded, for example, using IE on Windows, making subsequent access by Chrome distrusted.

**Comment by selecadm** [comment]
I lost the point: https://github.com/ssllabs/ssllabs-scan/issues/280

**Comment by ivanr** [comment]
Tricky. If sites that use certificates related to G1 really do stop working in Chrome I suppose a warning would be in order, but that will be very difficult explaining to end users.

**Comment by ivanr** [comment]
My understanding of this problem is that, because Chrome relies on OS libraries for certificate validation, they can't choose which trust path they use. Then, if it happens that the path (selected by the OS libraries) includes the blacklisted G1 certificate, the certificate validation fails.

**Comment by ivanr** [comment]
Closing this old ticket.
