### ISSUE TITLE
Remove "R" Reference Browser from iOS 6 

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#285]
see
https://mixpanel.com/trends/#report/ios_7

**Comment by selecadm** [comment]
WontFixed 9 months ago: https://github.com/ssllabs/ssllabs-scan/issues/74

Let's see…

**Comment by RobTho** [comment]
Marketshare is <0.5%

**Comment by bhushan5640** [comment]
Removed "R" Reference Browser from iOS 6. Deployed on dev.ssllabs.com
