### ISSUE TITLE
PostSignum Root QCA 2 not trusted by SSLLabs?

### ISSUE THREAD

**Issue by martinsuchan** [ssllabs/ssllabs-scan#286]
Hi, I've just noticed that the PostSignum Root QCA 2 is not trusted in SSLLabs?
https://crt.sh/?caid=224

Example of a domain using certificate issued by this Root CA:
https://www.ssllabs.com/ssltest/analyze.html?d=viola.mfcr.cz

![screenshot 7](https://cloud.githubusercontent.com/assets/3041397/11913010/6be469d0-a656-11e5-921f-e8e21f16fcb3.png)

This CA is currently in Root trust store on Windows and is trusted by IE, Edge, Chrome or Opera running on Windows machine.
Note it's currently not trusted in Firefox and Microsoft plans to remove this CA from trusted roots in January 2016, this does not change the fact that the SSLLabs test Root trust store is not sync with Windows trust store.
https://blogs.technet.microsoft.com/mmpc/2015/12/17/microsoft-updates-trusted-root-certificate-program-to-reinforce-trust-in-the-internet/

Maybe SSLLabs should be more transparent about in which trust stores is the Root for given domain certificate located?

**Comment by selecadm** [comment]
> this does not change the fact that the SSLLabs test Root trust store is not sync with Windows trust store

SSL Labs currently uses only Mozilla trust store. It's not a bug not to consider other trust stores. It's a enhancement to do so.

**Comment by martinsuchan** [comment]
I agree that it's an enhancement. Just like it shows HSTS preload in different browsers it could show trust status on different platforms/browsers.

**Comment by ivanr** [comment]
Yes, it could add support for multiple stores, but that has nothing to do with PostSignum :)
