### ISSUE TITLE
"Incorrect order" for btc-trade.com.ua

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#288]
https://www.ssllabs.com/ssltest/analyze.html?d=btc-trade.com.ua
https://dev.ssllabs.com/ssltest/analyze.html?d=btc-trade.com.ua

The order isn't incorrect, just missing SHA2 intermediate under SHA1 root + that SHA1 root sent.

![image](https://cloud.githubusercontent.com/assets/10382329/11970993/ab927caa-a946-11e5-9a96-8b546ada675f.png)

**Comment by ivanr** [comment]
I hear what you're saying, but "incorrect order" is close enough in meaning. Also, it identifies the problem so that a human can deal with it.
