### ISSUE TITLE
Handshake Simulation, loads of "protocol or cipher suite mismatch"

### ISSUE THREAD

**Issue by tiferrei** [ssllabs/ssllabs-scan#290]
Hello, I was able to optimise my web server to an A+, but now I get loads of "protocol or cipher suite mismatch", am I being to strict? Also, now that I have the A+, how can I get 100% on the Protocol Support, Key Exchange and Cipher Strength?

website: tiferrei.com

Thank you,
tiferrei

![screen shot 2016-01-01 at 18 22 31](https://cloud.githubusercontent.com/assets/8849915/12071760/a765f560-b0b4-11e5-92bd-5f67867ce2e4.png)

[SSL Server Test: tiferrei.com.pdf](https://github.com/ssllabs/ssllabs-scan/files/75994/SSL.Server.Test.tiferrei.com.Powered.by.Qualys.SSL.Labs.pdf)

**Comment by selecadm** [comment]
> but now I get loads of "protocol or cipher suite mismatch", am I being to strict?

TLS 1.0 is disabled.

> how can I get 100% on the Protocol Support

Disable TLS 1.1 also.

> Key Exchange

Obtain new certificate with 4096-bit RSA key, use 4096-bit Diffie-Hellman parameters and 384-bit elliptic curve (secp384r1).

> Cipher Strength

This must not be 100%. Standards say 128-bit encryption must be supported.

**Comment by tiferrei** [comment]
Hum so should I disable both TLS 1 and 1.1 or just the 1.1?

**Comment by selecadm** [comment]
Both for 100% protocol.

**Comment by ivanr** [comment]
You are most likely being too strict. But, at the end of the day, if you're happy with the performance of a 100%-graded server and with that fact that some (many?) clients can't connect, then all is well.

BTW, please use this tracker only to report issues with the test. You can post general questions on the SSL Labs community site: https://community.qualys.com/community/ssllabs

**Comment by tiferrei** [comment]
Sure, my website doesn't need to be compatible with a lot of platforms, but it really needs to be as safe as possible has it handles personal files.
