### ISSUE TITLE
Handshake Simulation for Android

### ISSUE THREAD

**Issue by St3ve92** [ssllabs/ssllabs-scan#291]
Hello,

Your "SSL Server Test" is a very nice tool :o)  but I've a small criticism about "Handshake Simulation" for Android.

The "Handshake Simulation" for different releases of Android is quite confusing...

I suppose it simulates the handshake with the default browser ?
It seems quite curious to do that...
You certainly know that you can install on Android many different browsers (Firefox, Chrome, Opera...) like on Windows ! ;o)
So, why don't you take browser type into account for Android devices like you do for Windows ???

For example, I set on a "Tomcat 7" server only 3 strong cipher suites:

TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384

Your handshake simulation gives:

Android 4.0.4 	Protocol or cipher suite mismatch
Android 4.1.1 	Protocol or cipher suite mismatch
Android 4.2.2 	Protocol or cipher suite mismatch
Android 4.3 	Protocol or cipher suite mismatch

You should clarify: "with default Android browser" (usually obsolete and not upgradable !)

I've tested last available releases in "Google Play" of Firefox, Chrome and Opera : they work fine on Android 4.2.2 and 4.1.1 with these strong cipher suites ! :o)
I can connect to the server, using HTTPS, without any problem.

Please, tell me if I missed something...

Thanks.

Best regards,

Steve.

**Comment by selecadm** [comment]
"Android" on SSL Labs means Android browser. Other browsers' capabilities are different, and so are mentioned too.

Firefox capabilities should be the same on all platforms.

Chrome capabilities may be different, but it's more about Apple software issues, so there should be different simulations for Chrome on Windows and Chrome on OS X.
