### ISSUE TITLE
Client Test: Which client has problems with DH groups >= 2048 bit?

### ISSUE THREAD

**Issue by KommX** [ssllabs/ssllabs-scan#293]
It would be nice to see in the client test if this specific client only has support for small DH groups with <= 1024 bit p.

**Comment by selecadm** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=dh4096.serverhello.com
https://dev.ssllabs.com/ssltest/analyze.html?d=dh4096.serverhello.com

> Java 7u25	Client does not support DH parameters > 1024 bits
TLS 1.0   TLS_DHE_RSA_WITH_AES_128_CBC_SHA   DH 4096
Java 8u31	Client does not support DH parameters > 2048 bits
TLS 1.2   TLS_DHE_RSA_WITH_AES_128_GCM_SHA256   DH 4096

Java 6u45 is similar to Java 7u25, but my site requires SNI.

Among browsers, you typically won't have problems with DH <= 4096, but I've been thinking about it too.

**Comment by KommX** [comment]
Thanks for the info!
