### ISSUE TITLE
Invalid: Server provided more than one HSTS header 

### ISSUE THREAD

**Issue by busbauen** [ssllabs/ssllabs-scan#294]
Got this HSTS comment scanning my server. It's wrong I just send the heade once.

bus

**Comment by ivanr** [comment]
What's your hostname?

**Comment by busbauen** [comment]
cloud.androidloves.me

**Comment by selecadm** [comment]
How is this called sending once?

> HTTP/1.1 200 OK
Date: Sat, 09 Jan 2016 23:47:06 GMT
Server: Apache/2.4.7 (Ubuntu)
Strict-Transport-Security: max-age=15768000
-
Public-Key-Pins: pin-sha256="f34hUQIulHdIkuBfnlaMXBvfp0135eKnj31WzuQRJjM="; pin-sha256="TsbfSXbUOkDqow/mBdhBJNTJkl3WQsKg2EOuB6kRQWU="; max-age=7776000;
X-Powered-By: PHP/5.5.9-1ubuntu4.14
Set-Cookie: oc4cgvjz9051=c559hu217d4u8lkotaalli14e1; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
-
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
X-Robots-Tag: none
Content-Type: text/html; charset=UTF-8

**Comment by richhollis** [comment]
Just in case it helps others: This just hit me too and I was trying to figure out where the extra header crept in from - I thought it was happening from nginx, but it was being added from rails, by way of the production config: 

```ruby
# Force all access to the app over SSL, use Strict-Transport-Security, and use secure cookies.
config.force_ssl = true
```

**Comment by ivanr** [comment]
Also useful, in the next version of the API, all HTTP responses with full headers are exposed. For example: https://dev.ssllabs.com/api/v3/analyze?host=www.cloudflare.com&all=on (look for "httpTransactions").

**Comment by richhollis** [comment]
Very nice! I didn't even realise this project was on github - so cool.

**Comment by gnussbaum1** [comment]
I'm getting this using IIS 7.5 and I can't find where it's happening.  Any ideas?  I installed the HSTS module and I know where that puts the code but don't know where the other is

**Comment by richhollis** [comment]
@gnussbaum1 In my case the order of the headers was significant - the rails headers were above the nginx headers. Is it possible the extra header is being added from your application? What happens if you use a blank web site project with the module? How many headers do you get then.

**Comment by katopz** [comment]
In my case it stuck old cache so it appear twice and it can be clear by navigate to `chrome://net-internals/#hsts`

**Comment by aberenyi** [comment]
It's worth noting that [helmet](https://helmetjs.github.io/) adds HSTS headers by default too.
