### ISSUE TITLE
Public suffix list is outdated on production and broken on development

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#299]
Scanning second-level domain.

While production shows this:
> Prefix handling	Non-prefixed access only, but DNS not configured for prefix

Development shows this:
> Prefix handling	Not required for subdomains

For new TLDs it's always "Not required for subdomains".

**Comment by ivanr** [comment]
Example please?

**Comment by selecadm** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=rc4.io
> Prefix handling	Non-prefixed access only, but DNS not configured for prefix

https://dev.ssllabs.com/ssltest/analyze.html?d=rc4.io
> Prefix handling	Not required for subdomains

https://www.ssllabs.com/ssltest/analyze.html?d=ssl.rip
https://dev.ssllabs.com/ssltest/analyze.html?d=ssl.rip
> Prefix handling	Not required for subdomains

**Comment by ivanr** [comment]
Hmmm, I don't see .rip on the list https://publicsuffix.org/list/public_suffix_list.dat
I did update it (dev). However, I have also removed any mention of prefix handling from the UI for now. Dev doesn't check in DNS for variants any more and I'll think about what I want to do in the future, if anything.

**Comment by nextPrime** [comment]
Actually, _.rip_ is there. 

>  // rip : 2014-07-10 United TLD Holdco Ltd. 
>  rip 

https://github.com/publicsuffix/list/blob/master/public_suffix_list.dat#L9464

**Comment by ivanr** [comment]
Right. Sorry, I missed it.
