### ISSUE TITLE
Contradiction between cipher suites and handshake simulation

### ISSUE THREAD

**Issue by HansWurst33** [ssllabs/ssllabs-scan#302]
Test case:
https://www.ssllabs.com/ssltest/analyze.html?d=lidl-voyages.ch&s=185.5.82.223
https://dev.ssllabs.com/ssltest/analyze.html?d=www.lidl-voyages.ch&s=185.5.82.223

Both versions say that "IE 8 / XP" uses "TLS_RSA_WITH_3DES_EDE_CBC_SHA" to connect but this cipher suite is missing in the list of cipher suites.

**Comment by RobTho** [comment]
found simmilar (with RC4 issue here) and page got A+ / no RC4 warn
https://dev.ssllabs.com/ssltest/analyze.html?viaform=on&d=caseking.de
https://www.ssllabs.com/ssltest/analyze.html?d=caseking.de

other:
please also note the indemediate extra download cert difference between
v1.21.13 > v1.22.16 on the URL above

**Comment by selecadm** [comment]
> Both versions say that "IE 8 / XP" uses "TLS_RSA_WITH_3DES_EDE_CBC_SHA" to connect but this cipher suite is missing in the list of cipher suites.

SSL Labs lists cipher suites supported by WWW subdomain as specified in SNI.
3DES is supported by the default host, and is negotiable with non-SNI clients.

> found simmilar (with RC4 issue here) and page got A+ / no RC4 warn

Similar. caseking.de negotiates RC4 with non-SNI clients.

> other:
please also note the indemediate extra download cert difference between
v1.21.13 > v1.22.16 on the URL above

caseking.de doesn't send intermediate to non-SNI clients.

**Comment by RobTho** [comment]
should there not be a warning, if there is such a stange behavior ?

**Comment by ivanr** [comment]
AFAIK, per-protocol scanning for cipher suites is on the TODO list. A test without SNI could be added too.
