### ISSUE TITLE
Firefox will no longer trust the Equifax Secure Certificate Authority 1024-bit root certificate 

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#304]
Firefox will no longer trust the Equifax Secure Certificate Authority 1024-bit root certificate or the UTN - DATACorp SGC

https://www.mozilla.org/en-US/firefox/44.0/releasenotes/

Please update ssllabs test

**Comment by selecadm** [comment]
Pretty sure even the production was already updated in 2015 year.

**Comment by ivanr** [comment]
@RobTho can you provide an example where this root is trusted in SSL Labs?

**Comment by selecadm** [comment]
It's not. When I was dealing with UTN - DATACorp SGC on 31 December 2015, it had already been distrusted on production.

**Comment by RobTho** [comment]
Hi 
ok i didn't know that you had already implemented that.Thanks
Assumed not and wanted to remind.
