### ISSUE TITLE
Allow hostfile to contain comment lines

### ISSUE THREAD

**Issue by slolife** [ssllabs/ssllabs-scan#305]
Allow hostfile to contain comment lines by ignoring them
Also ignore blank lines

**Comment by ivanr** [comment]
May I propose that you submit a patch for this? It's a great idea for a first contribution!

**Comment by ingben** [comment]
I think this can be closed. See [this line](https://github.com/ssllabs/ssllabs-scan/blob/stable/ssllabs-scan.go#L894).

**Comment by ivanr** [comment]
Thanks!
