### ISSUE TITLE
www subdomain

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#306]
Hi
maybe it would be a better idea to test 
e.g domain.com and www.domain.com a litte bit more seperated than it is currently done.

Suggestion:
If enter www.domain.com or Domain.com still test both but seperated simmilar to a URL with several IPs,
next to list www.domain.com and domain.com like currently done for different IPs (of cause ignore if one of it do not exist) and calculate result by worse result, like done with different IP results currently.

**Comment by ivanr** [comment]
On dev.ssllabs.com it's fully separated now. I've thought about testing example.com if www.example.com is entered, but my current thinking is to simply propose a link to test it, not mix the two.

**Comment by RobTho** [comment]
Hi,

this way is also a good solutions to resolve this lttle mixup :)

Thanks.

**Comment by fishouttah20** [comment]
@ivanr Oh no! I get that this was done for the website but this change appears to have been propagated down to the API and pushed into production (1.22.37) My previous list of domains assumed that WWW would be checked automatically, now I have to double the size of my domains list to scan and sites with both WWW.domain and just domain will have twice as many entries.

Is this really more helpful for most use cases? I can't see how it is for bulk scans of large sets of (miss)managed domains.

Could this behaviour be configurable? I'd target a previous API version but want the benefit of DROWN testing.

**Comment by ivanr** [comment]
The behaviour is not going to change at the API level. What could happen in the future is that there is a higher-level API that tests "sets" of hostnames.

For now, you could extend ssllabs-scan with a switch that initiates potentially 2 scans for each hostname given (based on DNS configuration).

**Comment by fishouttah20** [comment]
I appreciate the decision has been made and it's probably the right call moving forward to keep things clear. 

It's just that without any announcement a number of users are going to kick off a new scan in the coming days and find that a sizeable chunk of their endpoints  have disappeared or they have a load of hosts coming back with assessment failed which worked fine just last week.

**Comment by ivanr** [comment]
I understand and I am sorry that you were surprised. However, I did announce the change on 1 Dec 2015 on the ssllabs-devel mailing list, which is where I discuss all matters related to the API. (SourceForge's mailing list archives seem to be down at the moment so I can't leave the link to the message.)

**Comment by fishouttah20** [comment]
Didn't realize you had announced it previously, I'll follow the dev mailing list (once it's back up). Thanks for providing this free service and all that you've done for progressing awareness around SSL/TLS, and your book which is a fantastic resource!
