### ISSUE TITLE
Strict Transport Security (HSTS) Invalid Failed to parse header 

### ISSUE THREAD

**Issue by N3bu14** [ssllabs/ssllabs-scan#307]
Hello,

can you tell me where exactly the Problem is? It was working ca. 2-3 Months ago, now I get this error as seen in the Subject. 
My Header:

Strict-Transport-Security: max-age=31536000; include SubDomains

Am I missing something?

Regards

**Comment by ivanr** [comment]
Yes, "includeSubDomains" should be a single word.

**Comment by N3bu14** [comment]
Thank you!
