### ISSUE TITLE
Assessment failed: Unable to connect to the server 

### ISSUE THREAD

**Issue by renarios** [ssllabs/ssllabs-scan#308]
Hi! 
I host a few domains on the same ip address. After successfully testing one (www.superjuf.com), the other domains fail with: **Assessment failed: No secure protocols supported**
After reporting this issue on ssllabs, Ivan asked me to test the domains on dev.ssllabs.com. Same here: Fist domain went well, the others fail with **Assessment failed: Unable to connect to the server**.
Please help me on this issue.
Cheers,
Rene

**Comment by ivanr** [comment]
It seems like a problem with your server. I managed to open the web site in my browser once, but I am unable to do it again. From the server, I get this:

$ openssl s_client -connect www.superjuf.com:443 -servername www.superjuf.com
connect: Connection refused
connect:errno=61

**Comment by renarios** [comment]
I found the reason why: the server got banned. Now it works on dev.ssllabs.com. 
Thanks helping!

**Comment by sabdullah98** [comment]
@renarios  please share how you got it working, i am facing the same issue

**Comment by renarios** [comment]
@sabdullah98 My issue was that the ssllabs server got banned by fail2ban

**Comment by sailfish009** [comment]
firewall (sw / hw) should have to allow port 443 (https default port)
