### ISSUE TITLE
Incorrect renegotiation results with Akamai nodes

### ISSUE THREAD

**Issue by seccubus** [ssllabs/ssllabs-scan#310]
Reference: https://www.ssllabs.com/ssltest/analyze.html?d=akamai.com&s=23.59.205.233&latest

Says:
```
Protocol Details
Secure Renegotiation	Supported
Secure Client-Initiated Renegotiation	No
Insecure Client-Initiated Renegotiation	No
```

When I connect manually the tls handshake shows that renegotionation is supported and I can issue multiple renegotiations at the beginning of the session:
```
$ ./bin/openssl.Darwin.x86_64 s_client -connect 23.59.205.233:443 2>&1
CONNECTED(00000003)
<snip>
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
<snip>
    Start Time: 1454925327
    Timeout   : 300 (sec)
    Verify return code: 20 (unable to get local issuer certificate)
---
R
RENEGOTIATING
depth=2 C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
verify error:num=20:unable to get local issuer certificate
R
RENEGOTIATING
depth=2 C = IE, O = Baltimore, OU = CyberTrust, CN = Baltimore CyberTrust Root
verify error:num=20:unable to get local issuer certificate
^C
```

However if I follow the test described at https://blog.ivanristic.com/2009/12/testing-for-ssl-renegotiation.html I get a different result:

```
$ ./bin/openssl.Darwin.x86_64 s_client -connect 23.59.205.233:443 2>&1
CONNECTED(00000003)
<snip>
---
HEAD / HTTP/1.0
R
RENEGOTIATING
140735261676368:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:s3_pkt.c:656:
```

Is ssllabs giving the incorrect result or am I missing something here?

**Comment by ivanr** [comment]
I can't replicate this problem because the SSL Labs report now correctly indicates secure client-initiated renegotiation as supported. What could have happened is that there were two servers with the same IP address, and SSL Labs seeing one while you're seeing another.
