### ISSUE TITLE
domain "jobs" returns result

### ISSUE THREAD

**Issue by ukaccount123** [ssllabs/ssllabs-scan#313]
https://www.ssllabs.com/ssltest/analyze.html?d=jobs

SSL Report: jobs (50.19.241.165)

Subject 	*.pearsoninternal.jobs
Fingerprint SHA1: ccdf7fd45391a6114eeff0eed1681b58d581a988
Pin SHA256: ceqZH2kNoIoda05qfrJX0eKyOxNypmTTbVRZDTm1RuM=
Common names 	*.pearsoninternal.jobs   MISMATCH
Alternative names 	*.pearsoninternal.jobs pearsoninternal.jobs

**Comment by ukaccount123** [comment]
In face various other "domains" do this e.g. "finance"

https://www.ssllabs.com/ssltest/analyze.html?d=finance

resolves to 104.236.139.31

Could this be due to the many new TLDs?

**Comment by ivanr** [comment]
It's mostly because SSL Labs will attempt to prepend "www" to whatever hostname is entered. However, this is true only in production. The next version changes behaviour and doesn't do this any more: https://dev.ssllabs.com/ssltest/analyze.html?d=jobs&hideResults=on
