### ISSUE TITLE
(EC)DH strength not shown for other detected suites

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#315]
https://www.ssllabs.com/ssltest/analyze.html?d=oag.ca.gov
https://dev.ssllabs.com/ssltest/analyze.html?d=oag.ca.gov

> Other detected suites (e.g., used with older protocol versions)
> TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x39) 256
> 
> Forward Secrecy   Weak key exchange   WEAK

**Comment by bhushan5640** [comment]
Fixed in per protocol suite detection
