### ISSUE TITLE
Questions to the sql pulse schema

### ISSUE THREAD

**Issue by stoennies** [ssllabs/ssllabs-scan#316]
Hi all,

right now I am going to implement a java based client for the ssl-labs api. I also would like to use the sql pulse schema. But now I have some fields in there which I do not know how to calculate the content with the ssl-labs api e.g. for the suites:

```
private Boolean supports_no_bits;
private Boolean supports_low_bits;
private Boolean supports_128_bits;
private Boolean supports_256_bits;

```
Can anybody help?

Bests
Sushi

**Comment by ivanr** [comment]
Sure:
1. Set all flags to false.
2. Loop through all supported cipher suites.
3 For each suite, determine encryption strength and set the corresponding flag.

**Comment by stoennies** [comment]
Thanks Ivanr!
May I also ask for the other open fields?

1) 	private Boolean em_ssl2, em_40_bits, em_56_bits, em_64_bits;
2)	private Integer toleranceMinorLow;
3)	private Integer toleranceMinorHigh;
4)	private Integer toleranceMajorHigh;
5)	private String trustAnchor;
6)	private Integer rg2009b_grade;
7)	private String beastSuites;
8)	private Integer protocolIntolerance;
9)	private Integer miscIntolerance; 

Bests
Sushi
