### ISSUE TITLE
API should return ALPN status

### ISSUE THREAD

**Issue by wiktor-k** [ssllabs/ssllabs-scan#318]
Currently API returns only NPN status fields (`supportsNpn` and `npnProtocols`) but there is no ALPN status field. The ALPN status is available through the website (#86).

Tested on this endpoint: https://api.ssllabs.com/api/v2/getEndpointData?host=twitter.com&s=199.59.150.39

Thank you for such a great service!

**Comment by ivanr** [comment]
Implemented in 1.22.28, now running on dev.ssllabs.com. Thanks!

https://api.dev.ssllabs.com/api/v3/analyze.html?host=twitter.com&all=on

**Comment by wiktor-k** [comment]
Thank you very much! :)
