### ISSUE TITLE
Anyone can hide results, even if they didn't originally request them

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#319]
First, invoke the "clear cache" function. Wait for the new assessment to complete. The "hide" function will appear.

**Comment by J0WI** [comment]
It also seems to be IP based. This results in multiple issues, since not every device has a unique and persistent external IP.

**Comment by ivanr** [comment]
It's only partially IP-based. You are allowed to hide an assessment if either your IP or session cookie match.
