### ISSUE TITLE
SNI detection doesn't work reliably

### ISSUE THREAD

**Issue by HansWurst33** [ssllabs/ssllabs-scan#320]
Example:
https://www.ssllabs.com/ssltest/analyze.html?d=lidl-reisen.de
https://www.ssllabs.com/ssltest/analyze.html?d=universal.at

You can see that they share the IP 91.236.122.125:
https://www.ssllabs.com/ssltest/analyze.html?d=lidl-reisen.de&s=91.236.122.125
https://www.ssllabs.com/ssltest/analyze.html?d=universal.at&s=91.236.122.125

In the results for lidl-reisen.de there is nothing mentioned about SNI, but for universal.at there is:
![2016-02-24 08_37_34-ssl server test_ universal at powered by qualys ssl labs](https://cloud.githubusercontent.com/assets/16898078/13278620/182e9198-dad2-11e5-8bb3-6b501d4a315a.png)
![2016-02-24 08_37_03-ssl server test_ lidl-reisen de powered by qualys ssl labs](https://cloud.githubusercontent.com/assets/16898078/13278619/182bd6d8-dad2-11e5-91d5-64c69af17770.png)

I am pretty sure that yesterday I saw "SNI" mentioned on the result for lidl-reisen.de?!

**Comment by ivanr** [comment]
That's because universal.at and www.universal.at are differently configured. In production, we sometimes show one and sometimes the other. In the next version, behaviour changes, and we inspect the hostname exactly as provided. So have a look at this:

https://dev.ssllabs.com/ssltest/analyze.html?d=universal.at
https://dev.ssllabs.com/ssltest/analyze.html?d=www.universal.at

**Comment by HansWurst33** [comment]
In dev it's the same right now:
https://dev.ssllabs.com/ssltest/analyze.html?d=www.lidl-reisen.de&s=91.236.122.125
https://dev.ssllabs.com/ssltest/analyze.html?d=universal.at

**Comment by ivanr** [comment]
What is the same? www.lidl-reisen.de works without SNI from what I can tell.

**Comment by nextPrime** [comment]
@HansWurst33 That two hosts share the same IP doesn't mean they both require SNI to work correctly. When SNI extension is not sent, the server 91.236.122.125 sends the certificate of www.lidl-reisen.de, so visiting www.lidl-reisen.de doesn't require SNI, but visiting other hosts on the same IP do.

**Comment by HansWurst33** [comment]
Thanks for the answers. I now understand that one site is the one that works with the default certificate that is delivered for the shared IP address.
