### ISSUE TITLE
Warning Bar for DROWN Attack 

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#321]
Beside SSL2 supporting Servers already get an "F"

"This server supports SSL 2, which is obsolete and insecure. Grade set to F."

I think it would be a good idea to add an extra notice to Drown attack to this Warning Bar ?

at least "MORE INFO" Point to https://blog.qualys.com/securitylabs/2016/03/01/drown-abuses-ssl-v2-to-attack-rsa-keys-and-tls 

Or better extra Bar for "Drown" like for "Poodle" and extra info @Protocol Details

BEAST attack:
POODLE (SSLv3):
POODLE (TLS):
Drown (SSLv2): ......
Downgrade attack prevention:
SSL/TLS compression:

To make clear there is a real risk still supporting SSL2

**Comment by ivanr** [comment]
There will be a bar tomorrow. @selecadm that's already done, but not deployed. Will be tomorrow too.

**Comment by ivanr** [comment]
This is done now on dev.ssllabs.com.
