### ISSUE TITLE
API Documentation missing sha1Hash and pinSha256

### ISSUE THREAD

**Issue by fishouttah20** [ssllabs/ssllabs-scan#322]
Looked in the API documentation (all versions) to see where a hash of the cert was being stored and couldn't find it. Looked in json output to find that it's in Endpoints - Details - Cert - sha1Hash. Noticed that pinSha256 also wasn't referenced in API docs.

**Comment by ivanr** [comment]
The v3 API is work in progress. There's currently no documentation for it, but there will be in due course.
