### ISSUE TITLE
Hang on "Simulating handshakes"

### ISSUE THREAD

**Issue by J0WI** [ssllabs/ssllabs-scan#323]
v1.22.37 shipped with a additional check for the drown attack.
This slows down the test a lot (> 20 min) without any other information than "Simulating handshakes", specifically on shared hosting providers with a bunch of IPs.

**Comment by ivanr** [comment]
Please give me one hostname as an example. I suppose there's some heavy key/certificate reuse with a large number of hostnames that SSL Labs is checking for DROWN.

**Comment by J0WI** [comment]
e.g.https://www.ssllabs.com/ssltest/analyze.html?d=schiller.metanet.ch

**Comment by ivanr** [comment]
Indeed, it's slow, because there are > 1600 candidates for DROWN testing. I suppose I could give up after a certain number of hosts, but then the test would be inaccurate. Hmmm.

**Comment by J0WI** [comment]
Why is the test that much slower than on https://drownattack.com/?
Doesn't it cache any results?

**Comment by ivanr** [comment]
No, there's no result caching at the moment.

**Comment by ivanr** [comment]
In 1.22.38 I've limited the number of DROWN checks to 25. It's being installed on dev.ssllabs.com now.
