### ISSUE TITLE
Chain issues shouldn't say "contains anchor" for servers with self-signed certificates

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#324]

**Comment by bhushan5640** [comment]
Works for me
![self-signed-cert](https://cloud.githubusercontent.com/assets/6083185/17883845/9905be60-6932-11e6-9085-097b520df928.jpg)

**Comment by ivanr** [comment]
Closing. Will reopen if we come across it again.

**Comment by ivanr** [comment]
I came across is here: https://dev.ssllabs.com/ssltest/analyze.html?d=tls-test-01-sep-2016-01.qlued.net

**Comment by bhushan5640** [comment]
Fixed. deployed on dev.
Issue was when self signed certificate is CA cert
