### ISSUE TITLE
drownVulnerable False on endpoints with SSLv2 supported

### ISSUE THREAD

**Issue by fishouttah20** [ssllabs/ssllabs-scan#326]
Trying to understand the logic for the drownVulnerable parameter. Initially thought it was only if the censys data had a hostname showing as drown vulnerable but have found hosts (apologies can't disclose) where test.drownattack.com shows host is currently vulnerable but drownVulnerable is False. Also found where API shows endpoint currently supports SSLv2 but drownVulnerable is False. This is on production 1.22.37

**Comment by ivanr** [comment]
drownVulnerable will be set if the same RSA key or matching certificate is found on another server with SSL v2 enabled. If the server support SSLv2 that's a vulnerability in itself, but drownVulnerable won't be set, allowing differentiation between the two.

**Comment by fishouttah20** [comment]
Ah, ok. Thanks for clarification, much appreciated
