### ISSUE TITLE
Chacha20 and Poly1305

### ISSUE THREAD

**Issue by andrepereiradasilva** [ssllabs/ssllabs-scan#33]
As a suggestion, shouldn't the use of ChaCha20-Poly1305 and AES GCM as a prefered ciphers considered to obtain an A+ ( or A++ ;) )?

As you know better than i, performance is an important part of https implementations.

As posted in Google Security blog post and Adam Langley in his blog, the performance of ChaCha20-Poly1305 (without special hardware) is pretty good, and it's considered secure.

> https://www.imperialviolet.org/2013/10/07/chacha20.html
> http://googleonlinesecurity.blogspot.pt/2014/04/speeding-up-and-strengthening-https.html

From my point of view, who configured this ciphers in their servers normally knows what is doing, and so there's a clear effort to have an "exceptional" configuration in terms of security and performance.

As you know, Chacha20-Poly1305 it's not an IETF standard yet, but there is already a rfc draft made by Nir and Langley (https://tools.ietf.org/html/draft-irtf-cfrg-chacha20-poly1305-03 and http://tools.ietf.org/html/draft-mavrogiannopoulos-chacha-tls-03)

Daniel J. Bernstein work on ChaCha20 > http://cr.yp.to/chacha/chacha-20080120.pdf

**Comment by HLFH** [comment]
@ivanr [OpenSSL 1.02g](https://www.openssl.org/news/changelog.html#x1) (03/01/2016) supports CHACHA20-POLY1305. Could you reopen the issue?
