### ISSUE TITLE
Incorrect DROWN grade when certificate is not trusted

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#330]
As reported here: https://community.qualys.com/message/33121
Example site: https://www.ssllabs.com/ssltest/analyze.html?d=www.juventus.jeep.com&s=23.61.194.49&ignoreMismatch=on
There are two issues: 1) the grade is incorrect, should be F and 2) the grade is trust is ignored should also be F.

**Comment by intcc** [comment]
This issue is fixed. Please check in dev.ssllabs.com

Regards,
Yash K.S
