### ISSUE TITLE
dev and production Assessment failed: Unexpected failure [RenegotiationTest]: Exception: Unexpected failure [RenegotiationTest]: Connection failed

### ISSUE THREAD

**Issue by leefisher** [ssllabs/ssllabs-scan#331]
https://dev.ssllabs.com/ssltest/analyze.html?d=origin-wwwtest.vishay.com&hideResults=on

I keep getting failures on my origin-wwwtest.vishay.com  I cannot figure out the issue.

**Comment by intcc** [comment]
Please use https://www.ssllabs.com/ssltest/analyze.html?d=wwwtest.vishay.com&hideResults=on

I am able to view result. 

Regards,
Yash K.S

**Comment by leefisher** [comment]
Hi Yash, I know wwwtest works, but this is verifying from akamai side and not my nginx on origin.

Thanks,
Lee

**Comment by bhushan5640** [comment]
Resolved.
