### ISSUE TITLE
Error with chain of trust with multiple intermediates with same name

### ISSUE THREAD

**Issue by martinsuchan** [ssllabs/ssllabs-scan#332]
See:
https://dev.ssllabs.com/ssltest/analyze.html?d=signed.bad.horse
https://signed.bad.horse

![capture](https://cloud.githubusercontent.com/assets/3041397/14325133/2e41a3fe-fc28-11e5-987a-c65803713d92.PNG)

This domain is more of a joke than actual web, but it uses valid chain with self-signed cert on the top.
The problem is it uses multiple intermediates with same CN and SSLLabs probably uses CN as unique ID for certs, and it then fails to rebuild the original chain of trust.

Expected behavior - the chain of trust should be rebuilt properly for https://signed.bad.horse

**Comment by intcc** [comment]
Overall Rating is T, if trust is ignored, it will be A. Please check in dev.ssllabs.com

Regards,
Yash K.S

**Comment by ivanr** [comment]
From memory, path building does use SKI/AKI if they're present, but it falls back to using Subject/Issuer otherwise. However, I think this is a bug in the "is_self_signed" method, which looks only at Subject/Issuer and not SKI/AKI. Should be easy to fix.

**Comment by bhushan5640** [comment]
Fixed, deployed on Dev.
https://dev.ssllabs.com/ssltest/analyze.html?d=signed.bad.horse
