### ISSUE TITLE
Update BEAST tooltip in SSL Pulse

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#334]
BEAST is generally no longer considered a treat for anyone with modern browsers. And RC4 is certainly not a viable mitigation approach.
Reported by Bálint Szilakszi here: https://twitter.com/szbalint/status/718353976677294081

**Comment by ivanr** [comment]
As discussed in email, it's probably best to remove the BEAST chart altogether. However, it might be a good idea to remove it from the future reports only, leaving previous months as a historical record.

**Comment by bhushan5640** [comment]
It is updated on pulse server.
