### ISSUE TITLE
Colors of "Yes" in Protocol section are incorrect when firewall detected

### ISSUE THREAD

**Issue by nextPrime** [ssllabs/ssllabs-scan#336]
If the protocol support test failed due to firewall restriction, the colors of the "Yes" and "No" for TLS 1.1, TLS 1.0, SSL 3.0 and SSL 2.0 are always red, regardless of whether the condition is secure or not. 
![ssllabs firewall](https://cloud.githubusercontent.com/assets/3375825/14817898/9a68c174-0bec-11e6-81d5-a8f0bdf4e2f0.png)
The "No" for SSL 2.0/3.0 should be black. "Yes" for TLS 1.0 and 1.1 should be black.

**Comment by bhushan5640** [comment]
@nextPrime : issue is resolved, please test on dev.ssllabs.com

**Comment by nextPrime** [comment]
Indeed! Thanks for the info.
