### ISSUE TITLE
Misconfigured v3 API entry point on production servers

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#337]
Version 3 of the API is currently in development, but an experimental deployment has been pushed to production servers. However, it appears that the entry point has been misconfigured.
This is the entry point for v2: https://api.ssllabs.com/api/v2/info
If an equivalent URI is attempted for v3: https://api.ssllabs.com/api/v3/info it is redirected to https://www.ssllabs.com/api/v3/info.
There are two bugs here: 1) the correct v3 entry point should work and 2) access to /api/ should **not** be allowed on the main www.ssllabs.com name. **EDIT:** I made a mistake here; direct access to the /api/ folder should not be allowed on the main web site. SSL Labs should require all API access to go via the separate hostname api.ssllabs.com. Added "not".

**Comment by bhushan5640** [comment]
Please confirm:
1.Correct v3 entry point = https://api.ssllabs.com/api/v3/info

and

2. This /api/ should be allowed means following: 
https://www.ssllabs.com/api/v3/info
https://www.ssllabs.com/api/v2/info

Resolved as per above details. Will be deployed on ssllabs.com with next release.

Correct behaviour observed on dev.ssllabs.com.

**Comment by ivanr** [comment]
I am sorry, I made a mistake when reporting this bug. API access via www.ssllabs.com should **not** be allowed. When I reported the bug, access to /api/v3 was allowed (incorrectly); access to /api/v2 wasn't (correctly).

**Comment by bhushan5640** [comment]
So only following should be allowed :
https://api.ssllabs.com/api/v2/info
https://api.ssllabs.com/api/v3/info

right ?

**Comment by ivanr** [comment]
Correct!

**Comment by ivanr** [comment]
This doesn't appear to be fixed in the just-released production version: https://www.ssllabs.com/api/v3/analyze?host=williamfeely.info&all=done

**Comment by bhushan5640** [comment]
Not deployed in this build.

**Comment by bhushan5640** [comment]
Deployed on prod https://api.ssllabs.com/api/v3/analyze?host=ssllabs.com&all=done
