### ISSUE TITLE
Some user agents are being repeated in the user agent database

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#338]
This was reproted to me via Twitter, but unfortunately I don't have a record of whom. The problem is on this page: https://www.ssllabs.com/ssltest/clients.html In several cases, IE user agents appear more than once.

**Comment by bhushan5640** [comment]
We have resolved this issue, currently deployed on dev.ssllabs.com.
More details available at:
https://community.qualys.com/thread/16107

**Comment by ivanr** [comment]
I see now that the links lead to correct user agent instances. Perhaps it would be useful to add testing date to each of the entries. That way, it would be clear that SSL Labs is showing different behaviours of the same browser over time? The date could be part of the name and also be shown on the details page.

**Comment by bhushan5640** [comment]
Or we can add testing date in separate column for each entry. And yes on the details page. But Need to get the testing dates for each one, Dates are mentioned in the comments only for few clients. Where else i can get the dates?

**Comment by ivanr** [comment]
I think the only way is to go through the commit messages and get the dates from there.

**Comment by bhushan5640** [comment]
I also thought of the same option left.
