### ISSUE TITLE
Unable to resolve domain name

### ISSUE THREAD

**Issue by thomo2000** [ssllabs/ssllabs-scan#340]
One of my Domains can not be checked. Unable to resolve domain Name. Other Domains on the same Server with exactly the same (dns) Settings can be checked.

https://dev.ssllabs.com is working!

Problem Domain: groudly.com

**Comment by ivanr** [comment]
DNSSEC is misconfigured on that domain name. Our production servers will respect DNSSEC when present. Have a look here for the details: http://dnsviz.net/d/groudly.com/dnssec/
