### ISSUE TITLE
Trusted path and/or chain issues not shown with alternative SHA-1 intermediate

### ISSUE THREAD

**Issue by jbrowngithubuser** [ssllabs/ssllabs-scan#342]
If a SHA-256 cert can use either a fully SHA-256 trusted path or a partially SHA-256 trusted path, only the fully SHA-256 path is shown, but any SHA-1 intermediates are not marked as "Extra certs" in the "Chain issues" section.

e.g. https://www.ssllabs.com/ssltest/analyze.html?d=www.clarks.co.uk

**Comment by ivanr** [comment]
This is probably a feature request and not a bug. Other paths are not shown because those SHA1 intermediates (served by the server) chain to root(s) that are not in the SSL Labs' root store. If the root store included more roots, more paths would show.
