### ISSUE TITLE
OCSP Must-staple

### ISSUE THREAD

**Issue by SkateScout** [ssllabs/ssllabs-scan#347]
Hi,
it would be great if the SSL-Scan would at least mention if this flag is set in the certificate.
Because on supported clients if enforces the usage of OCSP-Staple information.
And also tell the client that the server must support this feature.

https://community.letsencrypt.org/t/improving-revocation-will-lets-encrypt-support-ocsp-must-staple/4334/40

**Comment by bhushan5640** [comment]
dev.ssllabs.com now supports OCSP must staple test
