### ISSUE TITLE
Assessment failed: Unknown EC curve: 1d

### ISSUE THREAD

**Issue by Michsior14** [ssllabs/ssllabs-scan#348]
Hi,
I have site https://irf2.pl running on Windows Server 2016 with default ciphers suite, because it only works with http/2 in Chrome/Firefox. I wanted to test how insecure is this, but i always get error as above.

**Comment by nextPrime** [comment]
That EC curve is Curve25519, which latest preview versions of Windows Server 2016 and Windows 10 support. SSL Labs correctly detects this EC curve in client tests, but not in server tests.

**Comment by wmark** [comment]
I am getting this sporadically with https://plugin.hosting — https://www.ssllabs.com/ssltest/analyze.html?d=plugin.hosting which runs under Linux and negotiates taking into account the selected cipher suite, so X25519 is agreed on only with a subset of *ciphers.*

**Comment by Hillside502** [comment]
SSL Report v1.23.44 gives this error for:-
https://www.ssllabs.com/ssltest/analyze.html?d=plus.google.com

**Comment by hickford** [comment]
See also https://www.ssllabs.com/ssltest/analyze.html?d=mail.google.com&s=216.58.195.229

> Assessment failed: Unknown EC curve: 1d

**Comment by Hillside502** [comment]
Also:-
https://www.ssllabs.com/ssltest/analyze.html?d=accounts.google.com

**Comment by Wonderfall** [comment]
My websites are also affected since I've enabled x25519 for ECDH : 
https://www.ssllabs.com/ssltest/analyze.html?d=wonderfall.xyz

**Comment by bhushan5640** [comment]
Deployed on dev.ssllabs.com Please verify

**Comment by wmark** [comment]
The error is gone, great!

The group doesn't get recognized, though. For example, this shows that „P-256“ is negotiated when Android 5+ or Chrome would use „X25519“: https://dev.ssllabs.com/ssltest/analyze.html?d=plugin.hosting

**Comment by felipesabino** [comment]
@bhushan5640 Had the same issue and the error is gone for me too, thanks!

**Comment by bhushan5640** [comment]
X25519 and X448 supported

**Comment by istenrot** [comment]
I tested on dev.ssllabs.com and I can't get X25519 key exchange working. I'm about to setup a test server which can be used to verify.

**Comment by istenrot** [comment]
Issues with X25519:

https://dev.ssllabs.com/ssltest/analyze.html?d=x25519.crypto.report&s=2a03%3ab0c0%3a2%3ad0%3a0%3a0%3adf5%3a2001&latest

- Chrome 51 handshake simulation reports cipher suite TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 but it's not listed on the cipher suites list on the report page.
- X25519 ECDH algorithm RSA equivalence is 0 bits

**Comment by bhushan5640** [comment]
@istenrot  Sorry, missed it because this issue was closed.
