### ISSUE TITLE
Return human-readable strings for HTTP status codes

### ISSUE THREAD

**Issue by jbrowngithubuser** [ssllabs/ssllabs-scan#349]
Currently SSL Labs returns the http status code per host as a number e.g. 200, 301, 404.

Can you also return the human readable string versions e.g. "OK", "Moved permanently", "Not Found"

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes
https://hc.apache.org/httpclient-3.x/apidocs/org/apache/commons/httpclient/HttpStatus.html

**Comment by ivanr** [comment]
No, sorry. It's a trivial feature that adds little value and can be easily added client-side.
