### ISSUE TITLE
On dual-cert nginx 1.11.1 SSLLabs Authentication section only shows my old RSA certificate, not my new ECDSA certificate

### ISSUE THREAD

**Issue by WilliamFeely** [ssllabs/ssllabs-scan#350]
On my nginx 1.11.1 instance I just added dual RSA/ECDSA support.
On both of the following scans:
https://www.ssllabs.com/ssltest/analyze.html?d=williamfeely.info
https://www.ssllabs.com/ssltest/analyze.html?d=dxgl.info
it shows the RSA4096 certificate in the Authentication section but it does not show the secp384r1 (ECDSA) certificate.
The handshake simulation does indicate that ECDSA is being used on modern browsers, as does my Chrome and Firefox.
Both certificates have been obtained from Let's Encrypt; the ECDSA keys just generated and signed tonight.
Is this a bug that it is showing the RSA certificate, or is it a feature.  If it is a feature, is it because my RSA certificate expires sooner than my ECDSA certificate?

The SSL Labs version is "SSL Report v1.22.37"

**Comment by ivanr** [comment]
It's neither bug nor feature. SSL Labs currently collects all certificates but shows only the first one it encounters. Showing all certificates is planned for future releases.
You should be able to see all your certificates in the API v3 output: https://www.ssllabs.com/api/v3/analyze?host=williamfeely.info&all=done

**Comment by fishouttah20** [comment]
Getting forbidden message when trying to access that api/v3 link...

**Comment by bhushan5640** [comment]
Please use this link: 
https://api.ssllabs.com/api/v3/analyze?host=williamfeely.info&all=done
