### ISSUE TITLE
TLS 1.3

### ISSUE THREAD

**Issue by J0WI** [ssllabs/ssllabs-scan#352]
TLS 1.3 just landed in NSS and Firefox Nightly, so SSL Labs should be able to detect them.
See also https://github.com/tlswg/tls13-spec/wiki/Implementations#test-servers

**Comment by typingArtist** [comment]
Remember to also handle the new PSK ciphers 0x1301 to 0x1305 correctly. Currently my Firefox with enabled TLS 1.3 is shown with its three offered new PSK ciphers as WEAK.

**Comment by ivanr** [comment]
Let's close this old ticket, now that SSL Labs implements detection of TLS 1.3 draft 18.
