### ISSUE TITLE
Incorrect error with 10,000 entry Subject Alt Name field?

### ISSUE THREAD

**Issue by jbrowngithubuser** [ssllabs/ssllabs-scan#353]
badssl.com has tests for 1,000 and 10,000 subject alt names:

1000-sans.badssl.com
https://www.ssllabs.com/ssltest/analyze.html?d=1000-sans.badssl.com

10000-sans.badssl.com
https://www.ssllabs.com/ssltest/analyze.html?d=10000-sans.badssl.com

The 1,000 version works, but the 10,000 version gives the error "Assessment failed: Certificate chain too long: 284302". Is this the correct error (as the test is for number of Subject Alt Name entries, not chain length)?

...or is chain length in number of bytes, and not number of certificates sent?

**Comment by ivanr** [comment]
I think the error message comes from a hard-coded defence against DoS attacks by rogue servers. Certificate length is not limited, so someone could generate a large certificate and force SSL Labs to handle it.

**Comment by ivanr** [comment]
Closing this because it's not worth spending the time to fix it.
