### ISSUE TITLE
Clients are duplicated in the getClients API (how to know which one to pick?)

### ISSUE THREAD

**Issue by seccubus** [ssllabs/ssllabs-scan#356]
See https://api.dev.ssllabs.com/api/v3/getClients

https://dev.ssllabs.com/ssltest/viewClient.html?name=IE&version=6&platform=XP&key=18
```
{
    "id": 18,
    "name": "IE",
    "platform": "XP",
    "version": "6",
    "hexHandshakeBytes": 
```
vs. https://dev.ssllabs.com/ssltest/viewClient.html?name=IE&version=6&platform=XP&key=100
```
{
    "id": 100,
    "name": "IE",
    "platform": "XP",
    "version": "6",
```

**Comment by seccubus** [comment]
More duplicates found
* IE 8 / XP
  - https://dev.ssllabs.com/ssltest/viewClient.html?name=IE&version=8&platform=XP&key=20
  - https://dev.ssllabs.com/ssltest/viewClient.html?name=IE&version=8&platform=XP&key=101
* IE 8-10 / Win 7
  - https://dev.ssllabs.com/ssltest/viewClient.html?name=IE&version=8%2d10&platform=Win%207&key=23
  - https://dev.ssllabs.com/ssltest/viewClient.html?name=IE&version=8%2d10&platform=Win%207&key=113
* IE 11 / Win 7 (id 36 negotiates a different cipher then the other IDs)
  - https://dev.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%207&key=36
  - https://dev.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%207&key=95
  - https://dev.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%207&key=102
IE 11 Win 8.1 (id 24 negotiates a different cipher then the others)
  - https://dev.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%208.1&key=24
  - https://dev.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%208.1&key=71
  - https://dev.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%208.1&key=96
  - https://dev.ssllabs.com/ssltest/viewClient.html?name=IE&version=11&platform=Win%208.1&key=104

**Comment by bhushan5640** [comment]
They do have differences,  represents different state of browser over a period of time. You will see differences in Cipher suites / support for RI / SNI etc.

You may want to pick one used in the Server test Handshake simulation. In case of IE 6 XP you will see id : 100 is used (link on the Server test page under Handshake simulation)

**Comment by seccubus** [comment]
Is it save to say the largest ID is also the latest one? Or is there another way to find this out. 
It cannot be determined from the version strings.

**Comment by bhushan5640** [comment]
Yes largest ID denotes latest one. We are going to revamp user agent details to make it less confusing. Thanks.
