### ISSUE TITLE
new ciphers for W7/8.1/10/2008R2/2012R2 (TLS_DHE_RSA_WITH_AES)

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#358]
MS added more "new" ciphers to Windows

TLS_DHE_RSA_WITH_AES_128_CBC_SHA
TLS_DHE_RSA_WITH_AES_256_CBC_SHA 
https://support.microsoft.com/en-us/kb/3161639
this patch is included in June Patches.
For W10 it comes with https://support.microsoft.com/en-us/kb/3163018 (tested by myself)
another evidence that w10 have it, is that https://support.microsoft.com/en-us/kb/3161639 talks about 
EDGE which only exists on W10

Please update ssllabs browser Simulation and https://www.ssllabs.com/ssltest/clients.html

**Comment by nextPrime** [comment]
[Windows 10](https://www.ssllabs.com/ssltest/viewClient.html?name=Edge&version=13&platform=Win%2010&key=119) and [Windows 10 Mobile](https://www.ssllabs.com/ssltest/viewClient.html?name=Edge&version=13&platform=Win%20Phone%2010&key=120) have these two new ciphers too, although KB3161639 doesn't apply to Windows 10. I don't know if they were added to Windows 10 in June's patch.

**Comment by bhushan5640** [comment]
Updated Browser simulations added for IE11 on W7/W8.1/W10 and Edge 13 on W10. Check it here https://dev.ssllabs.com/ssltest/analyze.html?d=ssllabs.com
