### ISSUE TITLE
https://services.netbeans.org not reachable

### ISSUE THREAD

**Issue by CoSoCo** [ssllabs/ssllabs-scan#359]
I'm not able to reach
https://services.netbeans.org/dashboard/web/netcat_signup.php
with Firefox on Ubuntu 16.04, even your report shows no problems:
https://www.ssllabs.com/ssltest/analyze.html?d=services.netbeans.org

I get (in German):
Fehler: Gesicherte Verbindung fehlgeschlagen

Die Verbindung zum Server wurde zurückgesetzt, während die Seite geladen wurde.

```
Die Website kann nicht angezeigt werden, da die Authentizität der erhaltenen Daten nicht verifiziert werden konnte.
Kontaktieren Sie bitte den Inhaber der Website, um ihn über dieses Problem zu informieren.
```

**Comment by ivanr** [comment]
I get the same problem (connection reset) from my network position. @CoSoCo if you examine the report more closely, you'll see several notices that the HTTP request failed. @bhushan5640 I propose that SSL Labs adds a big orange warning (the same one used for B caps, for example) at the top whenever this happens.

**Comment by bhushan5640** [comment]
Warning box added for sites withfailed HTTP request. Deployed on dev
