### ISSUE TITLE
[Feature request] check CSP header

### ISSUE THREAD

**Issue by J0WI** [ssllabs/ssllabs-scan#36]
The test should also check if the server sends a content security header.

I propose the following grades if the header is present and valid:
A+ (when there are no other issues) if it allows no resources over http or port 80
C (maybe B) if it allows passive resources over http or port 80
F if it allows active resources over http or port 80

If no CSP header is sent, the grade should not change. Maybe you can't get A+ without.

Why should we have this feature?
This is a good way to prevent mixed content server side.

**Comment by ivanr** [comment]
The only thing we could add about CSP is to detect if the server uses it to prevent third-party mixed content. Everything else is out of scope.

**Comment by ivanr** [comment]
Out of scope, at least for the time being.

**Comment by J0WI** [comment]
You may also note the 'Upgrade Insecure Requests' feature (part of CSP), that is already detected in the client test.

**Comment by J0WI** [comment]
See https://securityheaders.io/
