### ISSUE TITLE
rc4WithModern value is inaccurate

### ISSUE THREAD

**Issue by anand-bhat** [ssllabs/ssllabs-scan#360]
The [API doc](https://github.com/ssllabs/ssllabs-scan/blob/stable/ssllabs-api-docs.md#endpointdetails) indicates that `rc4WithModern` is true if RC4 is used with modern clients. However, for ns-vid-chat2.rabobank.nl, the [UI scan](https://www.ssllabs.com/ssltest/analyze.html?d=ns-vid-chat2.rabobank.nl) caps the grade to C because "This server uses RC4 with modern protocols" while the [API returns](https://api.ssllabs.com/api/v2/analyze?host=ns-vid-chat2.rabobank.nl&all=done&fromCache=on&maxAge=24) `"rc4WithModern": false.`

![image](https://cloud.githubusercontent.com/assets/7332442/16438792/36a1e5d8-3dd0-11e6-97dc-e545f2c2f1ac.png)

![image](https://cloud.githubusercontent.com/assets/7332442/16438803/4680a9d0-3dd0-11e6-9f42-3ce320e88027.png)

Conversely, for reputatietool.rabobank.nl, the [UI scan](https://www.ssllabs.com/ssltest/analyze.html?d=reputatietool.rabobank.nl) does not indicate that the server uses RC4 with modern protocols but the [API returns](https://api.ssllabs.com/api/v2/analyze?host=reputatietool.rabobank.nl&all=done&fromCache=on&maxAge=24) `"rc4WithModern": true.`

![image](https://cloud.githubusercontent.com/assets/7332442/16438815/5a636712-3dd0-11e6-8dae-233daeb5cfec.png)

![image](https://cloud.githubusercontent.com/assets/7332442/16438832/6be130a0-3dd0-11e6-8674-804ef1b1dd18.png)

**Comment by ivanr** [comment]
Here are the direct links to the mentioned servers:
https://www.ssllabs.com/ssltest/analyze.html?d=ns-vid-chat2.rabobank.nl&hideResults=on
https://api.ssllabs.com/api/v2/analyze.html?host=ns-vid-chat2.rabobank.nl&all=done
https://www.ssllabs.com/ssltest/analyze.html?d=reputatietool.rabobank.nl&hideResults=on
https://api.ssllabs.com/api/v2/analyze.html?host=reputatietool.rabobank.nl&all=done

As far as I can tell (without access to the source code), the UI is correct and the API is wrong.

**Comment by bhushan5640** [comment]
Fix deployed on dev.ssllabs.com
https://api.dev.ssllabs.com/api/v2/analyze?host=ns-vid-chat2.rabobank.nl&all=on
https://api.dev.ssllabs.com/api/v2/analyze?host=reputatietool.rabobank.nl&all=on

**Comment by anand-bhat** [comment]
Thanks! :beers:
