### ISSUE TITLE
Suggestion on performance of SSLLabs scanning

### ISSUE THREAD

**Issue by ghost** [ssllabs/ssllabs-scan#362]
**Suggestion/Question 1**:
Hi! I used Wireshark to capture the requests sent by the SSLLabs scanner to my server. I find that from some point, SSLLabs sends a large number of TLS 1.0 client hello handshakes with only two cipher suites (one is fixed to TLS_EMPTY_RENEGOTIATION_INFO_SCSV; another is an insecure or deprecated cipher). This phase lasts for more than 30 seconds. I guess SSLLabs is testing weather my server supports that deprecated cipher suite. Is there any reason that you don't combine these into one (or at least fewer) handshakes?

I feel that you can greatly improve the performance if you send all of these cipher suites in one handshake, and if the server replies with a server hello, then you remove the negotiated cipher from your initial cipher suite list, and send client hello again. Repeat until the server says handshake failure, meaning no overlapped cipher suite. SSLLabs does scan it this way for TLS 1.2. Why not do the same for TLS 1.0?

**Suggestion/Question 2**:
Could you send a normal TLS handshake at the beginning of the scanning, so that you can catch if the server uses invalid certificate earlier?

Thanks!

**Comment by bhushan5640** [comment]
We are working on this :)

**Comment by ivanr** [comment]
Just FYI, yes, there is a reason for the current behaviour. There's a problem with some servers that refuse a handshake if the Client Hello is too large. Testing suites one by one is simple and avoids that problem. But, as you say, it's not fast.... which is why fixing it is on the development roadmap.

**Comment by bhushan5640** [comment]
Improved cipher suite testing now deployed on SSL Labs Dev.
