### ISSUE TITLE
SSL Expiration date 

### ISSUE THREAD

**Issue by reddy440** [ssllabs/ssllabs-scan#363]
HI,

I am not able to figure out the SSL expiration date after performing SSL test using command line mode.  From the SSL test result I can see that there is an attribute "not after" which defines SSL expiration date . But the problem here the result (ssl expiry date) is in different format like as shown below

"notAfter" :1633564799000

how can i convert the above value to get the SSL expiration date . Kindly help me on this.

**Comment by bhushan5640** [comment]
Its timestamp in milliseconds 
you can try http://www.epochconverter.com

**Comment by reddy440** [comment]
Thanks bro
