### ISSUE TITLE
Feature Request: Does not have the "Do not show the results on the boards" option

### ISSUE THREAD

**Issue by blade1989** [ssllabs/ssllabs-scan#365]
In the ssllabs website, before scanning a website you have the option to "... not show the results on the boards" - is this enabled by default? If so, that needs to be underlined.

**Comment by bhushan5640** [comment]
By default "Do not show the results on the boards" option is unchecked (i.e. results are added to board) on www.ssllabs.com

**Comment by blade1989** [comment]
Is there any option on how to not display the scanned domains in the board?

I - sometimes - scan domains for customers, and do not want to display their ratings on the boards, for security reasons.

**Comment by ivanr** [comment]
If you don't want to show the results on the boards, just make sure to tick the checkbox. If you forget to tick it by mistake, when the test is complete there will be a "Hide" link on the report page. Clicking there will hide the report and remove it from the boards.

**Comment by blade1989** [comment]
@ivanr I am not talking about the website. I am talking about the command line scanner. I would like to suggesta a `--dont-show-on-board` option into this.

This is not a website feature request, but a `ssllabs-scan` feature request.

**Comment by ivanr** [comment]
@blade1989 as far as I am aware, when using the API the results are not shown by default. It is optional to show them. And I just did a quick test and I can't see the hostname I tried on the boards.
