### ISSUE TITLE
Add a link to beekpr-ssllabs

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#366]
Filip recently posted about beekpr-ssllabs here: https://community.qualys.com/message/34095
We should add a link to it on the official API page: https://www.ssllabs.com/projects/ssllabs-apis/

**Comment by bhushan5640** [comment]
Done. deployed on dev.ssllabs.com
https://dev.ssllabs.com/projects/ssllabs-apis/index.html
