### ISSUE TITLE
Servers with OCSP ERROR should have a much degraded score

### ISSUE THREAD

**Issue by J0WI** [ssllabs/ssllabs-scan#37]
Because the connection will fail if the client checks the certificate revocation status.

**Comment by ivanr** [comment]
Possibly, but this is the best place to discuss improvements to scoring criteria. Please use https://lists.sourceforge.net/lists/listinfo/ssllabs-discuss instead.

That said, I am about to start working on the second major release of grading criteria, which is going to be redesigned from scratch. I will post the drafts to the mailing lists. Thanks!
