### ISSUE TITLE
API doesn't show protocol intolerance information

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#370]
The missing information includes protocol version intolerance, long handshake intolerance and possibly a few others.

**Comment by bhushan5640** [comment]
protocol intolerance information now available on Dev API V2.
Later will be added to API V3

protocolIntolerance
- bit 0: TLS 1.0
- bit 1: TLS 1.1
- bit 2: TLS 1.2
- bit 3: TLS 1.3
- bit 4: TLS 1.152
- bit 5: TLS 2.152

miscIntolerance
- bit 0: extension intolerance
- bit 1: long handshake intolerance
- bit 2: long handshake intolerance workaround success

**Comment by ShortyFR** [comment]
Good news. Thanks for the addition. I'll check it out a bit later.

Antoine

2016-08-30 14:30 GMT+02:00 Bhushan Lokhande <notifications@github.com>:

**Comment by ivanr** [comment]
Deployed in production in 1.24.0.
