### ISSUE TITLE
Processes spawned after fifth encounter an infinite loop

### ISSUE THREAD

**Issue by AverageS** [ssllabs/ssllabs-scan#371]
I was trying to optimize scanning with multiprocessing but i encountered this problem: all of the processes, spawned after fifth process had fallen into infinite loop (it was ~30 minutes i waited before killing them). The problem appears when you are trying to launch processes with a timeout between. _With simultaneous start you wont be able to start more then 5 processes simultaneously, but the others would only give an empty output and exit, without falling into infinite loop._ 
Shell code, that causes this:
`for i in {1..64};
do
  sleep 1
  ssllabs-scan  _some url here_ & 
done`

**Comment by ivanr** [comment]
There's no need to do what you're doing: ssllabs-scan will always run many tests in parallel. When it starts it contacts the API server to determine what the limits are, and then it runs as many as possible.

**Comment by AverageS** [comment]
Yep, i know that. But if i'm only able to run one process per url ( unable to run process with file, containing url list ) - then it becomes a problem, that can be solved, i think.
