### ISSUE TITLE
Make Client Test more accessible to clients with poor capabilities

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#372]
The main SSL Labs web site, on which the client test is currently running, has high-quality cipher suite configuration that might not allow connections from clients with poor capabilities. Additionally, it requires support for at least TLS 1.0.
We recently had a feature request from a user who couldn't use the test: https://blog.qualys.com/ssllabs/2013/10/02/introducing-the-ssl-client-test#comment-77237

**Comment by bhushan5640** [comment]
Related: #505

**Comment by nayankakati** [comment]
Hi All,
We have added this change in Production in the latest build.
Please visit ssllabs.com
Thanks
