### ISSUE TITLE
SSL Labs not showing HSTS on www.google.com

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#374]
Google deployed HSTS on www.google.com but it's not showing in SSL Labs: https://dev.ssllabs.com/ssltest/analyze.html?d=www.google.com&hideResults=on The problem seems to be that they're not sending the HSTS header unconditionally. In my tests with Chrome, I couldn't see HSTS at all, although it's showing to some other people. Given that Google's servers are frequently tested in SSL Labs, it would be useful to understand what triggers HSTS so that we can report on it accurately. (Perhaps it's accurate now?)

Google's HSTS announcement: https://security.googleblog.com/2016/07/bringing-hsts-to-wwwgooglecom.html

**Comment by bhushan5640** [comment]
In SSL Labs we set user agent as "SSL Labs (https://www.ssllabs.com/about/assessment.html)". If we set Mozilla/Chrome user agent for HTTPS test we are able to detect HSTS on www.google.com.

Google does user agent detection and does not set HSTS header for SSL Labs user agent. https://twitter.com/BhushanLokhande/status/759614764226142208

**Comment by bhushan5640** [comment]
dev.ssllabs.com now detects HSTS on www.google.com
https://dev.ssllabs.com/ssltest/analyze.html?d=www.google.com

Strict Transport Security (HSTS)	Yes   TOO SHORT (less than 180 days)  max-age=86400

**Comment by gwillem** [comment]
For anyone else interested in why Google doesn't return a HSTS header, it seems to depend on source IP (and UA, see above).

```
# curl -vH "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.110 Safari/537.36" -s https://www.google.com/  |& grep Strict
< Strict-Transport-Security: max-age=86400
```
When it doesn't work, I get redirected to a localized site:

```
< HTTP/1.1 302 Found
< Cache-Control: private
< Content-Type: text/html; charset=UTF-8
< Referrer-Policy: no-referrer
< Location: https://www.google.nl/?gfe_rd=cr&ei=qOQRWd-8G-il8wfT44tY
< Content-Length: 257
< Date: Tue, 09 May 2017 15:47:52 GMT
< Alt-Svc: quic=":443"; ma=2592000; v="37,36,35"
```
