### ISSUE TITLE
There should be a warning if not all trust paths are pinned

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#375]
Because we can't be 100% sure which trust path will be selected by a browser, SSL Labs should warn if there are paths that are not pinned. See: https://www.ssllabs.com/ssltest/analyze.html?d=tempoteamemployability.nl

Original bug report: https://twitter.com/rodehoed/status/761129589926158336

**Comment by bhushan5640** [comment]
Fixed, deployed on Dev.
