### ISSUE TITLE
"Unable to resolve domain name" error for mytaxcafe.com

### ISSUE THREAD

**Issue by anand-bhat** [ssllabs/ssllabs-scan#376]
Scanning mytaxcafe.com (https://www.ssllabs.com/ssltest/analyze.html?d=mytaxcafe.com) and www.mytaxcafe.com (https://www.ssllabs.com/ssltest/analyze.html?d=www.mytaxcafe.com) results in an "Unable to resolve domain name" error. I'm able to open these sites (not under my control) via my browser.

![image](https://cloud.githubusercontent.com/assets/7332442/17468507/43e00dde-5d46-11e6-9802-c38b5102ea7a.png)
![image](https://cloud.githubusercontent.com/assets/7332442/17468517/4fecbdca-5d46-11e6-9013-cd760047eee9.png)

**Comment by nextPrime** [comment]
SSL Labs can resolve these two domains now.

**Comment by anand-bhat** [comment]
Whatever the issue was appears to have been resolved or has corrected itself. SSL Labs is able to resolve these domains now.

**Comment by fishouttah20** [comment]
I've seen this intermittently on a small percentage of domains in the last week. Is there a short timeout on the DNS lookup? I can't seem to reproduce it consistently but nice to see I'm not the only one.

**Comment by ivanr** [comment]
IIRC, SSL Labs uses Google DNS. That means, if there's a problem with them, the hostname won't show. In practice, the reports I investigated in the past were all related to incorrect DNSSEC configuration. (I don't know if that's the case here.)

**Comment by Hillside502** [comment]
Suggest an alternative to Google DNS, such as the PRISM Break listing:-

DNS - PRISM Break
https://prism-break.org/en/all/#dns
