### ISSUE TITLE
debianflaw blank for ECDSA and 3072bit RSA instead of "false"

### ISSUE THREAD

**Issue by fishouttah20** [ssllabs/ssllabs-scan#381]
using the commandline scanner, debianflaw usually returns false, but on domains that have ECDSA certificates and those with 3072 bit RSA certificates (but not 4092), the debianFlaw output is blank. 

ssllabs.com indicates debianflaw "no" for these domains.

**Comment by ivanr** [comment]
I think the API is correct here, assuming you mean the debianFlaw field is absent. When a field is absent that usually means "don't know". IIRC, there are no tests for 3072-bit RSA certs and none for ECDSA.

**Comment by fishouttah20** [comment]
Yeah, our json > xlsx process gives me "blank" fields, but you're right, in the original json, the field is missing. We can force a false during our conversion process so I'll close this as it's behaving as designed.
