### ISSUE TITLE
Unexpected failure ?

### ISSUE THREAD

**Issue by roydacke** [ssllabs/ssllabs-scan#383]
We are getting this error checking 'secure.topsmarkets.com'.

The cert is on an HAproxy so I narrowed the group down to a single server just to avoid this "multiple hosts behind a single IP address" concern but got the same results. (have since returned to normal number of web servers in this group)

any ideas?

**Comment by roydacke** [comment]
Got this to work one time, right after I started OCSP stapling.  Thought that solved it, but now it doesn't work again even though I didn't change anything.

**Comment by roydacke** [comment]
After lots of testing it is clear this test passes / fails more or less randomly. It does seem to fail much more often than it passes though. About 4 out of 5 times it fails, otherwise gives an A.

This is all by simply refreshing the test page ("Clear cache") without changing anything at all on the server side.

Also pretty clear no one is looking at this issue. But if anyone else comes along getting random pass/fails from this test and you're using SSL termination on an HAproxy, just keep refreshing and eventually you'll get your results.

**Comment by bhushan5640** [comment]
works for me on local ssl labs. Test passes every time with grade A. Is it because some load balancer /firewall configuration?
