### ISSUE TITLE
Client scan incorrectly report "Your user agent doesn't support TLS 1.2. You should upgrade."

### ISSUE THREAD

**Issue by tdelmas** [ssllabs/ssllabs-scan#386]
(if it's not the correct place to report that issue, please advice where to do it...)

> Your user agent doesn't support TLS 1.2. You should upgrade.

And in the same time,

>Protocols
>TLS 1.2 	Yes
>TLS 1.1 	Yes
>TLS 1.0 	Yes
>SSL 3 	No
>SSL 2 	No

https://www.ssllabs.com/ssltest/viewMyClient.html with Firefox 48.0.1

**Comment by bhushan5640** [comment]
Does it reproduce every time, would you mind hard refresh (cntrl + f5).

**Comment by tdelmas** [comment]
It does not reproduce it anymore (tested www and dev), yesterday it produce it on www even after F5 (I didn't try ctrl+F5 yesterday)
