### ISSUE TITLE
Cipher Suite by Protocol

### ISSUE THREAD

**Issue by adamcaudill** [ssllabs/ssllabs-scan#389]
Is there a way in the API to determine which cipher suites are available for which protocol? I'd like to be able to determine, for example, if 3DES is enabled for all supported protocols or only older protocols.

**Comment by bhushan5640** [comment]
In SSL Labs v3 api per protocol cipher suites list will be available very soon.

**Comment by adamcaudill** [comment]
@bhushan5640 Thanks! That's great news for me, much appreciated!

**Comment by bhushan5640** [comment]
@adamcaudill you can now try https://api.dev.ssllabs.com/api/v3 for per protocol cipher suite list.
SSL Labs Dev now shows per protocol suites.
