### ISSUE TITLE
Support for GOST ciphers

### ISSUE THREAD

**Issue by J0WI** [ssllabs/ssllabs-scan#39]
GOST ciphers are not shown up. It would be interesting to support them, because there is no known vulnerability [1], so they would be a secure alternative to CBC ciphers.

https://www.openssl.org/docs/apps/ciphers.html#gost_ciphersuites_from_draft_chudov_cryptopro_cptls__extending_tls_v1_0
https://tools.ietf.org/id/draft-chudov-cryptopro-cptls-04.txt

[1] https://en.wikipedia.org/wiki/Transport_Layer_Security#Cipher

**Comment by ivanr** [comment]
The GOST suites are tested for and should show up when supported. If you have a list of servers known to support GOST, I can check to see why they are not detected.

**Comment by ivanr** [comment]
Closing this ticket because GOST detection works. I've found a few servers that support it among the SSL Pulse results.

**Comment by J0WI** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=lk3.nalog.ru
reopen?

**Comment by ivanr** [comment]
No, it's a different problem. I've opened a new issue for it: https://github.com/ssllabs/ssllabs-scan/issues/113
