### ISSUE TITLE
not all curves detected/shown

### ISSUE THREAD

**Issue by v4BL** [ssllabs/ssllabs-scan#391]
While testing individual curves, it was noticed that both sites don't detect all curves in use. And even display contradicting results - when they show no ECDH ciphers detected:
Cipher Suites (SSL 3+ suites in server-preferred order; deprecated and SSL 2 suites at the end) 
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x9f)   DH 4096 bits   FS  256 
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x9e)   DH 4096 bits   FS  128 

And then lower shows:
OpenSSL 1.0.2e  R     RSA 4096 (SHA256)    TLS 1.2    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384   ECDH brainpoolP512r1   FS

**Comment by v4BL** [comment]
It seems it only fails when "brainpool" curves are used exclusively:
OpenSSL 1.0.2e R RSA 4096 (SHA256) TLS 1.2 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 ECDH brainpoolP512r1 FS
OpenSSL 1.0.2e R RSA 4096 (SHA256) TLS 1.2 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 ECDH brainpoolP384r1 FS
OpenSSL 1.0.2e R RSA 4096 (SHA256) TLS 1.2 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 ECDH brainpoolP256r1 FS

**Comment by ivanr** [comment]
When you say "both sites" do you mean www.ssllabs.com and dev.ssllabs.com? Do you have any public servers we can test with?

**Comment by v4BL** [comment]
Yes - both = "www" and "dev" sites. 
Yes, test server setup using: 
SSLProtocol +TLSv1.2 
SSLCipherSuite HIGH:!SHA 
SSLOpenSSLConfCmd Curves brainpoolP512r1:brainpoolP384r1:brainpoolP256r1 
At: https://sha2.wetrag.net/

**Comment by v4BL** [comment]
To better show the problem, updated to use: 
(Site uses SNI - for the purpose of this test, all hosts on this IP now set this same way.) 
SSLCipherSuite ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256 
SSLOpenSSLConfCmd Curves brainpoolP512r1:brainpoolP384r1:brainpoolP256r1

**Comment by leonardomarino** [comment]
@ivanr I have a similar issue. I am running a server with a dual RSA and EC certificates. Please test using: https://dev.ssllabs.com/ssltest/analyze.html?d=marino-johnson.org I am using two different curves (secp256r1 for EC and secp521r1 for the RSA

This is when I have RSA only enabled (the curves are displayed correctly)

![screen shot 2016-10-28 at 9 28 50 am](https://cloud.githubusercontent.com/assets/7528337/19808413/bab71d08-9cf2-11e6-8805-e504b496b32e.png)

This is when I have both RSA and EC enabled (the curves are displayed incorrectly for RSA)

![screen shot 2016-10-28 at 9 25 58 am](https://cloud.githubusercontent.com/assets/7528337/19808418/c6103b1c-9cf2-11e6-9b1e-2cf006ecd27d.png)

**Comment by bhushan5640** [comment]
Now all ECDH curves are detected. Check https://dev.ssllabs.com
![image](https://cloud.githubusercontent.com/assets/6083185/21806576/152ff898-d760-11e6-905e-a793a8f81fd8.png)

**Comment by leonardomarino** [comment]
Hi @bhushan5640 The supported curves are now detected in the Protocol Details section (Supported EC Named Curves) but the correct curves are NOT shown correctly on the Cipher Suites section. Could you please check each Cipher Suite and display the correct curve for each case?
