### ISSUE TITLE
Domains preloaded for pinning in Chrome show as preloaded for HSTS

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#392]
[Lucas Garron reported this bug via Twitter, after [comfreak](https://twitter.com/comfreak) highlighted the problem.]
Chrome is not preloaded for HSTS:
https://chromium.googlesource.com/chromium/src/+/3f789c4c557c2c7a75e9c3d92c88fa602f5b67a9/net/http/transport_security_state_static.json#434
but SSL Labs shows it as such:
https://www.ssllabs.com/ssltest/analyze.html?d=www.google.com&s=216.58.194.164&hideResults=on

**Comment by bhushan5640** [comment]
Fixed, deployed on Dev.
