### ISSUE TITLE
Checking preloading with Tor doesn't work in production

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#394]
I've noticed several times that checking preloading with Tor doesn't work in production (it does in dev). https://www.ssllabs.com/ssltest/analyze.html?viaform=on&d=www.ssllabs.com

Rather than troubleshoot this problem, I actually propose to remove Tor preload checking. That's because they don't have a master branch and it's a time sink to track their stable releases and updated the preload URL constantly.

**Comment by bhushan5640** [comment]
Yes, It's failing too often on local also.

**Comment by bhushan5640** [comment]
Removed Tor preload checking. Deployed on Dev.
