### ISSUE TITLE
Remove "viaform" parameter when report is cached

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#395]
When a report is requested via the form on /ssltest/ and the result is immediately available, the URL ends up looking like this: https://dev.ssllabs.com/ssltest/analyze.html?viaform=on&d=www.ssllabs.com The "viaform=on" parameter shouldn't be there. To remove it, SSL Labs should issue a redirection to a clean URL that doesn't contain it.

**Comment by bhushan5640** [comment]
Fixed, deployed on Dev.
