### ISSUE TITLE
"All" filter for "analyze" api call doesn't seem to work

### ISSUE THREAD

**Issue by GregoirePiat** [ssllabs/ssllabs-scan#398]
When calling 
`curl https://api.ssllabs.com/api/v2/analyze?host=www.ssllabs.com&all=on`
or
`curl https://api.ssllabs.com/api/v2/analyze?host=www.ssllabs.com&all=done`

i receive following JSON :
`{
  "host": "www.ssllabs.com",
  "port": 443,
  "protocol": "HTTP",
  "isPublic": true,
  "status": "READY",
  "startTime": 1474020498481,
  "testTime": 1474020562286,
  "engineVersion": "1.24.0",
  "criteriaVersion": "2009l",
  "endpoints": [
    {
      "ipAddress": "64.41.200.100",
      "serverName": "www.ssllabs.com",
      "statusMessage": "Ready",
      "grade": "A+",
      "gradeTrustIgnored": "A+",
      "hasWarnings": false,
      "isExceptional": true,
      "progress": 100,
      "duration": 63688,
      "eta": 227,
      "delegation": 2
    }
  ]
}`

"All" filter for "analyze" api call seems to have a problem.
I don't receive full information, but only summaries. Is it an issue?

**Comment by ivanr** [comment]
It will work if you put question marks around the URL. Like this:

`curl "https://api.ssllabs.com/api/v2/analyze?host=www.ssllabs.com&all=done"`

So what's happening is that the ampersand is interpreted by the shell and everything after it is not seen by curl (and also not seen by SSL Labs).
