### ISSUE TITLE
CloudFlare incorrectly marked as intolerant to TLS 1.3

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#399]
Nick reported the problem via Twitter: https://twitter.com/grittygrease/status/776854040701390848

**Comment by WilliamFeely** [comment]
Apparently it only bugs out on the www site - https://www.ssllabs.com/ssltest/analyze.html?d=www.cloudflare.com
On an unrelated note, not sure if it is a SSLLabs glitch or something weird going on, somehow they got Chrome to preload HSTS for the site despite it not providing HSTS headers.
Have you contacted CloudFlare just in case it isn't a false positive?

**Comment by ivanr** [comment]
Nick works for CloudFlare. It's more likely that they deployed TLS 1.3 last week, per their blog post https://blog.cloudflare.com/encryption-week/

**Comment by ivanr** [comment]
Closing because there doesn't seem to be any intolerance warnings any more.
