### ISSUE TITLE
API: Unable to determine DH vs ECDH and FS from Simulation objects

### ISSUE THREAD

**Issue by seccubus** [ssllabs/ssllabs-scan#401]
If I look at the definition of https://github.com/ssllabs/ssllabs-scan/blob/stable/ssllabs-api-docs.md#simulation I am unable to tell if the handshake was done with DH or ECDH and if the client negotiated FS.

Can these fields the added to the API results?

**Comment by ivanr** [comment]
For each simulation you have the suite ID. You then look-up the suite in the list of supported suites and you'll find the information there (either in the name or you can look at dhStrength or ecdhStrength parameters). Or am I missing something?

**Comment by ivanr** [comment]
I think there's a different problem: when SSL Labs determines support for a cipher suite, the named curve used during the negotiation might not be the same as the simulated one. I opened #403 for this.

**Comment by seccubus** [comment]
I think I can work with that, but it is another case where parsing API results requires quite a bit of computational/alogrithmic work for the consumer.

If I understand I would have to:
* Read the suites object
* Iterate over the list object in the suits object and build an index of suite ID
* For each negotiated suite get the id and look it up
* Test if the suite has a DHbits property a ECDHbits property or neither

It still doesn't tell me if FS was or was not negotiated.
