### ISSUE TITLE
Windows XP handshake simulations

### ISSUE THREAD

**Issue by robmoss2k** [ssllabs/ssllabs-scan#402]
I believe there is an important browser missing from the handshake simulations. Commonly, users of Windows XP install either Chrome or Firefox to browse the web, after the demise of SSL 3.0 and RC4 combined with various limits (e.g. 64 cipher suites in the handshake for TLS 1.0). However, these users are not represented in the handshake simulations. I recently disabled everything except TLS_ECDHE_ECDSA cipher suites based on data within Google Analytics for most of our websites and got screamed at for it after users of Chrome on XP were no longer able to connect, as Chrome on XP only supports RSA and not ECDSA.

Could you please add in a handshake simulation for Chrome on XP, as it still uses certain parts of SChannel to provide TLS support and it's still many people's preferred browser choice if they're stuck on Windows XP?

**Comment by blblack** [comment]
+1 on this, and I'd say Firefox on XP is important as well.  Chrome doesn't actually support XP in new releases anymore AFAIK, whereas Firefox still does ( https://support.mozilla.org/en-US/kb/get-latest-version-firefox-windows-xp-vista ).

From the Wikimedia perspective, we've been advising stubborn XP users to at least migrate to Firefox with that link, as it seems the easiest/best-supported option they have if they're unwilling to get off of XP entirely.

**Comment by WilliamFeely** [comment]
I believe Firefox uses the same TLS support regardless of the version of Windows it is on; it has its own self-contained TLS stack.

**Comment by robmoss2k** [comment]
Yes, Firefox is OS-agnostic as far as SSL/TLS support is concerned, there's no need for any extra simulations for that - there are some performance differences across platforms but no differences that would show up in a handshake simulation.

Chrome, however, despite being unsupported on Windows XP, is still very popular on Windows XP - far more so than Internet Explorer, which has handshake simulations for both IE6 and IE8.

**Comment by ivanr** [comment]
It might still be useful to list Firefox on XP because people might not be aware that the functionality should be the same. Just a thought.

**Comment by robmoss2k** [comment]
Indeed so - but Chrome on XP is a necessity because the functionality is different.

Firefox have also announced they're dropping XP and Vista support today - Firefox 52 ESR will be the last supported version for those two OSes.

**Comment by bhushan5640** [comment]
Windows XP SP3
![system_info](https://cloud.githubusercontent.com/assets/6083185/18982355/203301e8-8703-11e6-9396-607522d3cd38.JPG)

Chrome v49
![chrome_v49](https://cloud.githubusercontent.com/assets/6083185/18982356/2033835c-8703-11e6-96d9-529a752fdb41.JPG)

Firefox v49 (official site gave me this version only and its not getting updated further)
![firefox_52](https://cloud.githubusercontent.com/assets/6083185/18982357/2035cbda-8703-11e6-86cd-ec90db89d6fe.JPG)

**Comment by robmoss2k** [comment]
To confirm, I get the exact same set of cipher suites on a Windows XP SP3 installation with the POSReady flag set. Firefox's current version is 49 - version 50 will be released 2016-11-08, 50.0.1 2016-12-13, 51 2017-01-24, 52 2017-03-07 and 53 2017-04-18, which will be the first one to completely drop Windows XP support, even via the updater.

![chrome on vista](https://cloud.githubusercontent.com/assets/15984835/18985845/e007cdb2-86f1-11e6-821f-ddbd1bec440f.PNG)

Chrome on Vista is also slightly different to the current version of Chrome and also differs from Chrome on XP, so it might be worth adding that one in too - it's the same final version of Chrome as there is on XP, making it different to the most recent version, but with a different underlying SChannel implementation. There's no support for AES_256_GCM cipher suites on Chrome on Vista as there is in the most recent version of Chrome, and the AES CBC cipher suites are in a slightly different order. However, Chrome on Vista does support the ECDSA cipher suites, unlike the XP version.

**Comment by bhushan5640** [comment]
Chrome v49 and Firefox v49 on Win XP SP3 now available on dev.ssllabs.com

**Comment by robmoss2k** [comment]
Fantastic - any chance of Chrome on Windows Vista too?

**Comment by bhushan5640** [comment]
It has very less market share
![win_os_market_share](https://cloud.githubusercontent.com/assets/6083185/19068183/1e2212e2-8a3f-11e6-8f14-2112e5421e6b.JPG)

**Comment by robmoss2k** [comment]
Fair enough, can't argue with that. Closing the issue - thanks!
