### ISSUE TITLE
API: Simulation object should contain DHE and ECDHE information

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#403]
Now that there are libraries and servers that support multiple named curves, SSL Labs should extend the API so that each simulation comes not only with a suite ID, but also with the negotiated DHE or ECDHE parameters. That's because some systems will negotiate one named curve (e.g., newer Chrome versions will use x25519) and SSL Labs another (e.g., P-256).

**Comment by bhushan5640** [comment]
Fixed. Please verify : https://api.dev.ssllabs.com/api/v2/analyze?host=www.google.com&all=on
