### ISSUE TITLE
Firefox 49 simulation (AES_256_GCM)

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#404]
Please add Firefox 49 to simulation and to https://www.ssllabs.com/ssltest/clients.html

Firefox now supports TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)  

Thanks 

btw, it also supports TLS 1.3 for experimental (disabled by default)

**Comment by WilliamFeely** [comment]
It seems as if the TLS 1.3 support, contrary to news reports, is not in the production version of Firefox.

**Comment by typingArtist** [comment]
@WilliamFeely, TLS 1.3 is in FF49, but –as @RobTho said, it is not enabled by default. So, if it’s about testing FF 49’s support for TLS 1.3, just set security.tls.version.max to 4 (and restart). If it’s about the actual capabilities of a freshly installed FF 49, I’d be with you by not claiming support for it.

**Comment by bhushan5640** [comment]
Updated on dev.ssllabs.com
