### ISSUE TITLE
Please delete old version of SSL/TLS Deployment Best Practices

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#407]
Please remove this old document: https://www.ssllabs.com/downloads/SSL_TLS_Deployment_Best_Practices.pdf

I've noticed that there are some direct links to this PDF (rather than to the project page), leading to some people using this older version instead of the most recent one.

**Comment by roycewilliams** [comment]
Rather than deleting, could you please link (or redirect, or redirect to a landing page that links)  to whatever the canonical version is now (is it https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices ?)

**Comment by bhushan5640** [comment]
deployed on dev.ssllabs.com
