### ISSUE TITLE
Intermediates reported as invoked when only the leaf is revoked

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#408]
Reported via the community site: https://community.qualys.com/message/34937-possible-bug-in-reporting-revoked-certificates

**Comment by fishouttah20** [comment]
I think I'm seeing a similar issue where SSLLabs reports an Intermediate as being SHA1 but it is in fact the root which is SHA1 (and therefore not an issue) Sending through example domain privately.

**Comment by bhushan5640** [comment]
Fix is deployed on Dev server, kindly verify.
https://dev.ssllabs.com/ssltest/analyze.html?d=revoked.badssl.com
