### ISSUE TITLE
Sites that do not score an 'A-' or better should not be listed in the 'Recent Best' section

### ISSUE THREAD

**Issue by anand-bhat** [ssllabs/ssllabs-scan#409]
As SSL Pulse classifies sites a B/ C as sites with 'inadequate security', these should not be listed in the 'Recent Best' section on the SSL Labs Server test page.

![image](https://cloud.githubusercontent.com/assets/7332442/19079554/a688bac8-8a71-11e6-8b35-c8e7b7132af8.png)

**Comment by roycewilliams** [comment]
"Best" is intended to be relative, not absolute, and really means "recent highest grades", regardless of how good the grades themselves are. If the recent 10 best were all F grades, I would expect to see them all in the Recent Best for the given time window.
