### ISSUE TITLE
Is secp521r1 really gone in Safari 10 / OS X 10.12 (dev.ssllabs.com)?

### ISSUE THREAD

**Issue by Darkudorus** [ssllabs/ssllabs-scan#411]
@ivanr  @bhushan5640 
**Is this really true? Which (beta?) version exaclty had this, when you checked it?**
https://dev.ssllabs.com/ssltest/viewClient.html?name=Safari&version=10&platform=OS%20X%2010.12&key=138
>  Safari 10 / OS X 10.12
> Elliptic curves: x25519, secp256r1, secp384r1 

**My email to Apple because I was afraid about this**
Subject: Re-enable curve secp521r1 (TLS implementation) / broken systems
> Please re-enable P-521 again. (missing since Safari 10 / macOS 10.12)
> https://www.keylength.com/en/3/ Level 8 (same security level as symmetric 256 bit) is desired.
> Please don't weaken long-term security without need.
> You can stop announce P-521 be default, only if Curve 448 has been implemented
> and if Let's Encrypt signs Curve 448 Certificates and if other browsers speak that curve too.
> Mozilla is keeping P-521 too https://bugzilla.mozilla.org/show_bug.cgi?id=1128792#c19

**Apple's reply**
> Please include the line below in follow-up emails for this request.
>
> Follow-up: [...]
> Hello,
> 
> Thank you for contacting us. Apple takes all reports of potential security issues seriously.
> 
> In order to help us reproduce and investigate this issue, we will need some additional details. Do you have a packet capture showing a TLS handshake from Safari on macOS 10.12 where the P-521 curve is disabled? If so, we would appreciate it if you could send that along to us.
> 
> Best regards,
[...]
> Apple Product Security

Someone wrote on the [heise.de forums](https://www.heise.de/forum/Mac-i/News-Kommentare/Apple-Chef-Tim-Cook-Ohne-Verschluesselung-keine-Sicherheit/Re-A-hat-elliptische-Kurve-secp521r1-long-term-security-bei-OS-X-10-12-entfe/posting-29311249/show/) that he has macOS 10.12 (16A323)  + safari 10.0 (12602.1.50.0.10) and gets "Elliptic curves secp256r1, secp384r1, secp521r1" as result. And where is x25519?

**Comment by Darkudorus** [comment]
Apple:
> Follow-up: [...]
> 
> Hello,
> 
> Thank you for reporting this issue to SSL Labs.
> 
> The "Safari 10 / OS X 10.12" results from https://dev.ssllabs.com/ssltest/clients.html are incorrect. > macOS 10.12 continues to support elliptic curves secp256r1, secp384r1, and secp521r1.
> 
> If you have any questions or concerns please feel free to contact us.
> 
> Best regards,
> [...]
> Apple Product Security

**Comment by ivanr** [comment]
Hmmm, the output for Safari 10/ OS X 10.12 is identical to Chrome's: https://dev.ssllabs.com/ssltest/viewClient.html?name=Chrome&version=51&platform=Win%207&key=126

**Comment by bhushan5640** [comment]
@Darkudorus please verify now https://dev.ssllabs.com/ssltest/viewClient.html?name=Safari&version=10&key=138

**Comment by Darkudorus** [comment]
VERIFIED FIXED
