### ISSUE TITLE
Prod and Dev sites don't give option to Ignore Cert Name Mismatch if domain has multiple endpoints

### ISSUE THREAD

**Issue by fishouttah20** [ssllabs/ssllabs-scan#412]
Trying to scan a domain that has multiple IPs but 3 of the IPs have a mismatched cert and 2 get an "unable to connect" error. On the website there is no option to ignore the certificate name mismatch and complete a scan of the domain. 

I believe previously there was a link to Ignore mismatch.

**Comment by ivanr** [comment]
Any chance you could tell us what the hostname is? It will take a lot of time to test in a lab.

There's a workaround you can deploy. When on any existing report, copy the URL, change the hostname to the one you wish to test, then append "&ignoreMismatch=on". The result must not be in the cache. If it is in the cache, you can append the same to the clearCache URL.

**Comment by fishouttah20** [comment]
sent via Twitter DM

**Comment by bhushan5640** [comment]
Fix deployed on Dev server, Please verify !

**Comment by fishouttah20** [comment]
I can confirm this is fixed on Dev. The Resolving Domain Names step seems to take much longer than previously, on the order of 15-20 seconds instead of 4-5.
