### ISSUE TITLE
RC4 accepted but not punished

### ISSUE THREAD

**Issue by mainboarder** [ssllabs/ssllabs-scan#414]
![bildschirmfoto vom 2016-10-20 17-05-27](https://cloud.githubusercontent.com/assets/3955011/19565592/9d815020-96e7-11e6-98a6-cc1704060098.png)
You see a configuration, where the server hides RC4 but accepts connection via this cipher.

In the protocol details section is no penalty for this configuration, it is recognized as RC4: no.

**Comment by ivanr** [comment]
It's possible that the server supports RC4 only with lower protocols and not with the highest-supported version, which SSL Labs currently uses for testing. Maybe @bhushan5640 can tell us because he's been working on implementing per-protocol cipher suite testing.

**Comment by bhushan5640** [comment]
@mainboarder as Ivan said it seems that the server supports RC4 suite, If you can share hostname I can verify it. We have implemented per-protocol cipher suite testing which should detect RC4 (We have not yet released per-protocol suite testing).

You can PM hostname on https://twitter.com/BhushanLokhande

**Comment by mainboarder** [comment]
Ok, just sent you the hostname

**Comment by bhushan5640** [comment]
RC4 suites are detected with per-protocol suite test. So, you will get correct results once per-protocol testing is released. 
![image](https://cloud.githubusercontent.com/assets/6083185/19593460/552d29ea-979e-11e6-9b99-b8fa0b8f3a18.png)

**Comment by mainboarder** [comment]
ok, so it is not a bug (at least in future). I close this ticket.
Thanks! :)
