### ISSUE TITLE
Investigate lack of HSTS on www.targobank.de

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#416]
Reported on https://community.qualys.com/message/35167-server-sends-hsts-twice-ssl-labs-reports-none

There's a couple of things going on here. First, it seems that this web site doesn't like the SSL Labs user agent, because it's responding with 403. The same happens with curl. When responding with 403, it sends two HSTS headers, but SSL Labs is not reporting anything. This is the second problem. SSL Labs should process the first and warn about the presence of the second, per the HSTS RFC.

**Comment by bhushan5640** [comment]
Fix deployed on the Dev server. Adding following request header resolved the issue
Accept: */*

We have warning for presence of more than one header
"Server provided more than one HSTS header"
