### ISSUE TITLE
No error messages for insecure ciphers

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#419]
There is no error message in the top section of the report when a site is penalized because it supports insecure ciphers. For example:
https://www.ssllabs.com/ssltest/analyze.html?d=static-rsa.badssl.com

**Comment by bhushan5640** [comment]
Fixed. Deployed on Dev server. https://dev.ssllabs.com/ssltest/analyze.html?d=static-rsa.badssl.com

**Comment by RobTho** [comment]
Hi,

no "insecure" BAR when other Ciphers that are treated as insecure like RC4 ? Only when Null ?
https://dev.ssllabs.com/ssltest/analyze.html?d=rc4.badssl.com&hideResults=on

**Comment by bhushan5640** [comment]
For various insecure Ciphers we have different messages
eg. For Anonymous insecure Ciphers we have different Bar that says Grade set to F because of Anonymous suites.

I think for above rc4.badssl.com Bar message is correct but it should also say Grade set to F.
