### ISSUE TITLE
ssllabs-scan.exe gives error as : JSON unmarshal error: json: cannot unmarshal array into Go value of type map[string]string. Was working well till 20th of october 2016. Has something changed?

### ISSUE THREAD

**Issue by marc88** [ssllabs/ssllabs-scan#421]
ssllabs-scan.exe gives erros as : JSON unmarshal error: json: cannot unmarshal array into Go value of type map[string]string. Was working well till 20th of october 2016. Has something changed ?

**Comment by bhushan5640** [comment]
Have you updated to the latest binary?
ssllabs-scan client 1.4.0 released (https://github.com/ssllabs/ssllabs-scan/releases). Kindly verify !

**Comment by shoaibz90** [comment]
tried with the latest binary too ssllabs-scan_1.4.0-linux64.tgz .. getting the same error. Kindly help!

**Comment by marc88** [comment]
ssllabs-scan client 1.4.0 worked for me but, am not sure why should the ssllabs-scan client 1.2 fail at the first place?

**Comment by bhushan5640** [comment]
@shozibz90 please try now.
@marc88 we have some changes in API in SSL Labs version 1.24.4 that are not compatible with older clients.
