### ISSUE TITLE
Correctly identify GREASE in the client test

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#423]
As discussed on the community site: https://community.qualys.com/message/35341-re-new-suites-in-chrome

**Comment by bhushan5640** [comment]
Grease suites are now identified in the client test.https://dev.ssllabs.com/ssltest/viewMyClient.html

**Comment by ArchangeGabriel** [comment]
Then what are those “Signature algorithms” `Unknown (0x8)/Unknown (0x4), Unknown (0x8)/Unknown (0x5), Unknown (0x8)/Unknown (0x6)` and “Elliptic curves” `Unknown (0x100), Unknown (0x101)` I just got?

**Comment by bhushan5640** [comment]
These are from TLS 1.3 Signature algorithms (https://tools.ietf.org/html/draft-ietf-tls-tls13-18#section-4.2.3),
These will be added later once draft is finalized as they are having some overrides with TLS 1.2 Signature algorithms (https://tools.ietf.org/html/rfc5246#section-7.4.1.4.1)

For GREASE suites/curves are added from following rfc draft : https://tools.ietf.org/html/draft-davidben-tls-grease-01#section-5
