### ISSUE TITLE
SHA-1 deprecation

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#425]
ssllabs test with sha-1 currently only result

"Certificate has a weak signature and expires after 2015. Upgrade to SHA2 to avoid browser warnings"
https://www.ssllabs.com/ssltest/analyze.html?d=sha1-2017.badssl.com
https://www.ssllabs.com/ssltest/analyze.html?d=sha1-2016.badssl.com

due Browsers will block sha-1 soon:
https://community.qualys.com/message/35468-sha-1-deprecation-countdown

The warning bar might should be changed to something like the RC4 warning, now.
e.g  ".... From early 2017, modern browsers won't connect to it."

**Comment by bhushan5640** [comment]
SHA1 certs are downgraded via Future grade feature.
