### ISSUE TITLE
Better error message on connection failure

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#428]
As discussed here https://community.qualys.com/message/35500-re-ssl-test-fails-due-to-firewall-rules-on-number-of-states-per-source-ip it's possible that the cipher suite support test is hiding connection problems. In addition, when the test does fail because of a connection problem we should have an explanation on the same page to explain that it usually happens due to firewall restrictions.

**Comment by bhushan5640** [comment]
per protocol suite testing is correctly showing connection problems.

Description updated:
**Unable to connect to server** - failed to connect to the server, it usually happens due to firewall restrictions
