### ISSUE TITLE
Move famous vulnerabilities to separate subdoc

### ISSUE THREAD

**Issue by AverageS** [ssllabs/ssllabs-scan#429]
Right now vulnerabilities such as BEAST, Poodle, heartbleed are just fields in details subdoc. That make their parsing really difficult in case there is some new vulnerability with name - one should add its name to parser manually. Are there any chances to automate this process, maybe add these vulnerabilities to separate subdoc ?

**Comment by ivanr** [comment]
I am sorry, do you mean the API or some of the documentation?

**Comment by AverageS** [comment]
I mean API. 
Now returned json looks like { 
poodle: 0/1, 
vulnbeast = 0/1,
} and so on. Imagine there is a new vulnerability called xxxx. In that case returned json would be like 
{ 
poodle: 0/1,
vulnbeast: 0/1,
xxxx: 0/1 
} and it breaks automatic scans. If i want to write a script that notificates me if vulnerability exists in my site i would have to hardcode each vulnerability in my script, which is not supportable at all.

**Comment by ivanr** [comment]
I understand, I think this ticket is a duplicate of #52.
