### ISSUE TITLE
CORS or json-p

### ISSUE THREAD

**Issue by ngavard** [ssllabs/ssllabs-scan#430]
Hi ssllabs team,

I don't know if this is the right place (ssllabs-scan) for a request on the api but I try :
Is there a way to add cors or json-p capabilities to your api in order to call it from a web page of our own domain ?

**Comment by bhushan5640** [comment]
you need to adhere to SSL Labs terms of use https://www.ssllabs.com/downloads/Qualys_SSL_Labs_Terms_of_Use.pdf
you can reach out https://community.qualys.com/people/ysannegowda through Qualys community

**Comment by ngavard** [comment]
Thanks bhushan5640 for your reply.

I"m not sure to understand the how CORS/jsonp is related to ssl labs terms of use. Perhaps, you guess that an access to the api from a web page means "access for commercial purposes" ?

We just want to scan our server from an internal HTML web page (that performs others checks too) without the need for a server.

As stated in the following thread https://community.qualys.com/thread/15042
It's seems we are ok with the term of use.

**Comment by bhushan5640** [comment]
1. Yes. using api to show results on webpage is not allowed

2. With SSL Labs you can not scan Internal (Intranet ) servers. You can scan your own public servers using API that's what it means.

**Comment by ngavard** [comment]
Ok thanks again for your reply.

**Comment by semangar** [comment]
Maybe at least you should allow HEAD http request in order to just get the grade.
It is the solution for example provided by https://securityheaders.io/
