### ISSUE TITLE
Incorrect KX reported

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#431]
See here: https://dev.ssllabs.com/ssltest/analyze.html?d=www.rlove.org&s=2600%3a3c03%3a0%3a0%3af03c%3a91ff%3afe93%3a8a0b

In a few quick tests with OpenSSL I saw nothing but 4096-bit DHE.

Reported via Twitter:  https://twitter.com/rlove/status/804699201716285440

**Comment by bhushan5640** [comment]
Resolved !
