### ISSUE TITLE
Unable to connect to the server

### ISSUE THREAD

**Issue by beamzer** [ssllabs/ssllabs-scan#432]
I have read previous issues which gave this error message, but fail to debug it myself.
The website i want to test seems perfectly reachable, and results in a grade:
[https://dev.ssllabs.com/ssltest/analyze.html?d=info.amc.nl&hideResults=on](info.amc.nl)
but the cmd-line test fails:
> ~/ssllabs-scan]$ go run ssllabs-scan.go --grade=true --verbosity=debug info.amc.nl
> 2016/12/09 15:15:04 [DEBUG] Request #1: https://api.ssllabs.com/api/v2/info
> 2016/12/09 15:15:05 [DEBUG] Response #1 status: HTTP/1.1 200 OK
> 2016/12/09 15:15:05 [DEBUG] Server set current assessments to 0
> 2016/12/09 15:15:05 [DEBUG] Server set maximum assessments to 25
> 2016/12/09 15:15:05 [INFO] SSL Labs v1.25.2 (criteria version 2009l)
> 2016/12/09 15:15:05 [NOTICE] Server message: This assessment service is provided free of charge by Qualys SSL Labs, subject to our terms and conditions: https://www.ssllabs.com/about/terms.html
> 2016/12/09 15:15:07 [INFO] Assessment starting: info.amc.nl
> 2016/12/09 15:15:07 [DEBUG] Request #2: https://api.ssllabs.com/api/v2/analyze?host=info.amc.nl&all=done&startNew=on
> 2016/12/09 15:15:08 [DEBUG] Response #2 status: HTTP/1.1 200 OK
> 2016/12/09 15:15:08 [DEBUG] Server set current assessments to 1
> 2016/12/09 15:15:13 [DEBUG] Request #3: https://api.ssllabs.com/api/v2/analyze?host=info.amc.nl&all=done
> 2016/12/09 15:15:13 [DEBUG] Response #3 status: HTTP/1.1 200 OK
> 2016/12/09 15:15:18 [DEBUG] Request #4: https://api.ssllabs.com/api/v2/analyze?host=info.amc.nl&all=done
> 2016/12/09 15:15:18 [DEBUG] Response #4 status: HTTP/1.1 200 OK
> 2016/12/09 15:15:23 [DEBUG] Request #5: https://api.ssllabs.com/api/v2/analyze?host=info.amc.nl&all=done
> 2016/12/09 15:15:23 [DEBUG] Response #5 status: HTTP/1.1 200 OK
> 2016/12/09 15:15:23 [DEBUG] Server set current assessments to 0
> 2016/12/09 15:15:23 [DEBUG] Server set maximum assessments to 24
> 2016/12/09 15:15:24 [INFO] Assessment complete: info.amc.nl (1 host in 15 seconds)
    145.117.214.28: Err: Unable to connect to the server
> 2016/12/09 15:15:24 [DEBUG] Active assessments: 0 (more: false)
> 2016/12/09 15:15:24 [INFO] All assessments complete; shutting down

The API call returns:

`{
  "host": "info.amc.nl",
  "port": 443,
  "protocol": "HTTP",
  "isPublic": false,
  "status": "READY",
  "startTime": 1481292986414,
  "testTime": 1481293001451,
  "engineVersion": "1.25.2",
  "criteriaVersion": "2009l",
  "cacheExpiryTime": 1481293601451,
  "endpoints": [
    {
      "ipAddress": "145.117.214.28",
      "serverName": "info.amc.nl",
      "statusMessage": "Unable to connect to the server",
      "statusDetails": "TESTING_PROTO_2_0",
      "statusDetailsMessage": "Testing SSL 2.0",
      "progress": -1,
      "duration": 15013,
      "eta": -1,
      "delegation": 1,
      "details": {
        "hostStartTime": 1481292986414,
        "key": {},
        "cert": {},
        "chain": {},
        "protocols": [],
        "suites": {},
        "prefixDelegation": false,
        "nonPrefixDelegation": true
      }
    }
  ]
}`

Testing other servers works without problems.
Any clues?

**Comment by bhushan5640** [comment]
Have you tried with --api https://api.dev.ssllabs.com/api/v2  ?

**Comment by beamzer** [comment]
Yes! That works.
Thanks for helping me out!
