### ISSUE TITLE
Problem with v1.26.1

### ISSUE THREAD

**Issue by SkateScout** [ssllabs/ssllabs-scan#434]
Hi,

i am not shure why but the DEV test fail while the Produktion work.
DEV is going up to over 90% on cipher suite tests.

https://dev.ssllabs.com/ssltest/analyze.html?d=suche.org
-> Assessment failed: Internal Error  (Assessed on:  Tue, 13 Dec 2016 10:48:43 UTC ; SSL Report v1.26.1)
https://www.ssllabs.com/ssltest/analyze.html?d=suche.org
-> A+ (Assessed on:  Tue, 13 Dec 2016 10:45:39 UTC ; SSL Report v1.25.2)

**Comment by bhushan5640** [comment]
Resolved Kindly verify !

**Comment by SkateScout** [comment]
Thanks works fine :-)

**Comment by bhushan5640** [comment]
Does this server actually works on TLS 1.0 clients ?
Android 4.3 EC 521 (SHA256)   TLS 1.0	TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA   ECDH secp521r1  FS

**Comment by SkateScout** [comment]
The answer is not an single yes or no. The server "works" with an selected list of clients. Using older Protocol. These clients only see an information page requesting them to upgrade the browser. They are identified by their SSL-Hello Fingerprint. That is why the overall test say that the server does not work with anything than TLSv1.2. I got the idea by two points SSL-Slabs report about Fingerprint and the Discussion about LegacyValidated Certificates with MD5. If you like more Information you can send me an mail (Username at Domain)
