### ISSUE TITLE
[v1.26.0/1.26.1] Wrong Curves and DH sizes displayed

### ISSUE THREAD

**Issue by zzq1015** [ssllabs/ssllabs-scan#435]
In the "Cipher Suites" section, beside the ECDHE suites, wrong curves are displayed, X25519 sometimes displayed for servers not supporting it.
Also, sizes for DHE suites are inconsistent. Servers using 2048-bit DH could be displayed as 4096 bits or worse, 1024 bits, causing your grade capped at B.
Examples: 
https://dev.ssllabs.com/ssltest/analyze.html?d=bugs.launchpad.net&s=91.189.89.225
https://www.ssllabs.com/ssltest/analyze.html?d=bugs.launchpad.net&s=91.189.89.225
The client handshake simulation section seems to be fine.

**Comment by bhushan5640** [comment]
Resolved Kindly verify !!
