### ISSUE TITLE
A cipher is not in the "Cipher Suites" list but in the "Handshake Simulation" as successful connection

### ISSUE THREAD

**Issue by eitancaspi** [ssllabs/ssllabs-scan#438]
Hello,

The cipher of TLS_RSA_WITH_3DES_EDE_CBC_SHA is shown in the “Handshake Simulation” list as a successful connection:
“
IE 8 / XP   No FS 1	  No SNI 2	RSA 2048 (SHA256)  	TLS 1.0	TLS_RSA_WITH_3DES_EDE_CBC_SHA
“
But not found at the "Cipher Suites" itself.

If I understand correctly – if it is not in the “Cipher Suites” list, it should have shown as failed in the "Handshake Simulation" list

I have a SSL server test link to demonstrate it, but I wish not to disclose it publicly, so if you wish for it – please send me an email from sslLabs and I will reply with a link to it.

Thanks!

**Comment by bhushan5640** [comment]
could you please check on dev.ssllabs.com
If cipher suite is shown in the supported list.

you can DM me on twitter @BhushanLokhande
https://mobile.twitter.com/bhushanlokhande

**Comment by eitancaspi** [comment]
I didn't find such list in the link. do you have a more accurate link?

**Comment by RobTho** [comment]
https://dev.ssllabs.com/

**Comment by bhushan5640** [comment]
@eitancaspi Please check if cipher suite is listed under below section on dev.ssllabs.com
**# TLS 1.0 No SNI (suites in server-preferred order)**
