### ISSUE TITLE
Invalid JSON returned...

### ISSUE THREAD

**Issue by seccubus** [ssllabs/ssllabs-scan#44]
In some cases the API results invalid JSON accoording to the perl library JSON.

E.g. 

$ ./ssllabs-scan.pl -h seccubus.com -v -v -v --from-cache
calling info
SSL Labs v1.12.8 (criteria version 2009i)
Maximum number of concurrent assessments: 5
Starting scan of seccubus.com
Calling analyze?host=seccubus.com&all=done&fromCache=on
*** RESPONSE HEADERS ***
Connection : close
Date : Tue, 27 Jan 2015 21:42:09 GMT
Server : Apache
Content-Type : application/json;charset=ISO-8859-1
Client-Aborted : die
Client-Date : Tue, 27 Jan 2015 21:42:49 GMT
Client-Peer : 104.130.202.77:443
Client-Response-Num : 1
Client-SSL-Cert-Issuer : /C=GB/ST=Greater Manchester/L=Salford/O=COMODO CA Limited/CN=COMODO RSA Domain Validation Secure Server CA
Client-SSL-Cert-Subject : /OU=Domain Control Validated/OU=PositiveSSL/CN=api.dev.ssllabs.com
Client-SSL-Cipher : DHE-RSA-AES256-SHA
Client-SSL-Socket-Class : IO::Socket::SSL
Client-SSL-Warning : Peer certificate not verified
Client-Transfer-Encoding : chunked
Set-Cookie : JSESSIONID=290B2398A7C36B8CF65DF7197FF3B9DF; Path=/; Secure; HttpOnly
Strict-Transport-Security : max-age=31536000
X-ClientMaxAssessments : 5
X-Died : Missing newline after chunk data: 'e":"BingBot",' at /System/Library/Perl/Extras/5.16/Net/HTTP/Methods.pm line 481.
*** RESPONSE DATA ***
{"host":"seccubus.com","port":443,"protocol":"HTTP","isPublic":false,
  "status":"READY","startTime":1422393462881,"testTime":1422393606749,
  "engineVersion":"1.12.8","criteriaVersion":"2009i","endpoints":[{
      "ipAddress":"178.237.34.227","serverName":
      "a4091.mcehosting.atom86.net","statusMessage":"Ready","grade":"M",
      "hasWarnings":false,"isExceptional":false,"progress":100,"duration":
      93366,"eta":24,"delegation":1,"details":{"hostStartTime":
        1422393462881,"key":{"size":4096,"alg":"RSA","debianFlaw":false,
          "strength":4096},"cert":{"subject":
          "1.2.840.113549.1.9.1\u003d#161a706f73746d61737465724073656374696f6e7a65726f2e6f7267,CN\u003dssl.sectionzero.org,C\u003dNL,2.5.4.13\u003d#13105741557563715339456b4745364c4a65",
          "commonNames":["ssl.sectionzero.org"],"altNames":[
            "ssl.sectionzero.org","sectionzero.org"],"notBefore":
          1413388924000,"notAfter":1445029542000,"issuerSubject":
          "CN\u003dStartCom Class 1 Primary Intermediate Server CA,OU\u003dSecure Digital Certificate Signing,O\u003dStartCom Ltd.,C\u003dIL",
          "sigAlg":"SHA1withRSA","issuerLabel":
          "StartCom Class 1 Primary Intermediate Server CA","revocationInfo":
          3,"crlURIs":["http://crl.startssl.com/crt1-crl.crl"],"ocspURIs":[
            "http://ocsp.startssl.com/sub/class1/server/ca"],
          "revocationStatus":2,"sgc":0,"issues":8},"chain":{"certs":[{
              "subject":
              "1.2.840.113549.1.9.1\u003d#161a706f73746d61737465724073656374696f6e7a65726f2e6f7267,CN\u003dssl.sectionzero.org,C\u003dNL,2.5.4.13\u003d#13105741557563715339456b4745364c4a65",
              "label":"ssl.sectionzero.org","issuerSubject":
              "CN\u003dStartCom Class 1 Primary Intermediate Server CA,OU\u003dSecure Digital Certificate Signing,O\u003dStartCom Ltd.,C\u003dIL",
              "issuerLabel":
              "StartCom Class 1 Primary Intermediate Server CA","raw":
              "-----BEGIN CERTIFICATE-----\nMIIHZjCCBk6gAwIBAgIDE51oMA0GCSqGSIb3DQEBBQUAMIGMMQswCQYDVQQGEwJJTDEWMBQGA1UE\r\nChMNU3RhcnRDb20gTHRkLjErMCkGA1UECxMiU2VjdXJlIERpZ2l0YWwgQ2VydGlmaWNhdGUgU2ln\r\nbmluZzE4MDYGA1UEAxMvU3RhcnRDb20gQ2xhc3MgMSBQcmltYXJ5IEludGVybWVkaWF0ZSBTZXJ2\r\nZXIgQ0EwHhcNMTQxMDE1MTYwMjA0WhcNMTUxMDE2MjEwNTQyWjBxMRkwFwYDVQQNExBXQVV1Y3FT\r\nOUVrR0U2TEplMQswCQYDVQQGEwJOTDEcMBoGA1UEAxMTc3NsLnNlY3Rpb256ZXJvLm9yZzEpMCcG\r\nCSqGSIb3DQEJARYacG9zdG1hc3RlckBzZWN0aW9uemVyby5vcmcwggIiMA0GCSqGSIb3DQEBAQUA\r\nA4ICDwAwggIKAoICAQDD3NC+uCEUItP+2Ote59n2Ah3bEQcpf7D2qqRS5NrvUJsVk558YVOPG1Cx\r\n9ORpk9CBp6EfF9Rnnidgn0gXEVJsHttLoyueiT1n0DrL4cLKYdcSGNMhCG51EypVq98VIIbxouqc\r\nwnLHjjdBA4yiZPFpnjMqJLlJjJrh2S3eUixCpWk5rqH+8Oyl36kYVOuju1GlJ2ch14IXdAjVSxjg\r\nnoK4niVrSNAEgQ6iz/byCgLD0e4Zwd2R+u9ujvOstAmGLCQ9HvFcQo/GLPnfc9b1ZOewqZZRKUsW\r\nDt7VaWaF1qBsStU+/10fIjyW72xP6QpiqRXDRM57c+LhhjGpoaTv8rfV9UaW2XYCw1ouEiQShxfn\r\nejTH/rdmyfqQ7baPXdQw5JGjHF7z+Wu0QDh1oVpRxauwGVRwov/yB0s+UCmrFZc3Lg4oUHyXkGuK\r\nEhJpNmfGdEtWXMWmqfb1jvskcMUfP1IkHR7fmDjtwNvH1saQtbkuSqkuLKe6Gy3O3dczwGNypgEx\r\nI10VTZaxWVV7b6C+LnoR/O3lhm8smOzu+gvyqTC4OXAyvOym1CH5O9CDf6QPDu1y82PlUJZhynWv\r\nk5CR2iAMIoD/Txas0HnfXR6a4lglYJALFKov9Ep/J0Z+8CLM5/cU1DjniQ21P8Gj8Ly04Ycxuc8Q\r\nBb1gsybwjgO+INeKuwIDAQABo4IC6TCCAuUwCQYDVR0TBAIwADALBgNVHQ8EBAMCA6gwEwYDVR0l\r\nBAwwCgYIKwYBBQUHAwEwHQYDVR0OBBYEFDjYnPa4rHIVD2nd9X3zcKsuR1+RMB8GA1UdIwQYMBaA\r\nFOtCNNCYsKuf9BtrCPfMZC7vDixFMC8GA1UdEQQoMCaCE3NzbC5zZWN0aW9uemVyby5vcmeCD3Nl\r\nY3Rpb256ZXJvLm9yZzCCAVYGA1UdIASCAU0wggFJMAgGBmeBDAECATCCATsGCysGAQQBgbU3AQID\r\nMIIBKjAuBggrBgEFBQcCARYiaHR0cDovL3d3dy5zdGFydHNzbC5jb20vcG9saWN5LnBkZjCB9wYI\r\nKwYBBQUHAgIwgeowJxYgU3RhcnRDb20gQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwAwIBARqBvlRo\r\naXMgY2VydGlmaWNhdGUgd2FzIGlzc3VlZCBhY2NvcmRpbmcgdG8gdGhlIENsYXNzIDEgVmFsaWRh\r\ndGlvbiByZXF1aXJlbWVudHMgb2YgdGhlIFN0YXJ0Q29tIENBIHBvbGljeSwgcmVsaWFuY2Ugb25s\r\neSBmb3IgdGhlIGludGVuZGVkIHB1cnBvc2UgaW4gY29tcGxpYW5jZSBvZiB0aGUgcmVseWluZyBw\r\nYXJ0eSBvYmxpZ2F0aW9ucy4wNQYDVR0fBC4wLDAqoCigJoYkaHR0cDovL2NybC5zdGFydHNzbC5j\r\nb20vY3J0MS1jcmwuY3JsMIGOBggrBgEFBQcBAQSBgTB/MDkGCCsGAQUFBzABhi1odHRwOi8vb2Nz\r\ncC5zdGFydHNzbC5jb20vc3ViL2NsYXNzMS9zZXJ2ZXIvY2EwQgYIKwYBBQUHMAKGNmh0dHA6Ly9h\r\naWEuc3RhcnRzc2wuY29tL2NlcnRzL3N1Yi5jbGFzczEuc2VydmVyLmNhLmNydDAjBgNVHRIEHDAa\r\nhhhodHRwOi8vd3d3LnN0YXJ0c3NsLmNvbS8wDQYJKoZIhvcNAQEFBQADggEBAIVe75Qg8U4HimwR\r\n3TGIdvDiUkDFaeO670JlPnaaKW0kZFU3iGhxu7pmBZ0onhb1ZRGC2EBXpz6nRvcBRgnX+wInNgXN\r\nNRWhJ496neZj5EIh47L3LOmrXz0VATZIfw/VQ6hNuKwpZoPzvvcR+GTKjmK4yyn4xlKWNjRtLyaf\r\nlAaD7Lgmdc6xzeMzB65fXYd51eiDdtWgmzUSfycYvh+qSnl1dYo/gH0RNTZHmt7beH1PQqhA4MCq\r\nbqq3IKuaG5UpSr/eJJfx8ZEpmscMM6aGS2zgaPjnSk5XRssi7U/hEc+VKnYjXKNDcSF56AwvilL6\r\n0whsS2Y/p4JRRE0tt+pz2z8\u003d\r\n-----END CERTIFICATE-----\n"}],
          "issues":2},"protocols":[{"id":769,"name":"TLS","version":"1.0"},{
            "id":770,"name":"TLS","version":"1.1"},{"id":771,"name":"TLS",
            "version":"1.2"}],"suites":{"list":[{"id":49199,"name":
              "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256","cipherStrength":128,
              "ecdhBits":256,"ecdhStrength":3072},{"id":49200,"name":
              "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384","cipherStrength":256,
              "ecdhBits":256,"ecdhStrength":3072},{"id":158,"name":
              "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256","cipherStrength":128,
              "dhStrength":4096,"dhP":512,"dhG":1,"dhYs":512},{"id":159,
              "name":"TLS_DHE_RSA_WITH_AES_256_GCM_SHA384","cipherStrength":
              256,"dhStrength":4096,"dhP":512,"dhG":1,"dhYs":512},{"id":
              49191,"name":"TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256",
              "cipherStrength":128,"ecdhBits":256,"ecdhStrength":3072},{"id":
              49171,"name":"TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
              "cipherStrength":128,"ecdhBits":256,"ecdhStrength":3072},{"id":
              49192,"name":"TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384",
              "cipherStrength":256,"ecdhBits":256,"ecdhStrength":3072},{"id":
              49172,"name":"TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
              "cipherStrength":256,"ecdhBits":256,"ecdhStrength":3072},{"id":
              103,"name":"TLS_DHE_RSA_WITH_AES_128_CBC_SHA256",
              "cipherStrength":128,"dhStrength":4096,"dhP":512,"dhG":1,
              "dhYs":512},{"id":51,"name":
              "TLS_DHE_RSA_WITH_AES_128_CBC_SHA","cipherStrength":128,
              "dhStrength":4096,"dhP":512,"dhG":1,"dhYs":512},{"id":107,
              "name":"TLS_DHE_RSA_WITH_AES_256_CBC_SHA256","cipherStrength":
              256,"dhStrength":4096,"dhP":512,"dhG":1,"dhYs":512},{"id":57,
              "name":"TLS_DHE_RSA_WITH_AES_256_CBC_SHA","cipherStrength":
              256,"dhStrength":4096,"dhP":512,"dhG":1,"dhYs":512}],
          "preference":true},"serverSignature":"Apache","prefixDelegation":
        false,"nonPrefixDelegation":true,"vulnBeast":true,"renegSupport":2,
        "sessionResumption":2,"compressionMethods":0,"supportsNpn":false,
        "sessionTickets":1,"ocspStapling":false,"sniRequired":false,
        "httpStatusCode":403,"supportsRc4":false,"forwardSecrecy":4,
        "rc4WithModern":false,"sims":{"results":[{"client":{"id":56,"name":
                "Android","version":"2.3.7","isReference":false},"errorCode":
              0,"attempts":1,"protocolId":769,"suiteId":51},{"client":{"id":
                58,"name":"Android","version":"4.0.4","isReference":false},
              "errorCode":0,"attempts":1,"protocolId":769,"suiteId":49171},{
              "client":{"id":59,"name":"Android","version":"4.1.1",
                "isReference":false},"errorCode":0,"attempts":1,"protocolId":
              769,"suiteId":49171},{"client":{"id":60,"name":"Android",
                "version":"4.2.2","isReference":false},"errorCode":0,
              "attempts":1,"protocolId":769,"suiteId":49171},{"client":{"id":
                61,"name":"Android","version":"4.3","isReference":false},
              "errorCode":0,"attempts":1,"protocolId":769,"suiteId":49171},{
              "client":{"id":62,"name":"Android","version":"4.4.2",
                "isReference":false},"errorCode":0,"attempts":1,"protocolId":
unexpected end of string while parsing JSON string, at character offset 8192 (before "(end of string)") at ./ssllabs-scan.pl line 179.
              771,"suiteId":49199},{"client":{"id":41,"nam

**Comment by cognusion** [comment]
I think you're having a character encoding problem. If you strip out the certificates (which I wish we didn't return to begin with) I believe everything will be fine.

**Comment by ivanr** [comment]
Frank, are you always getting the same result when scanning the same host? The Go JSON decoder doesn't seem to have any problems handling that host.

Also, did you notice the X-Die message, which seems to come from the Perl package? JSON parsing might be failing because only partial response is being received by the client.

**Comment by seccubus** [comment]
@ivanr the X-Die messages seems to suggests that the client is expecting a chucked response, but the chunk isn't terminated by a newline.

So it is not the json that it invalid, but the http response. Is it possible that, because seccubus.com points to an akamai node and thus has multiple servers it returns a large response wich is incorrectly transfer encoded? Odd thing is that wget doesn't seem to have a problem here.

I have not been able to see if I can reproduce just using LWP::UserAgent.

**Comment by ivanr** [comment]
No, the responses you get from SSL Labs are not influenced by the tested infrastructure. I think this might be a bug in the Perl module. Is there a better version you could upgrade to?

**Comment by seccubus** [comment]
Did some further investigation and it does seem like a bug in the one of the core perl modules. 

I downloaded the result with openssl and the check it is offended by is the correct size. So  Net::HTTP seems to have bug here.

**Comment by seccubus** [comment]
It was a known bug in LWP::Protocol::https

https://bugzilla.redhat.com/show_bug.cgi?id=768394

Updated this LWP and LWP:Protocol::https and it works now.
