### ISSUE TITLE
Unable to scan all sites

### ISSUE THREAD

**Issue by ghusk** [ssllabs/ssllabs-scan#443]
Recently following our migration to new load balancers the tool is unable to complete a scan  (note the web-site tool is fine) the exe indicates that it cannot unmarshal the JSON.

`
C:\SSLLabs\ssllabs-scan.exe origin-ecol-eu2.responsetek.com
2017/01/06 17:32:25 [INFO] SSL Labs v1.25.2 (criteria version 2009l)
2017/01/06 17:32:25 [NOTICE] Server message: This assessment service is provided free of charge by Qualys SSL Labs, subject to our terms and conditions: https://www.ssllabs.com/about/terms.html
2017/01/06 17:32:27 [INFO] Assessment starting: origin-ecol-eu2.responsetek.com
2017/01/06 17:34:03 [ERROR] JSON unmarshal error: json: cannot unmarshal array into Go value of type map[string]string
[
]

2017/01/06 17:34:04 [INFO] All assessments complete; shutting down
`

Until this we've had no issues with the tool.  Initially I thought it might be how I was handling the output but I just get the output above.

**Comment by bhushan5640** [comment]
Could you please confirm that you are using the latest client tool binary from the latest release : https://github.com/ssllabs/ssllabs-scan/releases/tag/v1.4.0

**Comment by ghusk** [comment]
I was using v1.3.0.  Scan is working with v1.4.0 .  What I've noticed though is that it is rejecting domains  not using the same case  as the certificate.

**Comment by bhushan5640** [comment]
There isn't any change related to that in API client. It should work as the previous version. Only changes in v1.4.0 is that it handles some API changes (which used to cause unmarshal issue)
