### ISSUE TITLE
Support RFC 7919

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#446]
https://tools.ietf.org/html/rfc7919
Firefox supports one of these at the moment: ffdhe2048(256)

EDIT: Changed ticket name after realising that the new RFC applies equally when testing what it's at the moment called "named curves". Thus it applies to both server and client tests.

**Comment by bhushan5640** [comment]
Support for RFC 7919 added to server and client tests.
https://dev.ssllabs.com
