### ISSUE TITLE
DEV: "ECDE public server parameter resuse" with IIS

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#450]
1) Is this a known issue for IIS or false positive ?
2) No "more info" behind this detection

![d3](https://cloud.githubusercontent.com/assets/11462929/21956599/e2732bdc-da84-11e6-91b5-4047782f05d6.jpg)

**Comment by BPiEnterprise** [comment]
config

**Comment by ivanr** [comment]
As far I am aware, IIS does reuse server parameters for a period of time. IIRC, it's 2 hours.
