### ISSUE TITLE
certificate serial numbers not displayed

### ISSUE THREAD

**Issue by moustafak** [ssllabs/ssllabs-scan#453]
Presently the certificate serial numbers are not displayed anywhere in the ssllabs api response.

Can I request for the certificate serial number for each of the certificates in chain be shown in the following paths?

details -> cert (cert object)
details -> chain -> certs (each cert object)

**Comment by bhushan5640** [comment]
Fixed. we have added serial number in API v3 certs section
cert -> serialNumber

https://api.dev.ssllabs.com/api/v3/analyze?host=www.ssllabs.com&all=on
