### ISSUE TITLE
Extend the API to expose future grade

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#454]
The future grade information is currently available only via the UI, but not in the API. Those who rely on the API would appreciate the early warning, and maybe even more so.

**Comment by bhushan5640** [comment]
API updated https://api.dev.ssllabs.com/api/v3/analyze?host=3des.badssl.com&all=on

**Comment by Paradox924X** [comment]
This seems to be an issue again.
The futureGrade property is no longer returned by the API.

Ex: https://api.dev.ssllabs.com/api/v3/analyze?host=3des.badssl.com&all=on

**Comment by CKnoxy** [comment]
Is there an expected date when this will return
