### ISSUE TITLE
Change the "more info" link for forward secrecy

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#455]
It currently leads to an old post from 2013, which is now obsolete.

**Comment by jsoref** [comment]
It should probably point to: https://github.com/ssllabs/research/wiki/SSL-and-TLS-Deployment-Best-Practices#25-use-forward-secrecy

I'd offer a PR, but this doesn't appear to be in this repo...

**Comment by bhushan5640** [comment]
Link updated. Check on https://dev.ssllabs.com
