### ISSUE TITLE
Trojan false positive?

### ISSUE THREAD

**Issue by wkrick** [ssllabs/ssllabs-scan#459]
The ssllabs-scan_1.4.0_win64.zip download is being flagged as containing a trojan...

https://www.virustotal.com/en/file/8c682c380d2cf115d1b90c71ef19ec41140ec6f73aa9de476eb36ff3c0b50ccc/analysis/

**Comment by bhushan5640** [comment]
Yes It is false positive. Even for the previous versions of ssllabs-scan binary, some AV reported positive.
