### ISSUE TITLE
Too many failed HTTP requests

### ISSUE THREAD

**Issue by StevenRoddis** [ssllabs/ssllabs-scan#46]
`# ./ssllabs-scan www.google.com`
...
2015/01/29 04:19:22 [ERROR] Too many failed HTTP requests

**Comment by ivanr** [comment]
Please supply additional data for troubleshooting. For example: are all hosts failing for you, or just that one? Always or sometimes? What version of Go are you using and on what operating system? Also, please re-run with -verbosity=trace and paste the output here. Thanks.

**Comment by StevenRoddis** [comment]
I tried with a `--hostfile` (huge list of hosts) and directly with `www.google.com` and `www.github.com`. It waits for a long time then fails each time.

Ubuntu 14.04x64 `3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

go1.2.1 linux/amd64

-verbosity=trace
```
~/ssllabs-scan# ./ssllabs-scan -verbosity=trace www.github.com
2015/01/29 04:36:51 [DEBUG] Request (1): https://api.dev.ssllabs.com/api/fa78d5a4//info
2015/01/29 04:37:21 [DEBUG] Request (2): https://api.dev.ssllabs.com/api/fa78d5a4//info
2015/01/29 04:37:51 [DEBUG] Request (3): https://api.dev.ssllabs.com/api/fa78d5a4//info
2015/01/29 04:38:21 [DEBUG] Request (4): https://api.dev.ssllabs.com/api/fa78d5a4//info
2015/01/29 04:38:52 [DEBUG] Request (5): https://api.dev.ssllabs.com/api/fa78d5a4//info
2015/01/29 04:39:22 [DEBUG] Request (6): https://api.dev.ssllabs.com/api/fa78d5a4//info
2015/01/29 04:39:52 [DEBUG] Request (7): https://api.dev.ssllabs.com/api/fa78d5a4//info
2015/01/29 04:39:52 [ERROR] Too many failed HTTP requests
```
curl -i -X HEAD https://api.dev.ssllabs.com
HTTP/1.1 200 OK
Date: Thu, 29 Jan 2015 09:41:21 GMT
Server: Apache
Content-Type: text/html;charset=UTF-8
Transfer-Encoding: chunked
...
```

**Comment by ivanr** [comment]
I think that's a Go bug. Please try with Go 1.3 or better.

**Comment by StevenRoddis** [comment]
Works with go 1.4.1! Thanks, first time using Go and I grabbed it through `apt-get`.
