### ISSUE TITLE
TLS_FALLBACK_SCSV fails on hiawatha-webserver.org 

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#460]
Hugo reported the problem:

"Since the SSL Labs grading change, I noticed that SSL Labs says my webserver doesn’t support TLS_FALLBACK_SCSV. It did say so before. I use the Hiawatha webserver which uses mbed TLS. mbed TLS has SCSV support. Can you tell me what’s going on?"

Source: https://blog.qualys.com/ssllabs/2016/11/16/announcing-ssl-labs-grading-changes-for-2017#comment-112341

**Comment by hsleisink** [comment]
FYI: The tool https://github.com/rbsec/sslscan says my webserver supports SCSV.

**Comment by bhushan5640** [comment]
Yes test using openssl also shows support for SCSV. We will resolve it soon. Thanks for reporting.

**Comment by bhushan5640** [comment]
There are no changes in [SCSV fallback](https://tools.ietf.org/html/rfc7507#section-3) test on SSL Labs.

I observed the following behavior: when TLS_FALLBACK_SCSV is sent at the end of the list, Server correctly sends fallback alert but not when it is not last one.

Case 1: Client should send TLS_FALLBACK_SCSV at the [end of ciphers it intends to negotiate](https://tools.ietf.org/html/rfc7507#section-4). SSL Labs send it at the end but before the TLS_EMPTY_RENEGOTIATION_INFO_SCSV

![scsv_2](https://cloud.githubusercontent.com/assets/6083185/22963873/8e095160-f37b-11e6-8c71-d5ef35a2b422.JPG)
Here server should send the fallback alert and reject handshake as described [here](https://tools.ietf.org/html/rfc7507#section-3), but it does not.

Case 2: When TLS_FALLBACK_SCSV is sent at the end of the all ciphers, Server behaves correctly with fallback alert

![scsv_1](https://cloud.githubusercontent.com/assets/6083185/22963736/909477d0-f37a-11e6-86d9-f99b99b13ac8.JPG)

Tools which send Fallback scsv at the very end reports positive. But It seems issue on the Server end, It doesn't behave correctly in all cases.

**Comment by hsleisink** [comment]
I have notified the [mbed TLS developer](https://github.com/pjbakker).

**Comment by hsleisink** [comment]
Submitted an [issue](https://github.com/ARMmbed/mbedtls/issues/810) to the mbed TLS development team.

**Comment by hsleisink** [comment]
Is it possible to receive a patch for this issue? I want to release a new Hiawatha version and I want this issue to be fixed in this new release. Or can I wait for a new mbed TLS release? Thanks.

**Comment by hsleisink** [comment]
Sorry, forget the patch comment. Should have been posted in the mbed TLS issue. ;)

**Comment by hsleisink** [comment]
There was indeed a bug in mbed TLS, which has been [fixed](https://github.com/ARMmbed/mbedtls/pull/816). This issue can be closed. Thanks for the help!
