### ISSUE TITLE
JSON unmarshal errors when cloning master branch

### ISSUE THREAD

**Issue by fishouttah20** [ssllabs/ssllabs-scan#461]
Trying to get future grade data via the command line scanner. Performed a git clone --branch --single-branch to get latest Master branch. Running a scan results in unmarshal errors as follows:

2017/02/13 14:35:04 [INFO] SSL Labs v1.27.2 (criteria version 2009m)
2017/02/13 14:35:04 [NOTICE] Server message: This assessment service is provided free of charge by Qualys SSL Labs, subject to our terms and conditions: https://dev.ssllabs.com/about/terms.html
2017/02/13 14:35:06 [INFO] Assessment starting: domain-with-future-grade-change
2017/02/13 14:35:07 [ERROR] JSON unmarshal error: json: cannot unmarshal array into Go value of type map[string]string
2017/02/13 14:35:08 [INFO] All assessments complete; shutting down
x$ go run ssllabs-scan.go -version
ssllabs-scan v1.4.x (dev $Id: 4032f71b0b96983e00bd6d543aaeb7f3ae4d6e66 $)
API location: https://api.dev.ssllabs.com/api/v2

**Comment by bhushan5640** [comment]
Fixed issues in the master branch. Command line scanner uses API v2 , It will not work with API V3

Future grade is exposed via API V3 on dev server 
https://api.dev.ssllabs.com/api/v2/analyze?host=3des.badssl.com&all=on

**Comment by fishouttah20** [comment]
Thanks, I can confirm the JSON unmarshal error's aren't appearing in the master branch.

I didn't realize the command line scanner can't handle API v3 yet, I'm assuming that's a planned feature at some stage? I hadn't tried it before but thought the "-api" option would allow me to specify the dev server and /v3/ but having just tried it, more unmarshal errors, which are to be expected when the tool isn't compatible with v3.

Unfortunately this means at this stage there isn't an easy way to check future grades in bulk prior to the grade changes happening.

**Comment by bhushan5640** [comment]
We are working on API V3 client. For now, checking future grade in bulk would need some script which calls api and  check for future grade.

**Comment by bhushan5640** [comment]
You can now get the future grade in json format using SSL Labs API V3 client **ssllabs-scan-v3.go** [GitHub - ssllabs/ssllabs-scan at master](https://github.com/ssllabs/ssllabs-scan/tree/master) 
For now, you can use --api https://api.dev.ssllabs.com/api/v3

For raw Json use:
$ go run ssllabs-scan-v3.go --hostfile hostfile.txt 
 
If you only want to see grades use:
$ go run ssllabs-scan-v3.go --usecache --grade --quiet --hostfile hostfile.txt 
"www.ssllabs.com": "A+"
"3des.badssl.com": "B" -> "C"

**Comment by fishouttah20** [comment]
That's brilliant, you're a rockstar, thanks!!!!

**Comment by fishouttah20** [comment]
So close....see #462
