### ISSUE TITLE
SHAttered

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#466]
https://community.qualys.com/message/36416-shattered-time-to-sha-1-rating

**Comment by ivanr** [comment]
@RobTho I don't know what to do with a one-word title and a link someplace else. If all you need to discuss something, you don't need to cross-post here. Otherwise, please clearly state what the problem is and (optionally) what the expected solution should be. Thanks.

**Comment by RobTho** [comment]
Hi,

please reflect SHA-1 issue (SHAttered) in SSLLabs rating

**Comment by strugee** [comment]
@RobTho SHAttered isn't something you can test for like you can test for e.g. Heartbleed. It's a problem in the SHA-1 algorithm itself, so the only way to really "penalize" for SHAttered is to penalize SHA-1 usage. Which SSL Labs has done for a long while now.

**Comment by RobTho** [comment]
Hi
there is a bar info about SHA1 only but no decrease in rating, when i do not go wrong.
