### ISSUE TITLE
Win64 build 1.40 contains ransomware

### ISSUE THREAD

**Issue by ronaldbckl** [ssllabs/ssllabs-scan#468]
According to my virusscanner zonealarm.
v1.30 does not so there seems to be a trigger in 1.40.
Trojan-Ransom.Win32.Gen.ua
![2017-02-27 12_01_36-zonealarm](https://cloud.githubusercontent.com/assets/15361953/23359241/a6604cd2-fce5-11e6-8f5f-55dc881d8744.png)

**Comment by strugee** [comment]
Duplicate of #459?

**Comment by ronaldbckl** [comment]
Your right, sorry for that!
