### ISSUE TITLE
401 should not affect rating

### ISSUE THREAD

**Issue by felfert** [ssllabs/ssllabs-scan#469]
Just stumbled over this:
If I test the same server twice and enable basic-auth for the index page for the second test (everything else unchanged), then the first test reports A+ and the second test reports A.

-Fritz

**Comment by ivanr** [comment]
If we don't see the Strict-Transport-Security header we have no way of knowing that a site supports HSTS. I don't see a way around it. You can fix this easily by making sure the HSTS header is served on the 401 response. IIRC, with Apache you can use the "always" condition when setting the header. Nginx has a similar facility.
