### ISSUE TITLE
Please make Windows binary

### ISSUE THREAD

**Issue by Cattze2015** [ssllabs/ssllabs-scan#47]
e.g., "TestSSLServer.exe" without java.

I don't use Qualys Webservice because it expose server FQDN & result to public.
I will use your service if I can use it locally(offline). Without online is important.

sslscan.exe --scan 10.0.0.1:443

**Comment by Cattze2015** [comment]
and a source code(*.sln, *.c) so I can verify/improve/recommend/send-pull-request this development.

**Comment by yakatz** [comment]
You can scan without exposing your FQDN. As a matter of fact, when you use the API, the default is not to publish it:  https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs.md.

Anyway, this is only an example and documentation of the API to the SSL Labs service. It can not perform scans offline.

**Comment by seccubus** [comment]
I'm working a perl version of ssl-scan would this work for you @Cattze2015 "?

**Comment by AshleyPoole** [comment]
@Cattze2015  I've already written and released a .NET library you can use to achieve this. In fact, I've even just written a PowerShell that incorporates this for the scrip type folk. I can share this if you'd like?

Here's some information on the .NET library / wrapper as well as the NuGet link.
http://www.ashleypoole.co.uk/ssllwrapper
https://www.nuget.org/packages/SSLLWrapper/

**Comment by ivanr** [comment]
Done.
