### ISSUE TITLE
Unusual error message when certificate not trusted

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#470]
See this report: https://www.ssllabs.com/ssltest/analyze.html?d=www.sos-wp.it

The no-SNI certificate is not trusted because: "invalid certificate: qsPNcxYwjcgoeIq5uu2AwQpNlDGmtg1gkDaEVyxhx0M="

I know this may be an issue with JSSE, but, if it's not a bug in SSL Labs, it would be nice to know what the actual problem was.

**Comment by bhushan5640** [comment]
Certificate with Pin SHA256 "qsPNcxYwjcgoeIq5uu2AwQpNlDGmtg1gkDaEVyxhx0M=" is invalid. 
That particular certificate causes path to be "Not Trusted"

Should we have invalid certificate = [SHA1 fingerprint] here?

**Comment by ivanr** [comment]
I think I got confused because PEM certificates use base64 and look like that pin. In fact, I didn't recognise the pin at all... so I though that there was an internal error of some sort. When identifying the certificate, I'd use the label and maybe say (Pin SHA256: $PIN) in brackets. Is it possible to provide a better message, for example to say why was the certificate deemed invalid?

In any case, it's probably a rare error and not worth spending a lot of time on. I see that the invalid certificate is no longer there. So feel free to close if you don't wish to pursue. Thanks!
