### ISSUE TITLE
SSL Labs rendering issue

### ISSUE THREAD

**Issue by alex** [ssllabs/ssllabs-scan#472]
![screen shot 2017-03-01 at 9 26 48 am](https://cloud.githubusercontent.com/assets/772/23463928/4d16fb8a-fe61-11e6-86df-24185c4b81ff.png)

**Comment by bhushan5640** [comment]
Steps to reproduce? Do you see this behaviour on dev.ssllabs.com or www.ssllabs.com

After which test status this comes?

**Comment by alex** [comment]
This was www.ssllabs.com -- I'm not seeing it anymore, I'll close this unless I can reproduce.
