### ISSUE TITLE
Unexpected version number: 250

### ISSUE THREAD

**Issue by ip6li** [ssllabs/ssllabs-scan#473]
I got on dev.ssllabs.com and www.ssllabs.com following error: "Unexpected version number: 250"

Test object is test.felsing.net, which is implemented with Nginx (git/master) and OpenSSL (git/master) and offers TLSv1.3. Firefox, Chrome/Chromium are able to negotiate TLSv1.3, Internet Explorer negotiates to TLSv1.2.

**Comment by stefanb** [comment]
I am having the same problem on one of my sites:
> Assessment failed: Unexpected version number: 250
Both nginx and openssl built from master branches.

**Comment by stefanb** [comment]
Thank you @bhushan5640 for looking into it.

These sites with same problem can be observed on the "Recently Seen" list:
* https://dev.ssllabs.com/ssltest/analyze.html?d=niklas.pw
* https://dev.ssllabs.com/ssltest/analyze.html?d=test.felsing.net (mentioned by @ip6li)

...
Those might help you verify your fix.

**Comment by hotaru2k3** [comment]
the same thing happens with Apache 2.4 and OpenSSL git/master with TLS 1.3 enabled.

tls13.cloudflare.com uses TLS 1.3 with chrome but doesn't have this issue, so not all TLS 1.3 sites are affected:
https://dev.ssllabs.com/ssltest/analyze.html?d=tls13.cloudflare.com

**Comment by Night1** [comment]
I se the same issue 

built nginx and openssl from source with tls v1,3 enabled,

`nginx version: nginx/1.11.10
built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
built with OpenSSL 1.1.1-dev  xx XXX xxxx
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --conf-path=/etc/nginx/nginx.conf --pid-path=/usr/local/nginx/nginx.pid --with-pcre=../pcre-8.
40 --with-zlib=../zlib-1.2.11 --with-http_ssl_module --with-openssl=/home/niklas/Downloads/nginx/openssl --with-openssl-opt=enable-tls1_3 --with-http_gzip_static_m
odule --with-http_addition_module --with-http_geoip_module --with-http_dav_module --with-http_stub_status_module --with-http_sub_module --with-http_ssl_module --wi
th-stream --with-stream_ssl_module --with-mail=dynamic --with-http_v2_module --add-dynamic-module=/opt/nginx-ct --with-mail=dynamic`

**Comment by bhushan5640** [comment]
We will deploy fix asap. Test used to fail while testing SSL v2. 

Updated openssl responds unexpectedly while testing SSL v2 where we observe unexpected version number.

**Comment by Night1** [comment]
Thank you @bhushan5640, 

Any idea why it triggers for some while not others?

**Comment by bhushan5640** [comment]
I see this issue Openssl specific. All other TLS 1.3 implementations seems to be working with SSL Labs.
https://github.com/tlswg/tls13-spec/wiki/Implementations

**Comment by Night1** [comment]
TLSv1.3 is still in draft, so odd behavior is expected.

**Comment by Henrocker** [comment]
@Night1 Upgrading to draft-19 triggers the error, as well as the current draft-18 branch of openssl... My Website [here](https://dev.ssllabs.com/ssltest/analyze.html?d=www.henrock.net) also says `Incorrect Version number 250` although I use openssl's branch: `tls1.3-draft-18`.

**Comment by bhushan5640** [comment]
Deployed fix on dev.ssllabs.com. Please verify.
Note: SSL Labs will not give results for hosts that support TLS 1.3 only for now.

**Comment by Henrocker** [comment]
Works, www.henrock.net is testable. Thank you!

**Comment by stefanb** [comment]
Works for me too! Thanks!

**Comment by Night1** [comment]
@bhushan5640 
Thank you works fine :) 


Is there an eta on TLSv1.3 support?

**Comment by bhushan5640** [comment]
@Night1 expect it soon

**Comment by Henrocker** [comment]
Thank you, that TLS1.3 gets tested as well now.

**Comment by Night1** [comment]
@bhushan5640  is it only draft-18 which is supported?

**Comment by bhushan5640** [comment]
we will upgrade to draft 20 as soon as browsers start rolling out draft 20
