### ISSUE TITLE
Secondary SSL cert

### ISSUE THREAD

**Issue by SquitoHUN** [ssllabs/ssllabs-scan#476]
I tested my domain's SSL cert (hfhosting.pw) and I can see a second certificate for cloud.hfhosting.pw. It is an existing subdomain (personal storage) with an existing certificate, but these two SSL certificates are not related. These are two separate certificates, the domains are contained in different directories (and are in different config files). Also the second certificate is "NOT TRUSTED", although both domains achieved A+ rating.
[Test of hfhosting.pw](https://www.ssllabs.com/ssltest/analyze.html?d=hfhosting.pw&hideResults=on)
[Test of cloud.hfhosting.pw](https://www.ssllabs.com/ssltest/analyze.html?d=cloud.hfhosting.pw&hideResults=on)

**Comment by strugee** [comment]
@SquitoHUN SSL Labs wouldn't be able to find a second certificate unless it was sent a second certificate. Sounds like your domain is misconfigured.

**Comment by drwetter** [comment]
```
"Certificate #2: RSA 2048 bits (SHA256withRSA) No SNI [Hide Server Certificate] "
                                               ^^^^^^^
```
That is probably the default vhost.

**Comment by bhushan5640** [comment]
Yes, that's default virtual host. For Test of hfhosting.pw
Clients/Browsers (only very old) without SNI support will see "No SNI" certificate (CN: cloud.hfhosting.pw)
![image](https://cloud.githubusercontent.com/assets/6083185/24488469/aa121d8a-1534-11e7-8076-fca00a5af6af.png)

Which is not valid for "hfhosting.pw" so it shows not trusted. (Hostname mismatch)

As explained in "No SNI" tooltip
We've obtained this certificate while connecting to the TLS server without Server Name Indication (SNI) enabled. Only very old clients will get this certificate. Review the complete results in the simulations section.
![image](https://cloud.githubusercontent.com/assets/6083185/24488591/7537217c-1535-11e7-848d-1836ac8289ab.png)

Your site "hfhosting.pw" works only with browsers with SNI support. Nowadays all modern browsers support it. That's the reason we show "No SNI certificate" hidden by default. And you may ignore this certificate if you are not really concerned with supporting very old browsers (eg. IE8/XP)
