### ISSUE TITLE
Grade Changes delayed?

### ISSUE THREAD

**Issue by fishouttah20** [ssllabs/ssllabs-scan#480]
The new grading changes haven't been implemented on production and now say "Our gradings will change in a month" instead of "on April 1st". Has this been delayed a full month or just not switched over yet due to the weekend? Dev appears to have been switched.

**Comment by bhushan5640** [comment]
Not switched over due to weekend. 
Yes Dev is switched.

**Comment by bhushan5640** [comment]
Grade changes now deployed on production www.ssllabs.com

**Comment by fishouttah20** [comment]
Unsure if it's related to the grade change but SSLLabs appears to be down

**Comment by bhushan5640** [comment]
you can track status here https://status.qualys.com
