### ISSUE TITLE
Wrong key size displayed for 3DES in Client Test and User Agent Capabilities

### ISSUE THREAD

**Issue by zzq1015** [ssllabs/ssllabs-scan#484]
https://dev.ssllabs.com/ssltest/viewClient.html?name=IE&version=6&platform=XP&key=100
```
TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)
SSL_CK_DES_192_EDE3_CBC_WITH_MD5 (0x700c0)
TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA (0x13)
```
and anything else contains "`3DES`" should have 112 bits of security instead of 168.
Server Test seems fine.

**Comment by bhushan5640** [comment]
Fixed. Deployed on dev server
https://dev.ssllabs.com/ssltest/viewMyClient.html
