### ISSUE TITLE
cipher not marked as insecure

### ISSUE THREAD

**Issue by xardiasx** [ssllabs/ssllabs-scan#487]
TLS_ECDHE_RSA_WITH_RC4_128_SHA not marked as insecure. However, the site does indicate that it is.

**Comment by bhushan5640** [comment]
Please provide​ details/steps to reproduce.

SSL Labs marks RC4 as insecure.
https://www.ssllabs.com/ssltest/analyze.html?d=rc4.badssl.com&hideResults=on

**Comment by xardiasx** [comment]
Using thesite:             
|  https://www.ssllabs.com/ssltest/analyze.html?d=abaretirement.com&hideResults=on I see this: TLS_ECDHE_RSA_WITH_RC4_128_SHA (0xc011)   ECDH secp256r1 (eq. 3072 bits RSA)   FS   INSECURE   |  128  |
|  TLS_RSA_WITH_RC4_128_SHA (0x5)   INSECURE                   |  128  |
|  TLS_RSA_WITH_RC4_128_MD5 (0x4)   INSECURE  Using api (output attached): curl https://api.ssllabs.com/api/v2/analyze?host=abaretirement.com&all=on or using getEndpointData.   I don’t know if weak cipher suites are indicated in the output, but I was expecting in the cipher object for these 3 to find a field (q=1) to indicate these were insecure.  |  |

 

    On Thursday, April 20, 2017 12:40 AM, Bhushan Lokhande <notifications@github.com> wrote:
 

 Please provide​ details/steps to reproduce.

SSL Labs marks RC4 as insecure.
https://www.ssllabs.com/ssltest/analyze.html?d=rc4.badssl.com&hideResults=on

**Comment by bhushan5640** [comment]
Fixed, deployed on dev server
https://api.dev.ssllabs.com/api/v2/analyze?host=abaretirement.com&all=on

API documentation for cipher suites: https://github.com/ssllabs/ssllabs-scan/blob/stable/ssllabs-api-docs.md#suite
