### ISSUE TITLE
Links to test.drownattack.com no longer valid

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#492]
In the SSL Labs report, the DROWN section includes links to test.drownattack.com, but this web site is no longer operational. The links should be removed.

**Comment by jtkoerting** [comment]
not even that ;) Please have a look at #495 as the the DROWN check is used and getting into the grade of the whole check is wrong.

**Comment by bhushan5640** [comment]
Fixed on https://dev.ssllabs.com
