### ISSUE TITLE
Inconsistent SSL scans

### ISSUE THREAD

**Issue by svmurali** [ssllabs/ssllabs-scan#493]
I have remediated my exchange server to have TLS 1.0 and TLS 1.1 disabled.

However scan comes up on Protocol check as 👍 
TLS .0 Yes  and TLS 1.1 No 

This does not make sense as both should be disabled. Not clear what 'Yes' means blocked or allowed?

Is this a known problem ?

Thanks

SV
Reference:
https://support.microsoft.com/en-us/help/187498/how-to-disable-pct-1.0,-ssl-2.0,-ssl-3.0,-or-tls-1.0-in-internet-information-services

**Comment by svmurali** [comment]
TLS 1.0 Yes and TLS 1.1 No

**Comment by strugee** [comment]
No one can really diagnose this without the server address.

**Comment by bhushan5640** [comment]
Could you share the hostname to reproduce this issue?
You can PM me here
https://community.qualys.com/people/blokhande or
https://twitter.com/BhushanLokhande

**Comment by svmurali** [comment]
Hi

Sorry man can’t

However after using Microsoft update toll scans came out clean and TLS 1.0 and TLS 1.1 was disabled

Thx and Regards

SV
