### ISSUE TITLE
Explain that simulations don't check trust

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#494]
There should be a note in the simulations section somewhere to explain that trust is not checked at all, that only TLS handshaking is taking place. As it is, user are sometimes confused when a simulation is positive in the case when it's known to fail (because of trust). For example: https://community.qualys.com/message/36981-handshake-simulation-not-showing-failure-for-letsencrypt-certs-java-78-clients

**Comment by bhushan5640** [comment]
Fixed.
