### ISSUE TITLE
https://api.ssllabs.com/api/v2/info is out of sync with documented api.

### ISSUE THREAD

**Issue by david-dick** [ssllabs/ssllabs-scan#497]
https://api.ssllabs.com/api/v2/info is documented to return a version attribute in https://github.com/ssllabs/ssllabs-scan/blob/stable/ssllabs-api-docs.md#info but it currently returns the following json structure

{
  "engineVersion": "1.28.5",
  "criteriaVersion": "2009o",
  "clientMaxAssessments": 25,
  "maxAssessments": 25,
  "currentAssessments": 0,
  "newAssessmentCoolOff": 1000,
  "messages": [
    "This assessment service is provided free of charge by Qualys SSL Labs, subject to our terms and conditions: https://www.ssllabs.com/about/terms.html"
  ]
}

it looks like engineVersion is being used instead of version.  Please bring the documentation into sync with the api call.

**Comment by bhushan5640** [comment]
Updated API v2 Info object
https://github.com/ssllabs/ssllabs-scan/blob/stable/ssllabs-api-docs.md#info

FYI, we are now adding all new features to API V3
https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md
