### ISSUE TITLE
Check CAA for www. if no CAA issuewild is set and no wildcard cert is in use for www.

### ISSUE THREAD

**Issue by TerraX-net** [ssllabs/ssllabs-scan#499]
(copied from an email)

Cloudflare wanted to get feedback regarding CAA: https://twitter.com/prdonahue/status/864260907576119296

Then I thought, Oh, stop, I think we missed something...and found this:
https://ma.ttias.be/caa-checking-becomes-mandatory-ssltls-certificates/
> ttias.be. CAA 0 issue "letsencrypt.org"
> this means that only Let's Encrypt can issue a certificate for the domain "ttias.be". **Note this doesn't cover the subdomains, like www.**

What is your understanding of this?
Letsencrypt doesn't issue wildcard certs, so it doesn't check "issuewild".
I think issuewild is only for wildcard certs and does not cover something like "You can issue certs for any subdomain".
**So Hardenize (and SSLLabs) should check for CAA records for www. if issuewild is not used for an in-use wildcard certificate.**

https://tools.ietf.org/html/rfc6844#page-6
> issue <Issuer Domain Name> [; <name>=<value> ]* :  The issue property
      entry authorizes the holder of the domain name <Issuer Domain
      Name> or a party acting under the explicit authority of the holder
      of that domain name **to issue certificates for the domain in which
      the property is published.**
> 
> issuewild <Issuer Domain Name> [; <name>=<value> ]* :  The issuewild
      property entry authorizes the holder of the domain name <Issuer
      Domain Name> or a party acting under the explicit authority of the
      holder of that domain name **to issue wildcard certificates** for the
      domain in which the property is published.

We have A/AAAA records for www., and there is no issuewild plus no wildcard cert in use for www, so we know, that my SAN for www.terrax.net should fail?!
https://www.hardenize.com/report/terrax.net/1494880310#domain_caa

https://cabforum.org/2017/03/08/ballot-187-make-caa-checking-mandatory/
> As part of the issuance process, the CA must check for a CAA record for each dNSName in the subjectAltName extension of the certificate to be issued, according to the procedure in RFC 6844, following the processing instructions set down in RFC 6844 for any records found.

----

And please also check for the flag: 0 (non-critcal) and 128 (critical). 1 is a misunderstanding and should not be set. https://github.com/letsencrypt/boulder/issues/2245#issuecomment-270450182

**Comment by TerraX-net** [comment]
Or is this case handled by
>    o  If X is not a top-level domain, then R(X) = R(P(X)), otherwise
if www.example.com is not a TLD, then the relevant record for www.terrax.net is the relevant one of the parent zone, so example.com CAA may be enough?

**Comment by strugee** [comment]
Did you mean to close this?

**Comment by TerraX-net** [comment]
Yes. There are fallbacks, our current understandig is:
> dyndns.tld CAA 128 issue "comodoca.com" # all subdomains would be bound to Comodo
> home123.dyndns.tld CAA 128 issue "letsencrypt.org" # we make an exeption with this
> http-only.dyndns.tld CAA 128 issue ";" # forbid any CA. without this, Comodo would be allowed

**Comment by ArchangeGabriel** [comment]
So what happens if you ask a wild cert and only have a CAA issue record?

**Comment by ivanr** [comment]
@ArchangeGabriel you get a wildcard certificate. The "issue" directive has an implicit "issuewild" meaning, but only if "issuewild" is not explicitly in the configuration.
