### ISSUE TITLE
Missing output for sites that has errors

### ISSUE THREAD

**Issue by eitancaspi** [ssllabs/ssllabs-scan#503]
Hello,

I found that:

1.	If you use the "--quiet" option, the output simply omit any domains that has any kind of error, e.g. "Unable to connect to the server" or "No secure protocols supported" (I guess the same will happen for non-resolvable FQDN)

2.	If the scanned site has more than one IP address, the process probably refers only to the first IP, because I had a site with four IPs, when the first two had an error of "Err: Unable to connect to the server" and the last two had valid grade character – so eventually, as mentioned in the first issue above – the domain was omitted from the output when I used the "--quiet" option

So, I think that the following fixes are needed:

1.	Site with an error will not be omitted from the output, and instead get an output like "ErrorUnableToConnectToTheServer". This will help to get a matching response for any site name input

2.	Multiple IPs is, of course, a bigger issue, also because different IP can have different grades. A possible solution can be to break such site to multiple output records with a different IP for the same site on every line. On the other hand, it will be a different output format from the one-to-one sites (one FQDN = one IP). Maybe add the IP to the output as a default, built-in, value, to all kinds of sites.

Thanks!

Eitan

**Comment by strugee** [comment]
@eitancaspi just FYI, in the future, it's easier if you open separate issues for unrelated problems. This lets them be tracked/resolved/labeled/etc. separately.

Cheers!

**Comment by eitancaspi** [comment]
Got it, you are right. I was in the middle of the passion of debugging... :) it was hard to control myself!

**Comment by bhushan5640** [comment]
Fixed in ssllabs-scan-v3
https://github.com/ssllabs/ssllabs-scan/commit/cabfb5ebacaf03aa14a1df8427514dc6d327f2d4

**Comment by eitancaspi** [comment]
Thanks for the fix. When will this release be available? as .exe?
Thanks!

**Comment by bhushan5640** [comment]
For now, you can go build on windows for exe
`go build ssllabs-scan-v3.go`

**Comment by eitancaspi** [comment]
Cool, thanks!
