### ISSUE TITLE
v3 API 500 (Internal Server Error)

### ISSUE THREAD

**Issue by anand-bhat** [ssllabs/ssllabs-scan#506]
Analyzing `vpn.danica.no` via the v3 API results in an internal server error (status code 500). I have seen this error only for this domain.

Via ssl labs client:
`2017/05/27 15:42:35 [ERROR] Unexpected response status code 500`

The client terminates at this point.

[API URL](https://api.ssllabs.com/api/v3/analyze?host=vpn.danica.no&all=done&fromCache=on&maxAge=24) via browser:
![image](https://cloud.githubusercontent.com/assets/7332442/26520706/6dacb5d2-42f5-11e7-9a27-c9dea1927fa9.png)

The v2 API URL and the UI scan work fine.
![image](https://cloud.githubusercontent.com/assets/7332442/26520729/bea30342-42f5-11e7-82f6-647f7b3647a0.png)

![image](https://cloud.githubusercontent.com/assets/7332442/26520726/b020fb62-42f5-11e7-916c-8242f11d7b37.png)

**Comment by bhushan5640** [comment]
Fixed.
https://api.dev.ssllabs.com/api/v2/analyze?host=vpn.danica.no&all=on
