### ISSUE TITLE
Error handling within 'normal' API response

### ISSUE THREAD

**Issue by seccubus** [ssllabs/ssllabs-scan#51]
As an API user I would like to get a "regular" API error reply back in stead of a special error reply for 400 situations.

E.g. testing oops.bla results in:
          'oops.bla' => {
                          'cacheExpiryTime' => '1423124841890',
                          'protocol' => 'HTTP',
                          'status' => 'ERROR',
                          'port' => 443,
                          'host' => 'oops.bla',
                          'statusMessage' => 'Unable to resolve domain name',
                          'startTime' => '1423124781882',
                          'testTime' => '1423124781890',
                          'engineVersion' => '1.13.3',
                          'isPublic' => bless( do{\(my $o = 0)}, 'JSON::PP::Boolean' ),
                          'criteriaVersion' => '2009i'
                        }

But testing 192.168.10.2 results in:
          'errors' => [
                        {
                          'message' => 'IP addresses are not allowed',
                          'field' => 'host'
                        }
                      ]

In my code I now have to translate the errors object into:

  "192.168.10.2" => {
                          'status' => 'ERROR',
                          'statusMessage' => 'IP addresses are not allowed',
  }

In order for my reporting loop to function normally again.

**Comment by ivanr** [comment]
I agree. Will fix.

**Comment by seccubus** [comment]
Any indication on timeframes? Reason for asking is the release of Seccubus with SSL labs api support.

**Comment by ivanr** [comment]
From what I can see this was fixed a long time ago. It was later broken (see #211), but in 1.20.x it will be fixed again. The output in response to a blacklisted hostname is now this:

{"host":"example.com","port":443,"protocol":"HTTP","status":"ERROR",
  "statusMessage":"Hostname blacklisted","engineVersion":"1.20.10",
  "criteriaVersion":"2009k"}
