### ISSUE TITLE
[SSL Pulse] wrong reference in index.json

### ISSUE THREAD

**Issue by kjur** [ssllabs/ssllabs-scan#511]
It seems a json data reference is missing in Jul 2016 in index.json.

https://www.ssllabs.com/assets/project/ssl-pulse/data/index.json

```
               ... snip ...
                { "timestamp": 1467812372, "path": "pulse-2016-07-02.json" },
                { "timestamp": 1462404394, "path": "pulse-2016-05.json" },
               ... snip ...
```

Could you fix it?

**Comment by bhushan5640** [comment]
Hi Kenji,

We have not published Jul 2016 results because of some inaccuracy.

Regards,
Bhushan

**Comment by kjur** [comment]
Thank you for your reply. I got it.
