### ISSUE TITLE
JSON unmarshal error (main.LabsSuites) with API v3

### ISSUE THREAD

**Issue by raulsiles** [ssllabs/ssllabs-scan#518]
The current stable version of ssllabs-scan for Linux (v1.4.0) generates the following "JSON unmarshal error" when API version 3 is used:

[ERROR] JSON unmarshal error: json: cannot unmarshal array into Go value of type main.LabsSuites

Tool version:
```$ ssllabs-scan -version
ssllabs-scan v1.4.0 (stable $Id: 84740581ac9cc25312f1db3f80b94bb6a765d888 $)
```

Executed command:
```
./ssllabs-scan --ignore-mismatch --verbosity debug --api https://api.ssllabs.com/api/v3/ --hostfile file.csv > file.v3.out 2>&1
```

Output:
```2017/07/24 11:35:23 [DEBUG] Server set current assessments to 0
2017/07/24 11:35:23 [DEBUG] Server set maximum assessments to 23
2017/07/24 11:35:23 [DEBUG] Request #13: https://api.ssllabs.com/api/v3//analyze?host=XXX.com&all=done&ignoreMismatch=on
2017/07/24 11:35:24 [ERROR] JSON unmarshal error: json: cannot unmarshal array into Go value of type main.LabsSuites
2017/07/24 11:35:24 [DEBUG] Response #13 status: HTTP/1.1 200 OK
2017/07/24 11:35:24 [ERROR] JSON unmarshal error: json: cannot unmarshal array into Go value of type main.LabsSuites
[
{
  "host": ...
```

If you need to know the hostname used for the test, do not hesitate to contact me privately.

**Comment by ivanr** [comment]
It's admittedly been some time since I've used ssllabs-scan, but IIRC the stable version can only with with API v2. To use API v3, use the main branch. (Which, AFAIK, is also stable, it's just that API v3 hasn't been declared stable.)

**Comment by bhushan5640** [comment]
Yes for API V3 you have to use ssllabs-scan-v3 from the master branch. We will release binary soon for V3.

**Comment by raulsiles** [comment]
Confirmed: ssllabs-scan-v3 from the master branch works with API v3 as expected, with no errors. Thanks!!
