### ISSUE TITLE
SSL Labs shouldn't consider a SNI-only site vulnerable to POODLE

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#519]
SNI relies on extensions and thus can't be used with SSL 3, which doesn't support them. Thus, a SNI-only site can't be vulnerable to the POODLE attack.

Reported here: https://blog.qualys.com/ssllabs/2014/10/15/ssl-3-is-dead-killed-by-the-poodle-attack#comment-146205

**Comment by bhushan5640** [comment]
Fixed. Deployed on dev.ssllabs.com

**Comment by wojsmol** [comment]
Hallo
Any ETA  for pushing this change to main site?
