### ISSUE TITLE
protocol-relative `//path` redirect misinterpreted, infinite loop

### ISSUE THREAD

**Issue by cben** [ssllabs/ssllabs-scan#521]
The site `https://mathdown.com` redirects to `Location: //www.mathdown.net/`.
This is known as a "[protocol-relative url](https://www.paulirish.com/2010/the-protocol-relative-url/)", and while now not recommended is perfectly legal, and should resolve to `https://www.mathdown.net/`.  (works in curl and browsers).
On SSL Labs, it seems the leading double slash is not recognized as starting a hostname, but as a relative path, which leads to infinite loop: 
https://www.ssllabs.com/ssltest/analyze.html?d=mathdown.com#httpRequests

> HTTP request to this server failed, see below for details.
>
> 1 https://mathdown.com/  (HTTP/1.1 301 Moved Permanently)
> 2 https://mathdown.com//www.mathdown.net/  (HTTP/1.1 301 Moved Permanently)
> 3 https://mathdown.com//www.mathdown.net/www.mathdown.net/  (HTTP/1.1 301 Moved Permanently)
> 4 https://mathdown.com//www.mathdown.net/www.mathdown.net/www.mathdown.net/  (HTTP/1.1 301 Moved Permanently)
> ...

Well, at least it limits this loop to 6 requests aed faius...

(cf. non-redirecting https://www.ssllabs.com/ssltest/analyze.html?d=www.mathdown.net)

**Comment by ivanr** [comment]
AFAIK, this became legal only recently, in the most recent HTTP standard revision: https://tools.ietf.org/html/rfc7231#section-7.1.2 Prior to that it was illegal but widely accepted.

**Comment by bhushan5640** [comment]
Fixed. Deployed on dev
https://dev.ssllabs.com/ssltest/analyze.html?d=mathdown.com
