### ISSUE TITLE
Enhancement: Cap to B and give 0 at Key Exchange when no FS offered

### ISSUE THREAD

**Issue by luis140219** [ssllabs/ssllabs-scan#523]
I've tested svn.osgeo.org and found only two cipher suites were supported:

TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)  128 
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)  256 

Note all cipher suites use RSA as a key exchange method, that makes the suites using it not providing forward secrecy.

My proposed enhancement to SSL Labs is to do the following to servers not supporting FS suites:

- Cap the grade to B (or maybe C).
- Reduce the Key Exchange score to 0.

**Comment by bhushan5640** [comment]
Test on https://dev.ssllabs.com
