### ISSUE TITLE
Penalize or warn when server prefers AES-128 over AES-256

### ISSUE THREAD

**Issue by Razerwire** [ssllabs/ssllabs-scan#525]
The Dutch National Cyber Security Center (NCSC) released guidelines regarding crypto in a post-quantum cryptography world:
https://www.ncsc.nl/binaries/content/documents/ncsc-nl/actueel/factsheets/factsheet-postkwantumcryptografie/1/Factsheet%2BPostkwantumcryptografie.pdf

The factsheet is in Dutch but is based on recommendations written in English which I'll get to in a moment.

They advise the use or preference of AES-256 above AES-128 bit  ciphers, the gist of it being that the use of quantum-computers might seem a distant future but it's not, (encrypted traffic could be captured and stored for decryption using quantum-computers at a later time) and AES-256 is much much more resistant to decryption by quantum-computers.  

This advice is based on the:  "Initial recommendations of long-term secure post-quantum systems" written by "PQCRYPTO" a research project funded by the EU.

The recommendations can be found here:
https://pqcrypto.eu.org/press.html
https://pqcrypto.eu.org/docs/initial-recommendations.pdf

On page. 7 par. 3 of the document the use of AES-256 above AES-128 is recommended:
Symmetric systems are usually not affected by Shor’s algorithm, but they are affected by Grover’s algorithm. Under Grover’s attack, the best security a key of length n can offer is
2n/2, so AES-128 offers only 264 post-quantum security. PQCRYPTO recommends thoroughly analyzed ciphers with 256-bit keys to achieve 2128post-quantum security:
•AES-256 [8].
•Salsa20 [3] with a 256-bit key.

**My suggestion is for ssllabs-scan to penalize when AES-128 is preferred over AES-256, since AES-256 usage makes you quantum resistant for longer.** 

(Source: https://bugzilla.mozilla.org/show_bug.cgi?id=1357467 )

**Comment by ivanr** [comment]
I am not convinced that it's worth talking about this. If you're worried about someone using a quantum computer to attack your web site, then perhaps you shouldn't be putting your precious information on the Internet. My point being is that people who have assets worth attacking this way would be investing much more to keep them safe. TLS won't protect them!

**Comment by Razerwire** [comment]
@ivanr 

I don't think the scenario that the Dutch NCSC outlines, that TLS-traffic could be captured in bulk by (perhaps) state actors only to be decrypted using quantum when QC are available and less expensive, is BS. 

We all know by now that state actors (read: the NSA) have been doing bulk-interception for some time and have been breaking TLS (TLS/VPN) traffic on a massive scale (probably by leveraging weak-DH).
So this scenario isn't really far-fetched IMO.

I'm not talking about "putting your precious information on the Internet" that is a gross oversimplification of the problem at hand. 

I'm talking about a scenario where perhaps a web-form or web-application is used to relay sensitive information like,  for instance, personal medical data. Lot's of healthcare providers now use web-applications that are accessible over the internet e.g. via a website / web-app. 

In my understanding bulk interception is not about targeted attacks but about intercepting data in bulk and then looking if there's anything interesting in that bulk-data. 
So you might not be a real target, yet still can become a victim of bulk-interception and - at a later date - quantum decryption.

I don't think being paranoid and thinking ahead is not worth talking about, especially when switching preference to AES-256 is not that big of a deal, while providing more resistance to upcoming threats. 

If i had proposed to penalize 1024-bit DH keys four years ago you might have reacted the same yet that threat is more real then ever.
