### ISSUE TITLE
User Agent Capabilities - Googlebot update

### ISSUE THREAD

**Issue by zzq1015** [ssllabs/ssllabs-scan#526]
Googlebot has changed its SSL/TLS configuration a lot since February 2015. For example, Google has added support for chacha20, RSA-PSS, X25519, as well as dropping RC4, plain DH and many virtually unused ECDH curves. 
So, here is the detail:
Protocols supported: `SSLv3, TLSv1, TLSv1.1, TLSv1.2`
Cipher suites: 
```
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (0xc02b)
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca9)
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (0xcca8)
TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (0xc02c)
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)
TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA (0xc009)
TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)
TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA (0xc00a)
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)
TLS_RSA_WITH_AES_128_GCM_SHA256 (0x9c)
TLS_RSA_WITH_AES_256_GCM_SHA384 (0x9d)
TLS_RSA_WITH_AES_128_CBC_SHA (0x2f)
TLS_RSA_WITH_AES_256_CBC_SHA (0x35)
TLS_RSA_WITH_3DES_EDE_CBC_SHA (0xa)
```
Server Name Indication (SNI): `Yes`
Secure Renegotiation: `Yes`
TLS compression: `No`
Session tickets: `Yes`
OCSP stapling: `Yes`
Signature algorithms: `SHA256/ECDSA, RSA_PSS_SHA256, SHA256/RSA, SHA384/ECDSA, RSA_PSS_SHA384, SHA384/RSA, RSA_PSS_SHA512, SHA512/RSA, SHA1/RSA`
Named Groups: `x25519, secp256r1, secp384r1`
Next Protocol Negotiation: `Yes`
Application Layer Protocol Negotiation: `No`
SSL 2 handshake compatibility: `No`

**Comment by danger89** [comment]
Yea I think SSLLabs is currently not representing Googlebot correctly.

It now gives `Server sent fatal alert: handshake_failure`. I don't believe that with my setup, I think Googlebot can access my server very well, so this information is outdated.

**Comment by bhushan5640** [comment]
Googlebot is now updated https://www.ssllabs.com/ssltest/viewClient.html?name=Googlebot&version=Feb%202018&key=145
