### ISSUE TITLE
Incorrect HSTS configuration on plaintext.ssllabs.com breaks Client Test in Firefox 57+

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#527]
Alex Gaynor reported that the client test is showing incorrect mixed content results with Firefox 57:
    https://bugzilla.mozilla.org/show_bug.cgi?id=1387432

The root cause appears the combination of HSTS priming and the fact that we're returning HSTS on plaintext.ssllabs.com. This should be fixed as a matter of urgency, before too many FF 57 deployments.

**Comment by bhushan5640** [comment]
Fix deployed on dev.ssllabs.com
