### ISSUE TITLE
Production: Assessment failed: Unexpected failure [RenegotiationTest]: Connection failed

### ISSUE THREAD

**Issue by Jummartinezro** [ssllabs/ssllabs-scan#528]
https://www.ssllabs.com/ssltest/analyze.html?d=grj-sd-ppr-connectedliving-home.stg.as8677.net

I keep getting failures on my grj-sd-ppr-connectedliving-home.stg.as8677.net I cannot figure out the issue.

**Comment by naumanshah03** [comment]
Tested the site with the following [Nmap script]( https://nmap.org/nsedoc/scripts/ssl-enum-ciphers.html ) and observed the results and packets sent/received.

It seems that the server is giving an inconsistent result. You can use other tools to verify the change in result. It is some kind of server responding issue.

**Comment by Jummartinezro** [comment]
Thank you for your assistance @naumanshah03, problem was due to a different configuration on our replicated server
