### ISSUE TITLE
Please use alternative for bitmasks

### ISSUE THREAD

**Issue by seccubus** [ssllabs/ssllabs-scan#53]
Bitmasks are clumsy to handle in higher order languages.

The are used for e.g. certificate issues and revocation information. For my use case a simple text field or array would suffice.

**Comment by ivanr** [comment]
Yes, but they're great when you need to store large amounts of information into a relational database and keep the table at a reasonable size. Either way, it's too late to change the API now.

**Comment by seccubus** [comment]
It ties into the effort required from the API user to get usefull information from the data obtained via the API.

Worked on the API integration for seccubus.  120 lines to interact with the API, start scans and get the data.
190 lines of code to turn the data into information that can be processed for presentation for the end user.

Understand the difficulty of changing it now, happy to help defining 2.0
