### ISSUE TITLE
SSL Labs doesn't check for CAA in parent hostnames

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#532]
SSL Labs doesn't check for CAA in parent hostnames, at least not 100% correctly. As reported here: https://community.qualys.com/message/38213-ssl-server-test-caa-on-a-subdomain

**Comment by bhushan5640** [comment]
SSL Labs does check for CAA in parent hostnames. Maybe it took some time to reflect those CAA records.
DNS CAA is now detected on the hostname which was reported.
