### ISSUE TITLE
Suggestion: F- for www.iammoving.com

### ISSUE THREAD

**Issue by rdebath** [ssllabs/ssllabs-scan#534]
The site `www.iammoving.com` has four listed Grade F caps (and several other caps) I would suggest using an `F-` grade for sites like this that have multiple issues at this level.

I would have suggested adding a `-` for every extra cap, but `F---` looks silly, though `F***` might seem appropriate.

This could also be done at other grades, multiple `C` caps gets you a `C-`.

**Comment by bhushan5640** [comment]
SSL Labs grading version two preview:
https://community.qualys.com/docs/DOC-6321-ssl-labs-grading-2018
