### ISSUE TITLE
Clearer Api Results

### ISSUE THREAD

**Issue by AshleyPoole** [ssllabs/ssllabs-scan#54]
The API results are unclear in how vulnerabilities are shown. For example:
"heartbleed":false
"heartbeat":true
"openSslCcs":1
"poodleTls":1

Having a simply true/false with true being vulnerable would make things easier for consumers.

**Comment by ivanr** [comment]
Boolean fields are used when possible, but we can't use them when a field can have more than two  values - have a look at the documentation.

**Comment by AshleyPoole** [comment]
@ivanr Would it be possible to expand GetStatusCodes to include these numeric values a long with a English text value explaining the meaning? This would then allow a consumer to get an analysis result, then query to for the meanings? This also gives you the benefit of being able to add new entries and control the description to keep it consistent with the WUI scanner.
