### ISSUE TITLE
Two reference clients reporting "Server closed connection" for hackerone.com

### ISSUE THREAD

**Issue by reedloden** [ssllabs/ssllabs-scan#546]
SSL Labs is reporting `Server closed connection` for two different reference user agents (`Chrome 57 / Win 7` and `Firefox 53 / Win 7`) when testing `hackerone.com`.

Tested via both:
* https://www.ssllabs.com/ssltest/analyze.html?d=hackerone.com&s=104.16.99.52&hideResults=on&latest
* https://dev.ssllabs.com/ssltest/analyze.html?d=hackerone.com&s=104.16.99.52&hideResults=on&latest

I've tested both user agents via BrowserStack, and I can access https://hackerone.com fine on both.

Thoughts? Is this a SSL Labs bug or is something else going on that I'm not seeing?

**Comment by bhushan5640** [comment]
We have simulations for Chrome 57 and Firefox 53 with TLS 1.3 (draft 18) enabled.
https://www.ssllabs.com/ssltest/viewClient.html?name=Chrome&version=57&platform=Win%207&key=141
https://www.ssllabs.com/ssltest/viewClient.html?name=Firefox&version=53&platform=Win%207&key=142

hackerone.com is not doing fallback to TLS1.2 in this case

Chrome with with TLS1.3 (draft 18) enabled
![image](https://user-images.githubusercontent.com/6083185/33255346-22f8d4b2-d373-11e7-993e-2b3e936e74a8.png)

**Comment by reedloden** [comment]
@bhushan5640 I reached out to Cloudflare, who handles TLS termination for us, and this is what they said:

> That error suggests that SSL Labs' test environment currently uses a TLS intercept proxy in front of their Chrome/Firefox test clients (that makes sense, as it's probably easier for them to aggregate instrumentation data centrally rather than collecting it from each individual test client), and that the proxy isn't able to handle TLS 1.3's backwards compatibility properly. Please see comments from the Chrome TLS 1.3 team at https://superuser.com/questions/1217257/this-site-can-t-be-reached-mail-google-com-is-currently-unreachable and https://bugs.chromium.org/p/chromium/issues/detail?id=733223
> 
> Can you check with SSL Labs to see if they're aware of any such intercept proxy used in their scans? Are they able to provide any data that would indicate there's instead any issue with our TLS 1.3 stack? I'll check with our TLS engineers also, but so far we haven't had any general reports that error code from either Firefox or Chrome clients with TLS 1.3 enabled.
