### ISSUE TITLE
Update TLS 1.3 server test to draft 23

### ISSUE THREAD

**Issue by bhushan5640** [ssllabs/ssllabs-scan#547]
SSL Labs currently supports TLS 1.3 draft 18 in server test. Update to draft 22.
Firefox Nightly switched to draft 22.

Test server: https://tls13.crypto.mozilla.org/

All on draft 23 now update to draft 23

Update: update to the final draft 28

**Comment by hotaru2k3** [comment]
chrome dev channel is also supporting draft 22 now.

**Comment by stefanb** [comment]
Now
* Chrome canary
* OpenSSL 
* https://tls13.crypto.mozilla.org/

all supports TLS 1.3 *draft 23*.

You can enable it in Chrome Canary by entering chrome://flags/#tls13-variant into the url bar then enable it.

OpenSSL will deliver it in the next release ("OpenSSL 1.1.1 will not be released until (at least) TLSv1.3 is finalised") and has draft 23 already merged into the master branch now. 
More about that: https://www.openssl.org/blog/blog/2018/02/08/tlsv1.3/

**Comment by hotaru2k3** [comment]
chrome dev channel and firefox developer also support draft 23 now.

**Comment by shoujii** [comment]
Will draft 23 included soon? :O

**Comment by vinsonzou** [comment]
Now Chrome stable 65 is support TLS 1.3 draft 23.

**Comment by iz8mbw** [comment]
Yes, it's time to switch from draft 18 to draft 23.
Openssl-1.1.1-pre supports draft 23, Chrome supports draft 23.

**Comment by bhushan5640** [comment]
https://dev.ssllabs.com/ now supports draft 23

**Comment by HLeithner** [comment]
It seams it is only supported for RSA certificates is this correct or a bug?
ECDSA only Server isn't recognized.

**Comment by cascent** [comment]
Works for me on a server with only an ECDSA cert
![image](https://user-images.githubusercontent.com/29909333/37865438-d343ec4a-2f52-11e8-8b20-4fe4a7b65896.png)

**Comment by HLeithner** [comment]
Interesting, with haproxy 1.8.4 + openssl 1.1.1-pre2 it only works if the LE RSA certificate is available (dual stack or single stack).

do you think its a haproxy/openssl bug or ssllabs?

**Comment by cascent** [comment]
I'm using nginx 1.13.9 and OpenSSL 1.1.1-pre2.
Chrome, Firefox, and curl all connect over TLS 1.3

You may want to test with https://github.com/drwetter/testssl.sh (will need openssl command line client with TLS 1.3 support)

**Comment by HLeithner** [comment]
I don't want to hijack this this ticket... is there a better place to discuss this? 

testssl.ssh says it get an "unexpected result"
https://privatebin.at/?7c652b936428bac1#0zlOAgqPRUtCwXyjGbr3fPAvY/YZz482m5qDmioSz1c=

**Comment by drwetter** [comment]
> I don't want to hijack this this ticket... is there a better place to discuss this?

https://github.com/drwetter/testssl.sh/issues . Your case seems anyway interested to look into. Other than @cascent said it works without an openssl version with TLS 1.3 support.

(Sorry @bhushan5640 , hope my hint is ok with you)

**Comment by iz8mbw** [comment]
Now OpenSSL 1.1.1 pre3 is at TLSv1.3 draft 26.

**Comment by shoujii** [comment]
Is there any plan to move to Draft 28 (which should be the final one)?

**Comment by Graymanflo** [comment]
Hey there! 

I have a slight issue; my Nginx server compiled with OpenSSL 1.1.1pre4 is showing `TLSv1.3 - No` on your dev.ssllabs.com while `openssl s_client -connect 127.0.0.1:443` shows TLSv1.3 as the prefered protocol:

> Protocol  : TLSv1.3
> Cipher    : TLS_AES_256_GCM_SHA384

Is there anything wrong with my webserver or is it due to ssllabs not being on the same openssl version as mine? Thanks.

**Comment by shoujii** [comment]
dev.ssllabs.com = TLS 1.3 Draft 23
OpenSSL 1.1.1pre4 = TLS 1.3 Draft 28 (or smth like this)
= dev.ssllabs.com is not able to detect TLS 1.3 from OpenSSL 1.1.1pre4

**Comment by McKinleyGroup** [comment]
Hi @shoujii 
Hi @Graymanflo 
Hi @drwetter 
Hi @bhushan5640 bhushan5640

# git clone https://github.com/openssl/openssl

shows this:
---
Cloning into 'openssl'...
remote: Counting objects: 298544, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 298544 (delta 6), reused 8 (delta 5), pack-reused 298531
Receiving objects: 100% (298544/298544), 143.28 MiB | 28.91 MiB/s, done.
Resolving deltas: 100% (209470/209470), done.
[root@ip-16-0-0-97 openssl]# git branch -a
  master
* tls1.3-draft-18
  remotes/origin/HEAD -> origin/master
  remotes/origin/OpenSSL-engine-0_9_6-stable
  remotes/origin/OpenSSL-fips-0_9_7-stable
  remotes/origin/OpenSSL-fips-0_9_8-stable
  remotes/origin/OpenSSL-fips-1_2-stable
  remotes/origin/OpenSSL-fips-2_0-dev
  remotes/origin/OpenSSL-fips-2_0-stable
  remotes/origin/OpenSSL-fips2-0_9_7-stable
  remotes/origin/OpenSSL_0_9_6-stable
  remotes/origin/OpenSSL_0_9_7-stable
  remotes/origin/OpenSSL_0_9_8-stable
  remotes/origin/OpenSSL_0_9_8fg-stable
  remotes/origin/OpenSSL_1_0_0-stable
  remotes/origin/OpenSSL_1_0_1-stable
  remotes/origin/OpenSSL_1_0_2-stable
  remotes/origin/OpenSSL_1_1_0-stable
  remotes/origin/SSLeay
  remotes/origin/master
  remotes/origin/tls1.3-draft-18
  remotes/origin/tls1.3-draft-19
----

So, how do I get draft 26?

www.coldawn.com and blog.sandchaschte.ch  already seem to support draft 26...

However, I have no idea how to get it... the question is probably too easy? :-) :-)
Nonetheless, a short but concise answer would be cool!

Many thanks in advance... :-)

**Comment by ArchangeGabriel** [comment]
Just use the master branch (or a pre-release tag).

**Comment by tjikkun** [comment]
Since Firefox 61 released today has support for TLS 1.3 draft 28, any chance ssltest will be updated as well?

**Comment by DXGLdotinfo** [comment]
Since OpenSSL now (to the best of my knowledge) uses RFC8446 as of Beta 7, perhaps it is time to prioritize the update of sslscan to RFC?

**Comment by naumanshah03** [comment]
dev.ssllabs.com now supports TLS 1.3 RFC 8446

https://github.com/ssllabs/ssllabs-scan/issues/641#issuecomment-423982814

**Comment by DXGLdotinfo** [comment]
Since TLS 1.3 is now supported on the production server, this issue can be closed.

**Comment by McKinleyGroup** [comment]
Hi @DXGLdotinfo 

> dev.ssllabs.com now supports TLS 1.3 RFC 8446

Well, not so fast... do you have TLS 1.3 RFC 8446 running? I do, but I had to compile it myself...
TLS 1.3 now works in browsers only with the final spec, RFC8446, and only with the latest OpenSSL 1.1.1 (LTS) sources!!!

So, for most people TLS 1.3 as an issue is just getting started...
... I cross-compiled gcc 2.x twenty years ago on a SPARC (SPARC-to-Motorola cross compilation) but somehow I guess that is the exception not the rule... :-)

Most people will need some help, e.g. a distro and some guidance how to upgrade...

So far we have TLS 1.3 on all our servers.... however, the only other servers supporting TLS 1.3 are IETF.org and ssllabs.com right now .... it is the very exception I would say... :-)

**Comment by ArchangeGabriel** [comment]
@McKinleyGroup You’re definitively wrong, OpenSSL 1.1.1 is already packaged in a lot of distros, and the dev SSL Pulse (https://dev.ssllabs.com/ssl-pulse/) already shows 9% usage.

**Comment by McKinleyGroup** [comment]
Hi @ArchangeGabriel 

You rock!!!

> You’re definitively wrong, OpenSSL 1.1.1 is already packaged in a lot of distros, and the dev SSL Pulse (https://dev.ssllabs.com/ssl-pulse/) already shows 9% usage.

Wow, thank you so much! :-) :-) 
I am always eager to learn something new!!!

Is there a list of distros with TLS 1.3 support?

Thank you so much in advance for a short answer!

**Comment by DXGLdotinfo** [comment]
OpenSSL 1.1.1 is in Ondřej Surý's Apache 2.x PPA:
https://launchpad.net/~ondrej/+archive/ubuntu/apache2
This is where I downloaded OpenSSL 1.1.1 on my current setup; for nginx it just works as 1.1.1 is ABI-compatible with 1.1.0.

**Comment by DXGLdotinfo** [comment]
@McKinleyGroup If you want to use it with Nginx his Nginx Mainline PPA is now distributing OpenSSL 1.1.1:
https://launchpad.net/~ondrej/+archive/ubuntu/nginx-mainline

**Comment by McKinleyGroup** [comment]
@DXGLdotinfo 

Wow, that's very kind! :-)

> Nginx his Nginx Mainline PPA is now distributing OpenSSL 1.1.1:
> https://launchpad.net/~ondrej/+archive/ubuntu/nginx-mainline

Thank you so much! :-)

**Comment by DXGLdotinfo** [comment]
Thomas Ward started distributing Nginx Mainline again, but it might still be dependent on OpenSSL 1.0.2 instead of 1.1.x, so ever since finding Surý's PPAs (as well as his PHP PPA) I have stuck with his.

On Cosmic, installing OpenSSL 1.1.1 from his PPA even makes my Dovecot and Postfix servers support TLS 1.3.
