### ISSUE TITLE
Wrong valid from evaluation on dev

### ISSUE THREAD

**Issue by malviny** [ssllabs/ssllabs-scan#548]
On dev (ver. 1.30.3) does not work evaluation of "Valid from" certificate attribute well:
Valid from 	Mon, 04 Dec 2017 00:00:00 UTC   NOT YET VALID
Consequently:
Trusted 	No   NOT TRUSTED (Why?)
Mozilla  Apple  Android  Java  Windows  

On production system (ver. 1.29.7) is it ok:
Valid from 	Mon, 04 Dec 2017 00:00:00 UTC
...
Trusted 	Yes

**Comment by bhushan5640** [comment]
Fixed dev server time is in sync now. Thanks for reporting.
