### ISSUE TITLE
Client should let the server track how many ongoing assessments there are

### ISSUE THREAD

**Issue by ivanr** [ssllabs/ssllabs-scan#55]
At the moment, the client keeps track of how many concurrent assessments there are. This will match the value when there is only one client per IP address, or if there is only one client in a throttling group. It's more efficient to let the server track how many ongoing assessments there are. The client can calculate this by subtracting the value in X-Current-Assessments from X-Max-Assessments.

**Comment by seccubus** [comment]
This will require some way to identifying clients. Or it will hurn multiple clients behind a single IP (proxy/NAT)

**Comment by ivanr** [comment]
Fixed in master.
