### ISSUE TITLE
Drop HPKP support

### ISSUE THREAD

**Issue by HLFH** [ssllabs/ssllabs-scan#550]
Hi,

[Chrome is planning to drop support of HPKP](https://groups.google.com/a/chromium.org/forum/#!msg/blink-dev/he9tr7p3rZ8/eNMwKPmUBAAJ?hn).
Can you also drop the support?

Thanks,

**Comment by bhushan5640** [comment]
HPKP green summary headline removed. HPKP no longer awarded by SSL Labs.
Fix deployed on https://dev.sslabs.com

**Comment by HLFH** [comment]
Thank you so much!

**Comment by 4oo4** [comment]
Thanks for this. Can you provide a rough ETA when we can expect this on the main site?
