### ISSUE TITLE
issues representation 

### ISSUE THREAD

**Issue by parimalazoho** [ssllabs/ssllabs-scan#553]
The code 65 (meaning that bit 0 and bit 6 are set) How?????

**Comment by bhushan5640** [comment]
If you are talking about this field
**issues** - list of certificate issues, one bit per issue:
bit 0 (1) - no chain of trust
bit 1 (2) - not before
bit 2 (4) - not after
bit 3 (8) - hostname mismatch
bit 4 (16) - revoked
bit 5 (32) - bad common name
bit 6 (64) - self-signed
bit 7 (128) - blacklisted
bit 8 (256) - insecure signature

65 (dec) : 1000001 (binary)
means Cert is self-signed (bit 6) and not trusted (bit 0)
