### ISSUE TITLE
Assessment failed: Unable to connect to the server

### ISSUE THREAD

**Issue by GilbertH1** [ssllabs/ssllabs-scan#555]
SSL Report: cloudtrack.dichter-neira.com (190.102.61.108)
Assessed on:  Tue, 02 Jan 2018 17:35:54 UTC | 
Assessment failed: Unable to connect to the server

Hello, this website is up and running.  IT people change the firewall on new years eve, and now I got this message when try to test it. 
![capture](https://user-images.githubusercontent.com/35039888/34493575-8f55bf18-efba-11e7-9847-50b15e41bc8a.JPG)

![capture2](https://user-images.githubusercontent.com/35039888/34493611-b98ce266-efba-11e7-9e81-d9745d911f87.JPG)

**Comment by bhushan5640** [comment]
Unable to connect to server - it usually happens due to firewall restrictions.

Please check if any firewall restrictions causing the issue. SSL Labs IPs listed in this section needs to be whitelisted: https://community.qualys.com/docs/DOC-4865
