### ISSUE TITLE
domain saipm.com : Unable to connect to some server 

### ISSUE THREAD

**Issue by whyjack666** [ssllabs/ssllabs-scan#557]
Hello,

I am using ssllabs.com to follow my score when I renew certificates to be sure I haven't to review my SSL configuration on my servers.

Today, I tried to assess 'sslcheck.saipm.com' and 'dtl.saipm.com' with no success, when I successfully got my score with 's.ipmstore.be' (every domains hosted on the same machine but with different ip's).

The problem is the following : 'Assessment failed: Unable to connect to the server' @ SSL 3.0 test.
I have no indication on the reason of the failure and I see your traffic coming from 64.41.200.107 with a tcpdump when I assess my score for 's.ipmstore.be'.

Can you check on your side why my domain is rejected for those two specific hostnames ?

Thanks for your help !

**Comment by bhushan5640** [comment]
Looks like servers are down. Servers are not accessible form browsers as well.
http://downforeveryoneorjustme.com/s.ipmstore.be
http://downforeveryoneorjustme.com/sslcheck.saipm.com
