### ISSUE TITLE
DROWN reported when site using different wildcard certificate

### ISSUE THREAD

**Issue by rsawickisyki** [ssllabs/ssllabs-scan#558]
In case a company is using many websites, but has two different wildcard certificates one wildcard certificate is used by the new sites with SSL2/3 disabled and other wildcard certificate is for legacy sites where SSL2 is still enabled - in that scenario ssllabs-scan reports new sites as DROWN-vulnerable as if it wasn't checking that vulnerable sites with SSL2 enabled use different wildcard certificate. Is it possible to add certificate fingerprint check to the scan routine?

**Comment by bhushan5640** [comment]
The new site is vulnerable to Drown because the wildcard certificate on the SSLv2 enabled site is valid for the new domain and it can be used to attack your new site. Disable SSL v2 on that server.

Refere: https://blog.qualys.com/securitylabs/2016/03/04/ssl-labs-drown-test-implementation-details

**Comment by rsawickisyki** [comment]
Hi, On https://drownattack.com web I read: "A server is vulnerable to DROWN if:
1) It allows SSLv2 connections... or: 2) Its private key is used on any other server that allows SSLv2 connections, even for another protocol. Many companies reuse the same certificate and key on their web and email servers, for instance." In my previous post I forgot to mention that each wildcard certificate is using different pairs of keys, thus the new sites are not vulnerable as they use different private key as the sites that still have SSL2 enabled. I assume that if you can read public key from certificate, then you can figure out easily if each web sites is using vulnerable private key or not.

**Comment by bhushan5640** [comment]
The reuse of the server’s private keys and/or **certificate hostnames on other servers** with SSLv2 is vulnerable. For the second case even if you are not reusing the key pair you are still vulnerable. Because the certificate on the SSL v2 host can be used to attack your main host.

Above Qualys, blogs explain that. You can also check Drown paper for more details: https://drownattack.com/drown-attack-paper.pdf
