### ISSUE TITLE
dev (v1.30.6) / A+ rating

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#559]
If page have these warings:
- prewaring about Robot
- prewaring about AEAD
- contain static RSA (mark already as weak)
- maybe also if certificate distrust upcoming (prewarning)
it should not get A+ anymore  (max "A"), isn't it ?

**Comment by bhushan5640** [comment]
Hi Rob, All these pre-warnings are advance notice for the customers/users about **impending Grade changes**. 

So, we are not downgrading immediately (eg. A+ to A). The grade will downgrade to eg. B for no AEAD later.
