### ISSUE TITLE
Very Strange Results from Scanner

### ISSUE THREAD

**Issue by ryanrbftp** [ssllabs/ssllabs-scan#562]
We are having some very strange results reported for one of our sites.  We have tested another of our sites and this works fine.  The sites have exactly the same SSL config and we can't figure out why we are having issues.

This is the problem server with strange results:
https://www.ssllabs.com/ssltest/analyze.html?d=flyawaysimulation.com

This is an example of a working result:
https://www.ssllabs.com/ssltest/analyze.html?d=simshack.net

The main issue is the handshake simulation.  As you can see, we are getting lots of "Protocol or cipher suite mismatch".  Also, the cipher detection shows, "we could not determine if the server has a preference" - when the server DOES specify this.

Also, the test for the working result runs much faster than the test for the problem result.

The example of the working results above uses the exact same nginx server, with the exact same SSL/cipher config server albeit on a different IP address.

I can't figure this out - the configs for both sites are exactly the same.

Can anyone shed any light?

**Comment by bhushan5640** [comment]
Such issues will be addressed on SSL Labs community forum
https://community.qualys.com/community/ssllabs
