### ISSUE TITLE
Vulnerable by ssllabs but not from robot-detect/testssl script

### ISSUE THREAD

**Issue by chungangus** [ssllabs/ssllabs-scan#563]
Our company websites show vulnerable by the testing of ssllab.

We tried to investigate the cause and have the scanning using scripts from below sources but all show "NOT VULNERABLE"

https://github.com/robotattackorg/robot-detect
https://github.com/drwetter/testssl.sh/

Can ssllab check that?

**Comment by bhushan5640** [comment]
After investigating the provided sites, this bug is marked invalid.
