### ISSUE TITLE
Startcom certs shown as valid / Trusted

### ISSUE THREAD

**Issue by hannob** [ssllabs/ssllabs-scan#566]
See screenshot, this shows a Startcom-signed wildcard cert that is shown as Trusted by Mozilla, Apple, Android, Windows.
This is obviously not the case given the distrust of Startcom.
(Maybe you're blacklisting startcom and not checking for all known startcom roots?)

![startcom](https://user-images.githubusercontent.com/990588/36104768-2aee71a4-1013-11e8-998a-b7cc2945b1f0.png)

**Comment by bhushan5640** [comment]
Trust stores are updated
