### ISSUE TITLE
V2 API returns null startTime if a domain is blacklisted

### ISSUE THREAD

**Issue by liuzy163** [ssllabs/ssllabs-scan#567]
I recently noticed the Host startTime is null in the V2's analyze response when a domain is blacklisted.  Is this a new change? We have been using this value to make some automation logic and assuming it is not null and it has been working for a few years until very recent. 

Thanks.

**Comment by bhushan5640** [comment]
we stopped updating V2 API. Please use API v3
https://github.com/ssllabs/ssllabs-scan/tree/master
