### ISSUE TITLE
F grade (DROWN vulnerability) reported fort a site with no SSL* support

### ISSUE THREAD

**Issue by gstaniak** [ssllabs/ssllabs-scan#569]
Hi,

I tested the following site:  ui.benchmarkemail.com (174.35.10.221) using the https://www.ssllabs.com/ssltest/ page -- the server gets an F for DROWN vulnerability, even though the same page says it doesn't support any version of SSL. Am I missing the DROWN threat for TLS 1.*, or is this an error?

**Comment by RobTho** [comment]
see
Protocol Details 
38.126.54.3 443 Yes Yes Vulnerable (same hostname with SSL v2)

**Comment by gstaniak** [comment]
Thanks! Now I know what to look for. Much appreciated.
