### ISSUE TITLE
AEAD fails on Windows 2012 R2 (and earlier) when using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_P521

### ISSUE THREAD

**Issue by ctruxaw** [ssllabs/ssllabs-scan#571]
Hi,

Our server is running Windows 2012 R2 and we have specified several suites which I believe are AEAD (I may be wrong) like:
TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_P521
(it has to be AES at least 128-bit with GCM, not CBC, right?)

Windows 2012 R2 and earlier requires the elliptical curve suffix (e.g. _P521), and we can use TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384_P521 which shows up just fine in your report as TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384. So I don't think that's the problem. Yet oddly TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 does not appear on the report (even though it was added to SChannel as TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_P521).

I'm far from an TLS expert, so it's entirely possible I'm missing something obvious (e.g. AEAD isn't just about cipher suite selection, AEAD simply isn't supported by Windows Server 2012 R2, etc).

But the fact that TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 does not appear on our report makes me think that perhaps this is a bug?

Thanks for your help,
Chris

**Comment by bhushan5640** [comment]
Hi @ctruxaw,

Usually, you would get help for such configuration issues on SSL Labs community. Please post your question on the community forum. 
https://community.qualys.com/community/ssllabs

Yes, all GCM suites are AEAD. The suite you are trying to enable (TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_P521) is AEAD. You will get help on configuration issues on the community.

SSL Labs should be detecting ciphers correctly. If you still have doubt you can re-verify with other tools like testssl.sh etc

**Comment by ctruxaw** [comment]
Hi,

Sorry about that. You may want to update your website then because on page:
https://www.ssllabs.com/about/contact.html
Where your site states "Please report new issues/bugs here." (where here links to https://github.com/ssllabs/ssllabs-scan/issues)

I can open a post there too, but I do believe that the filter is being properly specified to Windows.

**Comment by ctruxaw** [comment]
For those looking for the answer to this question, the reason for the problem is described here:
https://serverfault.com/questions/895161/gcm-cipher-suites-are-enabled-but-not-discovered-by-ssl-labs-test

There is no bug. I'll mark this as closed.
