### ISSUE TITLE
"Certification Authority Authorization" (CAA) isn't recognized in scan results

### ISSUE THREAD

**Issue by dnno** [ssllabs/ssllabs-scan#573]
I've enabled Certification Authority Authorization (CAA) for some of my domains. For one of those domains (donneo.de) while the DNS resource record shows up correctly when querying a DNS server for the appropriate resource type ("dig donneo.de type257"), the SSL scan still reports back "No" when checking for CAA. It's been a while (~2 weeks) since I updated the DNS entry, so I think it DNS caching shouldn't be the issue here, especially, since other domains of mine work correctly (e.g. reinhard.codes).

**Comment by roycewilliams** [comment]
From a VPS with no previous exposure to your domain, cannot reproduce:
```
$ host -t caa donneo.de
donneo.de has no CAA record
$ dig +short -t TYPE257 donneo.de
$ 
```

**Comment by dnno** [comment]
This is strange. I got a  CAA Resource Record yesterday, but now I also don't see it anymore. Bumping this back to my domain hoster. Thanks for your feedback!
