### ISSUE TITLE
IE6 TLS support

### ISSUE THREAD

**Issue by tiaga** [ssllabs/ssllabs-scan#574]
Hello,

According to the information from [User Agent Capabilities](https://www.ssllabs.com/ssltest/clients.html) IE6 does not support TLS 1.0. However, **it does**! So, please correct this information.
As a proof you can check this article: https://warwick.ac.uk/services/its/servicessupport/web/sign-on/faqs/enable-tls/

**Comment by RobTho** [comment]
Hi 
the agent capabilities ahows always the default settings only

**Comment by bhushan5640** [comment]
Yes, all user agents are with default settings.
