### ISSUE TITLE
[SSL Pulse] Getting the results via JSON

### ISSUE THREAD

**Issue by fr0zenbits** [ssllabs/ssllabs-scan#578]
I noticed that on another issue, there is a [link ](https://www.ssllabs.com/assets/project/ssl-pulse/data/index.json) in which one lookup and eventually get the json for each SSL Pulse result. However, the site doesn't set the Access-Control-Allow-Origin header so I can't get the results via AJAX. Is this the official way to retrieve the results? If so, how can I get the results via AJAX?

**Comment by bhushan5640** [comment]
We don't support getting these results using CORS.
