### ISSUE TITLE
DNS record is not refresh after IP change

### ISSUE THREAD

**Issue by fab377** [ssllabs/ssllabs-scan#580]
Hello,

The webserver I'm trying to test IP address has changed. DNS have been updated, but the site still tests the old IP address.
Can you perhaps clezr the cached IP info for eos.davidson.fr

thx
BR,
Fabrice

**Comment by bhushan5640** [comment]
Check this https://developers.google.com/speed/public-dns/cache

SSL Labs uses Google DNS
