### ISSUE TITLE
Scan fails but website works in my browser

### ISSUE THREAD

**Issue by anupritaisno1** [ssllabs/ssllabs-scan#582]
I'm unable to scan review.aimrom.org however the website works just fine in my browser. Can you have a look?

**Comment by bhushan5640** [comment]
seems working now; should be some firewall restrictions
https://www.ssllabs.com/ssltest/analyze.html?d=review.aimrom.org&hideResults=on

**Comment by anupritaisno1** [comment]
I changed the configuration from HIGH:!AES:!aNULL:!MD5:!ARIA:!CAMELLIA:!CBC:!AES128 to HIGH:-AES:ECDHE-ECDSA-AES256-GCM-SHA384:!aNULL:!MD5:!ARIA:!CAMELLIA:!CBC:!AES128 and it worked

Why are sites with only chacha20 as a supported cipher not supported?

**Comment by bhushan5640** [comment]
please create a separate ticket for "sites with only chacha20 not supported by SSL Labs
