### ISSUE TITLE
Allow all ports to check

### ISSUE THREAD

**Issue by Somebodyisnobody** [ssllabs/ssllabs-scan#583]
Hello, I am running a webserver on port 444, tested TLS already with htbridge but still seeking a second opinion. Unfortunally i cannot scan the port 444. Is there a reason for that?

What's about to allow all ports?

**Comment by ArchangeGabriel** [comment]
See #441.

You can try [CryptCheck](https://tls.imirhil.fr/tls) in the meantime.

**Comment by Somebodyisnobody** [comment]
Ah ok, but like you said in https://github.com/ssllabs/ssllabs-scan/issues/270

> I think that allowing anyport is probably easier. ;) Since you might also want to be able to check on STARTTLS ports, so that’s 7 ports total for email purposes.

So i'll let this issue open. Just close it if you think that's more reasonable.

**Comment by bhushan5640** [comment]
We have a ticket for STARTTLS ports and non-standard HTTP ports
