### ISSUE TITLE
Ciphersuite list not provided per TLS version

### ISSUE THREAD

**Issue by jensguballa** [ssllabs/ssllabs-scan#585]
Hi,

when performing a scan using the web-interface the list of supported ciphersuites is provided per TLS version.

On the other hand ssllabs-scan (i.e. the API) provides the list of supported ciphersuites on a global base. 

Would it be possible to align the API to the structure which is used by the web-interface scan?

**Comment by bhushan5640** [comment]
You need to use API v3
API v3 doc: https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md
branch: https://github.com/ssllabs/ssllabs-scan/tree/master
