### ISSUE TITLE
Getting an F grade on a Server IP we don't own

### ISSUE THREAD

**Issue by DuzAwe** [ssllabs/ssllabs-scan#586]
Hey we operate 4 private serves but in our tests we are there is a list of 158 ips of which only 4 are ours? As a result we are failing on DROWN for an issue we can not fix. Why are there so many ips?

 https://www.ssllabs.com/ssltest/analyze.html?d=togetherdigital.ie

**Comment by bhushan5640** [comment]
These IPs should be using same key/hostname certificate. See following posts for more details 
https://community.qualys.com/thread/17907-the-explanation-and-meaning-of-the-report-of-drown
https://blog.qualys.com/securitylabs/2016/03/04/ssl-labs-drown-test-implementation-details
