### ISSUE TITLE
Disabling TLS 1.0/1.1 lowers grade

### ISSUE THREAD

**Issue by jklida** [ssllabs/ssllabs-scan#587]
Currently, my server is testing at an "A", however, when I disable TLS 1.0/1.1, it drops the grade to a "B" due to the AEAD requirement on TLS 1.2. This seems counter intuitive since disabling 1.0/1.1 should raise the grade, not lower it.

**Comment by bhushan5640** [comment]
Is AEAD ciphers supported on TLS 1.2?

Disabling 1.0/1.1 should not cause AEAD penalty. You must support AEAD ciphers in TLS 1.2, check cipher suite section.

You may also PM me the hostname if you think there is a bug. https://community.qualys.com/people/blokhande

**Comment by bhushan5640** [comment]
Here is site that disabled TLS 1.0 and TLS 1.1 with A grade.
It supports AEAD with TLS 1.2
https://www.ssllabs.com/ssltest/analyze.html?d=www.github.com&hideResults=on
