### ISSUE TITLE
TLS_FALLBACK_SCSV support

### ISSUE THREAD

**Issue by konklone** [ssllabs/ssllabs-scan#59]
I can't find this in the API documentation or the returned results. Any plans to include it?

**Comment by ivanr** [comment]
I should be able to add it on Monday, just before the final build for the next production release that will officially include the API in it. It's just a matter of exposing an existing variable.

**Comment by konklone** [comment]
Nice. :+1:

**Comment by ivanr** [comment]
Implemented in v1.13.12, which is now running in the development environment: https://api.dev.ssllabs.com/api/v2/analyze.html?host=www.ssllabs.com&all=done

Thanks for the nudge!
