### ISSUE TITLE
How does Qualys determine the server Cipher Suites?

### ISSUE THREAD

**Issue by MikeY2018** [ssllabs/ssllabs-scan#591]
Hi,

I shared this with the community and now need to verify if Qualys uses "nmap" to obtain cipher suites which ssl-enum-ciphers script could have a bug that will display cipher suites already disabled.

https://community.qualys.com/message/40764-how-does-qualys-determine-the-server-cipher-suites

Thanks,
Michael

**Comment by bhushan5640** [comment]
Only bugs/issues should be reported on Github.
For queries please use https://community.qualys.com/community/ssllabs
