### ISSUE TITLE
Unable to scan IP Address

### ISSUE THREAD

**Issue by michaelkennedy** [ssllabs/ssllabs-scan#593]
The UI does not permit the scanning of IP addresses. However, IP addresses can be a SAN on a certificate, so should be scannable.

https://crt.sh/?id=371015548

IPv4 Addresses give an "IP addresses are not allowed" error:
https://www.ssllabs.com/ssltest/analyze.html?viaform=on&d=1.1.1.1

Attempting to use IPv6 gives a different error: Invalid port (4700:4700::1111)
https://www.ssllabs.com/ssltest/analyze.html?viaform=on&d=2606%3A4700%3A4700%3A%3A1111

**Comment by m-terlinde** [comment]
Dear Michael,

this repository is only for the command line tool.
The correct platform for your request is https://community.qualys.com/community/ssllabs.

But SSL Labs doesn't scan IPs by policy, so this is intended behaviour.
https://community.qualys.com/message/32730

This could change in the future: https://community.qualys.com/message/40642-specifying-both-a-domain-ip-address-to-test

Kind regards,
Matthias

**Comment by naumanshah03** [comment]
Dear Michael,

We have no plans on adding IP scanning in SSL Labs.

Please refer to this ticket - #730 

Regards,
Nauman Shah
