### ISSUE TITLE
Scan does not detect TLS 1.3 support

### ISSUE THREAD

**Issue by awnumar** [ssllabs/ssllabs-scan#594]
Screenshot of the test results:

![screenshot_20180402-140046](https://user-images.githubusercontent.com/8942495/38197087-6f72373e-367e-11e8-9af4-988d03d0f5c0.png)

Screenshot of an actual connection:

![screenshot_20180402-135839](https://user-images.githubusercontent.com/8942495/38197095-7d13943c-367e-11e8-8079-1f5aed9c2c5f.png)

**Comment by bhushan5640** [comment]
www.ssllabs.com currently supports TLS 1.3 draft 18; Please see the footer mentions that.

cryptolosophy.org supports TLS 1.3 draft 23. SSL Labs dev server currently supports draft 23, so dev.ssllabs.com detects it.

https://dev.ssllabs.com/ssltest/analyze.html?d=cryptolosophy.org&s=104.24.115.61&hideResults=on&latest
