### ISSUE TITLE
DNS delays

### ISSUE THREAD

**Issue by brian-memeo** [ssllabs/ssllabs-scan#596]
My root servers are updated in a five minute window, but the test site seems to be caching even when explicitly using "clear cache."  I updated at least two hours ago, and it's still tied to an old IP.

**Comment by bhushan5640** [comment]
SSL Labs currently uses Google public DNS.
Please refer this
https://github.com/ssllabs/ssllabs-scan/issues/554

Also try flush cache
https://developers.google.com/speed/public-dns/cache
