### ISSUE TITLE
Server scan doesn't grade 3DES as documented

### ISSUE THREAD

**Issue by dougkiwi** [ssllabs/ssllabs-scan#599]
The rating guide says that 3DES in TLS1.1+ will grade at C.  But I see sites such as atlassian.net are graded at A even though they use 3DES in TLS1.2.  Is that because stronger ciphers precede 3DES in the server preference order?  If so, documentation should be amended.
IMO: capping at C for 3DES is too harsh unless modern browsers are forced to use it.

**Comment by bhushan5640** [comment]
Our grading criteria to penalize sites that **negotiate** 3DES with TLS 1.1 and newer protocols. Such sites will have their scores capped at C. Sites that continue to support 3DES and keep it at the end of their ordered list of suites will not be affected.

Introduce a penalty (C) for using 3DES (and other ciphers with block sizes of 64 bits) with TLS 1.1+.
Here "using" we mean, if 3DES is negotiated with the Handshake simulations we have. You have to check in Handshake simulations and check if 3DES is negotiated with the TLS 1.1+

**Comment by dougkiwi** [comment]
Thanks, that makes sense, once you explain what “using” means in this context.
