### ISSUE TITLE
Contact Form on dev.ssllabs.com/ssltest

### ISSUE THREAD

**Issue by SkateScout** [ssllabs/ssllabs-scan#603]
The lastname and maybe the firstname does not accept UTF-8 characters.
But the limitation to a-z only apply to english speaking names. Even in germany
there are an set of 4 utf-8 characters that are common used.
So please enable utf-8 names in the contact form.

**Comment by tvlooy** [comment]
also the first name "Jean-Pierre" is not allowed because of the dash and the last name "Van Helsing" is not allowed because of the space, way too limited

**Comment by HLFH** [comment]
Please remove this contact form, don't put it in production, or can we login in the future to avoid this contact form?

**Comment by bhushan5640** [comment]
contact form is now removed.
https://dev.ssllab.com

**Comment by HLFH** [comment]
![typo](https://user-images.githubusercontent.com/2359059/39812807-ff13732a-5385-11e8-825b-a4fe96654137.PNG)

@bhushan5640 Typo.
