### ISSUE TITLE
Getting many 429 errors

### ISSUE THREAD

**Issue by keltia** [ssllabs/ssllabs-scan#606]
In https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md it is written than a well-written client will never get any 429 answers.

I'm using `ssllabs-scan` to scan our https hosts (54 total)  and I am getting lots of 429…  It is very recent, I did not get any of these last month (I do it at the beginning of each month).  Any idea?

```
2018/05/02 17:10:10 [INFO] Assessment starting: www.eatmportal.eu
2018/05/02 17:10:10 [DEBUG] Request #330: https://api.ssllabs.com/api/v2/analyze?host=trainingzonetest.eurocontrol.int&all=done&startNew=on
2018/05/02 17:10:10 [DEBUG] Request #331: https://api.ssllabs.com/api/v2/analyze?host=www.eatmportal.eu&all=done&startNew=on
2018/05/02 17:10:10 [INFO] Assessment starting: trainingzonetest.eurocontrol.int
2018/05/02 17:10:10 [DEBUG] Response #330 status: HTTP/1.1 200 OK
2018/05/02 17:10:10 [DEBUG] Response #331 status: HTTP/1.1 429 Too Many Requests
2018/05/02 17:10:10 [DEBUG] Server set current assessments to 6
2018/05/02 17:10:10 [DEBUG] Server set maximum assessments to 6
2018/05/02 17:10:12 [DEBUG] Request #332: https://api.ssllabs.com/api/v2/analyze?host=cefavalid.crco.eurocontrol.int&all=done
2018/05/02 17:10:12 [DEBUG] Response #332 status: HTTP/1.1 429 Too Many Requests
2018/05/02 17:10:13 [DEBUG] Request #333: https://api.ssllabs.com/api/v2/analyze?host=www.b2b.nmvp.nm.eurocontrol.int&all=done
2018/05/02 17:10:13 [DEBUG] Response #333 status: HTTP/1.1 429 Too Many Requests
2018/05/02 17:10:15 [DEBUG] Request #334: https://api.ssllabs.com/api/v2/analyze?host=trainingzonetest.eurocontrol.int&all=done
2018/05/02 17:10:15 [DEBUG] Response #334 status: HTTP/1.1 429 Too Many Requests
```

**Comment by tleemans** [comment]
Can confirm the same issue here. We created a fork for the code that contains an option to hard cap the amount of concurrent assessments to bypass the issue, although it takes a lot of extra time to go through the hostlist now. (see https://github.com/tleemans/ssllabs-scan/commit/937a8ffe7d3240938655fab0c765566b6b478f7d).

**Comment by yashks** [comment]
This is not issue. Please refer for correct usage - https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md#access-rate-and-rate-limiting

**Comment by keltia** [comment]
Uh, I'm just using `ssllabs-scan` so I was surprised it could not handle it properly the rate limits :)  It seems to be working now anyway.
