### ISSUE TITLE
Client test incorrectly reports "No" instead of "Firewall" when port 10303 is blocked

### ISSUE THREAD

**Issue by robmoss2k** [ssllabs/ssllabs-scan#607]
If you perform the test on a client that isn't able to communicate on non-standard ports, you get TLS 1.3 support as "No" and TLS 1.2 and earlier support as "Firewall", as detailed in the following thread:

https://community.qualys.com/thread/18279-ssllabs-tls-capabilities-output-different-from-chrome

I believe the following two lines should be inserted at line 271, although I'm not able to test:

jQuery('#protocol_tls1_3').text('Firewall');
jQuery('#protocol_tls1_3').css('color', 'red');

**Comment by tamthing** [comment]
This has now been fixed on version 1.32.15.
