### ISSUE TITLE
Set master as the default branch

### ISSUE THREAD

**Issue by anand-bhat** [ssllabs/ssllabs-scan#610]
When you visit https://github.com/ssllabs/ssllabs-scan, the stable branch is shown by default. As this holds the v2 API code and is deprecated, I suggest changing the default to master so that users do not think stable is the correct branch to use.

I do not know enough about git to suggest if renaming the branch to something other than stable is an option.

**Comment by bhushan5640** [comment]
Master branch is now set as default branch
