### ISSUE TITLE
TLS 1.3 enabled by default in Firefox 60 

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#612]
Please consider to add FF60 to Handshake Simulation 
and to https://www.ssllabs.com/ssltest/clients.html

**Comment by m-terlinde** [comment]
Hey Rob,

this repo isn't the right spot for feature requests regarding SSLLabs itself.
It's only for the command line tool "ssllabs-scan".
Please state your request at the SSL Labs community at https://community.qualys.com/community/ssllabs and close this issue.

Kind regards,
Matthias

**Comment by RobTho** [comment]
@Matthias, please review 
https://community.qualys.com/docs/DOC-4865-known-issues

Report SSL Labs issues > https://github.com/ssllabs/ssllabs-scan/issues  !!!

**Comment by bhushan5640** [comment]
dev.ssllabs.com now has Firefox 62 simulation
