### ISSUE TITLE
SSL Labs scanner IP Range

### ISSUE THREAD

**Issue by iqwebgroup** [ssllabs/ssllabs-scan#613]
Hello,
I am looking for an active IP range that your scanners use, both ipv4 and ipV6

our firewall is going crazy blocking SSL Labs all of a sudden, and we never had this issue.  Our clients use your scan all the time to scan our sites

**Comment by m-terlinde** [comment]
Hey,

please use the SSL Labs community side for such questions.
This repos is only for the command line tool.

Nevertheless, you can find the requested information here: https://community.qualys.com/docs/DOC-4865-known-issues

Kind regards,
Matthias
