### ISSUE TITLE
Deprecated Apple Truststore behavior for TrustedRoot certificates

### ISSUE THREAD

**Issue by thomas-schwieters** [ssllabs/ssllabs-scan#616]
Hello,

I'm working for the Atos Trustcenter. We operate the 'Atos TrustedRoot 2011' CA and the Atos Trustcenter website.
We have noticed in the SSL server test, that there is a remark, that our TrustedRoot Server certificate is not trusted by Apple. 
But since IOS 10 and MacOS sierra (which is not the latest version), we are in the TrustStore of Apple.
See: https://support.apple.com/en-us/HT207177
and https://support.apple.com/de-de/HT207189

Probably the test mechanism is still using the old truststore of Apple for verification.
Can this be updated, so that this message disappears?

Here is a sample page, which is using our Server certificate:
https://www.ssllabs.com/ssltest/analyze.html?d=pki.atos.net

**Comment by naumanshah03** [comment]
Hi @thomas-schwieters,

We have changed the Apple, Android and Java trust store to the latest one.
Current versions of trust stores used in SSL Labs.
Apple - MacOS 10.13.6
Android - 9.0
Java - 10.0.2

You can view the chages on dev.ssllabs.com
https://dev.ssllabs.com/ssltest/analyze.html?d=pki.atos.net
