### ISSUE TITLE
F grade for RC4?

### ISSUE THREAD

**Issue by andrepereiradasilva** [ssllabs/ssllabs-scan#62]
The new RFC 7465 "Prohibiting RC4 Cipher Suites" has been published.

> Because of the RC4 deficiencies noted in Section 1, the following apply:
> - TLS clients MUST NOT include RC4 cipher suites in the ClientHello message.
> - TLS servers MUST NOT select an RC4 cipher suite when a TLS client sends such a cipher suite in > the ClientHello message.
> - If the TLS client only offers RC4 cipher suites, the TLS server MUST terminate the handshake.  The TLS server MAY send the insufficient_security fatal alert in this case.»

Source: https://tools.ietf.org/html/rfc7465

So, in my opinion, it's time to give an F for servers using RC4 cipher suites.

**Comment by ivanr** [comment]
The grading will indeed change, but please keep this issue tracker for discussion of testing features (not grading criteria). Thanks.
