### ISSUE TITLE
"Connection is unsecure" on some devices

### ISSUE THREAD

**Issue by BlohoJo** [ssllabs/ssllabs-scan#622]
Tried running client test on Panasonic Web TV, which used to work. Now it doesn't... gives "This connection is unsecure" blue box message and won't display the web page. Happens on the entire site https://www.ssllabs.com/*. Browser uses TLS 1.1, which ssllabs.com is supposed to support.

User Agent:

Mozilla/5.0 (X11; FreeBSD; U; Viera; en-US) AppleWebKit/537.11 (KHTML, like Gecko) Viera/3.4.13 Chrome/23.0.1271.97 Safari/537.11

**Comment by bhushan5640** [comment]
We have recently updated www.ssllabs.com certificate with DigiCert signed cert. 
"DigiCert Global Root G2"
https://crt.sh/?q=cb3ccbb76031e5e0138f8dd39a23f9de47ffc35e43c1144cea27d46a5ab1cb5f

You need to check if underlying Trust store is updated and has the above root cert.
