### ISSUE TITLE
Cert in LabsReport struct is named wrong and LabsCert struct Id has the wrong type

### ISSUE THREAD

**Issue by schoenbornl** [ssllabs/ssllabs-scan#625]
The Json structure returned by the API has a field called certs. The corresponding golang struct LabsReport only has a field named Cert. For correct unmarshaling it should be called Certs.

Also the Id of the certs is a string and not an int as in the LabsCert struct. This results in an unmarshaling error.

**Comment by bhushan5640** [comment]
Fixed. Thanks for reporting
https://github.com/ssllabs/ssllabs-scan/commit/64e93cc6666b411aed5191948204067ddf9a81b0
