### ISSUE TITLE
Scroll to top each time percent completion updates

### ISSUE THREAD

**Issue by myxibrium** [ssllabs/ssllabs-scan#626]
Hi,

When using the following URL:
https://www.ssllabs.com/ssltest/analyze.html?d=some-domain-here

To test a domain which has not been previously tested, it takes time for the website to perform all the necessary steps. However, during this time the page scroll resets to 0 each time the percent completion updates. This is a poor user experience for someone who wants to preview the results before the entire suite of tests has been performed.

**Comment by bhushan5640** [comment]
Duplicate
https://github.com/ssllabs/ssllabs-scan/issues/422
