### ISSUE TITLE
TLS 1.3 site works in firefox but not ssl labs test

### ISSUE THREAD

**Issue by andrewmiller1** [ssllabs/ssllabs-scan#630]
www.andrewmiller.business
TLS_AES_256_GCM_SHA384

**Comment by bhushan5640** [comment]
dev.ssllabs.com supports TLS 1.3 draft 28. This site supports TLS 1.3 draft 28
https://dev.ssllabs.com/ssltest/analyze.html?d=www.andrewmiller.business&hideResults=on

**Comment by andrewmiller1** [comment]
Ah it works on the dev version of ssl labs. I see now. Thank you :)
