### ISSUE TITLE
Assessment failed with TLS_AES_128_CCM_SHA256 on Apache HTTP Server mod_ssl + OpenSSL 1.1.1-pre8

### ISSUE THREAD

**Issue by testtlnls** [ssllabs/ssllabs-scan#639]
Hi,

When I tested a website using Apache HTTP Server mod_ssl + OpenSSL 1.1.1-pre8, 
I met a error "Assessment failed: No OpenSSL mapping for suite 0x1304".
0x1304 means TLS1.3 TLS_AES_128_CCM_SHA256.
The website prefers TLS_AES_128_CCM_SHA256 and TLS_AES_128_CCM_8_SHA256 than other ciphersuites.
Could you solve this problem?

Thank you.
![2](https://user-images.githubusercontent.com/41869011/43367786-a9b01e40-938d-11e8-8688-4da4025bff86.png)

**Comment by joramk** [comment]
I am using HAProxy with OpenSSL 1.1.1-pre8 from Fedora Rawhide. It is working for me with a score of 90% on key exchange and 90% on cipher strength. Other scores are 100%. I have seen a similar error during my tests. It happend once only.

**Comment by naumanshah03** [comment]
Hi @testtlnls,

Please private message me the domain name at https://community.qualys.com/people/nshah

**Comment by testtlnls** [comment]
Thank you for replying.

When I tested my own test server for development using Apache HTTP Server 2.4.37 mod_ssl + OpenSSL 1.1.1(LTS),
I met a error "Assessment failed: No OpenSSL mapping for suite 0x1304" or "Assessment failed: No OpenSSL mapping for suite 0x1305" on another server.

The server showing 0x1304 error uses SSLOpenSSLConfCmd Ciphersuites "TLS_AES_128_CCM_SHA256:TLS_AES_128_CCM_8_SHA256:...
The server showing 0x1305 error uses SSLCipherSuite TLSv1.3 TLS_AES_128_CCM_8_SHA256:TLS_AES_128_CCM_SHA256:...

Now, I cannot bind it to port 443.
I am trying to ban Microsoft software from port 443.

If it get bound to port 443, I will tell you its domain name.

The tested route is not able to maintain its connection.

Thank you.

**Comment by naumanshah03** [comment]
@testtlnls Are you still facing this issue?

**Comment by testtlnls** [comment]
Yes, on Sat, 27 Apr 2019 00:51:05 UTC.

**Comment by testtlnls** [comment]
I confirmed this issue is solved.
Thank you for your working.
