### ISSUE TITLE
OCSP Stapling false-negative when using SNI

### ISSUE THREAD

**Issue by JimWolff** [ssllabs/ssllabs-scan#642]
I have noticed that OCSP Stapling often shows up as false, when scanning site that use IIS with SNI, if i host sites in such a way that i don't  use SNI, OCSP Stapling comes up as true.

As soon as i use SNI to have multiple sites with different certificates on the same IP address, OCSP Stapling shows as false after the scan.
This seems like bug to me, or maybe someone can elaborate, if i'm misunderstanding something here.

I haven't tested if this is also an issue on non-IIS servers, but i have tested both with win2k12/2k16
When looking at the json returned from the API:

endpoints -> details -> `ocspStapling: false,`
but
endpoints -> details -> cert -> `ocspURIs: [http://ocsp.int-x3.letsencrypt.org],`

**Comment by ArchangeGabriel** [comment]
Maybe this OCSP+SNI issue is in IIS and not SSL Labs? Because using nginx for my setup, I have no such issue.

**Comment by JimWolff** [comment]
Interesting, i was trying to test it with some other tool like openssl to see if OCSP is actually working and just getting mis-reported.

When running the command: `openssl s_client -connect foo.bar:443 -tls1_2  -tlsextdebug  -status`
it does give me a:
    `OCSP Response Status: successful (0x0)`

**Comment by ArchangeGabriel** [comment]
That `openssl` command does not include a `-servername` parameter, so no SNI here. Unless you’ve removed it completely when posting instead of redacting it like `-servername foo.bar`.

**Comment by JimWolff** [comment]
@ArchangeGabriel `-servername` put me on the right track, thank you.
After using `-servername foo.bar` i got `OCSP response: no response sent`

Searching a bit more, i found this [MSDN article](https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/dn786418(v=ws.11)) for win2k12, and is still relevant for win2016 after testing.
**Explaining OCSP is disabled by default for SNI and CCS per default because of performance issues.**

Enabling it can be done in the registry:
`[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL]`
by adding: `"EnableOcspStaplingForSni"=dword:00000001`

**From reference article:**
> **OCSP stapling**
Online Certificate Status Protocol (OCSP) stapling enables a web server, such as Internet Information Services (IIS), to provide the current revocation status of a server certificate when it sends the server certificate to a client during the TLS handshake. This feature reduces the load on OCSP servers because the web server can cache the current OCSP status of the server certificate and send it to multiple web clients. Without this feature, each web client would try to retrieve the current OCSP status of the server certificate from the OCSP server. This would generate a high load on that OCSP server.
>
>By default, OCSP support is enabled for IIS websites that have a simple secure (SSL/TLS) binding. However, this support is not enabled by default if the IIS website is using either or both of the following types of secure (SSL/TLS) bindings:
>
>- Require Server Name Indication
>
>- Use Centralized Certificate Store
>
>In this case, the server hello response during the TLS handshake won't include an OCSP stapled status by default. This behavior improves performance: The Windows OCSP stapling implementation scales to hundreds of server certificates. Because SNI and CCS enable IIS to scale to thousands of websites that potentially have thousands of server certificates, setting this behavior to be enabled by default may cause performance issues.
>
>To enable OCSP stapling for SNI and CCS bindings, locate the following registry subkey:
>
>**Registry path**: [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL]
>
>To this subkey, add the following key:
>
>"EnableOcspStaplingForSni"=dword:00000001
>
>**Note** Enabling this registry key has a potential performance impact.

Now everything works :)
