### ISSUE TITLE
Explanations of Ciphersuite Rating

### ISSUE THREAD

**Issue by manuelhartl** [ssllabs/ssllabs-scan#646]
Hi SSLLabs,

is there an explanation when ciphers are rated Weak? or Not?

**Comment by naumanshah03** [comment]
Hi @manuelhartl,

Please go through the SSLLabs grading document - https://github.com/ssllabs/research/wiki/SSL-Server-Rating-Guide

You can post such queries on community forum of SSLLabs - https://community.qualys.com/community/ssllabs
