### ISSUE TITLE
TLS 1.3 active, but not reported by ssllabs

### ISSUE THREAD

**Issue by sbordet** [ssllabs/ssllabs-scan#651]
webtide.com is now on TLS 1.3 via OpenJDK 11, but ssllabs does not report TLS 1.3.

However, openssl 1.1.1-pre9 does report TLS 1.3: https://github.com/eclipse/jetty.project/issues/2711#issuecomment-417861730.

From an analysis of the traffic on our server during the ssllabs scan, seems like ssllabs is not using TLS 1.3 `supported_versions` extension to negotiate the TLS version, or sends it with the wrong TLS protocol ID, for example we see:

```
"supported_versions (43)": {
  "versions": [(D)TLS--6.-6, (D)TLS-127.28, TLSv1.2, TLSv1.1, TLSv1]
}
```

The (D)TLS versions seem wrong and there is no TLSv1.3.

**Comment by lukvdborne** [comment]
I have the same problem with nginx 1.14.0 and openssl 1.1.1. A simple s_client call shows that TLSv1.3 can and is being used, but the scan insists TLSv1.3 has not been enabled. For what it's worth, Neither Chrome 69 nor the latest stable Firefox negotiate TLS 1.3 either. Apparently the final TLSv1.3 draft is somehow incompatible with earlier drafts, meaning that only as of Chrome 70 (due in October) will TLS  1.3 actually be used in combination with openssl 1.1.1. 

I suppose it's possible that the scan has the same problem and doesn't use the final spec either. Ostensibly this means that there will have to be multiple checks, but also that the check will be able to report which draft is being used, or at least if it's the final draft.

**Comment by lukvdborne** [comment]
Yes, but shouldn't the scan also be able to detect older drafts of the TLSv1.3 spec?

**Comment by Schmuuu** [comment]
The test of ssllabs only supports TLS v1.3 Draft 28 in the current version v1.32.5.
The Final version and the previous drafts are not compatible.

Firefox nightly build and htbridge.com ssl test support the final version already. 
As far as I know both browsers Chrome and Firefox will support final TLS 1.3 with the next release in October, which will be Firefox 63 and Chrome 70.

**Comment by DXGLdotinfo** [comment]
So everyone is on the same page, OpenSSL 1.1.1-pre9 and final support the final version of TLS 1.3, and as such SSL Labs would need to support the final version of TLS 1.3 to display as supported.

SSL Labs should certainly make it a priority to support RFC 8446 in the next version of the scanner.

**Comment by sbordet** [comment]
@adriancampos just tried webtide.com again, and dev.ssllabs.com reports no TLS 1.3.

**Comment by adriancampos** [comment]
@sbordet interesting, dev.ssllabs.com now reports TLS 1.3 with [www.mozilla.org](https://www.ssllabs.com/ssltest/analyze.html?d=www.mozilla.org&s=104.16.41.2).

Main difference I see running openssl s_client is that webtide.com reports an ssl chipher of TLS_AES_128_GCM_SHA256 whereas www.mozilla.org (and others that report TLS 1.3 in SSL Labs) report TLS_AES_256_GCM_SHA384. I don't know enough to know if that's the issue but could be worth a shot.

**Comment by sbordet** [comment]
@adriancampos were you able to negotiate TLS 1.3 with `openssl s_client`? (I was, see first comment)
 
If so, it cannot be a cipher issue, but just a reporting issue from ssllabs.

**Comment by adriancampos** [comment]
I don't have any servers to test it on right now. When you scan with dev.ssllabs.com, does it still report the obscure version numbers?

**Comment by sbordet** [comment]
@adriancampos yes, I still see obscure version numbers with dev.ssllabs.com.

This is what I saw:

```
    "supported_versions (43)": {
      "versions": [TLSv1.3]
    },
    ...
javax.net.ssl|ERROR|0F|qtp1112737073-15|2018-09-25 20:53:10.222 UTC|TransportContext.java:313|Fatal (HANDSHAKE_FAILURE): pre_shared_key key extension is offered without a psk_key_exchange_modes extension
```

```
    "supported_versions (43)": {
      "versions": [(D)TLS--6.-6, (D)TLS-127.28, TLSv1.2, TLSv1.1, TLSv1]
    },
```

```
    "supported_versions (43)": {
      "versions": [(D)TLS-10.10, TLSv1.3, TLSv1.2, TLSv1.1, TLSv1]
    },
    ...
javax.net.ssl|ERROR|11|qtp1112737073-17|2018-09-25 20:53:33.510 UTC|TransportContext.java:313|Fatal (HANDSHAKE_FAILURE): pre_shared_key key extension is offered without a psk_key_exchange_modes extension
```

```
    "supported_versions (43)": {
      "versions": [(D)TLS-127.28, TLSv1.2, TLSv1.1, TLSv1]
    },
```

**Comment by Dmole** [comment]
FireFox developer edition will happily use TLSv1.3 with OpenJDK 11 but dev.ssllabs.com still reports "No" 1.3.

**Comment by lukvdborne** [comment]
Both dev and production now correctly show that "This server supports TLS 1.3 (RFC 8446)." for me. Thanks!

**Comment by DXGLdotinfo** [comment]
In that case it would be a bug as my OpenSSL 1.1.1 server is properly detected.

**Comment by sbordet** [comment]
@DXGLdotinfo thanks for the report about privacy policy, we'll take care of complying ASAP.

**Comment by wiktor-k** [comment]
Yep, I also see "This server supports TLS 1.3 (RFC 8446)." but the JSON API endpoints (e.g. `api.dev.ssllabs.com`) show only TLS 1.2, is it planned to add TLS 1.3 there too?

**Comment by tamthing** [comment]
@sbordet After investigating we came across this OpenJDK 11 [bug](https://bugs.openjdk.java.net/browse/JDK-8210334) because of which the handshake was failing for TLS 1.3 for servers with this version of OpenJDK, which has now been resolved. It is advised to upgrade to a fixed version to get a correct result from SSL Labs.

**Comment by tamthing** [comment]
@wiktor-k  I can see that you have used the deprecated API _**/api/v2/**_, it is advised to use the new API _**/api/v3/**_  instead. The older API is yet to be updated. Refer https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs.md for the new API

**Comment by wiktor-k** [comment]
Oh, I was not aware that v2 is deprecated, thanks for the notice @tamthing!

(Maybe it would be useful to add an output to v2 JSON something like `"info":"This API is deprecated see docs at ..."`? I read this JSON a lot more than the docs... maybe that's because the API is really nicely designed :smile:)
