### ISSUE TITLE
unsupported ciphers show up in scan - for TLS V1.1 and TLS V1.2

### ISSUE THREAD

**Issue by ykosaraju** [ssllabs/ssllabs-scan#653]
`TLS_RSA_WITH_3DES_EDE_CBC_SHA`  and  `TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA` are only valid for TLSv1.0 according to  https://www.openssl.org/docs/manmaster/man1/ciphers.html
BUT these are shown as supported for TLSv1.1 and TLSv1.2 in the SSLabs scan

**Comment by hotaru2k3** [comment]
> only valid for TLSv1.0 according to https://www.openssl.org/docs/manmaster/man1/ciphers.html

that page doesn't say anything remotely like that.

**Comment by ykosaraju** [comment]
if you search for the ciphers in the page:
It lists supported ciphers for each version of SSL/TLS
AND  TLS_RSA_WITH_3DES_EDE_CBC_SHA and TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA are specified for TLSv1.0 (and not the others)

Scan shows these ciphers as being supported in other versions..
Am I missing something?

**Comment by hotaru2k3** [comment]
> It lists supported ciphers for each version of SSL/TLS

no, it doesn't.

**Comment by naumanshah03** [comment]
Hi @ykosaraju 

Your understanding of it is incorrect.
You can practically test it by running the below command with OpenSSL:
> /opt/ssllabs/bin/openssl s_client -connect www.google.com:443 -tls1 -cipher DES-CBC3-SHA

This command sends TLS 1.0 as protocol and DES-CBC3-SHA (TLS_RSA_WITH_3DES_EDE_CBC_SHA) as a cipher suite.

Hence the result shown in SSLLabs is correct.
Invalid request.
Closing the issue.

Regards,
Nauman Shah
