### ISSUE TITLE
IPv6 doesn't work any more 

### ISSUE THREAD

**Issue by maxmueller007** [ssllabs/ssllabs-scan#655]
Any test gets this error:
Unable to connect to the server

**Comment by cadirol** [comment]
Same here:
 Unable to connect to the server

The web Server is reachable over v6 - tested with several Testpages
In the Webserver access logs is no access logged from ssllabs

**Comment by nilsmeyer** [comment]
Tested with a few domains as well, also made sure sure that these work through other native IPv6 systems. A prominent example would be cloudflare. This causes false positives in monitoring systems for my client.

**Comment by DarkForce42** [comment]
IPv6 doesn't work at all. Not even with Google.com etc.
So it isn't only about new domains or wrong configured servers.

**Comment by priyankaraghavan** [comment]
We see the same issue as well. so +1 for the solution.

**Comment by naumanshah03** [comment]
Issue has been resolved.
https://www.ssllabs.com/ssltest/analyze.html?d=ipv6.google.com
