### ISSUE TITLE
Add a TLS 1.3 column at clients overview, please

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#656]
@
https://www.ssllabs.com/ssltest/clients.html
https://dev.ssllabs.com/ssltest/clients.html

**Comment by RobTho** [comment]
Additional it would be nice to see AEAD ciphers green and TLS 1.1 in yellow also on

https://www.ssllabs.com/ssltest/viewMyClient.html
and capabilities (Details) 

so that they are analog to Server result coloring

**Comment by naumanshah03** [comment]
@RobTho 

We've made this requested change.
Please visit https://dev.ssllabs.com/ssltest/clients.html

Regards,
Nauman Shah

**Comment by naumanshah03** [comment]
Closing this issue since the changes are now available on www.ssllabs.com
