### ISSUE TITLE
SSL Server Test fails for IPv6 (works on dev)

### ISSUE THREAD

**Issue by wibimaster** [ssllabs/ssllabs-scan#659]
Hi, 

Test for "devstroke.io" returns "Unable to connect to the server".
https://www.ssllabs.com/ssltest/analyze.html?d=devstroke.io&s=2607%3a5300%3a60%3a884%3a0%3a0%3a0%3a1

Trying :
```sh
$ ping -6 devstroke.io
PING devstroke.io(nestor.salade2chats.com (2607:5300:60:884::1)) 56 data bytes
64 bytes from nestor.salade2chats.com (2607:5300:60:884::1): icmp_seq=1 ttl=64 time=0.043 ms
```
 Seems OK, and trying :

```sh
$ openssl s_client -connect [2607:5300:60:884::1]:443
CONNECTED(00000003)
```
Seems OK too.

It works on dev.ssllabs.com, I got a A+ :

https://dev.ssllabs.com/ssltest/analyze.html?d=devstroke.io&s=2607%3a5300%3a60%3a884%3a0%3a0%3a0%3a1&hideResults=on&latest

Did I miss something ?

Thanks !

**Comment by naumanshah03** [comment]
Hi @wibimaster 

Your domain is not reachable with IPv4 or IPv6
Hence closing the issue.
