### ISSUE TITLE
Grade T overrides Grade M?

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [ssllabs/ssllabs-scan#666]
Hello,

I'm trying to figure out how to detect certificate name mismatch and other issues with only one API Call (i.e not perfoming the first analysis, detecting the mismatch and perfoming the second analysis with ignoreMismatch option ).

According to documentation, Endpoint's grade is defined as:

    grade - possible values: A+, A-, A-F, T (no trust) and M (certificate name mismatch)

But name mismatch is just one of the possible reasons for the lack of trust:

    There are many reasons why a certificate may not be trusted. The exact problem is indicated on the report card in bright red. The problems fall into three categories:

    Invalid certificate
    Invalid configuration
    Unknown Certificate Authority

    1. Invalid certificate
    A certificate is invalid if:

    It is used before its activation date
    It is used after its expiry date
    Certificate hostnames don't match the site hostname
    It has been revoked
    It has insecure signature
    It has been blacklisted

So, the detection of a grade T not implies a certificate name mismatch.
The CertificateChain's issues seem not detecting name mismatches, For instance, AlternativaPopolare website (https://www.ssllabs.com/ssltest/analyze.html?d=www.alternativapopolare.it) has a certificate mismatch, but issues' value is 0.

Am I missing something?

**Comment by tamthing** [comment]
Hi Antonio, the API scan result for the domain you provided correctly detected the hostname mismatch issue yielding an issue value 8 which matches the description given under [Cert](https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md#cert) section of the API documentation. Perhaps you are looking at a different section of the result json or the API documentation? Additionally, the web browser scan of the domain correctly detected the hostname mismatch as expected.
