### ISSUE TITLE
IPv6 problems

### ISSUE THREAD

**Issue by florian2833z** [ssllabs/ssllabs-scan#669]
If I test my server
https://dev.ssllabs.com/ssltest/analyze.html?d=florian2833z.de&latest

the ipv6 test fails with the reason " Assessment failed: No certificates found ". I dont know what the problem is, my web browsers are able to access the site. Can anyone tell me if the site works on their end via ipv6? 
Note: My server only allows TLS 1.3

**Comment by naumanshah03** [comment]
Thanks for the update. 
We will look into this issue and update about it

**Comment by yashks** [comment]
We are not able to replicate this issue, if you still see this issue, please reopen this ticket.

**Comment by MNibble** [comment]
while this is closed I have the same issue and can provide some details: 

I am running a hitch SSL proxy. When I allow TLSv1.2 and TLSv1.3 on ipv6 it's fine. When I switch to tlsv1.3 only, ipv4 still works from your test suite but ipv6 returns  "No certificates found" 

The installation is in docker containers and therefore the complete path is docker-proxy -> hitch -> wiki 

All internal docker IPs are ipv4 anyway. Browsers have no issue talking ipv6 with TLSv1.3.   
Domain is question is strasheim.eu ( your page should have the results stored, which should also contain the scans when both TLSv1.2 and TLSv1.3 showed a certificate for ipv6 ).

**Comment by florian2833z** [comment]
> When I allow TLSv1.2 and TLSv1.3 on ipv6 it's fine. When I switch to tlsv1.3 only, ipv4 still works from your test suite but ipv6 returns "No certificates found"

Yep, that is exactly my problem!

**Comment by MNibble** [comment]
To add some debugging help to this: Taken from a host fare away, meaning using the same internet we all do to reach the final server: 

```
openssl s_client -connect [2a01:4f8:c2c:1b3f::1]:443 -servername strasheim.eu
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = strasheim.eu
verify return:1
---
Certificate chain
 0 s:CN = strasheim.eu
   i:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
 1 s:C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
   i:O = Digital Signature Trust Co., CN = DST Root CA X3
---
Server certificate
-----BEGIN CERTIFICATE-----
```

Generally it's working for for browsers and even SSL testing it's just the test page that is failing to use pure TLSv1.3 on ipv6

**Comment by naumanshah03** [comment]
@MNibble thanks for sharing extra information. It will be helpful in figuring out the issue if any.

We will update you soon on this issue.

**Comment by tamthing** [comment]
The issue has now been resolved. You may test on dev.ssllabs.com to confirm.
