### ISSUE TITLE
TLS1.0 shouldn't provide A grade

### ISSUE THREAD

**Issue by jpptinsley** [ssllabs/ssllabs-scan#670]
TLS1.0 should be considered depreciated and cap grades at B or lower now; TLS1.0 will fail you for PCI compliance;
https://www.varonis.com/blog/ssl-and-tls-1-0-no-longer-acceptable-for-pci-compliance/

**Comment by jpptinsley** [comment]
PCI scanners are already treating support for TLS 1.0/1.1 as an immediate fail; surely the scan tool should at least highlight a warning note, even if it doesn't flag for an immediate downgrade?

**Comment by naumanshah03** [comment]
These changes have been implemented.
