### ISSUE TITLE
Please add an Android 8.0.0 testcase

### ISSUE THREAD

**Issue by toby78** [ssllabs/ssllabs-scan#672]
I noticed an increased crashrate for Android 8.0.0 only -> could you add this to the SSL Test please?
It only supports Android 7.

**Comment by tamthing** [comment]
Thanks for reporting. We would look into the issue and update on this.

**Comment by naumanshah03** [comment]
Hi @toby78 

Please find the newly added Android 8.0 simulation test on dev.ssllabs.com version 1.36.1

Regards,
Nauman Shah
