### ISSUE TITLE
Please update Apple's Root store

### ISSUE THREAD

**Issue by dzacharo** [ssllabs/ssllabs-scan#673]
IOS 12 added some Root CA Certificates (https://support.apple.com/en-in/HT209144), two of which are:

- Hellenic Academic and Research Institutions RootCA 2015
- Hellenic Academic and Research Institutions ECC RootCA 2015

Here is the link to the [latest Apple's Root Store](https://opensource.apple.com/source/security_certificates/security_certificates-55093.200.19/certificates/roots/)

Can you please add them in the ssllabs-scan engine as "Trusted by Apple"?

Thank you,
Dimitris Zacharopoulos (HARICA)

**Comment by tamthing** [comment]
Thank you for reporting. We will look into it.

**Comment by dzacharo** [comment]
You can also verify that these Root CA Certificates are Trusted by Apple by visiting crt.sh at:

- https://crt.sh/?caid=14566
- https://crt.sh/?caid=14546

Please correct the misleading information "This server's certificate is not trusted by Apple".

Thank you.
DZ.

**Comment by naumanshah03** [comment]
Hi @dzacharo 

Thanks for bringing this to our notice.

SSL Labs uses MacOS 10.13.6 (High Sierra) as Apple's trust store. Trust store for SSL Labs is updated with every release. In the upcoming release, you can expect an upgrade in Apple's trust store.

You can use the following [API](https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md#retrieve-root-certificates) to check for the list of certificates in a particular trust store. Also, in the first line, you can check the trust store version of the trust store used for server test. In webpage, you can hover on the trust store name mentioned in **Certification Paths** to get the trust store version used for server test.

Regards,
Nauman Shah

**Comment by naumanshah03** [comment]
@dzacharo,

SSL Labs had updated the Apple's Trust store to **MacOS 10.14.3**
Name of the certificates shared by you can be viewed in this [link](https://api.ssllabs.com/api/v3/getRootCertsRaw?trustStore=2)
This link shows all the CA certificates of Apple trust store (MacOS 10.14.3) used by SSL Labs for validation
