### ISSUE TITLE
Microsoft and Mozilla Root stores are out of date

### ISSUE THREAD

**Issue by dougbeattie** [ssllabs/ssllabs-scan#674]
Mozilla and Microsoft root stores are out of date.  We've added a new root and it should be marked as trusted in at least MS and Mozilla (still working with Apple).

https://bugzilla.mozilla.org/show_bug.cgi?id=1390803 

The Root has been in Microsoft for about a year.

**Comment by tamthing** [comment]
Thank you for reporting. We will update soon.

**Comment by naumanshah03** [comment]
Hi @dougbeattie 

Please use the following [mentioned api's here](https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md#retrieve-root-certificates) to check for the list of root certificate used in SSL Labs while performing server test.

After checking for the mentioned certificate it was found that the mentioned certificate is present while performing server test in SSL Labs. Checked for string "GlobalSign Root CA - R6"
Windows - https://api.ssllabs.com/api/v3/getRootCertsRaw?trustStore=5
Mozilla - https://api.ssllabs.com/api/v3/getRootCertsRaw?trustStore=1

If you still feel that SSL Labs is showing incorrect result then please share the domain name in DM with [me](https://community.qualys.com/people/nshah) or [tamthing](https://community.qualys.com/people/tamthing) to check the result.

Regards,
Nauman Shah

**Comment by naumanshah03** [comment]
No response closing the issue
