### ISSUE TITLE
No HTTP test with TLS 1.3 only host

### ISSUE THREAD

**Issue by Tributh** [ssllabs/ssllabs-scan#679]
Hi,
with an TLS 1.3 only host only the whole TLS scan will be done.
An HTTP connect to the webserver fails with "no shared ciphers" and the Security Headers like HSTS can not be checked.

Please add TLS 1.3 for the HTTP tests.

Cheers Torsten

**Comment by naumanshah03** [comment]
If this is still an issue please share the domain name in private with [me](https://community.qualys.com/people/nshah) or [Tamthing](https://community.qualys.com/people/tamthing)

**Comment by naumanshah03** [comment]
Closed the issue as no reply received
