### ISSUE TITLE
SSL Labs showing incorrect TLS status?

### ISSUE THREAD

**Issue by ndesimone** [ssllabs/ssllabs-scan#685]
I have TLS 1.0 and 1.1 disabled on my site https://www.milkstork.com, but SSL Labs is showing TLS 1.1 is disabled, but TLS 1.0 is still enabled.  I've used an another scanner that is showing that we're not offering 1.0 or 1.1 (as expected)

Can you please confirm?

**Comment by tamthing** [comment]
There is no such supported protocol detection error on SSL Labs like you described. On OpenSSL I could connect with TLS 1.0 & TLS 1.1 to your server. Please check your server configurations again.

**Comment by ndesimone** [comment]
@tamthing, a couple of things:

1. You were not accessing the Milk Stork server, you were hitting the CloudFlare WAF that is configured for minimum TLS 1.2
2. Would you mind posting your test results.  Here's what I'm getting:

`openssl s_client -connect www.milkstork.com:443 -tls1_2
... stuff deleted
Verify return code: 20 (unable to get local issuer certificate)`

`openssl s_client -connect www.milkstork.com:443 -tls1_1
... stuff deleted
Verify return code: 20 (unable to get local issuer certificate)`

`openssl s_client -connect www.milkstork.com:443 -tls1_2
... stuff deleted
Verify return code: 0 (ok)`
