### ISSUE TITLE
IPv6 and IP-Ranges

### ISSUE THREAD

**Issue by SkateScout** [ssllabs/ssllabs-scan#687]
Hi,

in the Document https://community.qualys.com/docs/DOC-4865-known-issues there is no information about the IP-Ranges used. I think these two should be mentioned in the document.

2001:4801:7827:102:93a4:e8aa:5bca:d1f  for dev.ssllabs.com
2600:c02:1020:4202::ac10:8268 for www.ssllabs.com

**Comment by naumanshah03** [comment]
Hi @SkateScout 

We've updated the document and added an outbound IP range for our prod and dev server.
Please check it.

Regards,
Nauman Shah
