### ISSUE TITLE
PKP header should be invalid without a backup pin

### ISSUE THREAD

**Issue by EiNSTeiN-** [ssllabs/ssllabs-scan#69]
The HPKP header seems to be marked valid even when there is only one pinned key. As per [the spec section 4.3](https://tools.ietf.org/html/draft-ietf-websec-key-pinning-21#section-4.3), browsers will not take the header into account when there is not a backup pin set. SSL Labs scanner should mark the header invalid in that case. The header should be considered valid only when there is at least one pin that does not match any of the presented certificates.

Here's an example of invalid header marked as valid by the scanner:
![screen shot 2015-03-02 at 6 19 46 pm](https://cloud.githubusercontent.com/assets/2053039/6453112/dd71068c-c108-11e4-944d-685b4003a688.png)

**Comment by tdelmas** [comment]
(feel free to open a new issue if my comment is misplaced)

Obviously wrong HPKP header produce a beautiful "green yes" : 

__Public Key Pinning (HPKP)	Yes   pin-sha256="obviouslywrong"; max-age=604800__

Please consider adding a message indicating that no check are performed, or better, add the following tests : 
- all pin-sha256 values should be the base64 of an sha256
- a least one value match the sha256 of a certificate on the chain
- a least one back-up pin is set (see https://tools.ietf.org/html/draft-ietf-websec-key-pinning-21#section-4.3 )

If these tests are performed, the result could display : 
- "no", if no HPKP are provided
- "invalid checksum", if the first test fail
- "key not in chain", if the second test fail
- "backup key missing", if the third test fail
- "server certificate pin", if one key match the sha256 of the server certificate
- "intermediary certificate pin", if one key match the sha256 of any other certificate of the chain

**Comment by tdelmas** [comment]
To add more informations, regarding https://twitter.com/ivanristic/status/583314833120104449 : 

HPKP is not anymore a draft but an RFC : https://tools.ietf.org/html/rfc7469

Chrome : 
- provide a specific UI for HPKP errors
- provide an UI to check and manage HPKP : chrome://net-internals/#hsts
- Robert Love (Google engineer) writes a clear and long blog post about it : http://blog.rlove.org/2015/01/public-key-pinning-hpkp.html and Adam Langley (Google Senior Staff Software Engineer) mention it on his last post : https://www.imperialviolet.org/2015/01/17/notdane.html

Firefox :
- provide a specific UI for HPKP errors
- provide an UI to check and manage HPKP : using the developer version, the network panel display a security tab 
- and mozilla provide a clean documentation about it : https://developer.mozilla.org/en-US/docs/Web/Security/Public_Key_Pinning

More information about browser support : https://projects.dm.id.lv/Public-Key-Pins_test

In my opinion, the only missing piece is a web checked with clear information to help people understood if they did it right, or what is wrong. Just like ssllabs do for others HTTPS/SSL/TLS technologies !

**Comment by ivanr** [comment]
Version 1.20.19 (now running on the dev server) full HPKP support.

**Comment by tdesaules** [comment]
Hi,

Maybe I made something wrong but I always get an error...
![2015-11-09_15-17-24](https://cloud.githubusercontent.com/assets/1481384/11035838/1add3b96-86f5-11e5-9517-886ebf415cff.png)

**Comment by selecadm** [comment]
@tdesaules so what's the site? We can't say what exactly you did wrong without knowing it.

**Comment by tdesaules** [comment]
I find the problem... sorry (two PIN are in the chain so doesn't work)

**Comment by florafrisia** [comment]
Here the same problem, my website pjnoe.org+

 	Invalid   Invalid HSTS header
pin-sha256="xN6JIS4n5cLnkk66mcq9+L/YC2qWxq8yIJsnKMx/sXA="; pin-sha256="pJ9PrX4U+hWFvZYgO5Qo0PX4C+dnEo+R9p0ek+2ssDE="; pin-sha256="h6801m+z8v3zbgkRHpq6L29Esgfzhj89C1SyUCOQmqU=" max-age=2592000

**Comment by ivanr** [comment]
@florafrisia you have pinned three certificates from the same chain. As a result, you don't have any backup pins, which are mandatory for HPKP to be activated. (I plan to improve the presentation for this case to make it easier to understand what's going on.)

**Comment by florafrisia** [comment]
The same problem. I left the pis-sha256 fro the intermediate certificate out.

Incomplete   No chains pinned; check backup pins
pin-sha256="xN6JIS4n5cLnkk66mcq9+L/YC2qWxq8yIJsnKMx/sXA="; pin-sha256="h6801m+z8v3zbgkRHpq6L29Esgfzhj89C1SyUCOQmqU="; max-age=2592000

**Comment by ivanr** [comment]
You still have the same problem -- no backup pins. There has to be at least one pin that doesn't match the chain. The two pins you now have both match on the same chain.

**Comment by florafrisia** [comment]
Thanks

**Comment by tdesaules** [comment]
Hi,

At this time it work if you add the two same pin (I put two time my inter
cert just to test) strange !

Thank you
