### ISSUE TITLE
TLS 1.0 reported Yes when SNI-only site does not support TLS 1.0

### ISSUE THREAD

**Issue by iterop** [ssllabs/ssllabs-scan#690]
**Summary:**

The ssllabs report for site "cdn-a.dburd.org", accurately denotes at the top of the report:  "This site works only in browsers with SNI support"

Configuration:Protocols section denotes TLS 1.0 = Yes.  However, that hostname is not configured to support TLS 1.0 and openssl s_client confirms that TLS 1.0 connections are not supported with that hostname.

**Details:**

In previous similar cases, the no-SNI certificate was pointed as a source of confusion. This doesn't appear to be the case here.

I believe ssllabs intention is to not report, or score, measurements from a certificate which does not support the specified site hostname.  In this case "cdn-a.dburd.org" is serviced by a multi-tenant provider that also services a default no-SNI certificate which does support TLS 1.0 but does not support the "cdn-a.dburd.org" hostname.  This hostname mismatch of the no-SNI certificate is what leads to the accurate ssllabs note at top of the report: "This site works only in browsers with SNI support", thus the no-SNI TLS negotiation measurements should not be included in the report for the site "cdn-a.dburd.org" or effect its overall score.

Also note that TLS 1.1 is correctly denoted "No" in the report.  The site "cdn-a.dburd.org" is configured to not support TLS 1.1, while the multi-tenant default no-SNI certificate is configured to support TLS 1.1 - yet accurately ignored in the report for "cdn-a.dburd.org".

So where does the TLS 1.0 = Yes come from?  A bug in the reporting code?  How will this effect the overall grading of the site under test (particularly important when TLS 1.0 is considered a lower grade)?

**Investigations:**

To reduce clutter I'll paste only the openssl command and interpreted results below (feel free to run the commands on your own - the site was created to investigate this issue):

Connecting to the site cdn-a.dburd.org at 23.61.195.9:

openssl s_client -connect 23.61.195.9:443 -servername cdn-a.dburd.org -tls1_2
_YES (CN=cdn-a.dburd.org)_
openssl s_client -connect 23.61.195.9:443 -servername cdn-a.dburd.org -tls1_1
_NO_
openssl s_client -connect 23.61.195.9:443 -servername cdn-a.dburd.org -tls1
_NO_

Connecting to an IP where cdn-a.dburd.org and thousands of other hostnames are serviced in multi-tenant fashion (thus are not relavent to the report for cdn-a.dburd.org):

openssl s_client -connect 23.61.195.9:443 -tls1_2
_YES (CN=a248.e.akamai.net)_
openssl s_client -connect 23.61.195.9:443 -tls1_1
_YES (CN=a248.e.akamai.net)_
openssl s_client -connect 23.61.195.9:443 -tls1
_YES (CN=a248.e.akamai.net)_
 
SSLlabs results under Configuration/Protocols:
_TLS 1.2 = Yes
TLS 1.1 = No
TLS 1.0 = Yes_

Saved PDF of sslabs report: [SSL-Server-Test_cdn-a.dburd.org.pdf](https://github.com/ssllabs/ssllabs-scan/files/2881333/SSL-Server-Test_cdn-a.dburd.org.pdf)

**Conclusion:**

The report inaccurately denotes TLS 1.0 = Yes, it should be TLS 1.0 = No for this site.

**Comment by tamthing** [comment]
We appreciate your detailed investigation report on this. We will come back once we verify the results.

**Comment by tsasakiventuretech** [comment]
Another evidence:

When I test the server, the SSL Server Test evaluates the TLSv1.0 is available, for example,
https://www.ssllabs.com/ssltest/analyze.html?d=www.runza.com&hideResults=on

However, when I do the check with nmap linux command, only TLSv1.2 is available.
nmap www.runza.com -p 443 --script ssl-enum-ciphers
Starting Nmap 7.70 ( https://nmap.org ) at 2019-05-02 10:48 CDT
Nmap scan report for www.runza.com (107.23.128.138)
Host is up (0.044s latency).
rDNS record for 107.23.128.138: ec2-107-23-128-138.compute-1.amazonaws.com

PORT STATE SERVICE
443/tcp open https
| ssl-enum-ciphers:
| TLSv1.2:
| ciphers:
| TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp256r1) - A
| TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (secp256r1) - A
| TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (secp256r1) - A
| TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 (secp256r1) - A
| compressors:
| NULL
| cipher preference: server
| warnings:
| Key exchange (secp256r1) of lower strength than certificate key
|_ least strength: A

Nmap done: 1 IP address (1 host up) scanned in 2.37 seconds

**Comment by iterop** [comment]
The hostname posted by @tsasakiventuretech follows the same pattern as my example.

That "www.runza.com" hostname is hosted by another multi-tenant provider that utilizes SNI to support per customer certificates and TLS configurations.  That provider also services a default no-SNI certificate which is configured to support TLS 1.0 & TLS 1.1 but does not support the per customer SNI based hostnames.

The resulting SSL labs report also shows TLS 1.0 as YES, with TLS 1.1 as NO for the "www.runza.com" hostname - when it should be TLS 1.0 = NO and TLS 1.1 = NO for that hostname.  Using openssl commands, the resulting pattern is the same as my example.

@tamthing, thank you for looking into this issue. Let me know if there's any additional information I can provide to help resolve the issue.

**Comment by tamthing** [comment]
While the above observations made are correct, there is a miss which wasn't obvious initially. On the scan result page, if you hover over the **Yes** text corresponding to **TLS 1.0** it highlights with the following text:
_TLS 1.0 support observed only with client that does not support Server Name Indication._

It becomes apparent then that the TLS 1.0 support is for clients that does not support SNI. Also, it should be noted that for this scenario, the no SNI TLS 1.0 support does not affect the overall grade of the scan result. I hope that clarifies the doubt.

**Comment by iterop** [comment]
@tamthing, It's good to hear that the backend is evaluating the status correctly, however I believe there is sufficient evidence that users are misinterpreting the results from the report.

The SSL Labs tool is beneficial to the web community as it strives to provide end users with clear, concise and accurate evaluation of there site in terms of TLS security.  As a representative of a multi-tenant provider, I have seen numerous cases where customers run a SSL Labs report on their hosted site and question the provider as to why TLS 1.0 = YES when they have disabled it in their configuration.  This particular issue is increasingly important with customers using SSL Labs reports as part of their PCI audit preparation and process - (where TLS 1.0 is disabled for PCI DSS 3.2 compliance).

While this ticket can be shared with customers as a reference to help explain the discrepancy, I think it would be more beneficial for everyone involved to make some changes to the report so that the results are more clearly understood.

In specific response to the hover text you referenced:
1.  There is unfortunately no indication to the user that *there is* hover text (tooltips commonly utilize dotted underlines to indicate hover text)
2.  A PDF of the report, potentially used when submitting documentation for auditing purposes, does not include the hover text
3.  There remains an unexplained inconsistency in the report where TLS 1.1 is denoted as "NO" when the non-SNI certificate supports TLS 1.1 - this is different behaviour than TLS 1.0 results

In lieu of the hover text, it might be less ambiguous to the user if the non-SNI measurements were omitted from the site report when dealing with an SNI only hostname, or were presented in an entirely different section, with clear language denoting that such measurements are not relevant to an SNI only hostname.

Thanks again for your collaboration in regards to this matter.

**Comment by tamthing** [comment]
@iterop , your suggestion is appreciated and noted. We would look forward to how we can improve the visibility of the scan result.
