### ISSUE TITLE
https://www.ssllabs.com/ssltest/viewMyClient.html - "Connection is not secure"

### ISSUE THREAD

**Issue by szsahin** [ssllabs/ssllabs-scan#694]
When i tried to test my browser capability from "https://www.ssllabs.com/ssltest/viewMyClient.html" page, I noticed that page is not fully secure. I tried to reach this page from Firefox(52.9), Opera(58.0.3135.65), SRWare Iron(71.0.3700.0), Microsoft Edge and all resulted the same.

Root cause of the problem is this:
"http://plaintext.ssllabs.com/plaintext/1x1-transparent.png?t=1550836271100"

There is a http link in a https page. This is not necessarily a bug but a defect.

Fyi,

**Comment by seccubus** [comment]
The page contains a 'Mixed contents' test. Hence it needs to mix secure and insecure content.

It even says so on the page:
```
(1) These tests might cause a mixed content warning in your browser. That's expected.
```

**Comment by szsahin** [comment]
Thank you for the information. I missed the info.
