### ISSUE TITLE
supportsAead & implementsTLS13MandatoryCS Missing From API Docs

### ISSUE THREAD

**Issue by adamcaudill** [ssllabs/ssllabs-scan#695]
The [EndpointDetails](https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md#endpointdetails) documentation doesn't include `supportsAead` & `implementsTLS13MandatoryCS`, which are currently being returned from the API - if possible, it would be great to have these added, so that we can be sure these fields mean what we think they mean.

(Thanks again for the great work you all do on the API & docs - it really is appreciated!)

**Comment by naumanshah03** [comment]
Thanks for bringing this to our notice. Updated the API document :)
