### ISSUE TITLE
Please change default

### ISSUE THREAD

**Issue by JK-STFC** [ssllabs/ssllabs-scan#697]
Please can you change your Server Test default so that "Do not show the results on the boards" is automatically checked/ticked?

I made this request a year or 2 back and you agreed it should be changed, but then it has now come back to being de-selected and hence will effectively advertise your server's capabilities.

**Comment by yashks** [comment]
We dont have plan to change Default settings. User can select if they dont want result to display on site. 

Regards,
Yash K.S
