### ISSUE TITLE
Receiving error 529 ServiceOverloaded

### ISSUE THREAD

**Issue by vries294** [ssllabs/ssllabs-scan#698]
Since last Tuesday we receive an error 529, which means ServiceOverloaded. 

Call:
Invoke-RestMethod https://api.ssllabs.com/api/v3/analyze?host=<URL>

Respons:
![image](https://user-images.githubusercontent.com/14274401/54822765-ef52b300-4ca5-11e9-872e-e285aa5c1641.png)

**Comment by tamthing** [comment]
If the server returns error 529 (Server overload), it means the server is currently processing the maximum permissible assessments and that it cannot proceed with any further assessment until resources become available again. Under this scenario, it is advised to try calling the API again after some time. This is mentioned in https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md#access-rate-and-rate-limiting

Regarding the domain that you specified in the above link, I tried and initially I received the same error response but later on retry, the server was able to scan the domain and I received the correct response. Please let us know if this resolves your issue.

**Comment by tamthing** [comment]
If the server returns error 529 (Server overload), it means the server is currently processing the maximum permissible assessments and that it cannot proceed with any further assessment until resources become available again. Under this scenario, it is advised to try calling the API again after some time. This is mentioned in https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md#access-rate-and-rate-limiting

Regarding the domain that you specified in the above link, I tried and initially I received the same error response but later on retry, the server was able to scan the domain and I received the correct response. Please let us know if this resolves your issue.

**Comment by tamthing** [comment]
Assuming that your issue has been resolved.
