### ISSUE TITLE
dev.ssllabs.com gives 0 for key exchange while 100 is given by www.ssllabs.com

### ISSUE THREAD

**Issue by simondeziel** [ssllabs/ssllabs-scan#70]
https://dev.ssllabs.com/ssltest/analyze.html?d=sdeziel.info&hideResults=on key exchange:0
https://www.ssllabs.com/ssltest/analyze.html?d=sdeziel.info&hideResults=on key exchange:100

I couldn't find why the dev version is unhappy about my server.

Thank you!

**Comment by ivanr** [comment]
That was a bug, which is now fixed. What I _wanted_ to do is mark DH parameters < 1024 bits insecure. Instead, I effectively treated the DH key exchange as insecure..

**Comment by simondeziel** [comment]
Thanks for the quick fix and the excellent product!
