### ISSUE TITLE
TLS 1.0 reported as "No", but wget and openssl can connect with TLS 1.0

### ISSUE THREAD

**Issue by oheister** [ssllabs/ssllabs-scan#701]
https://www.ssllabs.com/ssltest/analyze.html?d=secure.rentalcars.com&hideResults=on
reports "TLS 1.0: No"

But
wget --secure-protocol=TLSv1 https://secure.rentalcars.com
and
openssl s_client -connect secure.rentalcars.com:443 -tls1
are able to connect with TLS 1.0

**Comment by naumanshah03** [comment]
Thank you for reporting. We will update soon.

**Comment by naumanshah03** [comment]
Hi @oheister 

Tested with the above command shared by you and I can't connect to https://secure.rentalcars.com with TLS 1.0

Also, tested by forcing only TLS 1.0 version on Mozilla Firefox 66.0.2.

OpenSSL version used for testing: OpenSSL 1.0.1e-fips 11 Feb 2013
Wget version used for testing: 1.12

Please update us on this since SSL Labs is displaying the correct result

**Comment by oheister** [comment]
Hi @naumanshah03 

I attached the output from OpenSSL 1.0.2k-fips  26 Jan 2017.
[openssl.txt](https://github.com/ssllabs/ssllabs-scan/files/3047659/openssl.txt)
I guess it depends on the supported ciphers of the client.

**Comment by oheister** [comment]
I also now configured Firefox 66.0.2 (64-bit) security.tls.version.max = 1 and could connect with TLS 1.0:
![firefox](https://user-images.githubusercontent.com/281672/55625186-54c79900-57a8-11e9-8f15-070df7181ec7.png)

Maybe they use different TLS configs for different regions. Which IP adress do you see in e.g. wget log? We could check this by creating a local HOSTS entry for the domain and testing again.
(If it really depends on the region then we can close this issue.)

**Comment by oheister** [comment]
Using https://dnschecker.org/#A/secure.rentalcars.com I could confirm that it's depeniding on the region.
From e.g. USA it's resolved to IP 91.206.233.34 which does not allow TLS 1.0.
From e.g. Europe it's resolved to IPs 54.77.224.13 and 63.34.114.239 which do allow TLS 1.0.
So it's not a bug in SSLLabs.
