### ISSUE TITLE
Encrypted SNI support detection in the web server

### ISSUE THREAD

**Issue by ilhansubasi** [ssllabs/ssllabs-scan#702]
The tool doesn't check whether server supports ESNI or not. I wish I was able to see whether the server supports ESNI. I know my Firefox supports ESNI by enabling `network.security.esni.enabled`.

More info: https://blog.cloudflare.com/encrypt-that-sni-firefox-edition/

**Comment by naumanshah03** [comment]
Hi @ilhansubasi 

ESNI is still in a draft mode so we will wait for it to complete and then analyze it to include it in SSLLabs server assessment test.

Regards,
Nauman Shah
