### ISSUE TITLE
Client result vs server result "rating" coloring 

### ISSUE THREAD

**Issue by RobTho** [ssllabs/ssllabs-scan#704]
It would be nice to see AEAD ciphers in green (good)  and "TLS 1.1" in yellow (weak)

also on client test https://www.ssllabs.com/ssltest/viewMyClient.html
and user Agent capabilities (Details) e.g 
https://www.ssllabs.com/ssltest/viewClient.html?name=Chrome&version=70&platform=Win%2010&key=153

so that they have same color "Rating" like at Server result

Thanks

**Comment by RobTho** [comment]
as well (this also still exists in SSL Report v1.34.2) should "handshake simulation" results not also show same coloring like in  "configuration" > "cipher suites does" ?

**Comment by naumanshah03** [comment]
@RobTho, SSL Labs version 1.35.1 client and server test color result is in sync

We will look into the handshake simulation part later. Please create a separate ticket for the handshake simulation issue.
