### ISSUE TITLE
Certificate name is case sensitive

### ISSUE THREAD

**Issue by marcomarsala** [ssllabs/ssllabs-scan#709]
Common Name is case insensitive by specs, but the tool treats them as case sensitive:

https://www.ssllabs.com/ssltest/analyze.html?d=fe.thenetworksolution.it

says “Certificate name mismatch”

**Comment by tamthing** [comment]
Your certificate doesn't have Subject Alternatives Name(SAN), although it does have the Common Name (CN). You should set the SAN. For instance, in Chrome 58 and later, only the subjectAlternativeName extension, not commonName, is used to match the domain name and site certificate.

https://support.google.com/chrome/a/answer/7391219?hl=en

As far as the case sensitivity is concerned, there is no issue on the SSL Labs side.
