### ISSUE TITLE
Favor AEAD ciphers

### ISSUE THREAD

**Issue by ouaibe** [ssllabs/ssllabs-scan#71]
As per a passed discussion thread on SSLLab's community https://community.qualys.com/thread/14192 the server cipher strength rating should favor GCM-based suites even if they have a lower key length than the CBC ones.

**Comment by ivanr** [comment]
Please use the issue tracker only to discuss bugs and features, but not grading criteria. I'll open a discussion about grading in a couple of months time and we'll talk about it on the ssllabs-discuss mailing list. In the meantime, I am closing this ticket as invalid. Sorry!
