### ISSUE TITLE
EXPIRED Certificate but "A" rating

### ISSUE THREAD

**Issue by beerisgood** [ssllabs/ssllabs-scan#715]
See https://www.ssllabs.com/ssltest/analyze.html?d=www.aachener-bank.de

Certificate #2 have expired cert but got still a good rating.

**Comment by tamthing** [comment]
Hi @beerisgood , the current grading algorithm only checks for first certificate for trust issues like expiry, revocation, name mismatch etc. We have plans to upgrade to a [new](https://community.qualys.com/docs/DOC-6321-ssl-labs-grading-2018) grading version where all certificates except (No SNI certificate) will be checked for the good grades. As a note, your certificate #2 is a non-SNI certificate.

For a similar report, please check https://community.qualys.com/message/39998-re-certificate-expired-and-not-expired-linkedin
