### ISSUE TITLE
Certificate expiry date not accurate

### ISSUE THREAD

**Issue by teamojo** [ssllabs/ssllabs-scan#718]
When I test quality.org, ssllabs fails the site and tells me the web certificate is expired.
Yet, when I open the site in the browser (either Chrome or FF), the certificate appears to have been renewed. Is this likely to be a bug, caching issue or some other explanation?
![Screenshot_3](https://user-images.githubusercontent.com/51291722/58762668-08030300-854a-11e9-9a31-8697296c35b6.png)
![Screenshot_2](https://user-images.githubusercontent.com/51291722/58762578-169cea80-8549-11e9-93c7-b6473b2ca370.png)

**Comment by naumanshah03** [comment]
Hi @teamojo,

For the URL provided by you i.e quality.org, the result produced by SSL Labs is correct. The certificate hosted on quality.org (217.182.143.44) has expired.

In browser why it is not seen as expired,

- Open developer tool on Chrome and navigate to Network tab, open quality.org
- It can be observed that there is redirection from quality.org (217.182.143.44) to www.quality.org (34.250.222.175)
![image](https://user-images.githubusercontent.com/22236992/58781356-499eb700-85f9-11e9-810e-4221721e8aca.png)
![image](https://user-images.githubusercontent.com/22236992/58781372-4f949800-85f9-11e9-9d39-f85458ab668e.png)
- Here the browsers are considering the redirected domain's certificate i.e https://www.quality.org

On the other hand, SSL Labs scans the domain given to it i.e quality.org which is also hosted on HTTPS protocol
If you wish to reproduce the certificate error in Chrome/Firefox then please open https://quality.org

Adding screenshot for reference,
![image](https://user-images.githubusercontent.com/22236992/58781454-85d21780-85f9-11e9-8ae7-72940742fa34.png)
![image](https://user-images.githubusercontent.com/22236992/58781480-984c5100-85f9-11e9-84da-1b06603bc4a8.png)

If you're looking for the result where SSL Labs shows the valid certificate result like browser's then click [here](https://www.ssllabs.com/ssltest/analyze.html?d=www.quality.org&hideResults=on)

If you've any query on the explanation then please ask

Regards,
Nauman Shah

**Comment by teamojo** [comment]
Thanks for the quick response Nauman.
That all makes sense.
