### ISSUE TITLE
/api/v3/getClients is very outdated

### ISSUE THREAD

**Issue by april** [ssllabs/ssllabs-scan#719]
The `getClients` API result is getting quite outdated at this point.

The latest Firefox it returns in Firefox 62, released nine months ago. For Chrome, it's Chrome 70, also about nine months ago. It used to be updated with almost every browser release, but there have been a huge number of changes in the browsers since then and none of that is currently reflected in `getClients`.

Thanks!

**Comment by naumanshah03** [comment]
@april please use dev.ssllabs.com v1.35.3

We have added a couple of new user agents

**Comment by tomato42** [comment]
@naumanshah03 I'm getting permission errors when trying to connect to it
