### ISSUE TITLE
SSL Poodle not in api result

### ISSUE THREAD

**Issue by andrepereiradasilva** [ssllabs/ssllabs-scan#72]
Hi ivan,

I didn't found the Poodle SSL vulnability test in SSL Scan Api, only found "poodleTls".
https://api.ssllabs.com/api/v2/analyze?host=ssllabs.com&all=done

Neither in the API documentation:
https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs.md

But that result is on the html version of the scan
https://www.ssllabs.com/ssltest/analyze.html?d=ssllabs.com&hideResults=on
"POODLE (SSLv3)	No, SSL 3 not supported (more info)"

Is this the way it should work?
If so, how do the online test calculate the poodle ssl vulnerability?

**Comment by nextPrime** [comment]
Actually you just need to check if the server supports SSL 3.0 or not, which is available in the API.

**Comment by andrepereiradasilva** [comment]
Ok, so if SSLv2 or/and SSLv3 = Vulnerable to Poodle, right?

**Comment by selecadm** [comment]
No, SSL 2 isn't vulnerable to POODLE, and SSL 3 also can be not vulnerable.

https://www.ssllabs.com/ssltest/analyze.html?d=eircom.net
This server supports SSL 2, which is obsolete and insecure. Grade set to F.
SSL 3	No
SSL 2   INSECURE	Yes
POODLE (SSLv3)	No, SSL 3 not supported

Interesting thought: https://community.qualys.com/thread/14767#27820

https://www.ssllabs.com/ssltest/analyze.html?d=google.com&s=74.125.239.96
This server uses SSL 3, which is obsolete and insecure. Grade capped to B.
POODLE (SSLv3) No, mitigated

**Comment by moheshmohan** [comment]
Hi Iavn, 

Yes I too have the same request, please make it available on the API. 

I think the online tool assess the server as mitigated if another cipher from SSL v3 is given preference over one with CBC mode.

But this is not reflected on the API results, and can we get this anytime soon?

**Comment by AshleyPoole** [comment]
It would be nice that within the DETAILS object if there were a sub object which contained just these type of vulnerabilities. This would allow an API consumer to loop through these looking for issues like Poodle or Heartbleed, etc.

**Comment by ivanr** [comment]
@AshleyPoole that will be added in a future revision.

**Comment by AshleyPoole** [comment]
@ivanr Thanks for the update. Looking forward to it. It there another issue tracking this particular request or is it combined with this request?

**Comment by ivanr** [comment]
Added to 1.16.8, now running on development servers.
