### ISSUE TITLE
OpenSSL 1.1.1 in Handshake Simulation

### ISSUE THREAD

**Issue by tomato42** [ssllabs/ssllabs-scan#720]
Since OpenSSL 1.1.1 supports TLS 1.3, has been shipped by a number of distributions and is the implementation used by Python, Perl, curl, etc. on most of them, having it as one of the compatibility targets is important from API point of view.

**Comment by tamthing** [comment]
Hi @tomato42 , yes we would be adding it to our list of handshake simulation soon.

**Comment by naumanshah03** [comment]
@tomato42 please use dev.ssllabs.com v1.35.3
We have added a couple of new user agents which also performs the simulation.

OpenSSL 1.1.1c is added as requested

**Comment by tomato42** [comment]
cool, thanks

there is a slight problem with it though: I've filed #726 to track ti

**Comment by tomato42** [comment]
Side note, are you _sure_ that openssl 1.1.1 in _default_ compile enables SSL 3? That's not my recollection, but would have to check the sources to be sure...
