### ISSUE TITLE
TLS 1.3 is a standard (not experimental any more)

### ISSUE THREAD

**Issue by emanruse** [ssllabs/ssllabs-scan#722]
Since August 2018 TLS 1.3 is a standard and should not be marked by the scan tool as experimental:

https://tools.ietf.org/html/rfc8446

**Comment by andrew-aitchison** [comment]
The linked page is marked "Category: Standards Track" and links to a errata at https://www.rfc-editor.org/errata_search.php?rfc=8446 
Thus https://tools.ietf.org/html/rfc8446 suggests that TLS1.3 is not yet a standard.

**Comment by emanruse** [comment]
Hm. I may be wrong but older RFCs (which are standards and which this RFC obsoletes/updates) also link to errata:

https://tools.ietf.org/html/rfc6961
https://tools.ietf.org/html/rfc5705
https://tools.ietf.org/html/rfc6066

Wikipedia also lists 1.3 in standards:

https://en.wikipedia.org/wiki/Transport_Layer_Security#Standards

**Comment by RobTho** [comment]
Maybe SSLABS mark it as experimental, as the test itself is in experimental stage, not the TLS 1.3 !?

**Comment by emanruse** [comment]
> Maybe SSLABS mark it as experimental, as the test itself is in experimental stage, not the TLS 1.3 !?

Makes no sense. A protocol is either supported or not.
What could be experimental about 0 or 1?

**Comment by RobTho** [comment]
Maybe the SSLLABS test function is not declared as stable and could result wrong result when test for TLS 1.3 !?

**Comment by emanruse** [comment]
I don't know. Too many maybes :)
Perhaps someone better confirm.

**Comment by Ruffio** [comment]
1.3 is a standard: https://en.m.wikipedia.org/wiki/Transport_Layer_Security

**Comment by RobTho** [comment]
see e.g here
the TEST ITSELF is experimental! (a security issue cannot be experimental)
https://community.qualys.com/message/29454?commentID=29454#comment-29454
https://community.qualys.com/message/33697?commentID=33697#comment-33697
https://community.qualys.com/message/22929?commentID=22929#comment-22929

As well it Point to FINAL RFC 8446!
"Experimental: This server supports TLS 1.3 (RFC 8446). "

so "Experimental (**TEST**): This server supports TLS 1.3 (RFC 8446). "
**not** "This server supports TLS 1.3 (**Experimental**). "

**Comment by emanruse** [comment]
So the confusion comes from the wording.

Assuming that TLS 1.3 is a standard, if the test is experimental the right action would be:

1. To be explicit that the test itself is experimental
2. To actually fix the test, so that it is not experimental but fully 1.3 capable.

IOW: the issue still needs to be resolved properly.

**Comment by naumanshah03** [comment]
Hello,

We've removed the experimental and RFC 8446 keyword for TLS 1.3. The TLS 1.3 tests were experimental hence we had used the word Experimental in summary.
Changes are now deployed on production www.ssllabs.com version 2.1.3

Regards,
Nauman Shah
