### ISSUE TITLE
False positive on openssl-based server for GOLDENDOODLE / Sleeping Poodle

### ISSUE THREAD

**Issue by ekangas1** [ssllabs/ssllabs-scan#724]
On investigating a report from a customer, we discovered that many of our servers running non-http services (sendmail and imap, for example) are showing vulnerability to GOLDENDOODLE / Sleeping Poodle.  I.e.

https://www.ssllabs.com/ssltest/analyze.html?d=email1029.luxsci.com&hideResults=on

I was surprised by this as the servers are patched RedHat Linux boxes using openssl as the back-end SSL library and openssl is not listed on these sites as typically vulnerable to these issues.

I checked the same server using another testing service:

https://www.immuniweb.com/ssl/?id=iwCczVxv

and it shows the same server on the same port as NOT being vulnerable to these -- so perhaps there is some false positive error on the scan here.

**Comment by naumanshah03** [comment]
Duplicate #741
