### ISSUE TITLE
Safari 12.1.2 / MacOS 10.14.6 Beta | negotiates chacha20 in test AES_GCM in practice

### ISSUE THREAD

**Issue by Razerwire** [ssllabs/ssllabs-scan#725]
At [www.bonnieradvocaten.nl](https://www.bonnieradvocaten.nl) we've implemented CHACHA20 prioritization for those clients that have CHACHA20 (0xcca8) at the top of their list in the ClientHello message (please note, that we do not support TLS 1.3 as of yet). 
When clients prefer the AES based (0xc030) cipher this Cipher-Suite is chosen. 

This works perfectly fine in practice. 
I've tested and verified this using Chrome / Chromium on a couple of devices without a AES instruction set, and (as expected) 0xcca8 is negotiated upon. 

When testing on devices that _do_ support AES-acceleration -  and thus prefer (0xc030) - 0xc030 is used, as is expected. 

**The problem:**
The handshake simulation for "_Safari 12.1.2 / MacOS 10.14.6 Beta R_" shows that 0xcca8 (CHACHA20) is chosen, even-though this client - according to the [User-Agent Capabilities  ](https://dev.ssllabs.com/ssltest/viewClient.html?name=Safari&version=12.1.2&platform=MacOS%2010.14.6%20Beta&key=161) - prefers 0xc030 (AES_256_GCM) and thus should use 0xc030 with our server. 

For you're convenience I've include  a [link](https://dev.ssllabs.com/ssltest/analyze.html?d=www.bonnieradvocaten.nl) to the (erroneous) results 

If you need any additional info please let me know. 

Regards,
Razerwire

**Comment by nayankakati** [comment]
Hi @Razerwire : Is this still valid ?

**Comment by nayankakati** [comment]
Hi @Razerwire :
The user agent capabilities now are shown as prefers (TLS_CHACHA20_POLY1305_SHA256 (0x1303))
https://dev.ssllabs.com/ssltest/viewClient.html?name=Safari&version=12.1.2&platform=MacOS%2010.14.6%20Beta&key=161

Closing this issue - please feel free to reopen 
--
