### ISSUE TITLE
sslcheck has a very long Duration for robpjewell.com

### ISSUE THREAD

**Issue by robskrob** [ssllabs/ssllabs-scan#728]
I'm very confused as to why some sites take only a few minutes (grandlife.com) while others take a very long time, such as -- robpjewell.com

in executing the command line script `./ssllabs-scan-v3 -grade -verbosity debug robpjewell.com` the sslcheck has been running for almost 35 minutes:
```
$ ./ssllabs-scan-v3 -grade -verbosity debug robpjewell.com
2019/06/26 20:40:32 [DEBUG] Request #1: https://api.ssllabs.com/api/v3/info
...
2019/06/26 21:15:35 [DEBUG] Response #416 status: HTTP/1.1 200 OK
```

I'm checking this against your site `https://www.ssllabs.com/ssltest/analyze.html?d=robpjewell.com&hideResults=on&latest` and so far it's been 15 minutes and `ssllabs.com/ssltest/analyze.html` has still not finished.

What explains the sslcheck duration disparity -- grandlife.com vs robpjewell.com ?

And is there any way to sensibly decrease the time it takes for the command line script to finish with its report?

**Comment by naumanshah03** [comment]
Hi Rob,

SSL Labs server tests are completed dependent on the response from the server. If the response time is slow then one can expect the report to appear late. We request you to please check the server response time to SSL Labs

As mentioned previously the result is totally dependent on the response time of the server, there is no way we can speed up the command line script. Once the scan is complete the tool will display the result.

PS: As observed robpjewell.com assessment result is produced in 71.412 seconds

Let me know if you need more information.

Regards,
Nauman Shah

**Comment by naumanshah03** [comment]
Closing the issue because the issue was actually observed at servers end
