### ISSUE TITLE
Provide ability to specify IP for analysis

### ISSUE THREAD

**Issue by rustyx** [ssllabs/ssllabs-scan#730]
It would be very useful if I could provide an alternative IP address for my domain, this way I could test my deployment before switching over the DNS to the new IP.

**Comment by naumanshah03** [comment]
Hi @rustyx 

We have no plans on adding IP scanning in SSL Labs. SSL Labs only supports scanning for public servers i.e server running on port 443 and with a DNS entry

Please refer to this comment by Robert - https://community.qualys.com/message/40642-specifying-both-a-domain-ip-address-to-test#comment-40661

Regards,
Nauman Shah
