### ISSUE TITLE
All TLS 1.0 ciphers are disabled but the sslabs-scan still showing TLS 1.0 as "yes".

### ISSUE THREAD

**Issue by Farhanfdema** [ssllabs/ssllabs-scan#732]
All TLS 1.0 ciphers are disabled but the sslabs-scan still showing TLS 1.0 as "yes". Understood that there are no handshakes to make to TLS 1.0 ciphers, but why is it still showing YES?

**Comment by naumanshah03** [comment]
Please share the domain name.

You can share it with me as a personal message [here](https://community.qualys.com/people/nshah)

**Comment by naumanshah03** [comment]
Thanks for sharing the domain name for assessing the result.

> On the scan result page, if you hover over the Yes text corresponding to TLS 1.0 it highlights with the following text:
> TLS 1.0 support observed only with client that does not support Server Name Indication.
Quoted from https://github.com/ssllabs/ssllabs-scan/issues/690#issuecomment-490231155

To confirm you can use openssl and connect with the commands mentioned,

1. Forcing TLS 1.0 and providing servername i.e SNI, result in the connection fails.
`openssl s_client -connect mtlms-dot-pitc-shared-dev.appspot.com:443 -servername mtlms-dot-pitc-shared-dev.appspot.com -tls1`
2. Forcing TLS 1.0 with no servername i.e SNI, result in the connection is successful
`openssl s_client -connect mtlms-dot-pitc-shared-dev.appspot.com:443 -tls1`

We request you to please check your configuration.
