### ISSUE TITLE
Assertion failures

### ISSUE THREAD

**Issue by netdefilr** [ssllabs/ssllabs-scan#733]
When scanning my server that returns 3 ip addresses in a round robin format, ssllabs will show the 3 ip addresses and scan them. It will eventually show results. As it continues to update this page, those results might vanish. Then when you select the server to review the results it might show an Assertion error where there's no results for the host. Clicking back, to look at the other hosts might refresh and it looks like its still scanning the servers even though it was already completed.

This behavior was never seen in ssllabs before. I noticed these issues last week and are still there today. I've been a long term ssllabs user and never had these experiences before last week.

**Comment by naumanshah03** [comment]
This behaviour is not expected in SSL Labs. Please share the domain name for us to assess the issue if it still persists for you.

You can share the domain name as a personal message [here](https://community.qualys.com/people/nshah) or [here](https://community.qualys.com/people/tamthing)

**Comment by naumanshah03** [comment]
@netdefilr is this still an issue for you?

**Comment by naumanshah03** [comment]
Closing the issue as no response received from user
