### ISSUE TITLE
X25519 90%

### ISSUE THREAD

**Issue by concatime** [ssllabs/ssllabs-scan#734]
Hi. My website currently supports only x25519 and secp384r1, but SSLabs reports 90% in key exchange. Is there an inherent issue with x25519?

**Comment by naumanshah03** [comment]
Please refer to the rating guide for key exchange [here](https://github.com/ssllabs/research/wiki/SSL-Server-Rating-Guide#key-exchange)

Also, refer to this [thread](https://community.qualys.com/thread/17641-ssllabs-key-exchange) to get 100% for key exchange

**Comment by ArchangeGabriel** [comment]
@concatime x25519 is ~2048 bits equivalent, so according to the table linked above it indeed rates 90% at most. You want x448 instead to have 100%.

**Comment by concatime** [comment]
ECDH x25519 is rather 3072 bit, but still under 4096, so 90% makes sens. Thank you!
