### ISSUE TITLE
Checking wrong server

### ISSUE THREAD

**Issue by pmodiano** [ssllabs/ssllabs-scan#735]
I ask it to look at www.logicaldevelopers.com.  That A record points to 54.165.247.96, yet it is scanning my mail server, which is mail.logicaldevelopers.com.

**Comment by naumanshah03** [comment]
As checked it is correctly scanning the server with IP 54.183.83.117 when www.logicaldevelopers.com is scanned.

We request you to please check again.

If the issue persists please share the complete information to assess the issue.
