### ISSUE TITLE
BEAST attack link is wrong

### ISSUE THREAD

**Issue by syquus** [ssllabs/ssllabs-scan#736]
On protocol details section, the tool shows this row:

BEAST attack | Mitigated server-side ([more info](https://community.qualys.com/blogs/securitylabs/2013/09/10/is-beast-still-a-threat?_ga=2.174891812.704516617.1565255916-1813856913.1563374251))
That URL is obsolete and should use the [new one](https://blog.qualys.com/ssllabs/2013/09/10/is-beast-still-a-threat)

Regards

**Comment by tamthing** [comment]
Thank you for reporting, we would look into it.

**Comment by naumanshah03** [comment]
To give an update we are in the process of fixing it - https://discussions.qualys.com/thread/20109-problems-with-renegotiation-testing-on-ssl-labs-reports#comment-48649

For now, please the new link that you've mentioned.

Duplicate of #745
