### ISSUE TITLE
Miscellaneous section of ssltest shows wrong info

### ISSUE THREAD

**Issue by mushu999** [ssllabs/ssllabs-scan#739]
Scan  agr.wa.gov  and see the "Server hostname" URL in the bottom section says  cms.agr.wa.gov  and I'm wondering where that data is coming from because the canonical URL is actually  agr.wa.gov  and the site does a redirect from  www.agr.wa.gov  anyway. See screenshot here:

![screenshot-www ssllabs com-2019 08 12-10-55-32](https://user-images.githubusercontent.com/11066472/62886671-6f7ac300-bcf0-11e9-9a06-6e7edaef08f5.png)

**Comment by naumanshah03** [comment]
SSL Labs performs a reverse IP lookup this way the Server hostname is populated

Please run the following command:
> nslookup 198.239.147.123

The above command returns the following result:

> Server:		192.168.244.2
> Address:	192.168.244.2#53
> 
> Non-authoritative answer:
> 123.147.239.198.in-addr.arpa	name = cms.agr.wa.gov.
> 123.147.239.198.in-addr.arpa	name = agrwboly600.agr.wa.gov.

**Comment by naumanshah03** [comment]
@mushu999 closing the issue since there has been no response from you and the server configuration has been updated to show the desired information
