### ISSUE TITLE
Safari 6 / iOS 6.0.1 — reference

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#74]
https://dev.ssllabs.com/ssltest/analyze.html?d=ssllabs.com
Safari 6 / iOS 6.0.1  R	TLS 1.2	TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA (0xc013)   FS	128

https://dev.ssllabs.com/ssltest/viewClient.html?name=Safari&version=6&platform=iOS%206.0.1

— No BEAST mitigation
— No ServerKeyExchange verification (goto fail)
— Supports NULL encryption
— No session tickets and OCSP stapling
— Accepts all mixed content

Web-servers should send a handshake failure or TCP Reset to this client for its own safety. Why "reference"?

**Comment by ivanr** [comment]
Reference is chiefly driven by client popularity. It means that a client is relevant, even if it's insecure.

**Comment by selecadm** [comment]
— FREAK attack also

> Reference is chiefly driven by client popularity. It means that a client is relevant, even if it's insecure.

<= iOS 6 market share is 3%

![image](https://cloud.githubusercontent.com/assets/10382329/6542351/d1055fe0-c506-11e4-864b-1c9f92764e9d.png)

OpenSSL 0.9.8 is also popular, but isn't reference because of no ECDHE support, so that ECDHE + static RSA servers (like google.com) get PFS with modern browsers.

**Comment by ivanr** [comment]
If so, then OpenSSL 0.9.8 should also be made a reference client. I suppose you're referring to its use in Android?

**Comment by selecadm** [comment]
No, OpenSSL 0.9.8 shouldn't be reference because ECDHE servers get Forward Secrecy "with some browsers" instead of "with modern browsers". Wouldn't it be better to check whether a server provides PFS to all ECDHE clients?

My point is that server admins should care about providing security to at least somehow secure clients. How can one provide security to a client that doesn't even verify ServerKeyExchange? It is similar to Server Gated Cryptography, when obsolete clients get 128-bit encryption without taking into account their vulnerabilities. Have seen some SGC-certificates with SHA2 signatures. Ha-ha, doesn't Symantec want to warn their clients that SGC-browsers don't support SHA2? Money and stupidity…

iOS 6 support is a security theater. I would even reward the servers that drop such connections.

**Comment by ivanr** [comment]
If OpenSSL 0.9.8 is indeed used widely, then it is important that sites use DHE suites to provide forward secrecy (for observers: this older version of OpenSSL doesn't support ECDHE). In that light, it's probably a bug that OpenSSL 0.9.8 is not considered a reference client. I will need to do some research to see if a change should be made.

As for Safari iOS 6.x, I am keeping it as a reference client for now and until its usage goes away.

**Comment by ivanr** [comment]
Perhaps we need two types of "reference" browsers; one to use to judge interoperability of a configuration and another to indicate modern clients. I think this is a good way forward.
