### ISSUE TITLE
False positive on Windows IIS server for Zombie Poodle/ GOLDENDOODLE 

### ISSUE THREAD

**Issue by ThomasTrain** [ssllabs/ssllabs-scan#741]
SSL Labs scans are repeatedly issuing false-positive failures on multiple fully patched and non-vulnerable Windows IIS based websites for Zombie Poodle / Golden Poodle / OpenSSL 0-Length, none of which are actual vulnerabilities on these hosts.

The same sites are scanned by other scanners properly.

**Comment by roycewilliams** [comment]
For testing purposes, could you cite a public example?

**Comment by ThomasTrain** [comment]
Here is a good example: of a public server failing on ssllabs but passing on immuniweb.

https://www.ssllabs.com/ssltest/analyze.html?d=email1029.luxsci.com&hideResults=on
vs
https://www.immuniweb.com/ssl/?id=iwCczVxv

**Comment by ThomasTrain** [comment]
Here is another example of two identically configured servers at the same patch levels:  one passed SSL labs and one failed SSL Labs with the same protocols and ciphers enabled.  Yet both passed the immuniweb tests.

**Comment by ThomasTrain** [comment]
Update - as soon as I enabled HTTP/2 on the second server that was failing but with no other cipher changes, the second server is now also reporting a pass.

**Comment by ThomasTrain** [comment]
Once I enabled HTTP/2 on the second server, but left all of other ciphers in place, the false-positive failures went away. So there is something wrong with the http 1.1 scanning tripping a false-positive.

https://www.ssllabs.com/ssltest/analyze.html?d=webmail.swafnet.com&hideResults=on

**Comment by emanruse** [comment]
Another test:

https://expeditedssl.com/poodle

And another way to test:

https://nmap.org/nsedoc/scripts/ssl-poodle.html

The false positive is also

**Comment by nayankakati** [comment]
Hi All,
We have deployed a potential solution for this and deployed the same in www.ssllabs.com v2.1.4
please check and confirm

Thanks
