### ISSUE TITLE
Empty issuer DN not allowed in X509Certificates

### ISSUE THREAD

**Issue by artsmm** [ssllabs/ssllabs-scan#744]
Hi

I have the following issue when testing my website:
"Empty issuer DN not allowed in X509Certificates".

I have a valid certificate by Sectigo installed on Nginx.
My site can be accessed through https and all other tools confirm it having a valid certificate.

What could it be and how I fix it?

**Comment by tamthing** [comment]
Can you tell us your domain with this certificate that you tried to scan? If it is private, you can message me on https://discussions.qualys.com/people/tamthing or https://discussions.qualys.com/people/nshah

**Comment by tamthing** [comment]
On no-sni connection to your server, it returns a self-signed certificate which has no CN value. You should give a valid value for the mandatory fields. Although most modern clients supports sni, SSLLabs perform detailed analysis to detect any misconfiguration. Once you fix this on your end, you should be able to scan on our site successfully. Let me know if this fixes your issue.

**Comment by tamthing** [comment]
Closing this issue as there is no response from the reporter.
