### ISSUE TITLE
404 Errors - Links to more info on your website

### ISSUE THREAD

**Issue by Undefined-Variables** [ssllabs/ssllabs-scan#745]
Just to inform you the links that give more information on known vulnerabilities upon completing a certificate scan are all going to 404 page not found, I tried to email  you at the email address given with the 404 but it came back to me with unknown  domain (dhnylf.com). Thought you might be unaware of the issue.

**Comment by naumanshah03** [comment]
To give an update we are in the process of fixing it - https://discussions.qualys.com/thread/20109-problems-with-renegotiation-testing-on-ssl-labs-reports#comment-48649

**Comment by FranklinYu** [comment]
@tamthing Please also redirect from the old URL to the new one. This way other websites (including Google) citing the old source will find its new home.

**Comment by tamthing** [comment]
The link redirection issue has been fixed.
