### ISSUE TITLE
Assessment failed: No secure protocols supported 

### ISSUE THREAD

**Issue by gjuric** [ssllabs/ssllabs-scan#75]
I was testing [a domain](https://www.ssllabs.com/ssltest/analyze.html?d=hide.me) that used to report normally before and now it returns the message from the subject.

I am pretty sure that that the error message is wrong since the site works and is accessible from all major browsers.

**Comment by ivanr** [comment]
Is that link correct, or is the hostname you used just a placeholder? Because it works right now. If the message "No secure protocols supported" is obviously incorrect, it's usually an indication that the server is blocking access from SSL Labs.

**Comment by gjuric** [comment]
The link is correct, I have tested it once again before posting this issue and now again (the pages says: "Assessed on:  Fri Mar 06 08:41:47 PST 2015") and I get the same error.

To many tries could trigger a firewall block, but I have been trying for last 2 days and I always get the same result.

I will try the go client now.

**Comment by ivanr** [comment]
Do you know for a fact that there's a firewall that monitors rate access? We have 4 nodes in the SSL Labs cluster; it's possible that I am assigned to one that can still access the server.

**Comment by ivanr** [comment]
But we have only one development server. Here's a working link: https://dev.ssllabs.com/ssltest/analyze.html?d=hide.me

**Comment by gjuric** [comment]
I just checked, there are no blocks in place, nor have they ever been on the https port.

**Comment by gjuric** [comment]
Tnx, please remove that link so it is not public.
