### ISSUE TITLE
Only ipv4 scan

### ISSUE THREAD

**Issue by aden7072** [ssllabs/ssllabs-scan#752]
For domains with multiple ip addresses, only scanning ipv4 addresses will ensure that scanning does not take longer. Looking forward to this feature.

**Comment by josephcsible** [comment]
This isn't a good idea. If you're not going to scan all of the IP addresses, then why not just remove multiple IP support altogether and just scan one? Plus, it's a step in the wrong direction if we want to eventually move the world to IPv6.

**Comment by naumanshah03** [comment]
This is an invalid request. All the resolved IPs for a domain will be scanned irrespective of it being an IPv4 or IPv6
