### ISSUE TITLE
SSL Server test fails for haveibeenpwned.com

### ISSUE THREAD

**Issue by rherstein** [ssllabs/ssllabs-scan#755]
I get a "Certificate name mismatch" error, and a link is then shown:"Click here to ignore the mismatch and proceed with the tests".  Upon clicking that link, an identical error as before is shown.

**Comment by tamthing** [comment]
Currently, we are experiencing scanning issues with Cloudflare-hosted domains. This is also being tracked on the community discussion https://discussions.qualys.com/thread/20235-failed-to-obtain-certificate-cloudflare

We will update further once we resolve the issue.

**Comment by dxgldotorg** [comment]
Could Cloudflare be deliberately blocking your scans?

**Comment by roycewilliams** [comment]
Unlikely - from the thread that @tamthing cites, it appears to be a testing mismatch issue.

**Comment by naumanshah03** [comment]
This issue has been fixed and deployed on dev.ssllabs.com v1.36.3

https://dev.ssllabs.com/ssltest/analyze.html?d=haveibeenpwned.com&hideResults=on&latest
Soon it will be deployed on www.ssllabs.com

**Comment by naumanshah03** [comment]
Update: Change is now available on www.ssllabs.com v1.36.3
