### ISSUE TITLE
The aliasses in SSL certificates are not recognized.

### ISSUE THREAD

**Issue by BethkePeter** [ssllabs/ssllabs-scan#756]
we have some customer working with cloudflare. In their SSL certificates are the aliases for the customer within. For example ww.logitel.de. I think with the latest Verson v1.36.2 the aliases are not 
not recognized. 

![www logitel de](https://user-images.githubusercontent.com/1373872/67668257-e0388f80-f96f-11e9-8ea6-b81ee049f5a3.jpg)

**Comment by mozdevcontrib** [comment]
I've the same issue with two sites. **[intr0.com](https://intr0.com/) & [iosprivacy.com](https://iosprivacy.com)**

**Comment by naumanshah03** [comment]
This issue has been fixed and deployed on dev.ssllabs.com v1.36.3

https://dev.ssllabs.com/ssltest/analyze.html?d=www.logitel.de&hideResults=on&latest
Soon it will be deployed on www.ssllabs.com

**Comment by naumanshah03** [comment]
**Update:** Change is now available on www.ssllabs.com v1.36.3
