### ISSUE TITLE
feature request: use Cipher Suite colors in Handshake Simulation section

### ISSUE THREAD

**Issue by roycewilliams** [ssllabs/ssllabs-scan#758]
It would be very useful to see at a glance if a cipher suite in the Handshake Simulation section is strong (green), OK (black), or weak (orange).

As initially discussed [here](https://discussions.qualys.com/thread/18431-feature-request-use-cipher-suite-colors-in-handshake-simulation-section?et=watches.email.outcome).

**Comment by RobTho** [comment]
also see
here https://github.com/ssllabs/ssllabs-scan/issues/717
and https://github.com/ssllabs/ssllabs-scan/issues/704

**Comment by roycewilliams** [comment]
Closing as duplicate of #704 / #717
