### ISSUE TITLE
Typo on HTTP 529 Error Code

### ISSUE THREAD

**Issue by nathan-hook** [ssllabs/ssllabs-scan#759]
Thanks for such a great api.  It is very useful and appreciated.

One small thing, my guess is that the error code that is returned when the server is busy should be 429 and not 529.

[429 Too Many Requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429).

[529 doesn't exist in the http spec](https://developer.mozilla.org/en-US/docs/Web/HTTP/status).

Thank you for your time.

**Comment by siccovansas** [comment]
According to the [SSL Labs API documentation](https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md#access-rate-and-rate-limiting):

> If the server is overloaded (a condition that is not a result of the client's behaviour), the 529 status code will be used instead. This is not a situation we wish to be in. If you encounter it, take a break and come back later.

**Comment by naumanshah03** [comment]
@nathan-hook this is a custom status code defined for SSL Labs hence we won't be fixing it.
