### ISSUE TITLE
Please Add CORS header to allow Javascript requests

### ISSUE THREAD

**Issue by tdelmas** [ssllabs/ssllabs-scan#76]
Please consider adding this header to the JSON API response : 
Access-Control-Allow-Origin: *
This header allow any origin to read the answer. Since the API doesn't used cookies, there is no security implications.

**Comment by ivanr** [comment]
So you're basically asking to enable the API to be used from browsers? What do you want to do with that ability?

**Comment by tdelmas** [comment]
Yes, it was the objective. I was thinking about building a simple static webpage who could use the API in javascript, but if you are not comfortable with this idea, I can put the logic in the back-end.

**Comment by ivanr** [comment]
No, I am simply trying to understand the need for such a feature. If we allow browser access to the APIs there will be no taking back later, and I wish to understand where the feature would be heading. Is the effort worth it? For example, anyone who wishes to access the SSL Labs API using their browser can already do that on the SSL Labs web site.

About your asking if I am comfortable with the idea: we have our terms and conditions where we specify how we'd like our APIs to be used. But, as a rule of thumb, that generally won't affect how the API is being developed and what features are added. Indirectly, perhaps: for example, if a feature is needed only for a use we're not interested in, I am not going to work on it :)

**Comment by tdelmas** [comment]
The basic idea was to provide an help for websites owners to check their infrastructure in a simple way, like www.ssllabs.com , but with some other feature, like dns check, redirects, headers, more HPKP checks, CSP hints... 
The idea was to build it in javascript, with call to APIs points (mine and others) to get the needed information, and using javascript (and some libs like https://github.com/travist/jsencrypt ) to make the information clear, and give hints to help correcting flaws.
But after a second read on the terms and conditions, I believe they forbid it...

**Comment by ivanr** [comment]
It's only against the terms if you put the software on a public web site. It's not if you publish the code as open source so that people can install it themselves.

However, most of the additional features you listed will actually be added to SSL Labs fairly soon. I updated the public to-do list yesterday: https://community.qualys.com/docs/DOC-5077

**Comment by tdelmas** [comment]
The idea was to build a public website, but with the incoming improvements,
a link to ssllabs will be enough, thank you ! You can consider the issue
closed.

Tom Delmas
