### ISSUE TITLE
webserver with mutual authentication are detecetd as revoked certificates

### ISSUE THREAD

**Issue by michaelsstuff** [ssllabs/ssllabs-scan#763]
Hi,

i scanned one of our webserver, which has mutual authentification (forced), and ssllabs ssltest showed that the Revocation status is Revoked

The same cert (wildcard cert) is on another webserver without mutual auth, and there it was fine.

Cheers
Michael

**Comment by naumanshah03** [comment]
Please share the domain name for us to assess the issue. Share both the domain names. You can also share it as a personal message [me](https://discussions.qualys.com/people/nshah)
Also please elaborate on how the mutual authentication is achieved on your server.

**Comment by michaelsstuff** [comment]
urgh.. shame on me. As I was to create a new webserver to recreate the issue for you, I noticed that our cert was actually revoked, but the browsers just ignored it.
So thank you for your amazing tool and sorry to bother you! :-)
