### ISSUE TITLE
MSIE 8 on XP cannot even reach ssllabs.com - even less so testing it's capabilities

### ISSUE THREAD

**Issue by NipLars** [ssllabs/ssllabs-scan#765]
Hi
Been trying to upgrade xp with 256-bit AES - an seems to work to a degree.
I get checkboxes and all for TLS 1.1 and TLS 1.2 and still not reaching your site.

I am using wininet.dll in my software and it goes by settings for internet through MSIE8.

So overall in search what is missing - I get 12157 using my own software towards place it needs to work. It uses TLS 1.2 only - but get the feeling something is not all right somehow.

So I thought I test towards you guys - and not even reaching site.
Something is strange then, I think.
Regards
NipLars

**Comment by naumanshah03** [comment]
As per the error code 12157 of MS IE 8 it says the following
> ERROR_INTERNET_SECURITY_CHANNEL_ERROR
> 12157
> The application experienced an internal error loading the SSL libraries.

Here is the client capability of the IE 8 as captured by SSL Labs long back - https://www.ssllabs.com/ssltest/viewClient.html?name=IE&version=8&platform=XP&key=101
As seen it only supports either insecure or weak ciphers suites.

Here is the configuration of www.ssllabs.com - https://www.ssllabs.com/ssltest/analyze.html?d=www.ssllabs.com&hideResults=on
SSL Labs supports some strong cipher suites as seen from the result.

I suspect even though you've updated IE 8 it is still using some cipher suites which are not supported by SSL Labs.
I would recommend you to use a better version than IE 8 to connect with www.ssllabs.com.

Reference: https://docs.microsoft.com/en-us/windows/win32/wininet/wininet-errors?redirectedfrom=MSDN

Regards,
Nauman Shah

**Comment by NipLars** [comment]
Thanks for response.
The idea to visit ssllabs.com was to figure out what was supported - and that idea fails if that site only supports the highest rated ciphers to start with, if you are to test something you got as a client.

My machine worked just fine until servers of a stock broker updated their servers - so doing development on this machine until it dies was the attempt upgrading and see capabilties why it still didn't work this upgrade to TLS 1.2. I've been doing that for 15 years on this machine now.

I've ran wininet.dll since 1996.

So to test IE8 and see what it does now and where it fails dispite upgrade was the mission. Is it handshake or something else like missing ciphers.

Finding other sites, i managed to see running only TLS 1.0 as original it works, but new upgrade TLS 1.2 does not fall back to TLS 1.0 correctly it seems.

Just some feedback - if to allow browsers people have tested - it kind of missing the point if your servers have only support for highest rated ciphers. You cannot even enter the site - to test anything.

I can use Opera v36 to enter - but it does use WinHttp as well above wininet.dll - and I need to get wininet to see the upgraded TLS 1.2 and troubleshoot that.

Everything works on Windows 7 and up - just extending life of perfectly healthy XP machine. And might be some customers also having XP still and find how this upgrade should be done to have our software run still. So two dimensions to this.

Just FYI....

**Comment by naumanshah03** [comment]
> Just some feedback - if to allow browsers people have tested - it kind of missing the point if your servers have only support for highest rated ciphers. You cannot even enter the site - to test anything.

We will be working on this one soon since we have plans on disabling TLS 1.0 and TLS 1.1 in the near future for SSL Labs by which only a few clients would be able to perform client tests.
Please refer to this ticket - #372 and #505

**Comment by nayankakati** [comment]
As Stated by @naumanshah03 : we have worked on this and it is deployed on production.
Thanks
