### ISSUE TITLE
SSLLabs sometimes tests different hostname than what was submitted.

### ISSUE THREAD

**Issue by koyowork** [ssllabs/ssllabs-scan#769]
SSLLabs sometimes tests a different hostname than what I submitted to be tested. The first time I encountered this issue, it gave a .ch address. I was able to resubmit the test, and it appeared to resume with the correct hostname where it would have left off if I hadn't exited the testing page of the incorrect hostname. Then, several minutes later, when testing another hostname, it again showed it testing a different hostname than the one that I submitted (ftconsumer.ipaydevx.com).
![ssllabs_bug3](https://user-images.githubusercontent.com/59655511/71988620-d2b44700-31f5-11ea-82a8-a7fd51827ae3.jpg)

**Comment by koyowork** [comment]
When I submitted the currservices.ipaydevx.com url again, it now gave me another different url.
![ssllabs_bug2](https://user-images.githubusercontent.com/59655511/71987417-c0390e00-31f3-11ea-9bd1-0524c0dbe868.jpg)

**Comment by koyowork** [comment]
Here is another run, trying to test another domain (ftbusiness.ipaydevx.com).
![ssllabs_bug4](https://user-images.githubusercontent.com/59655511/71992255-ba92f680-31fa-11ea-9f9c-3517c8a78c0d.jpg)

**Comment by koyowork** [comment]
Here is another run (nextbusiness.ipaydevx.com).
![ssllabs_bug5](https://user-images.githubusercontent.com/59655511/71995591-74d92c80-3200-11ea-80eb-f30cd3b600f4.jpg)

**Comment by koyowork** [comment]
And another run for nextbusiness.ipaydevx.com, right after the one that gave me kensicocapital.com. Before when I would go back and run it the second time, it would give the correct site on the second try.
![ssllabs_bug6](https://user-images.githubusercontent.com/59655511/71996002-15c7e780-3201-11ea-9150-d83825a46031.jpg)

**Comment by tamthing** [comment]
We are looking into this issue. Appears like a bug at our end. This would be fixed at the earliest. Thank you for reporting.

**Comment by Jas0n99** [comment]
Yes, I noticed this issue recently too... Occurred maybe one out of every 4 or 5 tests... Would start out with the site I entered, but as it was refreshing it would jump to a different one.

**Comment by digitaltoast** [comment]
Same here - tried to test bwbf.org.uk, but it ended up testing www.apinkellogg.com

**Comment by dausruddin** [comment]
Can confirm. Happened to me a lot today. There is no point hiding the domain if the server going to pop it out to random user :/

**Comment by pebbledavec** [comment]
Same here. Respectfully, I'd suggest rolling back to a stable version. Revealing fqdns users might not want others to be aware of should be considered a security issue.

**Comment by nayankakati** [comment]
Hi All,
We have fixed this issue and it is in the production, Kindly test.
Thanks

**Comment by Jas0n99** [comment]
Seems fixed! No issues since @nayankakati made his post.
