### ISSUE TITLE
Extra certificates with SHA-1 incorrectly results in "Intermediate certificate"-warning

### ISSUE THREAD

**Issue by KommX** [ssllabs/ssllabs-scan#77]
Example:
https://dev.ssllabs.com/ssltest/analyze.html?d=mercedes-benz-bank.de

They deliver the cert with Fingerprint: 32f30882622b87cf8856c63db873df0853b4dd27 with SHA-1 signature. But this cert isn't used in the trusted path.
So the "extra cert"-warning is ok, but I think it's not okay to say:
"Intermediate certificate has a weak signature. When renewing, ensure you upgrade to an all-SHA2 chain."

**Comment by selecadm** [comment]
This is a very common problem for sites with VeriSign certificates. Customers still receive the intermediate that chains to already distrusted 1024-bit root. Ridiculous!
https://community.qualys.com/thread/14754

**Comment by ivanr** [comment]
Generally speaking, it's impossible to say what trusted path is used. For example, if SSL Labs doesn't know of a particular root, it won't trust a path that terminates with it. For that reason, SSL Labs warns on the certificates sent by the server, even in the cases when a certificate is not used in any of the paths (we could construct).
