### ISSUE TITLE
Assessment failed: Unable to connect to the server 

### ISSUE THREAD

**Issue by Sami32** [ssllabs/ssllabs-scan#770]
https://www.ssllabs.com/ssltest/analyze.html?d=www.dismail.de&hideResults=on

This website is accessible so i'm wondering if it is because they asked you to not permit you to scan them or they have set their firewall to block you?

It will weird because they use your tools for their emails providers comparison page claiming that they are the safest...

Any idea?

Regards,

**Comment by naumanshah03** [comment]
Hi @Sami32 

They have not asked us to blacklist their domain from scanning on SSLLabs. You can use this URL to check for Blacklisted domain - https://www.ssllabs.com/ssltest/blacklistCheck.html?d=www.dismail.de

Currently, I'm not able to reproduce this issue. I suspect it might have been an issue with their server because of some network issues.
I request you please rescan the domain on www.ssllabs.com.

Regards,
Nauman Shah

**Comment by Sami32** [comment]
Thank you for the tip.

That is said i still get the same issue.
Maybe they blocked scan only from some countries?

**Comment by Sami32** [comment]
Could you post a snapshop of the www.dismail.de scan result that i can see
their score?

Thank you.

**Comment by nayankakati** [comment]
Hi @Sami32 :
We are not able to reproduce this, please check the screenshot

<img width="889" alt="dismail de" src="https://user-images.githubusercontent.com/13463099/72317821-7acb8380-36c0-11ea-8bc7-1295067a73fb.PNG">

**Comment by Sami32** [comment]
It failed with Android 7.0 each time and with any browsers tried: Firefox, Brave, Opera

But it worked with a german browser using a german VPN.

So yes, something is making SSLLABS fail after 90%, at least on Xiaomi Android 7.0 outside of germany.

**Comment by Sami32** [comment]
Tested from my Android 7.0 smartphone with Firefox, Brave, Opera and Bromite browsers:

![Screenshot_2020-05-23-20-51-42-171_com opera browser](https://user-images.githubusercontent.com/18471069/82741119-5018c800-9d4f-11ea-81ac-43ce5f7c92df.jpg)
![Screenshot_2020-05-23-20-51-21-358_com opera browser](https://user-images.githubusercontent.com/18471069/82741121-54dd7c00-9d4f-11ea-800d-bf1ff972098f.jpg)
![Screenshot_2020-05-23-20-52-03-185_com brave browser](https://user-images.githubusercontent.com/18471069/82741123-56a73f80-9d4f-11ea-82d2-d5ccb707d889.jpg)
![Screenshot_2020-05-23-20-51-55-123_com brave browser](https://user-images.githubusercontent.com/18471069/82741127-5d35b700-9d4f-11ea-8a48-8725f545aab0.jpg)
![Screenshot_2020-05-23-21-00-05-205_org bromite bromite](https://user-images.githubusercontent.com/18471069/82741128-5eff7a80-9d4f-11ea-89b4-a73c57156e48.jpg)
![Screenshot_2020-05-23-21-00-51-552_org mozilla firefox](https://user-images.githubusercontent.com/18471069/82741129-63c42e80-9d4f-11ea-867e-860597cbf0c1.jpg)
