### ISSUE TITLE
[...]TLS 1.2, which is the only secure protocol version.

### ISSUE THREAD

**Issue by fuu0** [ssllabs/ssllabs-scan#772]
Hey,

when you test an webserver with TLS1.0 only, there is the Hint for "capped grade C":
> No support for TLS 1.2, which is the only secure protocol version.

I think this is ambiguous, because TLS 1.3 is also secure... 

Best regards, fuu0

**Comment by tamthing** [comment]
We are in the process of the revamping all the corner cases especially w.r.t. TLS 1.3. This will be noted. Thank you for reporting.

**Comment by naumanshah03** [comment]
Hi @fuu0 

We have updated the text for the message.
Please test and confirm it.

Regards,
Nauman Shah

**Comment by naumanshah03** [comment]
Closing the issue as the text has been fixed
