### ISSUE TITLE
HTTP request failed on IPv6 whereas curl works

### ISSUE THREAD

**Issue by moviuro** [ssllabs/ssllabs-scan#774]
Hi,

My [blog](https://try.popho.be) works fine on TLSv1.3 (only) for both IPv4 and IPv6; however both ssllabs and dev.ssllabs tell me that the HTTP request failed on IPv6.

* [www report](https://www.ssllabs.com/ssltest/analyze.html?d=try.popho.be&s=2001%3a470%3a7a83%3a7765%3a7472%3a7970%3a6f70%3a686f&hideResults=on)
* [dev report](https://dev.ssllabs.com/ssltest/analyze.html?d=try.popho.be&s=2001%3a470%3a7a83%3a7765%3a7472%3a7970%3a6f70%3a686f&hideResults=on)

curl however works correctly (`curl -6 https://try.popho.be`); and so does internet.nl ([report](https://internet.nl/site/try.popho.be/750102/#))

**Comment by naumanshah03** [comment]
Thank you for bringing this issue to our notice and sharing the domain name as it will help us with the analysis and quick resolution process.

Thanks,
Nauman Shah

**Comment by naumanshah03** [comment]
Hi @moviuro 

We've deployed the fix for it on dev.ssllabs.com version 2.1.1
You can verify it over [here](https://dev.ssllabs.com/ssltest/analyze.html?d=try.popho.be&s=2001%3a470%3a7a83%3a7765%3a7472%3a7970%3a6f70%3a686f&hideResults=on)
Thank you for bringing this case to our notice.

Regards,
Nauman Shah

**Comment by moviuro** [comment]
Excellent, thank you!

**Comment by naumanshah03** [comment]
Hi,

These changes are now deployed to production www.ssllabs.com version 2.1.3

Regards,
Nauman Shah

**Comment by moviuro** [comment]
Hi @naumanshah03 , looks broken to me? https://www.ssllabs.com/ssltest/analyze.html?d=try.popho.be&hideResults=on&latest

It fails after the "Determining supported named groups" step. Which is weird, because my other server doesn't seem to break the server test: https://www.ssllabs.com/ssltest/analyze.html?d=sco.popho.be&hideResults=on
