### ISSUE TITLE
SSL/TLS Capabilities of Your Browser

### ISSUE THREAD

**Issue by mushu999** [ssllabs/ssllabs-scan#775]
On your webpage:  https://clienttest.ssllabs.com/ssltest/viewMyClient.html

When using latest version of Chrome and Firefox browsers on a Windows 10 desktop the section for "OCSP Stapling" says "No" when both browsers actually do support it.

**Comment by naumanshah03** [comment]
@mushu999 as tested on my system running Windows 10 it shows **OCSP Stapling** as **Yes**
Chrome version - 79.0.3945.130
Firefox version - 72.0.2

Please see if you've disabled something on your system which leads to this result.

**Comment by mushu999** [comment]
I think someone there fixed the code, since I just went to that tab and refreshed and now it says Yes. I changed nothing on my system or in the browser...hmmm...
