### ISSUE TITLE
False Positive for  F5 virtual server triggering OpenSSL 0-Length, GOLDENDOODLE Zombie POODLE

### ISSUE THREAD

**Issue by IsmailAgip** [ssllabs/ssllabs-scan#778]
Hello Team,

We have been getting F rating for the below site intermittently (50%) they should always show A+ rating when using Qualys SSL Labs,

URLs:
destinationretirement-staging.tomasonline.co.uk
transferright-staging.tomasonline.co.uk

The F5 version is not vulnerable as mentioned on the F5 site, also the correct ciphers are being used to obtain A+ rating for our customer, other sites we have used to test are showing good rating, please add exception to this false positive or escalate this bug to the relevant team

F5: https://support.f5.com/csp/article/K10065173

I used the sites below to test and returned with correct result,

https://www.immuniweb.com/ssl/?id=U8H8HJpx
https://expeditedssl.com/poodle?

I have also used nmap looked over the VIP config and everything is in order, please let me know if you need additional information, you can always test the domains above and draw your own conclusion.

Many thanks

Ismail Agip

**Comment by michalmiddleton** [comment]
+1 
F5 , SSL terminating on device... same symptoms.

**Comment by markw78** [comment]
+1, same situation as above.

**Comment by nayankakati** [comment]
Hi All,

We have deployed a potential solution for this false positive, Please check and confirm 
www.ssllabs.com v2.1.4
Thanks
