### ISSUE TITLE
[v1.16.0] "Incorrect SNI alerts". Does it work?

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#78]
Development v1.16.0 has "Incorrect SNI alerts" parameter, but doesn't seem to warn about inconsistency.

I have checked my servers, both require SNI, but one of them refuses to speak when it sees a non-SNI client, and another supports Android 2 and IE 8 XP using an incorrect certificate. Both have "Incorrect SNI alerts -".

SNI sites should not provide a default certificate, and that's what "Incorrect SNI alerts" should warn about, right?

**Comment by drwetter** [comment]
Am 8. März 2015 18:26:44 GMT+04:00, schrieb selecadm :

>I have checked my servers, both require SNI, but one of them refuses to
>speak when it sees a non-SNI client,

I am curious: how do you do that?

**Comment by ivanr** [comment]
This feature is intended to detect a configuration problem where SNI-aware servers don't have the correct site name configured. The alert should appear only if the server serves a working certificate but also sends a SNI alert (warning) complaining that the site name is incorrect. This will break some clients, for example IE and Java.

**Comment by drwetter** [comment]
Am 9. März 2015 13:11:57 GMT+04:00, schrieb "Ivan Ristić" <notifications@github.com>:
>This feature is intended to detect a configuration problem where
>SNI-aware servers don't have the correct site name configured. The
>alert should appear only if the server serves a working certificate but
>also sends a SNI alert (warning) complaining that the site name is
>incorrect. This will break some clients, for example IE and Java.

 Yes, excuse me, Ivan. I meant to address my question to selecadm.

Cheers,  Dirk

**Comment by selecadm** [comment]
> I am curious: how do you do that?

A default host uses elliptic curve cryptography. If a client doesn't support SNI, then it also doesn't support ECDSA, so it gets handshake failure because of no common cipher suites.

> the server serves a working certificate but also sends a SNI alert (warning) complaining that the site name is incorrect

Is there any example?

**Comment by ivanr** [comment]
@selecadm by the way, there are clients that support SNI but don't support EC crypto. Until fairly recently, Red Hat operating systems shipped without EC. Just saying. I am not aware the the current generation of servers have reliable ways to reject non-SNI clients.

**Comment by selecadm** [comment]
@ivanr yeah, that RHEL case was discussed 10 days ago, can drive crazy: https://community.qualys.com/thread/14797

But this is often a server, not a client. And if it supports SNI without ECDSA, no problems connecting to virtual RSA-hosts.

If a client supports ECDSA without SNI, like old versions of Bing and Yahoo bots, then there is a problem, but I hope there is no more clients like this.

**Comment by ivanr** [comment]
I have been unable to test this further, but I just saw it correctly detected on a web site. So, it does work.
