### ISSUE TITLE
dev api seems to be offline

### ISSUE THREAD

**Issue by beamzer** [ssllabs/ssllabs-scan#780]
Hi, I use ssllabs-scan with the dev api, i.e.
`
./ssllabs-scan/ssllabs-scan -api https://api.dev.ssllabs.com/api/v3/ etc.
`
but this seems to be offline (it returns a 403). 
Is this temporary, of is there an other way to use the dev environment with ssllabs-scan ?

thanks in advance,
Ewald....

**Comment by naumanshah03** [comment]
Hi @beamzer 

API v3 is accessible for dev.ssllabs.com
dev.ssllabs.com is our development server and you can expect downtime for it since it is a work in progress.

Regards,
Nauman Shah
