### ISSUE TITLE
Getting an 'A' with TLSv1.0 enabled.

### ISSUE THREAD

**Issue by TopherIsSwell** [ssllabs/ssllabs-scan#782]
I'm not sure if this is related to Issue #686 , but I've disabled TLSv1.1 and not TLSv1.0 and found that SSLabs reports this correctly, however it seems to score it as though both are disabled (giving an A with full points for protocol support).
I wonder if the logic after finding TLSv1.1 disabled might be confused.

According to the messages, any support for TLSv1.1 or TLSv1.0 will have grades capped at 'B', seems like the logic is more along the lines of support for TLSv1.1 AND TLSv1.0 will be capped.

Is this a bug or intended behavior?

The web server has the directive ```SSLProtocol All -SSL2 -SSL3 -TLSv1 -TLSv1.1 +TLSv1.2``` however, I've found that this does not disable TLSv1.0, by testing with curl.

**Comment by tamthing** [comment]
Hi, it seems likely to me that it is a no-sni support. If you can share your domain, it would be easier to confirm. You can privately message if you wish to https://discussions.qualys.com/people/tamthing

**Comment by nayankakati** [comment]
@TopherIsSwell : we are closing this as there is no response from your end. Feel free to re-open if required.
Thanks
