### ISSUE TITLE
"currentAssessment" always 0

### ISSUE THREAD

**Issue by smuda** [ssllabs/ssllabs-scan#783]
It seems calls to  https://api.ssllabs.com/api/v3/info now always returns 0 for currentAssessments, for example:

```
{
   "engineVersion":"2.1.3",
   "criteriaVersion":"2009q",
   "maxAssessments":17,
   "currentAssessments":0,
   "newAssessmentCoolOff":1000,
   "messages":["This assessment service is provided free of charge by Qualys SSL Labs, subject to our terms and conditions: https://www.ssllabs.com/about/terms.html"]
}
```

Even calls to "analyze" contains HTTP header "X-Current-Assessments" with value 0:
```
 HTTP/1.1 200 
Date: Wed, 18 Mar 2020 06:16:04 GMT
Server: Apache
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Strict-Transport-Security: max-age=31536000
X-ClientMaxAssessments: 6
X-Max-Assessments: 6
X-Current-Assessments: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
```

Since these values are recommended to use not to overload SSLLabs, it's rather easy to get 529 or 429 when "currentAssessment" is always 0, especially on shared IPs where you have no control over other persons assessment.

**Comment by nayankakati** [comment]
It is currently in testing phase - will be out on production in few days.
Thanks

**Comment by nayankakati** [comment]
Hi @smuda : We have deployed the changes on https://dev.ssllabs.com/, can you please test and confirm.

Thanks

**Comment by smuda** [comment]
When testing against dev.ssllabs.com I always get a correct X-Current-Assessments. Thank you!
