### ISSUE TITLE
HTTP 529 Error response when using client

### ISSUE THREAD

**Issue by kristoferlandgren** [ssllabs/ssllabs-scan#784]
I'm using the client that via the the docker image provided here @ https://hub.docker.com/r/jumanjiman/ssllabs-scan

I'm getting 529 error codes on quite a few of my scans. Sometimes it helps to wait but sometimes it doesn't. These tests have been running for many months without failing but for the past few days it's been very shaky.

**Comment by naumanshah03** [comment]
Hi @kristoferlandgren 

This issue is because of the #783 

Regards,
Nauman Shah

**Comment by nayankakati** [comment]
Hi @kristoferlandgren : We have increased our server capabilities - can you please check once again 
Thanks

**Comment by kristoferlandgren** [comment]
Hi @nayankakati : It has been working the last week for me. Thanks for the update!

**Comment by nayankakati** [comment]
Thank you, I will close this issue, please re-open if required.
