### ISSUE TITLE
DNS CAA reported no, when it is set

### ISSUE THREAD

**Issue by kunosee** [ssllabs/ssllabs-scan#785]
When there is a website, where the hostname is a CNAME in DNS there is no possibility to have a CAA parallel to this host.  As there is no other data allowed to an CNAME.
https://letsencrypt.org/docs/caa/
The CAA is set on that host, where the CNAME is pointing to.  This is the only possible setting in DNS.

However in this cases the server test reports:  "DNS CAA no"

**Comment by nayankakati** [comment]
Hi @kunosee :
Can you provide the domain, so that we can test it.
Thanks

**Comment by naumanshah03** [comment]
Similar issue reported earlier,

https://github.com/ssllabs/ssllabs-scan/issues/665

**Comment by naumanshah03** [comment]
@kunosee Please share the domain in a personal message [here](https://discussions.qualys.com/people/nshah) if you're not comfortable with sharing the domain name in public

Also, steps to reproduce will be appreciated.

Thanks and Regards,
Nauman Shah

**Comment by naumanshah03** [comment]
@kunosee Please share the domain so that we can assess the issue and fix it.

**Comment by naumanshah03** [comment]
@kunosee We are yet to receive a domain name to proceed further with your request

**Comment by naumanshah03** [comment]
Closing the issue as no response received from the user
