### ISSUE TITLE
Internal Error

### ISSUE THREAD

**Issue by parhamPudding** [ssllabs/ssllabs-scan#788]
Hello 
I get Internal Error every time, when I try to get/scan my sites by API.
I get the correct answer, every time, when I try to scan my site in the browser by this url: 
URL : https://api.dev.ssllabs.com/api/v2/analyze?host=xxx&publish=off&startNew=on&fromCache=off&ignoreMismatch=off

But I get Internal error all the time, if try to use the scan api in my php code.
*** If I scan one of my sites in browser then in my php code, I get the correct answer. I think 
"startNew" doesn't work, when I use scan in my php code.

Steps(1):
1) call api : https://api.dev.ssllabs.com/api/v3/analyze?host=xxxxxxx&publish=off&startNew=on&fromCache=off&ignoreMismatch=off
2) wait 90 sec
3) call api : https://api.dev.ssllabs.com/api/v3/analyze?host=xxxxxxx&publish=off&startNew=on&fromCache=on&ignoreMismatch=off
3) I get internal Error 

Steps (2):
1) [Browser]  call api : https://api.dev.ssllabs.com/api/v3/analyze?host=xxxxxxx&publish=off&startNew=on&fromCache=on&ignoreMismatch=off
1) [PHP Code] : call api : https://api.dev.ssllabs.com/api/v3/analyze?host=xxxxxxx&publish=off&startNew=on&fromCache=on&ignoreMismatch=off
2) wait 90 sec
3) call api : https://api.dev.ssllabs.com/api/v3/analyze?host=xxxxxxx&publish=off&startNew=on&fromCache=on&ignoreMismatch=off
3) I get correct answer

**Comment by markroland** [comment]
I am having this same exact issue.

I check my sites monthly on the 1st day of the month and didn't have this problem on 3/1/2020, so I think it was introduced after that date.

**Comment by lordkitsuna** [comment]
I am getting this same issue both on the API and just the web tool. It appears to die at the "determining available ciphers" stage.

**Comment by Prophet731** [comment]
I've also been getting this error through the API.

**Comment by nayankakati** [comment]
Hi @parhamPudding : Is it happening only on PHP code? Have you tried the same using CURL command?
On testing from CURL I have not faced any issues. Can you share your PHP code along with the domain?

Thanks

**Comment by parhamPudding** [comment]
I have fixed that and its working by CURL.

**Comment by nayankakati** [comment]
Hi @parhamPudding : Can you please tell us - what did you fix, it will be helpful for others?

**Comment by parhamPudding** [comment]
I hope I can help others. 
https://github.com/parhamPudding/SslLabAPIV3-helper/tree/master

**Comment by nayankakati** [comment]
Thank you @parhamPudding

**Comment by smuda** [comment]
I got rid of the "Internal Error" problem by setting the Connection header to "close" instead of "Keep-Alive".
That's why it works nicely with curl.

**Comment by markroland** [comment]
Thanks @parhamPudding. I modified my PHP script to use your CURL configuration options and it worked.

**Comment by kellermatthis** [comment]
Hi, I still have the same problem, but in C#, not php.
 _restClient.DefaultRequestHeaders.ConnectionClose = true; 
did not work. Does anyone have any suggestions? 
Kind regards, Matthis

**Comment by smuda** [comment]
@kellermatthis What I did was to use netcat as a webserver to compare the headers between my request and the curl request. Perhaps that's a way for you too?

`
nc -l 8080
`
to make netcat listen to the request.

**Comment by nayankakati** [comment]
Hi All,
We have found a potential bug for some clients, hence we will come up with a fix and deployment by next week.
Thanks

**Comment by nayankakati** [comment]
Hi All,
We have deployed a fix on de.ssllabs.com, Please check and confirm.

**Comment by nayankakati** [comment]
Hi All,
We have deployed the latest build to www.ssllabs.com with the above issue fix for all.

Thanks

**Comment by kellermatthis** [comment]
Hi, thanks! I can confirm - it works for me fine again.
Kind regards
