### ISSUE TITLE
HTTP request failed: Get https://api....: EOF

### ISSUE THREAD

**Issue by frnkblk** [ssllabs/ssllabs-scan#79]
I run the script daily out of cron.daily and received no output.  When I ran it manually today I received 
2015/03/09 09:14:04 [ERROR] HTTP request failed: Get
https://api.ssllabs.com/api/v2/analyze?host=www.unitedcommunitybank.com&all=
done&fromCache=on&maxAge=24: EOF

This is the syntax of the command I run:
/usr/local/bin/ssllabs-scan -grade -usecache=true -maxage=24 -hostfile="/tmp/cert.txt" -quiet=true > /tmp/ssllabs-scan.log 2>&1

/tmp/cert.txt has 249 hosts today.

root@node7:/etc/cron.daily# /tmp/go/bin/go version
go version go1.3.3 linux/386
root@node7:/etc/cron.daily#

Frank

**Comment by frnkblk** [comment]
This continues to plague us.

**Comment by ivanr** [comment]
Could you please try the latest version in the repository? That version shouldn't use keep alives. It should address the problems you're seeing until I am able to properly troubleshoot them.

**Comment by frnkblk** [comment]
Thanks.  I've compiled that release now and am running the script.  One successful run is not telling, so I will report back on Monday.

**Comment by ivanr** [comment]
Closing for now. We'll implement keep-alives as a performance optimization in the future.

**Comment by frnkblk** [comment]
Had this failure yesterday:
2015/03/17 07:44:35 [ERROR] HTTP request failed: Get https://api.ssllabs.com/api/v2/analyze?host=mail.hopehaven.org&all=done&fromCache=on&maxAge=24: EOF
and this one today:
2015/03/18 08:28:02 [ERROR] HTTP request failed: Get https://api.ssllabs.com/api/v2/analyze?host=webmail.aoacademy.com&all=done&fromCache=on&maxAge=24: EOF

**Comment by ivanr** [comment]
I am having trouble understanding how you'd get that error "EOF" with the latest ssllabs-scan version. With that error, it should try up to 5 times, then print a different error. Is it possible that you're not running the latest version for some reason?

In my tests, keep-alives are no longer used so Go shouldn't be returning EOF. Could you please upgrade to the latest ssllabs-scan version 1.0.0 and switch to the dev server (--api=https://api.dev.ssllabs.com/api/v2) where I can monitor your activity in real-time?

**Comment by frnkblk** [comment]
You are correct, the script was not using the new binary.  That's now fixed -- sorry for the confusion.

**Comment by obayesshelton** [comment]
Hi,

I am also getting this issue, I have cloned and pulled the latest code from master and v1.0.0 both give me this error. I have ran 'go clean' then 'go build' before running it after each branch pull

**Comment by J0WI** [comment]
@ivanr Please notify me when I can switch back to the stable api.
