### ISSUE TITLE
Instagram disallow URL with this SSL

### ISSUE THREAD

**Issue by Phunkky** [ssllabs/ssllabs-scan#792]
Instagram says the web URL is not allowed, with this SSL. Tried to add my web URL to my instagram profile and it said link not allowed.

**Comment by naumanshah03** [comment]
Hi @Phunkky 

Please elaborate on your query. It seems more like an issue or restriction from Instagram rather than an issue with SSLLabs.

Regards,
Nauman Shah

**Comment by naumanshah03** [comment]
No response received from the user hence closing it
