### ISSUE TITLE
Assessment failed: Directive already specified: max-age

### ISSUE THREAD

**Issue by amaciasf** [ssllabs/ssllabs-scan#793]
Hi! Thanks for your work.

With SSL Report v2.1.4 I get "Assessment failed: Directive already specified: max-age" when the scanner goes by 94% (Simulating handshakes) and stop.

Instead, 4 days ago with SSL Report v2.1.3 it worked correctly but I have not changed anything on the server.

Regards!

**Comment by Prophet731** [comment]
Also getting the same error on one of our domains.

**Comment by naumanshah03** [comment]
Please share the domain name for assessment of the issue.

**Comment by amaciasf** [comment]
> Please share the domain name for assessment of the issue.

traveler.consorseguros.info

**Comment by naumanshah03** [comment]
@Prophet731 please the domain name for which you're facing an issue.
Done the assessment on domain shared by @amaciasf and found the cause. Looking forward to the other domain to see if we have any other possibility of failure case.

**Comment by Prophet731** [comment]
@naumanshah03 

The domain is `panel.scalematrix.com`. That's the only one that seems to be failing the assessment.

**Comment by amaciasf** [comment]
It appears to be related to HSTS header with time zero or less.

**Comment by slclose** [comment]
Getting the same for: simplyyou.simplyhealth.co.uk

**Comment by carmelina2** [comment]
I'm also getting this result (on repeated testing over a number of days) for https://blog.westernstatesmetalroofing.com/

**Comment by naumanshah03** [comment]
All the domains shared by you all have been acknowledged

**Comment by naumanshah03** [comment]
Changes have been deployed to dev.ssllabs.com version 2.1.5

Please test it.

**Comment by slclose** [comment]
Dev version working for simplyyou.simplyhealth.co.uk.

**Comment by IIPoliII** [comment]
Dev version working for polisystems.ch too

**Comment by amaciasf** [comment]
Dev version working fine, Thanks!

**Comment by dserodio** [comment]
Another 👍 here for a domain which fails in prod version and works in dev version.

**Comment by Prophet731** [comment]
Same here 👍 works on the dev version.
