### ISSUE TITLE
Scan fails with EC certificate (TLS 1.3 only)

### ISSUE THREAD

**Issue by moviuro** [ssllabs/ssllabs-scan#795]
Hi,

I have 2 sites, with similar TLS setup except for the certificate:

* https://www.ssllabs.com/ssltest/analyze.html?d=try.popho.be&hideResults=on which fails (no grade is given) with obscure messages. This site uses an EC certificate.
* https://www.ssllabs.com/ssltest/analyze.html?d=sco.popho.be&hideResults=on which gets an A grade, and no error message. This site uses an RSA certificate.

Best regards,

**Comment by naumanshah03** [comment]
Hi @moviuro 

This issue has been fixed and changes have been deployed to dev.ssllabs.com version 2.1.5

https://dev.ssllabs.com/ssltest/analyze.html?d=try.popho.be

Regards,
Nauman Shah

**Comment by moviuro** [comment]
Confirmed working!
