### ISSUE TITLE
Server certificate issued by Thawte marked as incomplete chain

### ISSUE THREAD

**Issue by ruatag** [ssllabs/ssllabs-scan#799]
Server certificate issued by intermediate CA Thawte marked as incomplete chain

Thawte RSA CA 2018
AIA: http://cacerts.thawte.com/ThawteRSACA2018.crt

Issuer of this intermediate CA
CN=DigiCert Global Root CA,OU=www.digicert.com,O=DigiCert Inc,C=US
Authority Information Access:
OCSP - URI:http://ocsp.digicert.com
X509v3 CRL Distribution Points:
Full Name:
URI:http://crl3.digicert.com/DigiCertGlobalRootCA.crl
X509v3 Certificate Policies:
Policy: X509v3 Any Policy
CPS: https://www.digicert.com/CPS

**Comment by tamthing** [comment]
Could you share the domain to https://discussions.qualys.com/people/tamthing ?

We'll look at it.

**Comment by ruatag** [comment]
opentip.kaspersky.com

**Comment by tamthing** [comment]
Your server is not sending the intermediate certificate in the handshake. It is sending only the leaf certificate. That is why you are seeing the certificate chain as incomplete.

**Comment by ruatag** [comment]
We never have problem with browsers and modern OS, only with some automation tools.
Added intermediate certificate, can se the difference with openssl s_client but not for tools
Looks like also a client issue.
Thanks a lot
