### ISSUE TITLE
529 http response from server.

### ISSUE THREAD

**Issue by kristoferlandgren** [ssllabs/ssllabs-scan#800]
Same issue as was reported in https://github.com/ssllabs/ssllabs-scan/issues/784 is happening again.

I've been trying to run some tests today (May 8 2020 ) at CET 15:00-16:00.

**Comment by naumanshah03** [comment]
@kristoferlandgren is it still reproducible for you?

Please share the details to reproduce the issue as we had improved our server capabilities

**Comment by kristoferlandgren** [comment]
@naumanshah03 Sometimes when calling the API "too fast" but I have implemented backoff routines when it happens so it's not really an issue for me anymore.

**Comment by shawntoffel** [comment]
I started receiving 529s on every run of this tool around December 2020. Long sleeps on the very first run in several days. Someone else has also reported 529s in the docker image repo https://github.com/jumanjihouse/docker-ssllabs-scan/issues/86 which I assume is the same issue. 

```
$ ssllabs-scan https://google.com
2021/01/11 16:55:00 [INFO] SSL Labs v2.1.8 (criteria version 2009q)
2021/01/11 16:55:00 [NOTICE] Server message: This assessment service is provided free of charge by Qualys SSL Labs, subject to our terms and conditions: https://www.ssllabs.com/about/terms.html
2021/01/11 16:55:02 [INFO] Assessment starting: https://google.com
2021/01/11 16:55:02 [NOTICE] Sleeping for 26 minutes after a 529 response
2021/01/11 17:21:03 [NOTICE] Sleeping for 27 minutes after a 529 response
```
