### ISSUE TITLE
Assessment Failed 

### ISSUE THREAD

**Issue by anna1388** [ssllabs/ssllabs-scan#801]
Hi Team, 

I am not able to complete the TLS test of bireporting.costco.com using https://www.ssllabs.com/ssltest/, but I am ok of getting the report back using digiCert ssl checker. Could you please help find out the reasons?

Here is the error message: 
Assessment failed: Required directive missing: max-age

Thanks,

Anna Duan

**Comment by naumanshah03** [comment]
This issue relates to https://github.com/ssllabs/ssllabs-scan/issues/793

**Comment by naumanshah03** [comment]
Changes have been deployed to dev.ssllabs.com version 2.1.5

Please test it.

**Comment by naumanshah03** [comment]
Closing this issue as it has been resolved and deployed on www.ssllabs.com
