### ISSUE TITLE
SSL Client Test for IE11 incorrectly reports that browser doesn't have TLS 1.2 support

### ISSUE THREAD

**Issue by Safety1st** [ssllabs/ssllabs-scan#803]
[SSL Client Test](https://www.ssllabs.com/ssltest/viewMyClient.html) for IE11 incorrectly reports that browser doesn't have TLS 1.2 support. That option is enabled and TLS 1.2 connections tested. User Agent: `Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko`.

**Comment by RobTho** [comment]
Hi
check "mixed content" setting in IE Settings.
Test will fail if mixed content is blocked.

**Comment by Safety1st** [comment]
@RobTho yeah, you're right. Could you explain why is displaying of mixed content required for proper TLS support detection?

**Comment by Safety1st** [comment]
@RobTho yeah, you're right! Too bad access to http://plaintext.ssllabs.com:10080 required for proper TLS support detection :(
