### ISSUE TITLE
Internal error, TLSv1.3 only site

### ISSUE THREAD

**Issue by nieldk** [ssllabs/ssllabs-scan#804]
The scan engine fails with an “internal error” when scanning a TLSv1.3 only site (RSA cert).

For reference: https://www.ssllabs.com/ssltest/analyze.html?d=sec1.dk

**Comment by nayankakati** [comment]
Hi @nieldk :

This has already been fixed, please check the same on dev.ssllabs.com, we will deploy to production soon.

Thanks

**Comment by naumanshah03** [comment]
Hi @nieldk 

This issue has been fixed and changes have been deployed to dev.ssllabs.com version 2.1.5
Duplicate: https://github.com/ssllabs/ssllabs-scan/issues/795

https://dev.ssllabs.com/ssltest/analyze.html?d=sec1.dk

Regards,
Nauman Shah

**Comment by nieldk** [comment]
I can confirm.
However, its not a duplicate, #795 didnt experience this with RSA cert, i
did.

Best regards
Niel

**Comment by naumanshah03** [comment]
Hi @nieldk 

It is a duplicate of #795 because the issue was not related to the certificate being used whereas it was related to the use of ChaCha preference in TLS 1.3
Hence I mentioned about #795 issue

As verified able to scan sec1.dk on dev.ssllabs.com

Regards,
Nauman Shah
