### ISSUE TITLE
incorrect GOST ciphersuite support in SSL client test

### ISSUE THREAD

**Issue by ryabkov** [ssllabs/ssllabs-scan#805]
affected tests: https://clienttest.ssllabs.com:8443/ssltest/viewMyClient.html
problem: when i use browser with GOST ciphersuite(in client hello) i see error (Failed to process your browser's SSL/TLS handshake)

for example here setup for yandex browser (https://browser.yandex.ru/help/tls/tls.html) - sorry i can not find english manual

i think problem in client hello parser.

**Comment by DesWurstes** [comment]
In English: https://browser.yandex.com/help/tls/tls.html

**Comment by tamthing** [comment]
This has been fixed and now deployed on dev.ssllabs.com. Please verify at your ends.

**Comment by ryabkov** [comment]
it works
