### ISSUE TITLE
How to capture data from command line scans

### ISSUE THREAD

**Issue by akwete** [ssllabs/ssllabs-scan#81]
What is the most effective method for capturing the output of bulk scans using the command line tool?  When I use the following command, I see output on the screen but no data gets captured in the intended destination file. 

go run ssllabs-scan.go --hostfile SSL-Websites.txt > SSLLabs-Scan_Results.txt

I assume the data (once captured) will be in CSV (or similar) format?  Any suggestions on how to pre-format and publish the output?

**Comment by seccubus** [comment]
@akwete I have integrated it in Seccubus for bulk scanning. (Hope you don't mind the plug @ivanr ...) feel free to correct me.

**Comment by ivanr** [comment]
The default output format is JSON, and it will be a list of report structures, per the documentation. A CSV format is something we might add in the future. Personally, I quite like the idea of a configurable CSV format, which would contain only what one is interested in.

**Comment by akwete** [comment]
Thanks for the reply.  I looked at Seccubus (a web GUI is always attractive lol) however it requires a full server roll out.  If running these scans becomes an extended engagement, I just might take another look.

Date: Thu, 12 Mar 2015 08:46:24 -0700

**Comment by akwete** [comment]
Thanks for the feedback.   Unfortunately I do not have the skills to manipulate JSON data.  CSV output would definitively be a good feature addition.

Date: Thu, 12 Mar 2015 10:53:53 -0700
