### ISSUE TITLE
Android app

### ISSUE THREAD

**Issue by emartynov** [ssllabs/ssllabs-scan#810]
Hi people,

I really like your service.

I have an idea - the encryption and ssl stack on android depends on the os and vendor.
Do you think it is good idea to write and android app that will test the OS possibilities and report if some cyphers are not available?

**Comment by tamthing** [comment]
Hi @emartynov , have you checked our listed client tests? https://www.ssllabs.com/ssltest/clients.html

We have put up the capabilities of the client(here Android) including the supported ciphersuites. If you click any one of those, it will show you the details of capabilities of the selected Android version. I hope that concurs to your idea?

**Comment by emartynov** [comment]
Cool, this is good information but I was more referring about an app to
test specific particular android device.

**Comment by emartynov** [comment]
Closing since not much reaction. Thank you!
