### ISSUE TITLE
SSL scan from laptop locally

### ISSUE THREAD

**Issue by emartynov** [ssllabs/ssllabs-scan#811]
Hi people,

sometimes I want to check resources that are behind VPN. I had hope that command line tools are doing checks from my machine, but, unfortunately, it is client to your services. Do you think it would be good to have the local tool that does such checks?

Kind Regards,
Eugen

**Comment by smuda** [comment]
Personally I use https://testssl.sh for servers behind a firewall. Not as good and easily understod as ssllabs, but a really good substitute.

**Comment by emartynov** [comment]
Thank you for the tool suggestion - it was helpful and enough to find what I was looking for. I'm closing ticket unless ssl labs wants to proceed with it.
