### ISSUE TITLE
TLS1.0 is disabled in server but reported as "Yes" by ssllabs

### ISSUE THREAD

**Issue by t-bzhan** [ssllabs/ssllabs-scan#812]
Our sever nugetdev1.cdn.azure.cn has disable TLS1.0, but ssllabs reported it as "Yes":https://www.ssllabs.com/ssltest/analyze.html?d=nugetdev1.cdn.azure.cn&s=119.36.33.85&latest

![image](https://user-images.githubusercontent.com/61817681/89397724-c91a9f80-d742-11ea-835b-4389cbff53b8.png)

I tried with testssl.sh, sslyze and https://www.immuniweb.com/ssl/, all return the expected results:
![image](https://user-images.githubusercontent.com/61817681/89397887-fff0b580-d742-11ea-83b5-bc3a6a8b2ea7.png)

**Comment by tamthing** [comment]
Hi @t-bzhan , your server **does not** support TLS 1.0 **with** SNI. But it supports TLS 1.0 **without** SNI.

If you hover over the text "Yes" for TLS 1.0, then a title text appears with the indication. I hope that clear the confusion.

**Comment by t-bzhan** [comment]
@tamthing Thanks a lot for your explanation, I check with openssl and it behaves as you described. I will close the issue in that case.
