### ISSUE TITLE
[FEATURE REQUEST] Allow IP-address scan in case of IP-address valid certificate

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#82]
Have just seen an IP-address trusted server, first time in my life:
https://www.ssllabs.com/ssltest/analyze.html?d=vpn.trustedloyaltypartners.co.uk
Common names 82.145.37.236
Issuer COMODO High-Assurance Secure Server CA

https://www.ssllabs.com/ssltest/analyze.html?d=82.145.37.236
IP addresses are not allowed

If a publicly trusted certificate is valid for an IP-address, then it is public, right?

**Comment by ivanr** [comment]
We don't allow scanning of IP addresses because of policy, not because certificates use hostnames. Further, in order to get to the certificate we need to start testing, then give up. Given that this situation arises so frequently, I don't want to do it.
