### ISSUE TITLE
Output as html

### ISSUE THREAD

**Issue by gomanuke** [ssllabs/ssllabs-scan#823]
Hi.
It works great and ounput clear json format. But is it possible to get an formatted html, as it ste does?
Thnak You.

**Comment by naumanshah03** [comment]
@gomanuke 

In this tool, we use the API's of SSLLabs to get the result.
If you want the result in HTML format or the same result as SSLLabs then please use www.ssllabs.com as we do not have any plans on having a HTML format result for the ssllabs-scan tool

Regards,
Nauman Shah
