### ISSUE TITLE
Missing 'q' flag for weak cipher suites

### ISSUE THREAD

**Issue by chillheart** [ssllabs/ssllabs-scan#827]
I am working on a CLI tool that will flag weak and insecure cipher suites for our domains. The cipher suites array has a q value for insecure suites, however it does not return a value when the cipher suite is considered weak. Here is an example response with some weak cipher suites:

`{
  "suites": {
    "list": [
      {
        "id": 4865,
        "name": "TLS_AES_128_GCM_SHA256",
        "cipherStrength": 128,
        "ecdhBits": 256,
        "ecdhStrength": 3072
      },
      {
        "id": 4866,
        "name": "TLS_AES_256_GCM_SHA384",
        "cipherStrength": 256,
        "ecdhBits": 256,
        "ecdhStrength": 3072
      },
      {
        "id": 4867,
        "name": "TLS_CHACHA20_POLY1305_SHA256",
        "cipherStrength": 256,
        "ecdhBits": 256,
        "ecdhStrength": 3072
      },
      {
        "id": 49199,
        "name": "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "cipherStrength": 128,
        "ecdhBits": 256,
        "ecdhStrength": 3072
      },
      {
        "id": 49200,
        "name": "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "cipherStrength": 256,
        "ecdhBits": 256,
        "ecdhStrength": 3072
      },
      {
        "id": 49195,
        "name": "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
        "cipherStrength": 128,
        "ecdhBits": 256,
        "ecdhStrength": 3072
      },
      {
        "id": 49196,
        "name": "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
        "cipherStrength": 256,
        "ecdhBits": 256,
        "ecdhStrength": 3072
      },
      {
        "id": 52392,
        "name": "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
        "cipherStrength": 256,
        "ecdhBits": 256,
        "ecdhStrength": 3072
      },
      {
        "id": 52393,
        "name": "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
        "cipherStrength": 256,
        "ecdhBits": 256,
        "ecdhStrength": 3072
      },
      {
        "id": 156,
        "name": "TLS_RSA_WITH_AES_128_GCM_SHA256",
        "cipherStrength": 128
      },
      {
        "id": 157,
        "name": "TLS_RSA_WITH_AES_256_GCM_SHA384",
        "cipherStrength": 256
      },
      {
        "id": 158,
        "name": "TLS_DHE_RSA_WITH_AES_128_GCM_SHA256",
        "cipherStrength": 128,
        "dhStrength": 1024,
        "dhP": 128,
        "dhG": 1,
        "dhYs": 128
      },
      {
        "id": 159,
        "name": "TLS_DHE_RSA_WITH_AES_256_GCM_SHA384",
        "cipherStrength": 256,
        "dhStrength": 1024,
        "dhP": 128,
        "dhG": 1,
        "dhYs": 128
      }
    ]
  }
}`

**Comment by PejeDK** [comment]
I have same issue with the api and the documentation state otherwise:
https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md#%20suite

**Comment by naumanshah03** [comment]
@chillheart and @PejeDK 

Please use APIv3 and not APIv2. APIv3 has the q parameter that shows the insecure/weak cipher suite.
Here are some of the examples:
https://api.ssllabs.com/api/v3/analyze.html?host=rc4.badssl.com&all=on
![image](https://user-images.githubusercontent.com/22236992/106106553-b8843880-616b-11eb-92ac-4a1378b00e48.png)

https://api.ssllabs.com/api/v3/analyze.html?host=static-rsa.badssl.com&all=on
![image](https://user-images.githubusercontent.com/22236992/106106658-dfdb0580-616b-11eb-9416-6f41359264e3.png)
