### ISSUE TITLE
API Lowercasing the URL?

### ISSUE THREAD

**Issue by andrewfenn** [ssllabs/ssllabs-scan#828]
I have a URL which has some uppercase characters in the path. The response I get back from the API v3 is the same URL but lowercase with an error saying it's unreachable. If you attempt to go to this URL in lowercase I know it will not work. Is the API test lowercasing my URL before running it? If so is there a process to request that this be changed so that it doesn't lowercase the URL before running?

**Comment by naumanshah03** [comment]
Hi @andrewfenn 

From the URL we only scan the domain name and not the complete path. Domain should always be in lower case.
Please share the output and the URL to assess the issue

Regards,
Nauman Shah

**Comment by andrewfenn** [comment]
Hi Nauman,

In that case I think the problem must be on the website side and no issue on the API side. Thanks for clarifying. I'll close this issue for now.

Regards,
Andrew
