### ISSUE TITLE
QuoVadis Global SSL ICA G2/G3

### ISSUE THREAD

**Issue by josselinl** [ssllabs/ssllabs-scan#829]
Hi,
QuoVadis change sub certificates CA :
https://www.quovadisglobal.ch/Unternehmen/NewsAndEvents/Begrenzte%20Systemverfuegbarkeit.aspx?sc_lang=en-GB
All certificates signed by QuoVadis Global SSL ICA G2 or QuoVadis Global SSL ICAG3 seems to be unusable.
Could you please update them ?
Thanks.

**Comment by naumanshah03** [comment]
Hi @josselinl 

Those are intermediate certificates and SSLLabs does not store intermediate certificate. SSLLabs only has CA certificate to form the complete chain. The above certificates should be added on the server and not SSLLabs.

Regards,
Nauman Shah
