### ISSUE TITLE
Scan IPv6 too, because some sites differ in configuration.

### ISSUE THREAD

**Issue by noxxi** [ssllabs/ssllabs-scan#83]
Hi, I just happened to analyze a problem with `robot.your-server.de`. This sites works from some locations or some browsers or tools but fails with other locations or tools. SSLLabs reports the site as fine with no chain issues.

Turns out that this site is using a different setup for IPv4 and IPv6 and uses an incomplete certificate chain only with the IPv6 setup. Thus the connection succeeded only if the site hat no IPv6 or the browser/tool did not support IPv6. Because of this failure scenario it would be nice if SSLLabs checked IPv6 additionally to IPv4.

**Comment by ivanr** [comment]
Implemented in the development version.
