### ISSUE TITLE
Assessment failed: Unable to connect to the server 

### ISSUE THREAD

**Issue by qcybb** [ssllabs/ssllabs-scan#830]
I am unable to test any of my domains on my server. I've been using SSL Labs for years now and never had this issue until tonight.

All I get is "Assessment failed: Unable to connect to the server".

https://qcybb.com

- My firewall is turned off
- No allow/deny rules in server vhosts

Any ideas what the issue could be?

**Comment by naumanshah03** [comment]
Hi @qcybb 

As checked I'm able to scan the domain and here is the [result](https://casecurity.ssllabs.com/analyze.html?d=qcybb.com&hideResults=on)
Can you please share the complete URL of the report?

Regards,
Nauman Shah

**Comment by qcybb** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=qcybb.com&hideResults=on

**Comment by naumanshah03** [comment]
![image](https://user-images.githubusercontent.com/22236992/106097795-efebe880-615d-11eb-8608-3f946a6c6390.png)

Able to complete the scan with no error

**Comment by qcybb** [comment]
Ok, for some reason it's working just fine this morning. 

I changed nothing, so I'm not sure what ever caused this. Feel free to close this issue.

**Comment by naumanshah03** [comment]
@qcybb there was some network issue and it was resolved by our team.

**Comment by qcybb** [comment]
Thank you, that explains it then. All is well, I've had no issues since then.
