### ISSUE TITLE
You have too many assessments in progress

### ISSUE THREAD

**Issue by Legeril** [ssllabs/ssllabs-scan#833]
![153835497_774010310164893_5161951757742372158_n](https://user-images.githubusercontent.com/48111476/109055161-6c61e080-76a4-11eb-81f4-e3eb3a14fe24.png)

Verified multiple users are receiving the attached error when trying to scan any hostname from different locations in the USA

**Comment by RobTho** [comment]
i also contacted this issue. 
i used dev.ssllabs.com as a workaround

**Comment by RobTho** [comment]
https://qualys-secure.force.com/discussions/s/question/0D52L00005KmiQNSAZ/problems-using-the-web-version-of-the-ssltest

**Comment by naumanshah03** [comment]
This issue has been resolved. Hence closing
