### ISSUE TITLE
No "ignoreMismatch" in the go script?

### ISSUE THREAD

**Issue by andrepereiradasilva** [ssllabs/ssllabs-scan#84]
How can the web version "ignoreMismatch" query string parameter can be used in the go script.

Is there a parameter in the API for that?

**Comment by andrepereiradasilva** [comment]
Ok. i found the "--insecure" option does the work.

**Comment by ivanr** [comment]
No, --insecure doesn't do that. The Go script doesn't yet support ignoreMismatch.

**Comment by andrepereiradasilva** [comment]
ok thanks

**Comment by ivanr** [comment]
I've now added the --ignore-mismatch switch and documented the ignoreMismatch parameter.
