### ISSUE TITLE
IPv6 server test failed

### ISSUE THREAD

**Issue by KesunyianAyam** [ssllabs/ssllabs-scan#848]
I tried to test my server, but IPv6 tests seems to failed, so I tried with google and facebook servers, the results are the same, 

Error:
`Unable to connect to the server`

**Comment by miyurusankalpa** [comment]
I am seeing this error for AWS and cloudflare IPv6 address too.

![image](https://user-images.githubusercontent.com/1833185/128664663-5bdc37f0-9e21-4266-9e14-283e1c4f1e26.png)

Sad to see that they don't have IPv6 availability monitored. If it was _IPv4_ it would be been a priority 1 issue and fixed.

**Comment by naumanshah03** [comment]
Our network team is looking into this issue

**Comment by Marsupilani** [comment]
With SSL Report v2.1.9 (https://dev.ssllabs.com/ssltest/analyze.html) it works for IPv4 and IPv6 
With SSL Report v2.1.10 (https://www.ssllabs.com/ssltest/) IPv6 reports 'Unable to connect to the server' at the same server...

**Comment by naumanshah03** [comment]
This network issue is not resolved.
https://www.ssllabs.com/ssltest/analyze.html?d=miyuru.lk&hideResults=on
