### ISSUE TITLE
IPv6 doesn't work anymore

### ISSUE THREAD

**Issue by weinzierl** [ssllabs/ssllabs-scan#849]
Any site with IPv6 I tried reports: "Unable to connect to server".  I could not find a site where the test is successful for IPv6. This was different last week, at least for https://weinzierlweb.com. Verified with ready.chair6.net that IPv6 connectivity of the site is good. This leads me to assume the issue might be on SSL Labs' side.

See also this older bug report which looks similar:
https://github.com/ssllabs/ssllabs-scan/issues/655

I also checked with the URL mentioned in issue #655 (ipv6.google.com) and it also leads to  "Unable to connect to server", while other checks indicate that the IPv6 service there is OK.

**Comment by Rar9** [comment]
+1 for https://www.asset-trade.de
  ipv6 is ok according to https://ipv6-test.com/validate.php

**Comment by jpbion** [comment]
I see this problem as well. I tried my own site - then I tried a couple huge internet sites that support v6 - all returned "unable to connect to the server"

**Comment by naumanshah03** [comment]
Our network team is looking into this issue

**Comment by SamsonJohn** [comment]
I have created the separate ticket for this the ipv6 issue we are facing, https://github.com/ssllabs/ssllabs-scan/issues/851
so when I have verified on https://dev.ssllabs.com/ the website is showing correctly the rating .
Please get this fixed on SSLLabs

**Comment by Rar9** [comment]
Hi, 
on dev ssl ipv6 works but the issue remains and must be related to the redirect

asset-trade.de gets A
www.asset-trade.de  gets A+

-- 
Mit freundlichen Grüßen /with best regards,

Robert Krölls
Am Sonnenhof 16
47800 Krefeld

Am 12. August 2021 07:24:52 MESZ schrieb SamsonJohn ***@***.***>:

**Comment by weinzierl** [comment]
> I have created the separate ticket for this the ipv6 issue we are facing, #851
> so when I have verified on https://dev.ssllabs.com/ the website is showing correctly the rating .
> Please get this fixed on SSLLabs

I can confirm that. On dev.ssllabs.com everything looks good. Without knowing anything about SSL Labs infrastructure and purely from the outside this looks like a firewall issue to me.

**Comment by weinzierl** [comment]
> Hi, on dev ssl ipv6 works but the issue remains and must be related to the redirect asset-trade.de gets A [www.asset-trade.de](http://www.asset-trade.de) gets A+

The difference between the www and non-www version seems like a different and unrelated issue to me. I think the reason is that your server does not send the HSTS header with the 301 redirect. This is easy to fix, just add the header you send for the www version to the non-www version (which creates the redirect) too. As a counterexample:

[weinzierlweb.com](weinzierlweb.com) gets A+
[www.weinzierlweb.com](www.weinzierlweb.com) gets A+

**Comment by SamsonJohn** [comment]
> > I have created the separate ticket for this the ipv6 issue we are facing, #851
> > so when I have verified on https://dev.ssllabs.com/ the website is showing correctly the rating .
> > Please get this fixed on SSLLabs
> 
> I can confirm that. On dev.ssllabs.com everything looks good. Without knowing anything about SSL Labs infrastructure and purely from the outside this looks like a firewall issue to me.

Can you please confirm if this is firewall issue from the ssllabs or we need to take any action

**Comment by weinzierl** [comment]
> Our network team is looking into this issue

@naumanshah03 any news on your side?

**Comment by weinzierl** [comment]
Seems to be good now. Thanks a lot.
