### ISSUE TITLE
Bug with domain with mismatch certificate and no chain of trust?

### ISSUE THREAD

**Issue by andrepereiradasilva** [ssllabs/ssllabs-scan#85]
In a domain (www.domain.tld) with a mismatch certiicate and no chain of trust, if we use the API with
"go run ssllabs-scan.go --usecache --insecure --quiet www.domain.tld"
We get an something like:

```
[{
"host":"www.domain.tld",
"port":443,
"protocol":"HTTP",
"isPublic": false,
"status":"READY",
"startTime":1426417520867,
"testTime":1426417530335,
"engineVersion":"1.15.1",
"criteriaVersion":"2009i",
"cacheExpiryTime":1426418130335,
"endpoints":
[{
"ipAddress": "xxx.xxx.xxx.xxx",
"serverName":"mismatchdomain.tld",
"statusMessage": "Certificate not valid for domain name",
"statusDetails": "TESTING_HTTPS",
"statusDetailsMessage": "Sending one complete HTTPS request",
"progress":-1,
"duration":9298,
"eta":-1,
"delegation":3,
"details":
{
"hostStartTime":1426417520867,
"key": {},
"cert":{},
"chain":{},
"protocols":[],
"suites":{},
"prefixDelegation":true,
"nonPrefixDelegation":true
}
}],
"certHostnames":["www.mismatchdomain.tld"]
}]
```

But if use the same domain in the web version test we can see all the ssl/tls instalation properties.
https://www.ssllabs.com/ssltest/analyze.html?d=www.domain.tld&hideResults=on&ignoreMismatch=on

Shouldn't the API return the same result as the web version?

**Comment by ivanr** [comment]
That shouldn't be happening. In both cases the data is from the same source. But, without a hostname to test with, I can't troubleshoot.

**Comment by ivanr** [comment]
Fixed. This was a bug I introduced just before the final release. Currently, the default is not to proceed on certificate mismatch. This behaviour matches the SSL Labs web site. If the "ignoreMismatch" is set to "on" (or if the --ignore-mismatch switch is used) then the assessment proceeds.
