### ISSUE TITLE
Enhancement: ALPN (Application-Layer Protocol Negotiation)

### ISSUE THREAD

**Issue by cfhay** [ssllabs/ssllabs-scan#86]
It would be nice to see checking for ALPN support in the future. OpenSSL 1.0.2 supports it out of the box.

https://en.wikipedia.org/wiki/Application-Layer_Protocol_Negotiation

**Comment by selecadm** [comment]
This was discussed a month ago: https://community.qualys.com/thread/14198

IMO, having a GitHub issue with "enhancement" label is also good.

**Comment by cfhay** [comment]
Sorry, I have no idea how to add labels. I can't see knobs for it.

**Comment by ivanr** [comment]
No worries, I've added the label.

**Comment by ivanr** [comment]
Added in 1.21.3.

**Comment by Jan-E** [comment]
Is this already available at dev.ssllabs.com? It says SSL Report v1.21.3, but I do not see any remark about ALPN.

**Comment by ivanr** [comment]
If you look under simulations, whenever ALPN is negotiated the information is shown in the protocol column. But a remark about ALPN (in the protocol details section) is still missing. Tomorrow! :)

**Comment by Jan-E** [comment]
Right, Thanks:
https://dev.ssllabs.com/ssltest/analyze.html?d=fips.sessiondatabase.net

**Comment by wiktor-k** [comment]
Looks like it's only supported on the website but not through the API:
https://api.ssllabs.com/api/v2/getEndpointData?host=encrypted.google.com&s=216.58.192.46

(there are fields for NPN but not for ALPN).
