### ISSUE TITLE
Enhancement: Test TLS False Start capability

### ISSUE THREAD

**Issue by cfhay** [ssllabs/ssllabs-scan#87]
It would be nice to see tests for TLS False Start support on server side.

https://tools.ietf.org/html/draft-bmoeller-tls-falsestart-00
https://istlsfastyet.com/

**Comment by ivanr** [comment]
What do you mean by "support on server side"? Do you mean to see if the server would accept an application data write before the handshake is complete or simply if the server configuration is such that browsers will attempt False Start with it?

**Comment by cfhay** [comment]
Well I think both with an "AND". If the server supports false start but the clients will not try to use it, it's bad. If the client tries to connect with false start, but the server will not able to handle the situation is also bad.

If the clients try to use false start, I think they fall back when it doesn't work, so without checking the traffic on packet level (like with Wireshark or some other tool), only the timing would tell something about performance.

However I think the latter is more important than the former. If we see servers that implements false start badly, but the clients attempt to use it, then a packet level test would be handy.

**Comment by ivanr** [comment]
It's a lot of work to build that test (essentially hack a TLS stack to support False Start). At the same time, the specification doesn't match what is done in practice, so it's not clear what should be implemented. The TLS working group is expected to adopt the specification (after it is changed). I am not going to do anything at least until that happens, but I will keep this ticket around for later.

**Comment by inscale** [comment]
+1

**Comment by strugee** [comment]
@ivanr TLS False Start has been ratified as [RFC 7918][1] in August 2016; any chance of it showing up in SSL Labs soon? Seems like at least the browser criteria should be easy to implement - see https://hpbn.co/transport-layer-security-tls/#enable-tls-false-start

Cheers, and thanks for your work on SSL Labs! It's truly an awesome tool :tada:

 [1]: https://datatracker.ietf.org/doc/rfc7918/

**Comment by ivanr** [comment]
I think there was a window of opportunity for False Start to be relevant, but that it's closed now because TLS 1.3 is around the corner. In TLS 1.3, the protocol messages have been reworked to have similar performance characteristics as False Start. And there is of course a ton of other improvements. So virtually everyone would be much better off focusing on upgrading to TLS 1.3 rather than tinkering with False Start.

**Comment by strugee** [comment]
Neat, that makes sense (though I *will* point out that it'll take a while for TLS 1.3 to be widely deployed - though in general I agree with your decision to skip implementing this). Thanks :thumbsup:

**Comment by ivanr** [comment]
Fantastic, thanks!
