### ISSUE TITLE
[regression] Unexpected response status code 502 

### ISSUE THREAD

**Issue by J0WI** [ssllabs/ssllabs-scan#88]
Since the patch from #79 is landed I often get the following error:
[ERROR] Unexpected response status code 502

**Comment by ivanr** [comment]
Could you please switch to api.dev.ssllabs.com for testing purposes? I've fixed a configuration problem that might be causing this. I can see it in the logs, so no need to report back. Thanks.

**Comment by J0WI** [comment]
first try was successful, but I'll keep an eye on it.

**Comment by ivanr** [comment]
I haven't seen any warnings since I made the change. Previously, there were many every day. I will consider this fixed. (The fix for the production servers will take some time.) Thanks!
