### ISSUE TITLE
ipv6 not working

### ISSUE THREAD

**Issue by loutelecom** [ssllabs/ssllabs-scan#880]
It says unable to connect to server

**Comment by reneposthumus** [comment]
Same today, was troubleshooting cipher suites but no connection on IPv6, thought the issue was on my side.
Pls fix this gents!

**Comment by naumanshah03** [comment]
Please share the domain name for which this issue is appearing
We will get it checked with our network team

**Comment by kimboslice99** [comment]
@naumanshah03 

As I stated in my report, it happens on every domain

**Comment by naumanshah03** [comment]
This issue is now resolved. It was a network issue.
![image](https://user-images.githubusercontent.com/22236992/155461542-3f1cf918-260d-4363-a217-a714fff672de.png)


Regards,
Nauman Shah
