### ISSUE TITLE
api.dev.ssllabs.com unavailable

### ISSUE THREAD

**Issue by rajiv** [ssllabs/ssllabs-scan#883]
The dev site for the API at `https://api.dev.ssllabs.com/api/v3/` (as specified at https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md?plain=1#L20) has been offline since at least Feb 1, 2022. Same for the web version at `https://dev.ssllabs.com/`.

Both return `503 Service Unavailable` errors.

**Comment by naumanshah03** [comment]
Hi @rajiv 

The service is down. We will get it back up soon.

**Comment by naumanshah03** [comment]
It is up now
