### ISSUE TITLE
SSL Labs doesn't detect TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384

### ISSUE THREAD

**Issue by BryanS001** [ssllabs/ssllabs-scan#886]
I have  multiple Windows 2016 and 2019 servers that are configured to support TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, however, it is not detected by SSLLabs.  Is there a flaw in Windows, or SSLLabs?

**Comment by RobTho** [comment]
what kind of cert does your server use?
RSA or DSA

**Comment by BryanS001** [comment]
RSA

Bryan Starr
IT Director – American Mechanical Services

**Comment by RobTho** [comment]
Hi
you cannot use EC**DSA** cipher with **RSA** Certs. You need to use 
You could use e.g TLS_ECDHE_**RSA**_WITH_AES_256_GCM_SHA384 or you will need to use a **DSA** Cert

**Comment by BryanS001** [comment]
Thank you!  That’s what I was missing.

Bryan Starr
IT Director – American Mechanical Services

**Comment by naumanshah03** [comment]
Thanks @RobTho for clearing this to @BryanS001 

Closing this issue.

Regards,
Nauman Shah
