### ISSUE TITLE
DROWN	Unable to perform this test due to an internal error.

### ISSUE THREAD

**Issue by rso2020** [ssllabs/ssllabs-scan#889]
I see my sites and too many others with this internal error, maybe it is a bug on SSLLABS?
For example this is result with microsoft.com or google.com

Protocol Details
DROWN	Unable to perform this test due to an internal error.
(1) For a better understanding of this test, please read [this longer explanation](https://blog.qualys.com/securitylabs/2016/03/04/ssl-labs-drown-test-implementation-details)
(2) Key usage data kindly provided by the [Censys](https://censys.io/) network search engine; original DROWN website [here](https://drownattack.com/)
(3) Censys data is only indicative of possible key and certificate reuse; possibly out-of-date and not complete
INTERNAL ERROR: Connection refused (Connection refused)
INTERNAL ERROR: Connection refused (Connection refused)

**Comment by naumanshah03** [comment]
Hi @rso2020 

The API services provided by the researcher were down and now it has been brought back-up so you will be able to see the DROWN test working now.
