### ISSUE TITLE
Website showing two SSL

### ISSUE THREAD

**Issue by nagendraserver** [ssllabs/ssllabs-scan#895]
Hello Sir,
Why a domain nxp.futurewiz.co.in showing there are two SSL after SSL Server Test. I check at our end and with domain/hosting server team and got only one SSL certificate is marked for that particular domain.

I am requested, Please help us for the same issue.

Regards
Nagendra

**Comment by naumanshah03** [comment]
Hi @nagendraserver 

Your server is supporting NoSNI (No Server Name Indication) hence it is going to a default domain. You can read about SNI in detail. Please correctly configure your server for SNI.

**For reproducing the issue please follow the below commands:**

OpenSSL Command with SNI (Gives certificate `#1` from SSLLabs Report)
`openssl s_client -showcerts -connect nxp.futurewiz.co.in:443 </dev/null`

OpenSSL Command without SNI (Gives certificate `#2` from SSLLabs Report)
`openssl s_client -showcerts -servername nxp.futurewiz.co.in -connect nxp.futurewiz.co.in:443 </dev/null`

Regards,
Nauman Shah

**Comment by nagendraserver** [comment]
How can I remove these certificate . I have only one SSL and want to show only one. 
Please suggest the steps to removing this.

This is creating an issue when we configure our domain with Akamai.

Regards
Nagendra

**Comment by naumanshah03** [comment]
@nagendraserver I would not be able to help you with it.
I have shared the pointers so you can change the configuration based on your application that is performing HTTPS termination.
Look for setting Strict SNI configuration

Regards,
Nauman Shah
