### ISSUE TITLE
Hello Sir,

### ISSUE THREAD

**Issue by lamjay2704** [ssllabs/ssllabs-scan#896]
Hello Sir,
Why a domain nxp.futurewiz.co.in showing there are two SSL after SSL Server Test. I check at our end and with domain/hosting server team and got only one SSL certificate is marked for that particular domain.

I am requested, Please help us for the same issue.

Regards
Nagendra

__Originally posted by @nagendraserver in https://github.com/ssllabs/ssllabs-scan/issues/895__

**Comment by naumanshah03** [comment]
Closing as duplicate #895
