### ISSUE TITLE
Confusion about compressionMethods bit 0 is set for DEFLATE

### ISSUE THREAD

**Issue by yezhu6** [ssllabs/ssllabs-scan#899]
In the [SSL Labs API v3 Documentation](https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md#ssl-labs-api-v3-documentation-v135x-work-in-progress), there is a description about compressionMethods in EndpointDetails of Response Objects.

- compressionMethods - integer value that describes supported compression methods

   bit 0 is set for DEFLATE

When I call the api: https://api.ssllabs.com/api/v3/analyze?host=www.ssllabs.com and get the response, the compressionMethods value is 0:

    "compressionMethods":0,

According to the description in the documentation, the compression method is DEFLATE.
But when I test the host in the SSL test portal with the same hostname, get the result about compression is disabled:
![image](https://user-images.githubusercontent.com/92571997/184310934-76bd806a-6164-40c5-9cdd-92ca8bd944f5.png)

So I'm confused about the description in the documentation, compressionMethods's value is 0 means compression disabled or means using the DEFLATE compression method?

**Comment by naumanshah03** [comment]
Hi @yezhu6 

`bit 0 is set for DEFLATE` here it means that if `bit 0` is set it means the value is 1 or bitwise and check will also help to verify the value. For the compressionMethods parameter you can either check for 0 - for no compression support and 1 - for compression support

I hope this clarifies your doubt

Regards,
Nauman Shah
