### ISSUE TITLE
Replacing the X-Frame-Options header with Content-Security-Policy lowers our website's SSLLabs rating from A++ to A+

### ISSUE THREAD

**Issue by Alfred6556** [ssllabs/ssllabs-scan#900]
The X-Frame-Options header is generally deprecated. The recommendation is to use the Content-Security-Policy header instead. 

However, when we replace the X-Frame-Options header with the Content-Security-Policy header and scan our website on SSLLABS, our rating goes down from A++ to A+.

We're wondering why.

**Comment by naumanshah03** [comment]
Hi @Alfred6556 

SSLLabs does not have A++ grade. We do not have any rule related to  X-Frame-Options or Content-Security-Policy headers.

Please share the domain name and exact issue for me to check further

Regards,
Nauman Shah

**Comment by Alfred6556** [comment]
Hi Nauman Shah,

Thank you for your reply.

I had reported that, as a result of replacing X-Frame-Options headers with Content-Security-Policy headers, our web site’s rating had gone from A++ to A+.

That was an error on our part. The results we had been evaluating were not from SSLLabs. Therefore, there is no need for you to check any further.

Kind regards,

Alfred



Van: Nauman Shah ***@***.***>
Verzonden: maandag 5 september 2022 12:12
Aan: ssllabs/ssllabs-scan ***@***.***>
CC: Alfred Bakia ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [ssllabs/ssllabs-scan] Replacing the X-Frame-Options header with Content-Security-Policy lowers our website's SSLLabs rating from A++ to A+ (Issue #900)


Hi @Alfred6556<https://github.com/Alfred6556>

SSLLabs does not have A++ grade. We do not have any rule related to X-Frame-Options or Content-Security-Policy headers.

Please share the domain name and exact issue for me to check further

Regards,
Nauman Shah

**Comment by naumanshah03** [comment]
@Alfred6556 

Thanks for confirming marking the issue as closed

Regards,
Nauman Shah
