### ISSUE TITLE
ISRG Root X2 (self-signed root) inclusion on ssllabs.com

### ISSUE THREAD

**Issue by ghost** [ssllabs/ssllabs-scan#903]
Hi,
It appears that the self-signed version of ISRG Root X2 included in the Apple, Mozilla and (some of the) Google Trust Stores is not included in the trust chain lists for all websites using Let's Encrypt certificates from the E1 intermediate.

**Comment by naumanshah03** [comment]
Hi @aeternesatiatus 

Could you please share more details and some domains for me to verify the issue?

Regards,
Nauman Shah
