### ISSUE TITLE
ADD ISRG Root X2

### ISSUE THREAD

**Issue by liuxyon** [ssllabs/ssllabs-scan#904]
The ISRG Root X2 root certificate is already trusted by browsers and operating systems and is already in use. 
ssllabs.com still not updated.

https://valid-isrgrootx2.letsencrypt.org/

https://www.ssllabs.com/ssltest/analyze.html?d=valid-isrgrootx2.letsencrypt.org

**Comment by naumanshah03** [comment]
Hi @liuxyon 

This is already a part of dev.ssllabs.com. Soon the changes will be available on www.ssllabs.com
https://dev.ssllabs.com/ssltest/analyze.html?d=valid-isrgrootx2.letsencrypt.org

Regards,
Nauman Shah

**Comment by ghen2** [comment]
Hi @naumanshah03

When will this change go to the main www.ssllabs.com test?

**Comment by naumanshah03** [comment]
Hi @ghen2 

It is updated now. Hence closing the issue

Regards,
Nauman Shah
