### ISSUE TITLE
String index out of range: -1

### ISSUE THREAD

**Issue by gitcnd** [ssllabs/ssllabs-scan#906]
Re-loading a page I scanned yesterday, belonging to a scammer, gives a blank web page saying

String index out of range: -1

https://www.ssllabs.com/ssltest/analyze.html?viaform=on&d=ato-rebate.click

**Comment by naumanshah03** [comment]
Hi @gitcnd 

This issue is already fixed and changes are now available on dev.ssllabs.com
#890 #888 #870 

Regards,
Nauman Shah
