### ISSUE TITLE
Keep getting error 441

### ISSUE THREAD

**Issue by AskInward** [ssllabs/ssllabs-scan#907]
I am throttling the requests properly and don't receive the error 429 but I'm getting error 441 some times which I'm not sure what it is supposed to indicate. Your documentation doesn't mention it. Please clarify

**Comment by naumanshah03** [comment]
Hi @AskInward 

What is the client that you're using?
Please share the complete request that you're making and the logs by masking the domains if you do not prefer share the domain names in public with the response received. 
`Error code 441` is a Validation Error code

Regards,
Nauman Shah
