### ISSUE TITLE
String index out of range: -1

### ISSUE THREAD

**Issue by gitcnd** [ssllabs/ssllabs-scan#909]
https://www.ssllabs.com/ssltest/analyze.html?viaform=on&d=ato-rebate.click

`

# curl 'https://www.ssllabs.com/ssltest/analyze.html?viaform=on&d=ato-rebate.click' \
>   -H 'authority: www.ssllabs.com' \
>   -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' \
>   -H 'accept-language: en-US,en;q=0.9' \
>   -H 'cache-control: max-age=0' \
>   -H 'cookie: _ga=GA1.2.234838416.1668923676; JSESSIONID=456FEE8934A032FBD243D5750D96DFAC; _gid=GA1.2.1919877829.1670925845' \
>   -H 'sec-ch-ua: "Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"' \
>   -H 'sec-ch-ua-mobile: ?0' \
>   -H 'sec-ch-ua-platform: "macOS"' \
>   -H 'sec-fetch-dest: document' \
>   -H 'sec-fetch-mode: navigate' \
>   -H 'sec-fetch-site: none' \
>   -H 'sec-fetch-user: ?1' \
>   -H 'upgrade-insecure-requests: 1' \
>   -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36' \
>   --compressed -i
HTTP/2 500 
date: Tue, 13 Dec 2022 10:05:53 GMT
server: Apache
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
strict-transport-security: max-age=31536000
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: 0
x-frame-options: DENY
content-type: text/html;charset=ISO-8859-1
content-length: 29
set-cookie: JSESSIONID=9A49C445F548FE054EF7D772DDB87A9F; Path=/; Secure; HttpOnly
content-security-policy: default-src 'self' ssllabs.com *.ssllabs.com https://www.google-analytics.com/ https://www.googletagmanager.com/ https://stats.g.doubleclick.net https://www.google.com/ https://cdn.bizible.com https://serve.albacross.com https://collect.albacross.com https://tagmanager.google.com https://js.driftt.com; script-src 'self' https://cdnjs.cloudflare.com https://www.google-analytics.com/ https://www.googletagmanager.com/ https://stats.g.doubleclick.net https://www.google.com/ https://cdn.bizible.com https://serve.albacross.com https://collect.albacross.com https://tagmanager.google.com https://js.driftt.com 'sha256-khWDFUo/+h2RpY43Yb/fpJ+pKAOhiJcwX8XN0zNVIs4=' 'sha256-MIHgzD5ZYexjYZVdlcHHJQONMefhA7YQw4t+st69/FA=' 'sha256-BxzAkiq5sx2G9G9B83/+mizzq5uTli77I4plniiYufA=';

String index out of range: -1

`

**Comment by naumanshah03** [comment]
Hi @gitcnd 

This issue is fixed and available on www.ssllabs.com with v2.2.0

Regards,
Nauman Shah
