### ISSUE TITLE
No certificate transparency detection via OCSP

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#92]
https://dev.ssllabs.com/ssltest/analyze.html?d=ritter.vg

> Certificate Transparency	No

![image](https://cloud.githubusercontent.com/assets/10382329/6760288/5129ea28-cf58-11e4-817e-cf1a6fe02286.png)

![image](https://cloud.githubusercontent.com/assets/10382329/6760324/9e4dfc0e-cf58-11e4-9891-1d9f10fb0d7f.png)

**Comment by ivanr** [comment]
That's because I am not done developing this feature. You're too fast :)

**Comment by selecadm** [comment]
That's what she said :D.
