### ISSUE TITLE
HARICA's 2015 Roots not trusted by Java

### ISSUE THREAD

**Issue by AEtherC0r3** [ssllabs/ssllabs-scan#924]
The "SSL Server Test" reports certificates that chain to HARICA's 2015 Roots (https://crt.sh/?caID=14566, https://crt.sh/?caID=14546) as "not trusted by Java trust store".
e.g. https://www.ssllabs.com/ssltest/analyze.html?d=harica.gr&s=155.207.1.46

These root CAs have been included in the Java trust store since at least April 2021
https://www.oracle.com/java/technologies/javase/16all-relnotes.html
https://bugs.openjdk.org/browse/jdk-8256421

**Comment by naumanshah03** [comment]
Hi @AEtherC0r3 

Trust stores are now updated on www.ssllabs.com with v2.2.0 hence closing this issue
https://www.ssllabs.com/ssltest/analyze.html?d=harica.gr&s=155.207.1.46&latest

Regards,
Nauman Shah
