### ISSUE TITLE
GLOBALTRUST 2020 RootCA not trusted

### ISSUE THREAD

**Issue by DanielZens** [ssllabs/ssllabs-scan#925]
Dear, 

would you please include our RootCA GLOBALTRUST 2020 in your trust list?

It is a member of the major browser stores (Microsoft, Mozilla, Apple, Google) 

You can check this e.g. here https://crt.sh/?caid=165191

Here's the CA
– https://service.globaltrust.eu/static/globaltrust-2020-der.cer (DER-Format)
– https://service.globaltrust.eu/static/globaltrust-2020.crt (PEM-Format)
– https://service.globaltrust.eu/static/globaltrust-2020.p7b (PKCS#7-Format)
– https://service.globaltrust.eu/static/globaltrust-2020.txt (Text-Format)

Many thanks, 

Best regards
Daniel 
GLOBALTRUST

**Comment by naumanshah03** [comment]
Hi @DanielZens 

Please check now on www.ssllabs.com with v2.2.0
Accordingly you can close this issue since I don't have the domain to test it out

Regards,
Nauman Shah
