### ISSUE TITLE
DROWN: Unable to perform this test due to an internal error.

### ISSUE THREAD

**Issue by qwertychouskie** [ssllabs/ssllabs-scan#927]
![image](https://github.com/ssllabs/ssllabs-scan/assets/13989090/3334225d-b538-4d51-b489-009177dc5a47)
https://www.ssllabs.com/ssltest/analyze.html?d=jacobspctuneup.tk

**Comment by naumanshah03** [comment]
Hi @qwertychouskie 

We have stopped the extensive scanning support for DROWN Test. Please refer to the below notification
https://notifications.qualys.com/product/2024/03/28/ssl-labs-sunsetting-drown-test

Regards,
Nauman Shah
