### ISSUE TITLE
There should be "Not trusted as supplied" warning for payu.ru

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#93]
https://www.ssllabs.com/ssltest/analyze.html?d=payu.ru

> Chain issues	Extra certs, Contains anchor

Correct chain:
1. payu.ru
2. GeoTrust EV intermediate, second generation
3. GeoTrust pseudo-root cross-signed from Equifax (optional)

Current chain:
1. payu.ru
2. Equifax root
3. Equifax root (again)
4. GeoTrust pseudo-root cross-signed from Equifax
5. GeoTrust EV intermediate, first generation (not needed at all)
6. GeoTrust EV intermediate, second generation

**Comment by ivanr** [comment]
No, "Not trusted as supplied" is used when trust requires a certificate that's not sent by the server. That's not the case with this web site. Perhaps there should be a warning about invalid order in this case.
