### ISSUE TITLE
No support for IPv6 only hosts

### ISSUE THREAD

**Issue by minfrin** [ssllabs/ssllabs-scan#934]
When an attempt is made to scan an IPv6 only website, the page reloads and the text "To test IP addresses, please try [Qualys CertView](https://www.qualys.com/certview/)" appears.

It seems its only possible to test IPv6 if there is an IPv4 address already.

**Comment by TNTBOMBOM** [comment]
what it is the website?

**Comment by catharsis71** [comment]
Use their dev site at https://dev.ssllabs.com/ssltest/

they fixed it there last year but don't seem to care about pushing to production

**Comment by LucasMZReal** [comment]
Literally came here because of this issue. Please just push this already;

**Comment by naumanshah03** [comment]
Hi

This issue has been fixed with the new release of v2.2.0 on production
Please visit www.ssllabs.com and run scan for IPv6 only server - https://www.ssllabs.com/ssltest/analyze.html?d=ipv6.google.com&latest

Please reopen it if you see this issue again

Regards,
Nauman Shah

**Comment by minfrin** [comment]
Works great, thank you!
