### ISSUE TITLE
Numeric grades in the the API too

### ISSUE THREAD

**Issue by andrepereiradasilva** [ssllabs/ssllabs-scan#94]
In the web version there are numeric grades that are used to calculate the final grade.
Example:
![image](https://cloud.githubusercontent.com/assets/9630530/6770538/a48e1fc8-d0ba-11e4-9b42-c31f810fb897.png)

But in the API result that numeric grades are missing.

**Comment by selecadm** [comment]
Numeric grades are subject to disappear.
https://community.qualys.com/thread/12237
> The next version of the test will likely remove all numerical scores in order to emphasize this.

**Comment by ivanr** [comment]
The numeric grades are making people focus on the wrong thing, which is why they're going away.
