### ISSUE TITLE
Error Unable to connect to server.

### ISSUE THREAD

**Issue by alvarezh2000** [ssllabs/ssllabs-scan#941]
When trying to verify address telestaff.pd.danbury-ct.gov I'm getting "Assessment failed; unable to connect to server"
The Windows firewall is disabled. The certificate is good. We can get to the website without issues.
Why is ssllabs failing to coonect?
Thank you,
Hector

**Comment by naumanshah03** [comment]
@alvarezh2000 Please check the server because in between when ssllabs is running the tests the connection is breaking and I could be happening because ssllabs sends multiple set of request for the reports

Regards,
Nauman Shah
