### ISSUE TITLE
INTERNAL ERROR: test.drownattack.com

### ISSUE THREAD

**Issue by acbekoac** [ssllabs/ssllabs-scan#946]
https://www.ssllabs.com/ssltest/analyze.html

Unable to perform this test due to an internal error.
(1) For a better understanding of this test, please read this longer explanation
(2) Key usage data kindly provided by the Censys network search engine; original DROWN website here
(3) Censys data is only indicative of possible key and certificate reuse; possibly out-of-date and not complete
INTERNAL ERROR: test.drownattack.com
INTERNAL ERROR: test.drownattack.com
INTERNAL ERROR: test.drownattack.com

**Comment by naumanshah03** [comment]
Hi @acbekoac 

We have stopped the extensive scanning support for DROWN Test. Please refer to the below notification
https://notifications.qualys.com/product/2024/03/28/ssl-labs-sunsetting-drown-test

Regards,
Nauman Shah
