### ISSUE TITLE
Unable to resolve domain name

### ISSUE THREAD

**Issue by palmbeachcuisine** [ssllabs/ssllabs-scan#957]
I have been using this tool for years. Recently I have not been able to test my server. Keep seeing "Unable to resolve domain name". Haven't made any changes to the server that would cause this.

**Comment by naumanshah03** [comment]
Able to scan your domain and the result is available [here](https://www.ssllabs.com/ssltest/analyze.html?d=palmbeachcuisine.com&hideResults=on&latest)

**Comment by palmbeachcuisine** [comment]
palmbeachcuisine.com

Thank you!
