### ISSUE TITLE
when will v3 API be deprecated?

### ISSUE THREAD

**Issue by pixelpaulaus** [ssllabs/ssllabs-scan#959]
Hello,
I am not fan of providing my name and email on requests on the new v4. So I will continue to use v3, but are there any plans to close it off?

**Comment by rajiv** [comment]
https://notifications.qualys.com/api/2023/09/28/introduction-of-api-v4-for-qualys-ssllabs-and-deprecation-of-api-v3 says:
> The API v3 API will be available until the end of 2023 (Dec 31st 2023), and starting from 1st January 2024, we will be deprecating the API v3 support for SSL Labs. Request all customers to move to API v4.

**Comment by pixelpaulaus** [comment]
thats not good. tho strangely it is still working now for me.
I wonder what the email and name provided will be used for, to lots of unwanted emails?
