### ISSUE TITLE
405 error on register

### ISSUE THREAD

**Issue by pixelpaulaus** [ssllabs/ssllabs-scan#960]
When i try to register, i get a 405 error.
Using this API path:
GET https://api.ssllabs.com/api/v4/register/

I am providing all data: firstName, lastName, email, organization
And the Content-Type header

No body returned for response, just the status code.

**Comment by naumanshah03** [comment]
Hi @pixelpaulaus 

You're using incorrect HTTP Method you should be using POST method for register API
`POST https://api.ssllabs.com/api/v4/register/`

Regards,
Nauman Shah
