### ISSUE TITLE
3DES is shown as stronger than 128-bit AES

### ISSUE THREAD

**Issue by selecadm** [ssllabs/ssllabs-scan#99]
Subj.

![image](https://cloud.githubusercontent.com/assets/10382329/6880985/0ae389ca-d55c-11e4-92e6-c8d45473567d.png)

**Comment by RobTho** [comment]
i think it is still treated as 168 in background

**Comment by selecadm** [comment]
@RobTho my thoughts exactly. GlobalSign's version of SSL Labs shows 3DES 168, like old versions of Chrome and Firefox. Internet Explorer still does it, even in Windows 10. Only the matter of time.

**Comment by selecadm** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=gardenclinic.com.au

SSL2 cipher is shown as stronger than DHE + 128-bit AES. Shouldn't all SSL2 ciphers be at the top in case of no server preference?

![image](https://cloud.githubusercontent.com/assets/10382329/7030243/dd0e5efe-dd6b-11e4-8953-23ae53c78dfb.png)

**Comment by selecadm** [comment]
3DES is correctly shown as weaker that AES-128 in case of SSL Labs failure to detect server preference, but still wrong in case of verified lack of server preference.

https://www.ssllabs.com/ssltest/analyze.html?d=hnapay.com

![image](https://cloud.githubusercontent.com/assets/10382329/8384283/b9b2d22a-1c48-11e5-875b-edaa1a05a691.png)

https://www.ssllabs.com/ssltest/analyze.html?d=online.sberbank.ru

![image](https://cloud.githubusercontent.com/assets/10382329/8384310/e756713c-1c48-11e5-8d28-a220aedf06a5.png)

**Comment by ivanr** [comment]
This should be fixed in 1.19.16. Please reopen if it isn't. Thanks.

**Comment by selecadm** [comment]
Now it is weaker than RC4. Should RC4 be at the end (deprecated)?

![image](https://cloud.githubusercontent.com/assets/10382329/8416016/6dc9612a-1eab-11e5-9e20-bef7f551c06d.png)

**Comment by ivanr** [comment]
"Deprecated" in this context means cipher suites that are not used with the best protocol, but enabled with lower protocol revisions. I think I need a better word to (concisely) explain that.
